-- =====================================================================
-- VIRASAT FULL DATABASE SCHEMA FOR SUPABASE POSTGRESQL
-- Generated by combining migrations 001 through 005 in sequence
-- Target: Supabase PostgreSQL (SQL Editor / Direct Migration)
-- =====================================================================


-- =====================================================================
-- SECTION 1 / 5: MIGRATION 001 (PHASE 1: INITIAL SCHEMA & CORE ENTITIES)
-- Source: server/src/db/migrations/001_phase1_initial_schema.sql
-- =====================================================================

-- 1. Create Enums
DO $$ BEGIN
    CREATE TYPE data_confidence_enum AS ENUM (
        'official',
        'trusted_third_party',
        'community_reported',
        'modelled',
        'estimated',
        'stale',
        'unverified'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE transit_type_enum AS ENUM (
        'railway',
        'metro',
        'bus',
        'airport'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE user_role_enum AS ENUM (
        'traveller',
        'contributor',
        'verified_provider',
        'moderator',
        'heritage_officer',
        'admin'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Users Table
-- password_hash is nullable to support Firebase and external OAuth identities
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    home_city VARCHAR(100) DEFAULT 'Mumbai',
    auth_provider VARCHAR(50) DEFAULT 'local',
    role user_role_enum DEFAULT 'traveller',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. States Table (Aligned with TypeScript StateRecord)
CREATE TABLE IF NOT EXISTS states (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100),
    type VARCHAR(32) DEFAULT 'state',
    region_type VARCHAR(32) DEFAULT 'state',
    capital VARCHAR(100),
    region VARCHAR(50),
    official_tourism_url TEXT,
    description TEXT,
    status VARCHAR(50) DEFAULT 'verified',
    hero_image_id VARCHAR(100),
    hero_image_url TEXT,
    hero_image JSONB,
    source_url TEXT,
    source_name VARCHAR(255),
    creator VARCHAR(255),
    license VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Cities Table (Aligned with TypeScript CityRecord)
CREATE TABLE IF NOT EXISTS cities (
    id VARCHAR(64) PRIMARY KEY,
    state_id VARCHAR(64) REFERENCES states(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100),
    canonical_name VARCHAR(100),
    entity_type VARCHAR(32) DEFAULT 'city',
    district VARCHAR(100),
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    short_description TEXT,
    description TEXT,
    tagline TEXT,
    official_url TEXT,
    status VARCHAR(50) DEFAULT 'verified',
    state VARCHAR(100),
    region VARCHAR(50),
    city_type VARCHAR(50),
    tourism_categories JSONB DEFAULT '[]'::jsonb,
    prominence VARCHAR(50),
    is_capital BOOLEAN DEFAULT FALSE,
    capital_status VARCHAR(50),
    verification_status VARCHAR(50) DEFAULT 'verified',
    source_provenance TEXT,
    hero_image_url TEXT,
    hero_image JSONB,
    source_url TEXT,
    source_name VARCHAR(255),
    creator VARCHAR(255),
    license VARCHAR(100),
    places_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Places Table (Attractions & Heritage Sites, aligned with TypeScript PlaceRecord)
CREATE TABLE IF NOT EXISTS places (
    id VARCHAR(128) PRIMARY KEY,
    city_id VARCHAR(64) REFERENCES cities(id) ON DELETE SET NULL,
    state_id VARCHAR(64) REFERENCES states(id) ON DELETE SET NULL,
    district VARCHAR(100),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    canonical_name VARCHAR(255),
    aliases JSONB DEFAULT '[]'::jsonb,
    place_type VARCHAR(50),
    category VARCHAR(50) NOT NULL,
    categories JSONB DEFAULT '[]'::jsonb,
    subcategories JSONB DEFAULT '[]'::jsonb,
    topic VARCHAR(100),
    subtopic VARCHAR(100),
    category_links JSONB DEFAULT '[]'::jsonb,
    importance_level VARCHAR(32),
    locality_type VARCHAR(50),
    short_description TEXT,
    summary TEXT,
    detailed_description TEXT,
    description TEXT,
    history TEXT,
    address TEXT,
    area VARCHAR(100),
    best_for VARCHAR(255),
    suggested_duration VARCHAR(100),
    visitor_notes TEXT,
    map_search TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    opening_hours VARCHAR(255),
    visiting_hours VARCHAR(255),
    entry_fee TEXT,
    entry_fee_domestic NUMERIC(10,2) DEFAULT 0,
    entry_fee_intl NUMERIC(10,2) DEFAULT 0,
    best_time_to_visit VARCHAR(255),
    contact_information TEXT,
    official_website TEXT,
    heritage_status VARCHAR(100),
    data_confidence data_confidence_enum DEFAULT 'unverified',
    source_url TEXT,
    source_name VARCHAR(255),
    source_type VARCHAR(50),
    provenance_type VARCHAR(50),
    verification_status VARCHAR(50) DEFAULT 'unverified',
    source_quality VARCHAR(50),
    last_verified_on VARCHAR(32),
    last_verified_at TIMESTAMPTZ,
    rating NUMERIC(3,2) DEFAULT 4.5,
    thumbnail_url TEXT,
    sources JSONB DEFAULT '[]'::jsonb,
    media JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Place Images
CREATE TABLE IF NOT EXISTS place_images (
    id VARCHAR(100) PRIMARY KEY,
    place_id VARCHAR(128) REFERENCES places(id) ON DELETE CASCADE,
    storage_url TEXT NOT NULL,
    credit VARCHAR(255),
    license VARCHAR(100),
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Transit Nodes (Stations, Junctions, Hubs)
CREATE TABLE IF NOT EXISTS transit_nodes (
    id VARCHAR(64) PRIMARY KEY,
    type transit_type_enum NOT NULL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(32) UNIQUE NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    city_id VARCHAR(64) REFERENCES cities(id) ON DELETE SET NULL,
    is_junction BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Favorites (User Bookmarks)
CREATE TABLE IF NOT EXISTS favorites (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) REFERENCES users(id) ON DELETE CASCADE,
    place_id VARCHAR(128) REFERENCES places(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_favorite UNIQUE(user_id, place_id)
);

-- 9. Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id VARCHAR(64) PRIMARY KEY,
    actor_id VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    from_value JSONB,
    to_value JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- NOTE: Multi-day itineraries, itinerary_days, and itinerary_stops are
-- canonically defined in migration 003_phase3_itinerary_ai_schema.sql.

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_places_city_id ON places(city_id);
CREATE INDEX IF NOT EXISTS idx_places_state_id ON places(state_id);
CREATE INDEX IF NOT EXISTS idx_places_category ON places(category);
CREATE INDEX IF NOT EXISTS idx_places_slug ON places(slug);
CREATE INDEX IF NOT EXISTS idx_places_importance_level ON places(importance_level);
CREATE INDEX IF NOT EXISTS idx_places_verification_status ON places(verification_status);
CREATE INDEX IF NOT EXISTS idx_cities_state_id ON cities(state_id);
CREATE INDEX IF NOT EXISTS idx_cities_slug ON cities(slug);
CREATE INDEX IF NOT EXISTS idx_states_slug ON states(slug);
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_transit_nodes_city_id ON transit_nodes(city_id);
CREATE INDEX IF NOT EXISTS idx_transit_nodes_code ON transit_nodes(code);


-- ============================================================================
-- SECTION 2 / 5: MIGRATION 002 (PHASE 2: PROVENANCE & AUDIT)
-- Source: server/src/db/migrations/002_phase2_provenance_schema.sql
-- ============================================================================

-- 1. Source authority registry (Tier 1 to Tier 4 per Section XI.2)
CREATE TABLE IF NOT EXISTS place_sources (
    id VARCHAR(64) PRIMARY KEY,
    source_name VARCHAR(255) NOT NULL,
    source_type VARCHAR(32) NOT NULL CHECK (source_type IN ('tier1_official', 'tier2_trusted', 'tier3_secondary', 'tier4_community')),
    url VARCHAR(512) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Granular field-level facts table (Section XI.1 & XV.2)
-- data_confidence check is normalized to case-insensitive lower to match data_confidence_enum and TypeScript DataConfidence type
CREATE TABLE IF NOT EXISTS place_facts (
    id VARCHAR(64) PRIMARY KEY,
    place_id VARCHAR(128) NOT NULL REFERENCES places(id) ON DELETE CASCADE,
    fact_key VARCHAR(64) NOT NULL,
    fact_value TEXT NOT NULL,
    data_confidence VARCHAR(32) NOT NULL CHECK (LOWER(data_confidence) IN ('official', 'trusted_third_party', 'community_reported', 'modelled', 'estimated', 'stale', 'unverified')),
    source_url VARCHAR(512) NOT NULL,
    source_type VARCHAR(32) NOT NULL CHECK (source_type IN ('tier1_official', 'tier2_trusted', 'tier3_secondary', 'tier4_community')),
    verified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_place_facts_place_id ON place_facts(place_id);
CREATE INDEX IF NOT EXISTS idx_place_facts_fact_key ON place_facts(fact_key);

-- 3. Image licenses and attribution tracking (Section XI.4 & XV.2)
CREATE TABLE IF NOT EXISTS image_licenses (
    id VARCHAR(64) PRIMARY KEY,
    image_url VARCHAR(512) NOT NULL,
    license_type VARCHAR(64) NOT NULL DEFAULT 'editorial_fair_use',
    attribution_required BOOLEAN NOT NULL DEFAULT true,
    attribution_text VARCHAR(255),
    source_portal VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_image_licenses_url ON image_licenses(image_url);


-- ============================================================================
-- SECTION 3 / 5: MIGRATION 003 (PHASE 3: ITINERARIES, ROUTING, AI)
-- Source: server/src/db/migrations/003_phase3_itinerary_ai_schema.sql
-- ============================================================================

-- 1. Persistent Multi-Day Itineraries (Canonical Model)
CREATE TABLE IF NOT EXISTS itineraries (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    destination VARCHAR(128) NOT NULL,
    city VARCHAR(128),
    state VARCHAR(128),
    days_count INTEGER NOT NULL DEFAULT 1,
    pace VARCHAR(32) NOT NULL DEFAULT 'moderate' CHECK (pace IN ('relaxed', 'moderate', 'fast')),
    budget_level VARCHAR(32) NOT NULL DEFAULT 'moderate' CHECK (budget_level IN ('budget', 'moderate', 'luxury')),
    summary TEXT,
    total_cost NUMERIC(10, 2) DEFAULT 0,
    start_date DATE,
    end_date DATE,
    city_ids JSONB DEFAULT '[]'::jsonb,
    is_public BOOLEAN NOT NULL DEFAULT false,
    places_count INTEGER DEFAULT 0,
    total_distance_km NUMERIC(8, 2) DEFAULT 0,
    estimated_budget NUMERIC(10, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_itineraries_user_id ON itineraries(user_id);
CREATE INDEX IF NOT EXISTS idx_itineraries_city ON itineraries(city);

-- 2. Itinerary Days Breakdown
CREATE TABLE IF NOT EXISTS itinerary_days (
    id VARCHAR(64) PRIMARY KEY,
    itinerary_id VARCHAR(64) NOT NULL REFERENCES itineraries(id) ON DELETE CASCADE,
    day_number INTEGER NOT NULL,
    area_title VARCHAR(255) NOT NULL,
    theme VARCHAR(128),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_itinerary_days_itinerary_id ON itinerary_days(itinerary_id);

-- 3. Itinerary Ordered Stops
CREATE TABLE IF NOT EXISTS itinerary_stops (
    id VARCHAR(64) PRIMARY KEY,
    day_id VARCHAR(64) NOT NULL REFERENCES itinerary_days(id) ON DELETE CASCADE,
    itinerary_id VARCHAR(64) NOT NULL REFERENCES itineraries(id) ON DELETE CASCADE,
    place_id VARCHAR(128) REFERENCES places(id) ON DELETE SET NULL,
    place_name VARCHAR(255) NOT NULL,
    stop_order INTEGER NOT NULL,
    arrival_time VARCHAR(32),
    duration_minutes INTEGER NOT NULL DEFAULT 60,
    travel_mode VARCHAR(64) DEFAULT 'Auto-Rickshaw / Local Transit',
    travel_duration_minutes INTEGER DEFAULT 15,
    travel_distance_km NUMERIC(6, 2) DEFAULT 2.0,
    estimated_cost NUMERIC(10, 2) DEFAULT 50,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_itinerary_stops_day_id ON itinerary_stops(day_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_stops_itinerary_id ON itinerary_stops(itinerary_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_stops_place_id ON itinerary_stops(place_id);

-- 4. AI Conversation Sessions
CREATE TABLE IF NOT EXISTS ai_sessions (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL DEFAULT 'AI Concierge Session',
    context_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_sessions_user_id ON ai_sessions(user_id);

-- 5. AI Conversation Messages
CREATE TABLE IF NOT EXISTS ai_messages (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL REFERENCES ai_sessions(id) ON DELETE CASCADE,
    role VARCHAR(32) NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
    content TEXT NOT NULL,
    tool_calls_json TEXT,
    metadata_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_messages_session_id ON ai_messages(session_id);

-- 6. AI Fact-Grounding Records (Traceability & Provenance)
CREATE TABLE IF NOT EXISTS ai_grounding_records (
    id VARCHAR(64) PRIMARY KEY,
    message_id VARCHAR(64) NOT NULL REFERENCES ai_messages(id) ON DELETE CASCADE,
    place_id VARCHAR(128) REFERENCES places(id) ON DELETE SET NULL,
    fact_id VARCHAR(64) REFERENCES place_facts(id) ON DELETE SET NULL,
    field_name VARCHAR(64) NOT NULL,
    confidence VARCHAR(32) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    source_url VARCHAR(512) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_grounding_message_id ON ai_grounding_records(message_id);
CREATE INDEX IF NOT EXISTS idx_ai_grounding_place_id ON ai_grounding_records(place_id);


-- ============================================================================
-- SECTION 4 / 5: MIGRATION 004 (PHASE 3B: CITIZEN STEWARDSHIP & RBAC)
-- Source: server/src/db/migrations/004_phase3b_stewardship_schema.sql
-- ============================================================================

-- 1. Enhanced Citizen Heritage Issue Reports (Aligned with TypeScript CitizenReportRecord)
CREATE TABLE IF NOT EXISTS citizen_reports (
    id VARCHAR(64) PRIMARY KEY,
    place_id VARCHAR(128) REFERENCES places(id) ON DELETE SET NULL,
    place_name VARCHAR(255),
    city VARCHAR(128),
    reported_by VARCHAR(255) NOT NULL,
    user_id VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,
    issue_type VARCHAR(64) NOT NULL CHECK (issue_type IN ('cleanliness', 'structural_damage', 'vandalism', 'overcrowding', 'accessibility', 'signage', 'ticket_fraud', 'other')),
    title VARCHAR(255),
    description TEXT NOT NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'UNDER_REVIEW', 'IN_PROGRESS', 'RESOLVED', 'REJECTED')),
    media_url VARCHAR(512),
    resolution_notes TEXT,
    resolved_by VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_citizen_reports_place_id ON citizen_reports(place_id);
CREATE INDEX IF NOT EXISTS idx_citizen_reports_user_id ON citizen_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_citizen_reports_status ON citizen_reports(status);
CREATE INDEX IF NOT EXISTS idx_citizen_reports_severity ON citizen_reports(severity);

-- 2. Destination Health & Preservation Metrics (Aggregated Cache)
CREATE TABLE IF NOT EXISTS destination_health_metrics (
    place_id VARCHAR(128) PRIMARY KEY REFERENCES places(id) ON DELETE CASCADE,
    health_score INTEGER NOT NULL DEFAULT 100 CHECK (health_score BETWEEN 0 AND 100),
    open_issues_count INTEGER NOT NULL DEFAULT 0,
    resolved_issues_count INTEGER NOT NULL DEFAULT 0,
    status_label VARCHAR(64) NOT NULL DEFAULT 'Excellent / Well Maintained',
    last_inspected_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Ensure Audit Logs Table Indexes
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id ON audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_id ON audit_logs(entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);


-- ============================================================================
-- SECTION 5 / 5: MIGRATION 005 (PHASE 4: GOOGLE AUTH, FIREBASE & PROFILE STATE)
-- Source: server/src/db/migrations/005_phase4_google_auth_profile_schema.sql
-- ============================================================================

-- 1. Extend Users table for Firebase UID, Google OAuth, and Rich Profiles
ALTER TABLE users ADD COLUMN IF NOT EXISTS firebase_uid VARCHAR(128) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id VARCHAR(128) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(512);
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferences JSONB DEFAULT '{}'::jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS survey JSONB DEFAULT '{}'::jsonb;

-- 2. Indexes for fast authentication and OAuth lookups
CREATE INDEX IF NOT EXISTS idx_users_firebase_uid ON users(firebase_uid);
CREATE INDEX IF NOT EXISTS idx_users_google_id ON users(google_id);
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users(LOWER(email));

-- ============================================================================
-- SECTION 6 / 6: MIGRATION 006 (PHASE 6: FESTIVALS INTEGRATION)
-- Source: server/src/db/migrations/006_phase6_festivals_schema.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS festivals (
    id VARCHAR(128) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    state VARCHAR(100) NOT NULL,
    state_id VARCHAR(64) NOT NULL REFERENCES states(id) ON DELETE RESTRICT,
    primary_city VARCHAR(100) NOT NULL,
    primary_city_id VARCHAR(64) REFERENCES cities(id) ON DELETE SET NULL,
    alternate_locations TEXT[],
    description TEXT NOT NULL,
    cultural_vibe VARCHAR(255),
    typical_season VARCHAR(100),
    typical_month VARCHAR(50),
    exact_date_start DATE,
    exact_date_end DATE,
    is_date_verified BOOLEAN DEFAULT FALSE,
    is_recurring BOOLEAN DEFAULT TRUE,
    associated_places TEXT[],
    lat NUMERIC(9, 6),
    lng NUMERIC(9, 6),
    image_url TEXT,
    source_url TEXT,
    source_name VARCHAR(255),
    license VARCHAR(100),
    attribution_text TEXT,
    verification_status VARCHAR(50) DEFAULT 'verified',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for high-performance date and geographic lookups
CREATE INDEX IF NOT EXISTS idx_festivals_state_id ON festivals(state_id);
CREATE INDEX IF NOT EXISTS idx_festivals_city_id ON festivals(primary_city_id);
CREATE INDEX IF NOT EXISTS idx_festivals_month ON festivals(typical_month);
CREATE INDEX IF NOT EXISTS idx_festivals_dates ON festivals(exact_date_start, exact_date_end);
