import fs from 'fs';
import path from 'path';

export const CANONICAL_STATES = [
  // North (10)
  {
    id: 'chandigarh',
    name: 'Chandigarh',
    code: 'CH',
    capital: 'Chandigarh',
    region: 'North',
    region_full: 'Northern India',
    type: 'Union Territory',
    coordinates: { lat: 30.7333, lng: 76.7794 },
    hero_image_url: 'https://images.unsplash.com/photo-1598890777032-bde13fbe3493?w=1200&auto=format&fit=crop&q=80',
    description: 'The City Beautiful, planned by Swiss-French architect Le Corbusier, known for the Capitol Complex UNESCO site and Sukhna Lake.',
    heritage_overview: 'Modernist 20th-century urban design masterwork, the Rock Garden of Nek Chand, and open green corridors.'
  },
  {
    id: 'delhi',
    name: 'Delhi',
    code: 'DL',
    capital: 'Delhi',
    region: 'North',
    region_full: 'Northern India',
    type: 'Union Territory',
    coordinates: { lat: 28.6139, lng: 77.2090 },
    hero_image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&auto=format&fit=crop&q=80',
    description: "India's historic national capital featuring iconic Mughal citadels, colonial boulevards, and three UNESCO World Heritage complexes.",
    heritage_overview: 'Spanning eight historical cities from the Tomaras and Delhi Sultanate to Mughals and Lutyens Delhi.'
  },
  {
    id: 'haryana',
    name: 'Haryana',
    code: 'HR',
    capital: 'Chandigarh',
    region: 'North',
    region_full: 'Northern India',
    type: 'State',
    coordinates: { lat: 29.0588, lng: 76.0856 },
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    description: 'Vedic heartland of the epic Mahabharata, ancient Harappan archaeological mounds at Rakhigarhi, and Pinjore Mughal gardens.',
    heritage_overview: 'Sacred battlefields of Kurukshetra, Harappan excavations, and historic battlegrounds of Panipat.'
  },
  {
    id: 'himachal-pradesh',
    name: 'Himachal Pradesh',
    code: 'HP',
    capital: 'Shimla',
    region: 'North',
    region_full: 'Northern India',
    type: 'State',
    coordinates: { lat: 31.1048, lng: 77.1734 },
    hero_image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df8?w=1200&auto=format&fit=crop&q=80',
    description: 'Devbhoomi — Land of the Gods, featuring snow-capped Himalayan peaks, Kalka-Shimla mountain railway, and Buddhist gompas in Spiti.',
    heritage_overview: 'Kalka-Shimla UNESCO Railway, wooden Pagoda-style temples, Kangra miniature paintings, and Tabo Monastery.'
  },
  {
    id: 'jammu-and-kashmir',
    name: 'Jammu and Kashmir',
    code: 'JK',
    capital: 'Srinagar (Summer) / Jammu (Winter)',
    region: 'North',
    region_full: 'Northern India',
    type: 'Union Territory',
    coordinates: { lat: 33.7782, lng: 76.5762 },
    hero_image_url: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?w=1200&auto=format&fit=crop&q=80',
    description: 'Paradise on Earth, celebrated for Dal Lake shikaras, Mughal gardens, Vaishno Devi shrine, and alpine meadows of Gulmarg.',
    heritage_overview: 'Terraced Mughal pleasure gardens, Martand Sun Temple ruins, wooden Sufi shrines, and Pashmina handlooms.'
  },
  {
    id: 'ladakh',
    name: 'Ladakh',
    code: 'LA',
    capital: 'Leh',
    region: 'North',
    region_full: 'Northern India',
    type: 'Union Territory',
    coordinates: { lat: 34.1526, lng: 77.5771 },
    hero_image_url: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=1200&auto=format&fit=crop&q=80',
    description: 'High-altitude desert trans-Himalaya featuring Buddhist gompas, Pangong Tso azure waters, and high mountain passes.',
    heritage_overview: 'Tibetan Buddhist monasteries (Thiksey, Hemis, Alchi), Leh Palace, and ancient Silk Route caravanserais.'
  },
  {
    id: 'punjab',
    name: 'Punjab',
    code: 'PB',
    capital: 'Chandigarh',
    region: 'North',
    region_full: 'Northern India',
    type: 'State',
    coordinates: { lat: 31.1471, lng: 75.3412 },
    hero_image_url: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Five Rivers, home to the sacred Sri Harmandir Sahib (Golden Temple), vibrant folk heritage, and historic gurdwaras.',
    heritage_overview: 'Sikh spiritual centers, Wagah border ceremony, Harappan site at Ropar, and Qila Mubarak in Patiala.'
  },
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    code: 'RJ',
    capital: 'Jaipur',
    region: 'North',
    region_full: 'Northern India',
    type: 'State',
    coordinates: { lat: 27.0238, lng: 74.2179 },
    hero_image_url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Kings featuring UNESCO Hill Forts, the Thar Desert, Jaipur pink city, and ornate Shekhawati havelis.',
    heritage_overview: 'Six UNESCO Hill Forts (Amer, Kumbhalgarh, Chittorgarh, Jaisalmer, Ranthambore, Gagron), Jantar Mantar, and desert palaces.'
  },
  {
    id: 'uttar-pradesh',
    name: 'Uttar Pradesh',
    code: 'UP',
    capital: 'Lucknow',
    region: 'North',
    region_full: 'Northern India',
    type: 'State',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    hero_image_url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&auto=format&fit=crop&q=80',
    description: 'Cradle of Indian civilization featuring the Taj Mahal, sacred ghats of Varanasi, Ayodhya, and Awadhi royal culture.',
    heritage_overview: 'UNESCO Taj Mahal, Agra Fort, Fatehpur Sikri, Sarnath Buddhist deer park, and ancient Ganges river ghats.'
  },
  {
    id: 'uttarakhand',
    name: 'Uttarakhand',
    code: 'UK',
    capital: 'Dehradun',
    region: 'North',
    region_full: 'Northern India',
    type: 'State',
    coordinates: { lat: 30.0668, lng: 79.0193 },
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Gods (Devbhoomi), sacred Char Dham Himalayan pilgrimage, Yoga capital Rishikesh, and Nanda Devi UNESCO reserve.',
    heritage_overview: 'Ancient stone temple architecture (Kedarnath, Badrinath, Jageshwar), sacred river confluences (Panch Prayag), and colonial hill stations.'
  },

  // North East (8)
  {
    id: 'arunachal-pradesh',
    name: 'Arunachal Pradesh',
    code: 'AR',
    capital: 'Itanagar',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 27.0844, lng: 93.6053 },
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Dawn-Lit Mountains, featuring Tawang Monastery, alpine passes, Siang river expeditions, and indigenous tribal crafts.',
    heritage_overview: '400-year-old Tawang Monastery, ancient 14th-century Ita Fort, and UNESCO-tentative Apatani cultural landscape.'
  },
  {
    id: 'assam',
    name: 'Assam',
    code: 'AS',
    capital: 'Dispur',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 26.2006, lng: 92.9376 },
    hero_image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&auto=format&fit=crop&q=80',
    description: 'Brahmaputra valley home to Kaziranga one-horned rhinos, Majuli river island, Kamakhya temple, and lush tea gardens.',
    heritage_overview: '600-year Ahom royal monuments at Sivasagar, Vaishnavite Satras of Majuli, and Kamakhya Shakti Peetha.'
  },
  {
    id: 'manipur',
    name: 'Manipur',
    code: 'MN',
    capital: 'Imphal',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 24.6637, lng: 93.9063 },
    hero_image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    description: 'Jeweled land featuring Loktak Lake with floating phumdis, Keibul Lamjao Sangai deer park, and Kangla Fort.',
    heritage_overview: 'Ancient Meitei kingdom seat at Kangla Fort, Govindaji Temple, and world birthplace of modern Polo (Sagol Kangjei).'
  },
  {
    id: 'meghalaya',
    name: 'Meghalaya',
    code: 'ML',
    capital: 'Shillong',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 25.4670, lng: 91.3662 },
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&auto=format&fit=crop&q=80',
    description: 'Abode of Clouds, renowned for living root bridges, Cherrapunjee waterfalls, clean village Mawlynnong, and Khasi culture.',
    heritage_overview: 'Bio-engineered Living Root Bridges, sacred Khasi groves, colonial architecture of Shillong, and limestone caves.'
  },
  {
    id: 'mizoram',
    name: 'Mizoram',
    code: 'MZ',
    capital: 'Aizawl',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 23.1645, lng: 92.9376 },
    hero_image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Rolling Hills and bamboo forests, known for its ridge-top capital Aizawl, Cheraw bamboo dance, and pristine lakes.',
    heritage_overview: 'Mizo cultural heritage, Solomon\'s Temple in Aizawl, Reiek heritage village, and traditional handloom weaving.'
  },
  {
    id: 'nagaland',
    name: 'Nagaland',
    code: 'NL',
    capital: 'Kohima',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 26.1584, lng: 94.5624 },
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Festivals, celebrated for the Hornbill Festival, 16 indigenous warrior tribes, WWII Kohima War Cemetery, and Dzukou Valley.',
    heritage_overview: 'Dimapur Kachari monolithic ruins, Kohima Commonwealth War Cemetery, and indigenous Naga morungs.'
  },
  {
    id: 'sikkim',
    name: 'Sikkim',
    code: 'SK',
    capital: 'Gangtok',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 27.5330, lng: 88.5122 },
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&auto=format&fit=crop&q=80',
    description: 'Himalayan wonderland crowned by Mt. Khangchendzonga (UNESCO Mixed World Heritage), Buddhist monasteries, and alpine lakes.',
    heritage_overview: 'Khangchendzonga UNESCO National Park, Rumtek Monastery, ancient coronation throne of Norbugang at Yuksom.'
  },
  {
    id: 'tripura',
    name: 'Tripura',
    code: 'TR',
    capital: 'Agartala',
    region: 'North East',
    region_full: 'Northeastern India',
    type: 'State',
    coordinates: { lat: 23.9408, lng: 91.9882 },
    hero_image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    description: 'Historic kingdom featuring the lakeside Neermahal palace, Ujjayanta Palace, and colossal 7th-9th century rock reliefs at Unakoti.',
    heritage_overview: 'Rock-carved Shaivite sculptures of Unakoti, water palace Neermahal, and royal Manikya dynasty heritage.'
  },

  // East (5)
  {
    id: 'andaman-and-nicobar-islands',
    name: 'Andaman and Nicobar Islands',
    code: 'AN',
    capital: 'Sri Vijaya Puram',
    region: 'East',
    region_full: 'Eastern India',
    type: 'Union Territory',
    coordinates: { lat: 11.7401, lng: 92.6586 },
    hero_image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    description: 'Archipelago in the Bay of Bengal with historic Cellular Jail, pristine coral reefs, and limestone caves of Baratang.',
    heritage_overview: 'Cellular Jail National Memorial, British colonial ruins on Netaji Subhash Chandra Bose Island, and indigenous tribal heritage.'
  },
  {
    id: 'bihar',
    name: 'Bihar',
    code: 'BR',
    capital: 'Patna',
    region: 'East',
    region_full: 'Eastern India',
    type: 'State',
    coordinates: { lat: 25.0961, lng: 85.3131 },
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    description: 'Cradle of ancient empires (Maurya and Gupta), enlightenment grounds of Gautama Buddha, and birthplace of Guru Gobind Singh.',
    heritage_overview: 'UNESCO Mahabodhi Temple, ancient Nalanda University ruins, Rajgir hill caves, and the heritage ghats of Patna.'
  },
  {
    id: 'jharkhand',
    name: 'Jharkhand',
    code: 'JH',
    capital: 'Ranchi',
    region: 'East',
    region_full: 'Eastern India',
    type: 'State',
    coordinates: { lat: 23.6102, lng: 85.2799 },
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Forests and waterfalls, sacred Baidyanath Jyotirlinga at Deoghar, Parasnath Jain pilgrimage, and tribal cultural heritage.',
    heritage_overview: 'Baidyanath Dham Temple at Deoghar, ancient Maluti terracotta temples, and sacred tribal Sarna groves.'
  },
  {
    id: 'odisha',
    name: 'Odisha',
    code: 'OD',
    capital: 'Bhubaneswar',
    region: 'East',
    region_full: 'Eastern India',
    type: 'State',
    coordinates: { lat: 20.9517, lng: 85.0985 },
    hero_image_url: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=80',
    description: 'Soul of Incredible India featuring Konark Sun Temple (UNESCO), Puri Jagannath shrine, Chilika lagoon, and Kalinga architecture.',
    heritage_overview: 'UNESCO 13th-century Konark Sun Temple, ancient Kalinga temple architecture of Bhubaneswar, and Raghurajpur heritage crafts.'
  },
  {
    id: 'west-bengal',
    name: 'West Bengal',
    code: 'WB',
    capital: 'Kolkata',
    region: 'East',
    region_full: 'Eastern India',
    type: 'State',
    coordinates: { lat: 22.9868, lng: 87.8550 },
    hero_image_url: 'https://images.unsplash.com/photo-1558431382-27e303142255?w=1200&auto=format&fit=crop&q=80',
    description: 'Cultural capital of India featuring Victoria Memorial, UNESCO Sundarbans, Darjeeling Himalayan Railway, and terracotta Bishnupur.',
    heritage_overview: 'UNESCO Darjeeling Himalayan Railway, Sundarbans mangrove tiger reserve, Santiniketan of Rabindranath Tagore, and colonial architecture.'
  },

  // Central (2)
  {
    id: 'chhattisgarh',
    name: 'Chhattisgarh',
    code: 'CG',
    capital: 'Raipur',
    region: 'Central',
    region_full: 'Central India',
    type: 'State',
    coordinates: { lat: 21.2787, lng: 81.8661 },
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=1200&auto=format&fit=crop&q=80',
    description: 'Green heartland of India boasting Chitrakote Horseshoe Falls, ancient Sirpur Buddhist brick monuments, and Bastar tribal arts.',
    heritage_overview: '7th-century Lakshmana brick temple of Sirpur, Bhoramdeo medieval temple, and Bastar bell-metal Dhokra crafts.'
  },
  {
    id: 'madhya-pradesh',
    name: 'Madhya Pradesh',
    code: 'MP',
    capital: 'Bhopal',
    region: 'Central',
    region_full: 'Central India',
    type: 'State',
    coordinates: { lat: 22.9734, lng: 78.6569 },
    hero_image_url: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=80',
    description: 'The Heart of India with three UNESCO sites: Khajuraho temples, Sanchi Buddhist stupas, and Bhimbetka rock shelters.',
    heritage_overview: 'UNESCO Khajuraho monuments, Great Stupa at Sanchi, Bhimbetka Paleolithic rock shelters, and Orchha palace forts.'
  },

  // West (4)
  {
    id: 'dadra-and-nagar-haveli-and-daman-and-diu',
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    code: 'DD',
    capital: 'Daman',
    region: 'West',
    region_full: 'Western India',
    type: 'Union Territory',
    coordinates: { lat: 20.3974, lng: 72.8328 },
    hero_image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&auto=format&fit=crop&q=80',
    description: 'Coastal Portuguese heritage territory featuring sea-facing fortress walls, baroque churches, and pristine beaches of Diu.',
    heritage_overview: '16th-century Portuguese Moti Daman Fort, Diu Fort overlooking the Arabian Sea, St. Paul Church, and tribal art in Silvassa.'
  },
  {
    id: 'goa',
    name: 'Goa',
    code: 'GA',
    capital: 'Panaji',
    region: 'West',
    region_full: 'Western India',
    type: 'State',
    coordinates: { lat: 15.2993, lng: 74.1240 },
    hero_image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&auto=format&fit=crop&q=80',
    description: 'Coastal jewel celebrated for UNESCO Churches of Old Goa, golden sandy beaches, Portuguese architecture, and spice plantations.',
    heritage_overview: 'Churches and Convents of Goa (UNESCO), Basilica of Bom Jesus, Se Cathedral, Fort Aguada, and Latin Quarter of Fontainhas.'
  },
  {
    id: 'gujarat',
    name: 'Gujarat',
    code: 'GJ',
    capital: 'Gandhinagar',
    region: 'West',
    region_full: 'Western India',
    type: 'State',
    coordinates: { lat: 22.2587, lng: 71.1924 },
    hero_image_url: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Legends featuring Ahmedabad World Heritage City, Rani ki Vav stepwell, Champaner, Somnath, and Asiatic Lions of Gir.',
    heritage_overview: 'Four UNESCO World Heritage sites (Historic City of Ahmedabad, Rani ki Vav, Champaner-Pavagadh, Dholavira Harappan City).'
  },
  {
    id: 'maharashtra',
    name: 'Maharashtra',
    code: 'MH',
    capital: 'Mumbai',
    region: 'West',
    region_full: 'Western India',
    type: 'State',
    coordinates: { lat: 19.7515, lng: 75.7139 },
    hero_image_url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&auto=format&fit=crop&q=80',
    description: 'Gateway to India with 5 UNESCO World Heritage sites: Ajanta, Ellora, Elephanta Caves, Chhatrapati Shivaji Maharaj Terminus, and Victorian Ensembles.',
    heritage_overview: 'Rock-cut Ajanta & Ellora cave temples, Maratha hill forts of Chhatrapati Shivaji Maharaj, and Victorian Gothic architecture.'
  },

  // South (7)
  {
    id: 'andhra-pradesh',
    name: 'Andhra Pradesh',
    code: 'AP',
    capital: 'Amaravati',
    region: 'South',
    region_full: 'Southern India',
    type: 'State',
    coordinates: { lat: 15.9129, lng: 79.7400 },
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=1200&auto=format&fit=crop&q=80',
    description: 'Sacred coastal state home to the Tirumala Venkateswara shrine, Buddhist stupas of Amaravati, and Lepakshi hanging pillar marvel.',
    heritage_overview: 'Vijayanagara temple architecture of Lepakshi, Buddhist archaeological sites (Amaravati, Nagarjunakonda), and Kondapalli woodcraft.'
  },
  {
    id: 'karnataka',
    name: 'Karnataka',
    code: 'KA',
    capital: 'Bengaluru',
    region: 'South',
    region_full: 'Southern India',
    type: 'State',
    coordinates: { lat: 15.3173, lng: 75.7139 },
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=1200&auto=format&fit=crop&q=80',
    description: 'One State Many Worlds featuring UNESCO Vijayanagara ruins at Hampi, Hoysala Sacred Ensembles, and Badami Chalukya cave temples.',
    heritage_overview: 'UNESCO Hampi ruins, UNESCO Hoysala Temples (Belur, Halebidu, Somnathpura), Pattadakal monuments, and Mysore Palace.'
  },
  {
    id: 'kerala',
    name: 'Kerala',
    code: 'KL',
    capital: 'Thiruvananthapuram',
    region: 'South',
    region_full: 'Southern India',
    type: 'State',
    coordinates: { lat: 10.8505, lng: 76.2711 },
    hero_image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&auto=format&fit=crop&q=80',
    description: "God's Own Country featuring palm-fringed backwaters of Alappuzha, Munnar tea hills, historic Fort Kochi, and Kathakali traditions.",
    heritage_overview: 'Ancient spice route port of Muziris, Dutch Palace Mattancherry, Bekal coastal fort, and Padmanabhaswamy treasure temple.'
  },
  {
    id: 'lakshadweep',
    name: 'Lakshadweep',
    code: 'LD',
    capital: 'Kavaratti',
    region: 'South',
    region_full: 'Southern India',
    type: 'Union Territory',
    coordinates: { lat: 10.5669, lng: 72.6420 },
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&auto=format&fit=crop&q=80',
    description: 'Emerald coral atolls in the Arabian Sea with crystal lagoons, marine biodiversity, and traditional coir crafts.',
    heritage_overview: 'Ancient Arab seafaring heritage, 17th-century Ujra Mosque in Kavaratti, and sustainable marine reef ecology.'
  },
  {
    id: 'puducherry',
    name: 'Puducherry',
    code: 'PY',
    capital: 'Puducherry',
    region: 'South',
    region_full: 'Southern India',
    type: 'Union Territory',
    coordinates: { lat: 11.9416, lng: 79.8083 },
    hero_image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=80',
    description: 'French Riviera of the East, featuring tree-lined colonial boulevards in White Town, Sri Aurobindo Ashram, and universal city Auroville.',
    heritage_overview: 'French colonial grid layout architecture, Matrimandir golden globe at Auroville, and ancient Arikamedu Roman trade port.'
  },
  {
    id: 'tamil-nadu',
    name: 'Tamil Nadu',
    code: 'TN',
    capital: 'Chennai',
    region: 'South',
    region_full: 'Southern India',
    type: 'State',
    coordinates: { lat: 11.1271, lng: 78.6569 },
    hero_image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=80',
    description: 'Land of Living Chola Temples (UNESCO), soaring Dravidian gopurams of Madurai, Shore Temple of Mamallapuram, and Nilgiri Mountain Railway.',
    heritage_overview: 'Great Living Chola Temples (Brihadisvara at Thanjavur & Gangaikonda Cholapuram, Airavatesvara), Mamallapuram shore relief carvings.'
  },
  {
    id: 'telangana',
    name: 'Telangana',
    code: 'TS',
    capital: 'Hyderabad',
    region: 'South',
    region_full: 'Southern India',
    type: 'State',
    coordinates: { lat: 18.1124, lng: 79.0193 },
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=1200&auto=format&fit=crop&q=80',
    description: 'City of Pearls and Nizams, home to Charminar, Golconda Fort, and UNESCO World Heritage Kakatiya Rudreshwara (Ramappa) Temple.',
    heritage_overview: 'UNESCO Ramappa Temple, Qutb Shahi Tombs, monolithic granite fortress of Bhongir, and Thousand Pillar Temple of Warangal.'
  }
];

console.log('Total Canonical States defined:', CANONICAL_STATES.length);
