import fs from 'fs';

// Complete dictionary of all 257 required cities across 36 States/UTs
export const CANONICAL_CITIES_RAW = [
  // --- Andhra Pradesh (13) ---
  {
    id: 'amaravati',
    name: 'Amaravati',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Guntur',
    city_type: 'heritage_site',
    lat: 16.5735,
    lng: 80.3575,
    tagline: 'Ancient Seat of Buddhist Learning & Planned Capital',
    description: 'Ancient riverbank Buddhist site boasting the Great Mahachaitya stupa ruins, museums, and seat of Andhra Pradesh administration.',
    tourism_categories: ['heritage', 'buddhist_pilgrimage', 'archaeology'],
    prominence: 'State Capital & Ancient Buddhist Center',
    is_capital: true,
    capital_status: 'state_capital',
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'anantapur',
    name: 'Anantapur',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Anantapur',
    city_type: 'city',
    lat: 14.6819,
    lng: 77.6006,
    tagline: 'Gateway to Vijayanagara Rock Art & Lepakshi',
    description: 'Rayalaseema historic district home to Gooty Fort, clock tower heritage, and gateway to the hanging pillars of Lepakshi.',
    tourism_categories: ['heritage', 'forts', 'culture'],
    prominence: 'Regional Heritage Hub',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'chittoor',
    name: 'Chittoor',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Chittoor',
    city_type: 'city',
    lat: 13.2172,
    lng: 79.1003,
    tagline: 'Land of Mango Orchards, Waterfalls & Horsley Hills',
    description: 'Scenic district renowned for Gurramkonda Fort, Horsley Hills summer sanctuary, and proximity to sacred hill shrines.',
    tourism_categories: ['nature', 'heritage', 'hill_station'],
    prominence: 'Cultural & Agricultural Center',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'guntur',
    name: 'Guntur',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Guntur',
    city_type: 'city',
    lat: 16.3067,
    lng: 80.4365,
    tagline: 'Spice Capital of Andhra & Kondaveedu Fort Realm',
    description: 'Major commercial and historical hub famed for the 14th-century Kondaveedu hilltop fort, Buddhist stupa relics, and chilli trade.',
    tourism_categories: ['heritage', 'forts', 'culture'],
    prominence: 'Major Commercial & Historic City',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'kakinada',
    name: 'Kakinada',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Kakinada',
    city_type: 'city',
    lat: 16.9891,
    lng: 82.2475,
    tagline: 'The Fertilizer City & Coringa Mangrove Sanctuary',
    description: 'Deep-water port town nestled along the Bay of Bengal, gateway to Coringa Wildlife Sanctuary second largest mangrove in India.',
    tourism_categories: ['coastal', 'nature', 'wildlife'],
    prominence: 'Coastal Hub & Eco-Tourism Center',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'kurnool',
    name: 'Kurnool',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Kurnool',
    city_type: 'city',
    lat: 15.8281,
    lng: 78.0373,
    tagline: 'Gateway of Rayalaseema & Subterranean Caves',
    description: 'Historic city featuring the formidable Konda Reddy Buruju fort, Oravakallu natural rock garden, and Belum Caves.',
    tourism_categories: ['heritage', 'caves', 'geological_wonder'],
    prominence: 'Historical Citadel',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'machilipatnam',
    name: 'Machilipatnam',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Krishna',
    city_type: 'city',
    lat: 16.1875,
    lng: 81.1389,
    tagline: 'Cradle of Kalamkari Art & Ancient Coromandel Port',
    description: 'Ancient Coromandel trading port dating back to Periplus era, world-famous for block-printed Machilipatnam Kalamkari textiles.',
    tourism_categories: ['handloom_textiles', 'coastal', 'heritage'],
    prominence: 'Artisanal & Maritime Heritage Port',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'nellore',
    name: 'Nellore',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Sri Potti Sriramulu Nellore',
    city_type: 'city',
    lat: 14.4426,
    lng: 79.9865,
    tagline: 'Land of Ranganatha Shrines & Pulicat Flamingo Haven',
    description: 'Penna riverbank city famed for the ancient Talpagiri Ranganathaswamy temple, Udayagiri fort ruins, and Pulicat lake birds.',
    tourism_categories: ['temples', 'nature', 'bird_watching'],
    prominence: 'Spiritual & Coastal Center',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'rajahmundry',
    name: 'Rajahmundry',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'East Godavari',
    city_type: 'city',
    lat: 17.0005,
    lng: 81.8040,
    tagline: 'Cultural Capital of Andhra & Mighty Godavari Ghats',
    description: 'Historic city on the sacred Godavari river, birthplace of Telugu literature poet Nannayya, famed for Godavari Arch Bridge.',
    tourism_categories: ['culture', 'river_ghats', 'literature'],
    prominence: 'Cultural Epicenter',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'srikakulam',
    name: 'Srikakulam',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Srikakulam',
    city_type: 'city',
    lat: 18.2949,
    lng: 83.8938,
    tagline: 'Sun Temple of Arasavalli & Kalingapatnam Shores',
    description: 'Northern coastal district boasting the 7th-century Arasavalli Sun Temple, Sri Kurmam tortoise shrine, and Kalingapatnam lighthouse.',
    tourism_categories: ['sun_temple', 'heritage', 'coastal'],
    prominence: 'Ancient Kalinga Heritage Site',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'tirupati',
    name: 'Tirupati',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Tirupati',
    city_type: 'city',
    lat: 13.6288,
    lng: 79.4192,
    tagline: 'Spiritual Capital of Andhra & Sacred Seven Hills',
    description: 'World-renowned pilgrimage destination resting at the foothills of the holy Tirumala hills, home to Sri Venkateswara Swamy shrine.',
    tourism_categories: ['pilgrimage', 'heritage', 'dravidian_temples'],
    prominence: 'Global Pilgrimage Destination',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Visakhapatnam',
    city_type: 'city',
    lat: 17.6868,
    lng: 83.2185,
    tagline: 'Jewel of the East Coast & Eastern Ghats Harbor',
    description: 'Cosmopolitan coastal port city with golden beaches, INS Kursura submarine museum, Kailasagiri hill views, and Borra Caves.',
    tourism_categories: ['coastal', 'submarine_museum', 'caves', 'nature'],
    prominence: 'Tier 1 Major Hub & Tourism Gateway',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'vizianagaram',
    name: 'Vizianagaram',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'South',
    district: 'Vizianagaram',
    city_type: 'city',
    lat: 18.1133,
    lng: 83.4072,
    tagline: 'City of Victory & Princely Royal Fort',
    description: 'Heritage city celebrated for the grand stone-built Vizianagaram Fort, Moti Mahal royal palace, and classical music traditions.',
    tourism_categories: ['heritage', 'forts', 'music_heritage'],
    prominence: 'Princely Heritage Town',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80'
  },

  // --- Arunachal Pradesh (12) ---
  {
    id: 'bomdila',
    name: 'Bomdila',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'West Kameng',
    city_type: 'hill_station',
    lat: 27.2645,
    lng: 92.4235,
    tagline: 'Apple Orchards & Himalayan Monasteries',
    description: 'Picturesque hill town with panoramic vistas of snow-capped Gorichen and Kangto peaks, Buddhist gompas, and apple orchards.',
    tourism_categories: ['hill_station', 'buddhist_monasteries', 'nature'],
    prominence: 'Key Himalayan Destination',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'changlang',
    name: 'Changlang',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Changlang',
    city_type: 'town',
    lat: 27.1472,
    lng: 95.7411,
    tagline: 'Realm of Namdapha Biodiversity & Historic Stillwell Road',
    description: 'Eastern frontier district gateway to Namdapha National Park, historic World War II Stillwell Road, and Tangsa tribal culture.',
    tourism_categories: ['wildlife', 'rainforest', 'wwii_heritage'],
    prominence: 'Offbeat Eco-Tourism Frontier',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'dirang',
    name: 'Dirang',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'West Kameng',
    city_type: 'town',
    lat: 27.3564,
    lng: 92.2356,
    tagline: 'Picturesque Kameng River Valley & Historic Dzong',
    description: 'Serene mountain valley featuring 500-year-old stone fortified Dirang Dzong, natural hot water springs, and kiwi orchards.',
    tourism_categories: ['valley', 'heritage_dzong', 'hot_springs'],
    prominence: 'Scenic Transit Hub to Tawang',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'itanagar',
    name: 'Itanagar',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Papum Pare',
    city_type: 'city',
    lat: 27.0844,
    lng: 93.6053,
    tagline: 'Capital of the Rising Sun & 14th-Century Ita Fort',
    description: 'State capital guarded by the 14th-century irregular brick Ita Fort, serene Ganga Lake (Gyakar Sinyi), and Jawaharlal Nehru State Museum.',
    tourism_categories: ['heritage', 'forts', 'museums'],
    prominence: 'State Capital & Cultural Gateway',
    is_capital: true,
    capital_status: 'state_capital',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'mechuka',
    name: 'Mechuka',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Shi Yomi',
    city_type: 'valley',
    lat: 28.6019,
    lng: 94.1311,
    tagline: 'The Forgotten Shangri-La of the Eastern Himalayas',
    description: 'Pristine high-altitude valley bordered by snow peaks, 400-year-old Samten Yongcha gompa, Yargyapchu river, and Memba tribal villages.',
    tourism_categories: ['alpine_valley', 'monasteries', 'eco_tourism'],
    prominence: 'Iconic Remote Alpine Sanctuary',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'namsai',
    name: 'Namsai',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Namsai',
    city_type: 'town',
    lat: 27.6667,
    lng: 95.8667,
    tagline: 'Land of the Golden Pagoda & Tai Khamti Traditions',
    description: 'Spiritual haven famed for the glittering Burmese-style Golden Pagoda (Kongmu Kham) at Tengapani and Tai Khamti Buddhist festivals.',
    tourism_categories: ['golden_pagoda', 'buddhist_heritage', 'culture'],
    prominence: 'Theravada Buddhist Center',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'pakke-kesang-hill-station',
    name: 'Pakke Kesang Hill Station',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Pakke-Kessang',
    city_type: 'hill_station',
    lat: 27.1500,
    lng: 93.1833,
    tagline: 'Misty Evergreen Ridge & Hornbill Sanctuary Gateway',
    description: 'Untouched emerald hill station known for cool mountain climate, panoramic Himalayan viewpoints, and proximity to Pakke Tiger Reserve.',
    tourism_categories: ['hill_station', 'wildlife', 'nature'],
    prominence: 'Emerging Eco-Hill Destination',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'pasighat',
    name: 'Pasighat',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'East Siang',
    city_type: 'town',
    lat: 28.0664,
    lng: 95.3263,
    tagline: 'Oldest Town of Arunachal & Gateway to Siang River',
    description: 'Historic British-era settlement nestled where the roaring Siang river meets the plains, gateway to whitewater rafting expeditions.',
    tourism_categories: ['river_rafting', 'heritage', 'nature'],
    prominence: 'Adventure & Historic Riverfront Town',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'roing',
    name: 'Roing',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Lower Dibang Valley',
    city_type: 'town',
    lat: 28.1408,
    lng: 95.8344,
    tagline: 'Archaeological Citadel of Bhismaknagar & Mehao Lake',
    description: 'Fascinating valley holding ancient 8th-century burnt-brick fortress of Bhismaknagar, pristine Mehao high-altitude lake, and Idu Mishmi culture.',
    tourism_categories: ['archaeology', 'forts', 'nature'],
    prominence: 'Archaeological & Natural Wonder',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'tawang',
    name: 'Tawang',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Tawang',
    city_type: 'town',
    lat: 27.5861,
    lng: 91.8594,
    tagline: 'Cradle of Mahayana Monasteries & High Sela Pass',
    description: 'High-altitude sanctum at 10,000 feet home to India\'s largest Buddhist monastery (Tawang Gompa founded 1681), Sela Pass, and Madhuri Lake.',
    tourism_categories: ['buddhist_monastery', 'mountain_pass', 'high_altitude_lake'],
    prominence: 'Major Global Heritage Center',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'yingkiong',
    name: 'Yingkiong',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Upper Siang',
    city_type: 'town',
    lat: 28.6253,
    lng: 94.9961,
    tagline: 'Canyon Valleys of Upper Siang & Traditional Cane Bridges',
    description: 'Picturesque hill town set amidst dramatic gorges of the Siang River, traditional bamboo-cane suspension bridges, and Adi tribal villages.',
    tourism_categories: ['river_gorges', 'cane_bridges', 'tribal_culture'],
    prominence: 'Upper Siang Gateway',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'ziro',
    name: 'Ziro',
    state: 'Arunachal Pradesh',
    state_id: 'arunachal-pradesh',
    region: 'North East',
    district: 'Lower Subansiri',
    city_type: 'valley',
    lat: 27.6324,
    lng: 93.8340,
    tagline: 'Pine Valley of the Apatani & UNESCO Cultural Landscape',
    description: 'UNESCO-tentative valley renowned for unique sustainable paddy-cum-fish agro-systems, sacred Tarin groves, and annual outdoor Ziro Music Festival.',
    tourism_categories: ['unesco_tentative', 'tribal_culture', 'music_festival'],
    prominence: 'World Cultural Landscape',
    is_capital: false,
    capital_status: 'none',
    hero_image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80'
  }
];

console.log('Sample canonical cities defined:', CANONICAL_CITIES_RAW.length);
