import fs from 'fs';
import path from 'path';

// Complete dictionary of all 257 Cities/Destinations as requested by USER
export const CITIES_DATA = [
  // Andhra Pradesh (13)
  { id: 'amaravati', name: 'Amaravati', state_id: 'andhra-pradesh', district: 'Guntur', lat: 16.5735, lng: 80.3575, is_capital: true, capital_status: 'state_capital', type: 'heritage_site', desc: 'Ancient riverbank Buddhist site boasting the Great Mahachaitya stupa ruins, museums, and seat of Andhra Pradesh administration.' },
  { id: 'anantapur', name: 'Anantapur', state_id: 'andhra-pradesh', district: 'Anantapur', lat: 14.6819, lng: 77.6006, type: 'city', desc: 'Rayalaseema historic district home to Gooty Fort, clock tower heritage, and gateway to the hanging pillars of Lepakshi.' },
  { id: 'chittoor', name: 'Chittoor', state_id: 'andhra-pradesh', district: 'Chittoor', lat: 13.2172, lng: 79.1003, type: 'city', desc: 'Scenic district renowned for Gurramkonda Fort, Horsley Hills summer sanctuary, and proximity to sacred hill shrines.' },
  { id: 'guntur', name: 'Guntur', state_id: 'andhra-pradesh', district: 'Guntur', lat: 16.3067, lng: 80.4365, type: 'city', desc: 'Major commercial and historical hub famed for the 14th-century Kondaveedu hilltop fort, Buddhist stupa relics, and chilli trade.' },
  { id: 'kakinada', name: 'Kakinada', state_id: 'andhra-pradesh', district: 'Kakinada', lat: 16.9891, lng: 82.2475, type: 'city', desc: 'Deep-water port town nestled along the Bay of Bengal, gateway to Coringa Wildlife Sanctuary second largest mangrove in India.' },
  { id: 'kurnool', name: 'Kurnool', state_id: 'andhra-pradesh', district: 'Kurnool', lat: 15.8281, lng: 78.0373, type: 'city', desc: 'Historic city featuring the formidable Konda Reddy Buruju fort, Oravakallu natural rock garden, and Belum Caves.' },
  { id: 'machilipatnam', name: 'Machilipatnam', state_id: 'andhra-pradesh', district: 'Krishna', lat: 16.1875, lng: 81.1389, type: 'city', desc: 'Ancient Coromandel trading port dating back to Periplus era, world-famous for block-printed Machilipatnam Kalamkari textiles.' },
  { id: 'nellore', name: 'Nellore', state_id: 'andhra-pradesh', district: 'Sri Potti Sriramulu Nellore', lat: 14.4426, lng: 79.9865, type: 'city', desc: 'Penna riverbank city famed for the ancient Talpagiri Ranganathaswamy temple, Udayagiri fort ruins, and Pulicat lake birds.' },
  { id: 'rajahmundry', name: 'Rajahmundry', state_id: 'andhra-pradesh', district: 'East Godavari', lat: 17.0005, lng: 81.8040, type: 'city', desc: 'Historic city on the sacred Godavari river, birthplace of Telugu literature poet Nannayya, famed for Godavari Arch Bridge.' },
  { id: 'srikakulam', name: 'Srikakulam', state_id: 'andhra-pradesh', district: 'Srikakulam', lat: 18.2949, lng: 83.8938, type: 'city', desc: 'Northern coastal district boasting the 7th-century Arasavalli Sun Temple, Sri Kurmam tortoise shrine, and Kalingapatnam lighthouse.' },
  { id: 'tirupati', name: 'Tirupati', state_id: 'andhra-pradesh', district: 'Tirupati', lat: 13.6288, lng: 79.4192, type: 'city', desc: 'World-renowned pilgrimage destination resting at the foothills of the holy Tirumala hills, home to Sri Venkateswara Swamy shrine.' },
  { id: 'visakhapatnam', name: 'Visakhapatnam', state_id: 'andhra-pradesh', district: 'Visakhapatnam', lat: 17.6868, lng: 83.2185, type: 'city', desc: 'Cosmopolitan coastal port city with golden beaches, INS Kursura submarine museum, Kailasagiri hill views, and Borra Caves.' },
  { id: 'vizianagaram', name: 'Vizianagaram', state_id: 'andhra-pradesh', district: 'Vizianagaram', lat: 18.1133, lng: 83.4072, type: 'city', desc: 'Heritage city celebrated for the grand stone-built Vizianagaram Fort, Moti Mahal royal palace, and classical music traditions.' },

  // Arunachal Pradesh (12)
  { id: 'bomdila', name: 'Bomdila', state_id: 'arunachal-pradesh', district: 'West Kameng', lat: 27.2645, lng: 92.4235, type: 'hill_station', desc: 'Picturesque hill town with panoramic vistas of snow-capped Gorichen and Kangto peaks, Buddhist gompas, and apple orchards.' },
  { id: 'changlang', name: 'Changlang', state_id: 'arunachal-pradesh', district: 'Changlang', lat: 27.1472, lng: 95.7411, type: 'town', desc: 'Eastern frontier district gateway to Namdapha National Park, historic World War II Stillwell Road, and Tangsa tribal culture.' },
  { id: 'dirang', name: 'Dirang', state_id: 'arunachal-pradesh', district: 'West Kameng', lat: 27.3564, lng: 92.2356, type: 'town', desc: 'Serene mountain valley featuring 500-year-old stone fortified Dirang Dzong, natural hot water springs, and kiwi orchards.' },
  { id: 'itanagar', name: 'Itanagar', state_id: 'arunachal-pradesh', district: 'Papum Pare', lat: 27.0844, lng: 93.6053, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'State capital guarded by the 14th-century irregular brick Ita Fort, serene Ganga Lake (Gyakar Sinyi), and Jawaharlal Nehru State Museum.' },
  { id: 'mechuka', name: 'Mechuka', state_id: 'arunachal-pradesh', district: 'Shi Yomi', lat: 28.6019, lng: 94.1311, type: 'valley', desc: 'Pristine high-altitude valley bordered by snow peaks, 400-year-old Samten Yongcha gompa, Yargyapchu river, and Memba tribal villages.' },
  { id: 'namsai', name: 'Namsai', state_id: 'arunachal-pradesh', district: 'Namsai', lat: 27.6667, lng: 95.8667, type: 'town', desc: 'Spiritual haven famed for the glittering Burmese-style Golden Pagoda (Kongmu Kham) at Tengapani and Tai Khamti Buddhist festivals.' },
  { id: 'pakke-kesang-hill-station', name: 'Pakke Kesang Hill Station', state_id: 'arunachal-pradesh', district: 'Pakke-Kessang', lat: 27.1500, lng: 93.1833, type: 'hill_station', desc: 'Untouched emerald hill station known for cool mountain climate, panoramic Himalayan viewpoints, and proximity to Pakke Tiger Reserve.' },
  { id: 'pasighat', name: 'Pasighat', state_id: 'arunachal-pradesh', district: 'East Siang', lat: 28.0664, lng: 95.3263, type: 'town', desc: 'Historic British-era settlement nestled where the roaring Siang river meets the plains, gateway to whitewater rafting expeditions.' },
  { id: 'roing', name: 'Roing', state_id: 'arunachal-pradesh', district: 'Lower Dibang Valley', lat: 28.1408, lng: 95.8344, type: 'town', desc: 'Fascinating valley holding ancient 8th-century burnt-brick fortress of Bhismaknagar, pristine Mehao high-altitude lake, and Idu Mishmi culture.' },
  { id: 'tawang', name: 'Tawang', state_id: 'arunachal-pradesh', district: 'Tawang', lat: 27.5861, lng: 91.8594, type: 'town', desc: 'High-altitude mountain sanctum home to India\'s largest Buddhist monastery (Tawang Gompa), Sela Pass, and Madhuri Lake.' },
  { id: 'yingkiong', name: 'Yingkiong', state_id: 'arunachal-pradesh', district: 'Upper Siang', lat: 28.6253, lng: 94.9961, type: 'town', desc: 'Picturesque hill town set amidst dramatic gorges of the Siang River, traditional bamboo-cane suspension bridges, and Adi tribal villages.' },
  { id: 'ziro', name: 'Ziro', state_id: 'arunachal-pradesh', district: 'Lower Subansiri', lat: 27.6324, lng: 93.8340, type: 'valley', desc: 'UNESCO-tentative valley renowned for unique sustainable paddy-cum-fish agro-systems, sacred Tarin groves, and annual outdoor Ziro Music Festival.' },

  // Assam (9)
  { id: 'chirang', name: 'Chirang', state_id: 'assam', district: 'Chirang', lat: 26.5458, lng: 90.5400, type: 'town', desc: 'Bodoland territorial district bordering Bhutan, gateway to Manas National Park UNESCO biodiversity hotspot and Bodo tribal handlooms.' },
  { id: 'dibrugarh', name: 'Dibrugarh', state_id: 'assam', district: 'Dibrugarh', lat: 27.4728, lng: 94.9120, type: 'city', desc: 'Tea City of India nestled on the Brahmaputra, gateway to lush colonial tea estates, river cruises, and Dehing Patkai rainforest.' },
  { id: 'guwahati', name: 'Guwahati', state_id: 'assam', district: 'Kamrup Metropolitan', lat: 26.1445, lng: 91.7362, type: 'city', desc: 'Gateway to Northeast India, home to the sacred Kamakhya Shakti Peetha, Umananda peacock river island, and Brahmaputra ropeway.' },
  { id: 'jorhat', name: 'Jorhat', state_id: 'assam', district: 'Jorhat', lat: 26.7509, lng: 94.2037, type: 'city', desc: 'Historical cultural center, home to Tocklai Tea Research Institute, sprawling tea bungalows, and main ferry launch point for Majuli.' },
  { id: 'majuli', name: 'Majuli', state_id: 'assam', district: 'Majuli', lat: 26.9555, lng: 94.2057, type: 'island', desc: 'World\'s largest inhabited river island, spiritual heart of Neo-Vaishnavite Satras, traditional bamboo mask-making, and pottery.' },
  { id: 'sivasagar', name: 'Sivasagar', state_id: 'assam', district: 'Sivasagar', lat: 26.9826, lng: 94.6425, type: 'heritage_site', desc: 'Imperial capital of the 600-year Ahom Dynasty, famed for Rang Ghar amphitheatre, multi-storied Talatal Ghar palace, and massive tanks.' },
  { id: 'tezpur', name: 'Tezpur', state_id: 'assam', district: 'Sonitpur', lat: 26.6338, lng: 92.7926, type: 'city', desc: 'City of Eternal Romance along the northern Brahmaputra bank, featuring Agnigarh hill romantic ruins and 6th-century stone doorframe of Da Parbatia.' },
  { id: 'tinsukia', name: 'Tinsukia', state_id: 'assam', district: 'Tinsukia', lat: 27.5000, lng: 95.3667, type: 'city', desc: 'Commercial hub bordering Dibru-Saikhowa National Park, famed for feral horses, Dibru river boat safaris, and Digboi historic oil town.' },
  { id: 'umrangso', name: 'Umrangso', state_id: 'assam', district: 'Dima Hasao', lat: 25.5167, lng: 92.7833, type: 'hill_station', desc: 'Scenic hill town in Dima Hasao district with rolling green hillocks, turquoise Kopili reservoir lakes, and annual Falcon festival.' },

  // Bihar (4)
  { id: 'arrah', name: 'Arrah', state_id: 'bihar', district: 'Bhojpur', lat: 25.5560, lng: 84.6603, type: 'city', desc: 'Historic town famed for 1857 Indian Uprising hero Veer Kunwar Singh fort, Jagdishpur heritage, and Arrah House colonial battleground.' },
  { id: 'gaya', name: 'Gaya', state_id: 'bihar', district: 'Gaya', lat: 24.7955, lng: 85.0002, type: 'city', desc: 'Ancient spiritual sanctum including the Vishnupad Temple on the Falgu river and UNESCO World Heritage Mahabodhi Temple at Bodh Gaya.' },
  { id: 'nalanda', name: 'Nalanda', state_id: 'bihar', district: 'Nalanda', lat: 25.1357, lng: 85.4435, type: 'heritage_site', desc: 'UNESCO World Heritage 5th-century Buddhist university archaeological ruins, multimedia museum, and neighboring Magadha capital Rajgir.' },
  { id: 'patna', name: 'Patna', state_id: 'bihar', district: 'Patna', lat: 25.5941, lng: 85.1376, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Ancient Mauryan capital Pataliputra, home to Takht Sri Patna Sahib, historic Golghar beehive granary, and world-class Bihar Museum.' },

  // Chhattisgarh (5)
  { id: 'bilaspur', name: 'Bilaspur', state_id: 'chhattisgarh', district: 'Bilaspur', lat: 22.0797, lng: 82.1409, type: 'city', desc: 'Cultural and railway hub featuring the 11th-century Ratanpur Mahamaya Temple, Malhar archaeological remains, and Achanakmar Tiger Reserve.' },
  { id: 'dantewada', name: 'Dantewada', state_id: 'chhattisgarh', district: 'Dantewada', lat: 18.8950, lng: 81.3500, type: 'town', desc: 'Ancient sacred realm situated at the confluence of Shankhini and Dhankini rivers, celebrated for the 14th-century Danteshwari Shakti Peetha.' },
  { id: 'jagdalpur', name: 'Jagdalpur', state_id: 'chhattisgarh', district: 'Bastar', lat: 19.0740, lng: 82.0080, type: 'city', desc: 'Tourism capital of Bastar featuring the Niagara of India Chitrakote Falls, Tirathgarh cascades, Kotumsar dripstone caves, and Bastar crafts.' },
  { id: 'raipur', name: 'Raipur', state_id: 'chhattisgarh', district: 'Raipur', lat: 21.2514, lng: 81.6296, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'State capital on the Mahanadi basin featuring Purkhouti Muktangan cultural park, Swami Vivekananda Sarovar, and gateway to Sirpur.' },
  { id: 'rajnandgaon', name: 'Rajnandgaon', state_id: 'chhattisgarh', district: 'Rajnandgaon', lat: 21.0961, lng: 81.0336, type: 'city', desc: 'Historic princely seat known for Dongargarh Bambleshwari hilltop temple reached by ropeway, royal palaces, and peace-pagoda monuments.' },

  // Goa (1)
  { id: 'goa', name: 'Goa', state_id: 'goa', district: 'North Goa / South Goa', lat: 15.4909, lng: 73.8278, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Coastal paradise famed for UNESCO Churches of Old Goa, Baroque basilicas, Latin Quarters of Fontainhas, coastal forts, and sandy beaches.' },

  // Gujarat (18)
  { id: 'ahmedabad', name: 'Ahmedabad', state_id: 'gujarat', district: 'Ahmedabad', lat: 23.0225, lng: 72.5714, type: 'city', desc: 'India\'s first UNESCO World Heritage City, home to Sabarmati Ashram, Sidi Saiyyed Mosque filigree stone latticework, and Adalaj Stepwell.' },
  { id: 'balasinor', name: 'Balasinor', state_id: 'gujarat', district: 'Mahisagar', lat: 22.9567, lng: 73.3331, type: 'town', desc: 'India\'s Jurassic Park, site of Raiyoli Dinosaur Fossil Park containing world\'s largest dinosaur egg hatchery and royal palace heritage.' },
  { id: 'bhavnagar', name: 'Bhavnagar', state_id: 'gujarat', district: 'Bhavnagar', lat: 21.7645, lng: 72.1519, type: 'city', desc: 'Historic maritime kingdom with Nilambag Palace, Takhteshwar Temple hill, and gateway to the 800+ marble Jain temples of Palitana.' },
  { id: 'bhuj', name: 'Bhuj', state_id: 'gujarat', district: 'Kutch', lat: 23.2420, lng: 69.6669, type: 'city', desc: 'Historic desert capital featuring Aina Mahal hall of mirrors, Prag Mahal Venetian gothic palace, and gateway to White Rann artisan villages.' },
  { id: 'champaner', name: 'Champaner', state_id: 'gujarat', district: 'Panchmahal', lat: 22.4852, lng: 73.5338, type: 'heritage_site', desc: 'UNESCO World Heritage archaeological park combining pre-Mughal Islamic architecture, stepwells, mosques, and Kalika Mata hilltop shrine.' },
  { id: 'dwarka', name: 'Dwarka', state_id: 'gujarat', district: 'Devbhumi Dwarka', lat: 22.2442, lng: 68.9685, type: 'pilgrimage_destination', desc: 'Sacred Char Dham coastal pilgrimage center on the Arabian Sea, home to the multi-tiered 72-pillar Dwarkadhish temple of Lord Krishna.' },
  { id: 'gandhinagar', name: 'Gandhinagar', state_id: 'gujarat', district: 'Gandhinagar', lat: 23.2156, lng: 72.6369, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Green capital city planned on the Sabarmati river, home to the colossal carved sandstone Akshardham temple complex and Dandi Kutir museum.' },
  { id: 'gir-somnath', name: 'Gir Somnath', state_id: 'gujarat', district: 'Gir Somnath', lat: 20.9016, lng: 70.4042, type: 'pilgrimage_destination', desc: 'First of the twelve holy Jyotirlinga shrines facing the Arabian Sea, alongside the dry-deciduous forest kingdom of the Asiatic Lions in Gir.' },
  { id: 'jamnagar', name: 'Jamnagar', state_id: 'gujarat', district: 'Jamnagar', lat: 22.4707, lng: 70.0577, type: 'city', desc: 'Jewel of Kathiawar famed for Lakhota Palace inside a lake, Khijadiya Bird Sanctuary, Marine National Park coral reefs, and Bandhani silk.' },
  { id: 'junagadh', name: 'Junagadh', state_id: 'gujarat', district: 'Junagadh', lat: 21.5222, lng: 70.4579, type: 'heritage_site', desc: 'Ancient city at the base of holy Girnar mountain with 3rd-century BCE Ashokan rock edicts, Uparkot Fort, and gothic Mahabat Maqbara.' },
  { id: 'kutch', name: 'Kutch', state_id: 'gujarat', district: 'Kutch', lat: 23.7337, lng: 69.8597, type: 'desert', desc: 'Vast salt marsh wilderness hosting the world-famous Rann Utsav, Dholavira UNESCO Harappan archaeological site, and vibrant Rogan embroidery.' },
  { id: 'patan', name: 'Patan', state_id: 'gujarat', district: 'Patan', lat: 23.8493, lng: 72.1266, type: 'heritage_site', desc: 'Medieval Solanki capital housing UNESCO World Heritage Rani ki Vav seven-storey subterranean stepwell and master Patola silk weavers.' },
  { id: 'porbandar', name: 'Porbandar', state_id: 'gujarat', district: 'Porbandar', lat: 21.6417, lng: 69.6093, type: 'city', desc: 'Ancient port and birthplace of Mahatma Gandhi (Kirti Mandir memorial), Sudama Temple, flamingo-filled wetlands, and coastal promenades.' },
  { id: 'rajkot', name: 'Rajkot', state_id: 'gujarat', district: 'Rajkot', lat: 22.3039, lng: 70.8022, type: 'city', desc: 'Heart of Saurashtra with Kaba Gandhi No Delo childhood home of Mahatma Gandhi, Watson Museum, and renowned silver jewelry craft.' },
  { id: 'surat', name: 'Surat', state_id: 'gujarat', district: 'Surat', lat: 21.1702, lng: 72.8311, type: 'city', desc: 'Diamond City and historic Mughal trading port on the Tapi river, famous for textile markets, Dutch and British colonial cemeteries, and food.' },
  { id: 'vadnagar', name: 'Vadnagar', state_id: 'gujarat', district: 'Mehsana', lat: 23.7844, lng: 72.6394, type: 'heritage_site', desc: 'Continuous 2,500-year-old archaeological wonder featuring the monumental red sandstone Kirti Toran victory arches and Buddhist monasteries.' },
  { id: 'vadodara', name: 'Vadodara', state_id: 'gujarat', district: 'Vadodara', lat: 22.3072, lng: 73.1812, type: 'city', desc: 'Cultural capital of Gujarat home to the majestic 700-acre Laxmi Vilas Palace (4 times size of Buckingham), museums, and Sayaji Baug.' },
  { id: 'valsad', name: 'Valsad', state_id: 'gujarat', district: 'Valsad', lat: 20.5992, lng: 72.9342, type: 'city', desc: 'Coastal city renowned for Tithal black sand beach, historic Parnera hilltop fort, Swaminarayan sea temple, and sweet Alphonso mangoes.' },

  // Haryana (6)
  { id: 'faridabad', name: 'Faridabad', state_id: 'haryana', district: 'Faridabad', lat: 28.4089, lng: 77.3178, type: 'city', desc: 'Historic industrial city home to 10th-century Surajkund sun pool stepwell amphitheatre, annual International Crafts Mela, and Raja Nahar Singh Palace.' },
  { id: 'gurugram', name: 'Gurugram', state_id: 'haryana', district: 'Gurugram', lat: 28.4595, lng: 77.0266, type: 'city', desc: 'Millennium City combining futuristic cyber hubs with heritage Sheesh Mahal at Farrukhnagar, Sultanpur Bird Sanctuary, and Sheetla Mata temple.' },
  { id: 'hisar', name: 'Hisar', state_id: 'haryana', district: 'Hisar', lat: 29.1492, lng: 75.7217, type: 'city', desc: 'Historical fortified city founded in 1354 by Firoz Shah Tughlaq featuring Firoz Shah Palace complex, Lat Ki Masjid, and Harappan Rakhigarhi.' },
  { id: 'kurukshetra', name: 'Kurukshetra', state_id: 'haryana', district: 'Kurukshetra', lat: 29.9695, lng: 76.8783, type: 'pilgrimage_destination', desc: 'Sacred cradle of the Bhagavad Gita, huge Brahma Sarovar holy tank, Jyotisar banyan tree enlightenment site, and Sheikh Chilli tomb.' },
  { id: 'panipat', name: 'Panipat', state_id: 'haryana', district: 'Panipat', lat: 29.3909, lng: 76.9635, type: 'heritage_site', desc: 'City of Weavers and legendary battleground of three epoch-defining Indian wars, holding Kabuli Bagh Mosque, Ibrahim Lodi Tomb, and Hemu memorial.' },
  { id: 'yamunanagar', name: 'Yamunanagar', state_id: 'haryana', district: 'Yamunanagar', lat: 30.1290, lng: 77.2674, type: 'city', desc: 'Foothill district featuring Kalesar National Park sal forests, Buddhist stupa at Chaneti, and ancient Sugh archaeological mound.' },

  // Himachal Pradesh (13)
  { id: 'bilaspur-hp', name: 'Bilaspur', state_id: 'himachal-pradesh', district: 'Bilaspur', lat: 31.3325, lng: 76.7570, type: 'town', desc: 'Picturesque valley city on the emerald Gobind Sagar reservoir formed by Bhakra Dam, water sports hub, and Vyas Cave.' },
  { id: 'chamba', name: 'Chamba', state_id: 'himachal-pradesh', district: 'Chamba', lat: 32.5534, lng: 76.1258, type: 'heritage_site', desc: 'Ancient Ravi river kingdom famed for 10th-century stone Lakshmi Narayan temples, Chaugan green, Chamba Rumal embroidery, and Rang Mahal.' },
  { id: 'dalhousie', name: 'Dalhousie', state_id: 'himachal-pradesh', district: 'Chamba', lat: 32.5387, lng: 75.9710, type: 'hill_station', desc: 'Colonial hill retreat built across five pine-clad hills, featuring Victorian stone churches, Subhash Baoli, and Swiss meadow Khajjiar.' },
  { id: 'dharamshala', name: 'Dharamshala', state_id: 'himachal-pradesh', district: 'Kangra', lat: 32.2190, lng: 76.3234, type: 'hill_station', desc: 'Seat of the 14th Dalai Lama in Upper McLeod Ganj, Tsuglagkhang Buddhist temple, pine-shaded mountain trails, and scenic HPCA cricket stadium.' },
  { id: 'kangra', name: 'Kangra', state_id: 'himachal-pradesh', district: 'Kangra', lat: 32.0998, lng: 76.2691, type: 'heritage_site', desc: 'Historic town home to the impregnable 4th-century BCE Kangra Fort (oldest dated fort in Himalayas) and Brajeshwari Devi Shakti Peetha.' },
  { id: 'kasauli', name: 'Kasauli', state_id: 'himachal-pradesh', district: 'Solan', lat: 30.9013, lng: 76.9649, type: 'hill_station', desc: 'Peaceful British-era cantonment hill station framed by oak and cedar woods, Christ Church, Gilbert Nature Trail, and Monkey Point.' },
  { id: 'keylong', name: 'Keylong', state_id: 'himachal-pradesh', district: 'Lahaul and Spiti', lat: 32.5710, lng: 77.0320, type: 'town', desc: 'Administrative center of Lahaul valley situated above the Bhaga river, home to Shashur and Kardang Buddhist monasteries.' },
  { id: 'kullu', name: 'Kullu', state_id: 'himachal-pradesh', district: 'Kullu', lat: 31.9579, lng: 77.1095, type: 'valley', desc: 'Valley of the Gods renowned for the International Dussehra festival on Dhalpur ground, Raghunath Temple, and Kullu handloom shawls.' },
  { id: 'manali', name: 'Manali', state_id: 'himachal-pradesh', district: 'Kullu', lat: 32.2432, lng: 77.1892, type: 'hill_station', desc: 'High-altitude resort town at the northern end of Kullu Valley, featuring 1553 timber Hidimba Devi temple, Solang Valley, and Atal Tunnel gateway.' },
  { id: 'paonta-sahib', name: 'Paonta Sahib', state_id: 'himachal-pradesh', district: 'Sirmaur', lat: 30.4397, lng: 77.6247, type: 'town', desc: 'Sacred Yamuna riverbank town where Guru Gobind Singh penned the Dasam Granth, housing Gurdwara Paonta Sahib and historic museum.' },
  { id: 'shimla', name: 'Shimla', state_id: 'himachal-pradesh', district: 'Shimla', lat: 31.1048, lng: 77.1734, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Former British summer capital, UNESCO Kalka-Shimla Toy Train terminal, pedestrian Mall Road, neo-Gothic Christ Church, and Viceregal Lodge.' },
  { id: 'spiti-valley', name: 'Spiti Valley', state_id: 'himachal-pradesh', district: 'Lahaul and Spiti', lat: 32.2461, lng: 78.0349, type: 'valley', desc: 'The Middle Land trans-Himalayan desert holding 1000-year-old Key Monastery, Tabo UNESCO tentative monastery, and high fossil village Langza.' },
  { id: 'reckong-peo', name: 'Reckong Peo', state_id: 'himachal-pradesh', district: 'Kinnaur', lat: 31.5404, lng: 78.2778, type: 'town', desc: 'Headquarters of Kinnaur offering spellbinding views of the sacred Kinnaur Kailash peak, apple orchards, and Kalpa heritage village.' },

  // Jharkhand (3)
  { id: 'deoghar', name: 'Deoghar', state_id: 'jharkhand', district: 'Deoghar', lat: 24.4826, lng: 86.6978, type: 'pilgrimage_destination', desc: 'Abode of the Gods, home to Baba Baidyanath Jyotirlinga temple complex drawing millions of Kanwariya pilgrims, Naulakha temple, and Trikut Pahar.' },
  { id: 'jamshedpur', name: 'Jamshedpur', state_id: 'jharkhand', district: 'East Singhbhum', lat: 22.8046, lng: 86.2029, type: 'city', desc: 'The Steel City founded by Jamsetji Tata, an impeccably planned green oasis with Jubilee Park, Dalma Wildlife Sanctuary, and Dimna Lake.' },
  { id: 'ranchi', name: 'Ranchi', state_id: 'jharkhand', district: 'Ranchi', lat: 23.3441, lng: 85.3096, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'City of Waterfalls (Hundru, Jonha, Dassam), Pahari Mandir hilltop, Tagore Hill cultural retreat, and tribal heritage museums.' },

  // Karnataka (15)
  { id: 'badami', name: 'Badami', state_id: 'karnataka', district: 'Bagalkote', lat: 15.9189, lng: 75.6775, type: 'heritage_site', desc: 'Regal capital of the early Chalukyas, renowned for four monolithic rock-cut cave temples carved into red sandstone cliffs above Agastya Lake.' },
  { id: 'bagalkote', name: 'Bagalkote', state_id: 'karnataka', district: 'Bagalkote', lat: 16.1817, lng: 75.6958, type: 'city', desc: 'Northern Karnataka cultural hub on the Ghataprabha River, gateway to the temple architecture centers of Aihole and Pattadakal (UNESCO).' },
  { id: 'belagavi', name: 'Belagavi', state_id: 'karnataka', district: 'Belagavi', lat: 15.8497, lng: 74.4977, type: 'city', desc: 'Historic border city featuring the massive 12th-century Belgaum Fort with Kamala Basti Jain temple, military heritage, and Gokak Falls.' },
  { id: 'bengaluru', name: 'Bengaluru', state_id: 'karnataka', district: 'Bengaluru Urban', lat: 12.9716, lng: 77.5946, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Silicon Valley of India combining modern technology with heritage Lalbagh Botanical Gardens, Tudor-style Bangalore Palace, and Tipu Sultan Summer Palace.' },
  { id: 'bidar', name: 'Bidar', state_id: 'karnataka', district: 'Bidar', lat: 17.9104, lng: 77.5199, type: 'heritage_site', desc: 'Medieval Bahmani and Barid Shahi capital holding Bidar Fort with 30+ bastions, Mahmud Gawan Madrasa, and fine silver-inlaid Bidriware metalwork.' },
  { id: 'dharwad', name: 'Dharwad', state_id: 'karnataka', district: 'Dharwad', lat: 15.4589, lng: 75.0078, type: 'city', desc: 'Twin cultural capital with Hubli, celebrated as cradle of Hindustani classical music legends (Bhimsen Joshi, Gangubai Hangal) and Dharwad Peda.' },
  { id: 'gokarna', name: 'Gokarna', state_id: 'karnataka', district: 'Uttara Kannada', lat: 14.5479, lng: 74.3188, type: 'coastal', desc: 'Sacred Arabian coastal town home to the ancient Mahabaleshwar Temple Atmalinga, crescent Om Beach, Kudle Beach, and cliff walking trails.' },
  { id: 'hampi', name: 'Hampi', state_id: 'karnataka', district: 'Vijayanagara', lat: 15.3350, lng: 76.4600, type: 'heritage_site', desc: 'UNESCO World Heritage monument complex spanning 4,100 hectares of ruins of the medieval Vijayanagara Empire, Stone Chariot, and Virupaksha Temple.' },
  { id: 'kalaburagi', name: 'Kalaburagi', state_id: 'karnataka', district: 'Kalaburagi', lat: 17.3297, lng: 76.8343, type: 'city', desc: 'Historical Gulbarga featuring the 14th-century Gulbarga Fort containing the grand roofed Jami Masjid and sacred Sufi shrine of Khwaja Bande Nawaz.' },
  { id: 'lakkundi', name: 'Lakkundi', state_id: 'karnataka', district: 'Gadag', lat: 15.3850, lng: 75.7170, type: 'heritage_site', desc: 'Architectural jewel holding 50+ medieval Western Chalukya and Hoysala temples (Brahma Jinalaya, Kasi Visveshwara) and ornate stepped stepwells.' },
  { id: 'mangalore', name: 'Mangalore', state_id: 'karnataka', district: 'Dakshina Kannada', lat: 12.9141, lng: 74.8560, type: 'city', desc: 'Coastal port city famed for 10th-century Kadri Manjunatha temple bronze idols, St. Aloysius Chapel frescoes, Panambur beach, and coastal cuisine.' },
  { id: 'mysuru', name: 'Mysuru', state_id: 'karnataka', district: 'Mysuru', lat: 12.2958, lng: 76.6394, type: 'city', desc: 'Cultural Capital of Karnataka home to the Indo-Saracenic Mysore Palace illuminated by 100,000 bulbs, Chamundi Hill, and Mysore Dasara.' },
  { id: 'somnathpura', name: 'Somnathpura', state_id: 'karnataka', district: 'Mysuru', lat: 12.2764, lng: 76.8820, type: 'heritage_site', desc: 'UNESCO World Heritage site holding the 1268 CE trikuta Chennakeshava Temple, a pinnacle of Hoysala stone relief carving and stellate geometry.' },
  { id: 'udupi', name: 'Udupi', state_id: 'karnataka', district: 'Udupi', lat: 13.3409, lng: 74.7421, type: 'pilgrimage_destination', desc: 'Spiritual destination centered on the 13th-century Sri Krishna Matha founded by Madhvacharya with Kanakana Kindi window, Malpe beach, and St. Mary Island.' },
  { id: 'vijayapura', name: 'Vijayapura', state_id: 'karnataka', district: 'Vijayapura', lat: 16.8302, lng: 75.7100, type: 'heritage_site', desc: 'Historic Adil Shahi capital famed for the colossal dome of Gol Gumbaz (second largest dome in the world) with acoustic Whispering Gallery and Ibrahim Rauza.' },

  // Kerala (19)
  { id: 'alappuzha', name: 'Alappuzha', state_id: 'kerala', district: 'Alappuzha', lat: 9.4981, lng: 76.3388, type: 'coastal', desc: 'Venice of the East, heart of Kerala backwaters with houseboats cruising Vembanad Lake, Alappuzha beach lighthouse, and Nehru Trophy Snake Boat Race.' },
  { id: 'bekal', name: 'Bekal', state_id: 'kerala', district: 'Kasaragod', lat: 12.3926, lng: 75.0315, type: 'coastal', desc: 'Pristine coastal stronghold famous for the keyhole-shaped 17th-century Bekal Fort rising dramatically out of the Arabian Sea waves.' },
  { id: 'kannur', name: 'Kannur', state_id: 'kerala', district: 'Kannur', lat: 11.8745, lng: 75.3704, type: 'city', desc: 'Land of Looms and Lores, celebrated for vibrant Theyyam ritual dance, Portuguese St. Angelo Fort, and Muzhappilangad drive-in beach.' },
  { id: 'kasargod', name: 'Kasargod', state_id: 'kerala', district: 'Kasaragod', lat: 12.5102, lng: 74.9852, type: 'city', desc: 'Northernmost coastal district holding Ananthapura Lake Temple (only lake temple in Kerala), Chandragiri Fort, and Ranipuram hills.' },
  { id: 'kochi', name: 'Kochi', state_id: 'kerala', district: 'Ernakulam', lat: 9.9312, lng: 76.2673, type: 'city', desc: 'Queen of the Arabian Sea featuring cantilevered Chinese Fishing Nets, colonial Fort Kochi, Jewish Synagogue, and Mattancherry Dutch Palace.' },
  { id: 'kollam', name: 'Kollam', state_id: 'kerala', district: 'Kollam', lat: 8.8932, lng: 76.6141, type: 'city', desc: 'Ancient spice seaport on Ashtamudi Lake (gateway to backwaters), Tangasseri Lighthouse, and Thangassery British-era church ruins.' },
  { id: 'kottayam', name: 'Kottayam', state_id: 'kerala', district: 'Kottayam', lat: 9.5916, lng: 76.5222, type: 'city', desc: 'City of Letters and Lakes, rubber plantation belt holding ancient Syrian Christian churches (Valiyapally) and Thazhathangady Juma Masjid.' },
  { id: 'kovalam', name: 'Kovalam', state_id: 'kerala', district: 'Thiruvananthapuram', lat: 8.4004, lng: 76.9787, type: 'coastal', desc: 'World-famous crescent beach destination crowned by the striped red-and-white Vizhinjam Lighthouse, Hawa Beach, and Ayurvedic resorts.' },
  { id: 'kozhikode', name: 'Kozhikode', state_id: 'kerala', district: 'Kozhikode', lat: 11.2588, lng: 75.7804, type: 'city', desc: 'Historic City of Spices where Vasco da Gama landed at Kappad in 1498, UNESCO City of Literature, historic beach pier, and culinary delights.' },
  { id: 'kumarakom', name: 'Kumarakom', state_id: 'kerala', district: 'Kottayam', lat: 9.6175, lng: 76.4301, type: 'backwaters', desc: 'Cluster of mangrove islets on Vembanad Lake, home to Kumarakom Bird Sanctuary visited by migratory Siberian cranes, and luxury houseboats.' },
  { id: 'malappuram', name: 'Malappuram', state_id: 'kerala', district: 'Malappuram', lat: 11.0732, lng: 76.0740, type: 'city', desc: 'Cultural and historical center of Malabar holding Thirunavaya banks of Mamankam medieval festivals and ancient Kottakkal Arya Vaidya Sala.' },
  { id: 'munnar', name: 'Munnar', state_id: 'kerala', district: 'Idukki', lat: 10.0889, lng: 77.0595, type: 'hill_station', desc: 'Verdant hill station in the Western Ghats at 5,200 ft with emerald tea estates, Eravikulam National Park (endangered Nilgiri Tahr), and Anamudi peak.' },
  { id: 'palakkad', name: 'Palakkad', state_id: 'kerala', district: 'Palakkad', lat: 10.7867, lng: 76.6548, type: 'city', desc: 'Gateway to Kerala across the Palakkad Gap, featuring the granite-built 18th-century Palakkad Fort (Tipu\'s Fort), Malampuzha Dam, and Kalpathy agraharams.' },
  { id: 'pathanamthitta', name: 'Pathanamthitta', state_id: 'kerala', district: 'Pathanamthitta', lat: 9.2648, lng: 76.7870, type: 'town', desc: 'Pilgrim capital of Kerala on the Achankovil River, gateway to Sabarimala, Aranmula Parthasarathy Temple with metal mirrors, and Gavi eco-tourism.' },
  { id: 'sabrimala', name: 'Sabrimala', state_id: 'kerala', district: 'Pathanamthitta', lat: 9.4402, lng: 77.0819, type: 'pilgrimage_destination', desc: 'Sacred forested shrine of Lord Ayyappa perched atop Periyar Tiger Reserve hills, one of the largest annual pilgrimages in the world.' },
  { id: 'thiruvananthapuram', name: 'Thiruvananthapuram', state_id: 'kerala', district: 'Thiruvananthapuram', lat: 8.5241, lng: 76.9366, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Capital city holding the opulent Sree Padmanabhaswamy Temple, Kuthiramalika Palace Museum, Napier Museum, and Kovalam coastline.' },
  { id: 'thrissur', name: 'Thrissur', state_id: 'kerala', district: 'Thrissur', lat: 10.5276, lng: 76.2144, type: 'city', desc: 'Cultural Capital of Kerala famed for the spectacular Thrissur Pooram festival, circular Vadakkunnathan Temple, and Kerala Kalamandalam.' },
  { id: 'varkala', name: 'Varkala', state_id: 'kerala', district: 'Thiruvananthapuram', lat: 8.7379, lng: 76.7163, type: 'coastal', desc: 'Unique coastal destination where dramatic red laterite cliffs border the Arabian Sea, 2,000-year-old Janardhana Swamy Temple, and Papanasam beach.' },
  { id: 'wayanad', name: 'Wayanad', state_id: 'kerala', district: 'Wayanad', lat: 11.6854, lng: 76.1320, type: 'hill_station', desc: 'Mist-clad hill district featuring prehistoric petroglyphs at Edakkal Caves, Chembra Peak heart-shaped lake, Banasura Sagar dam, and spice groves.' },

  // Madhya Pradesh (15)
  { id: 'anuppur', name: 'Anuppur', state_id: 'madhya-pradesh', district: 'Anuppur', lat: 23.1000, lng: 81.6833, type: 'town', desc: 'Gateway to sacred Amarkantak, the origin of holy Narmada and Son rivers, Narmada Kund temples, and Kapildhara waterfall.' },
  { id: 'bhopal', name: 'Bhopal', state_id: 'madhya-pradesh', district: 'Bhopal', lat: 23.2599, lng: 77.4126, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'City of Lakes combining Begum architectural monuments (Taj-ul-Masajid, Shaukat Mahal), Bharat Bhavan arts center, and Upper Lake.' },
  { id: 'chanderi', name: 'Chanderi', state_id: 'madhya-pradesh', district: 'Ashoknagar', lat: 24.7118, lng: 78.1360, type: 'heritage_site', desc: 'Medieval Bundelkhand town dominated by a hilltop fort, Badal Mahal Gate, Koshak Mahal, and world-famous sheer Chanderi silk weaving.' },
  { id: 'chitrakoot-mp', name: 'Chitrakoot', state_id: 'madhya-pradesh', district: 'Satna', lat: 25.1764, lng: 80.8659, type: 'pilgrimage_destination', desc: 'Sacred tranquil forest town where Lord Rama spent 11 years of exile, featuring Ramghat on Mandakini river, Kamadgiri, and Gupt Godavari caves.' },
  { id: 'datia', name: 'Datia', state_id: 'madhya-pradesh', district: 'Datia', lat: 25.6667, lng: 78.4667, type: 'heritage_site', desc: 'Ancient town boasting the 7-storey stone Bir Singh Palace (marvel of Rajput-Mughal architecture built without wood or iron) and Pitambara Peeth.' },
  { id: 'gwalior', name: 'Gwalior', state_id: 'madhya-pradesh', district: 'Gwalior', lat: 26.2183, lng: 78.1828, type: 'city', desc: 'Historic citadel city crowned by the impregnable Gwalior Fort (Pearl in the necklace of forts), Man Singh Palace tiles, and Scindia Jai Vilas Palace.' },
  { id: 'indore', name: 'Indore', state_id: 'madhya-pradesh', district: 'Indore', lat: 22.7196, lng: 75.8577, type: 'city', desc: 'India\'s cleanest city and Holkar royal capital holding 7-storey Rajwada Palace, glass temple Kanch Mandir, and Sarafa night street-food bazaar.' },
  { id: 'jabalpur', name: 'Jabalpur', state_id: 'madhya-pradesh', district: 'Jabalpur', lat: 23.1815, lng: 79.9864, type: 'city', desc: 'Cultural center on the Narmada featuring dramatic Marble Rocks canyon at Bhedaghat, roaring Dhuandhar waterfall, and Madan Mahal fort.' },
  { id: 'khajuraho', name: 'Khajuraho', state_id: 'madhya-pradesh', district: 'Chhatarpur', lat: 24.8318, lng: 79.9199, type: 'heritage_site', desc: 'UNESCO World Heritage complex of medieval Hindu and Jain temples renowned for nagara architectural beauty and exquisite sculptural art.' },
  { id: 'mandsaur', name: 'Mandsaur', state_id: 'madhya-pradesh', district: 'Mandsaur', lat: 24.0722, lng: 75.0683, type: 'city', desc: 'Historic Malwa city on the Shivna river famed for the unique eight-faced Pashupatinath Temple and 6th-century Yasodharman victory pillars.' },
  { id: 'morena', name: 'Morena', state_id: 'madhya-pradesh', district: 'Morena', lat: 26.5000, lng: 78.0000, type: 'heritage_site', desc: 'Chambal district holding the 64-yogini circular Chausath Yogini Temple at Mitawali (inspiration for Parliament House) and Bateshwar temple complex.' },
  { id: 'orchha', name: 'Orchha', state_id: 'madhya-pradesh', district: 'Niwari', lat: 25.3508, lng: 78.6416, type: 'heritage_site', desc: 'Medieval Bundela kingdom on the boulder-strewn Betwa river featuring Jahangir Mahal palace, Ram Raja Temple (where Rama is king), and chhatris.' },
  { id: 'pachmarhi', name: 'Pachmarhi', state_id: 'madhya-pradesh', district: 'Narmadapuram', lat: 22.4674, lng: 78.4344, type: 'hill_station', desc: 'Queen of Satpura, only hill station in MP, featuring Pandava Caves, Bee Falls, Dhoopgarh sunset peak (highest in MP), and sal forests.' },
  { id: 'sanchi', name: 'Sanchi', state_id: 'madhya-pradesh', district: 'Raisen', lat: 23.4795, lng: 77.7397, type: 'heritage_site', desc: 'UNESCO World Heritage site holding the 3rd-century BCE Great Stupa commissioned by Emperor Ashoka with four exquisitely carved stone torana gates.' },
  { id: 'ujjain', name: 'Ujjain', state_id: 'madhya-pradesh', district: 'Ujjain', lat: 23.1765, lng: 75.7885, type: 'pilgrimage_destination', desc: 'Ancient holy city on the Shipra River, hosting Simhastha Kumbh Mela, Mahakaleshwar Jyotirlinga temple, and Jantar Mantar observatory.' },

  // Maharashtra (11)
  { id: 'amravati', name: 'Amravati', state_id: 'maharashtra', district: 'Amravati', lat: 20.9320, lng: 77.7523, type: 'city', desc: 'Cultural capital of Vidarbha featuring the historic Ambadevi and Ekvira Devi temples and gateway to Melghat Tiger Reserve and Chikhaldara hills.' },
  { id: 'chhatrapati-sambhaji-nagar', name: 'Chhatrapati Sambhaji Nagar', state_id: 'maharashtra', district: 'Chhatrapati Sambhajinagar', lat: 19.8762, lng: 75.3433, type: 'heritage_site', desc: 'Tourism Capital of Maharashtra, gateway to UNESCO World Heritage Ajanta & Ellora cave complexes, Daulatabad Fort, and Bibi Ka Maqbara.' },
  { id: 'igatpuri', name: 'Igatpuri', state_id: 'maharashtra', district: 'Nashik', lat: 19.6967, lng: 73.5594, type: 'hill_station', desc: 'Western Ghats hill station enveloped in monsoon mists, home to Vipassana International Academy (Dhamma Giri), Tringalwadi Fort, and waterfalls.' },
  { id: 'jalgaon', name: 'Jalgaon', state_id: 'maharashtra', district: 'Jalgaon', lat: 21.0077, lng: 75.5626, type: 'city', desc: 'Banana City and Golden City of Maharashtra, railhead gateway to the 30 rock-cut Buddhist caves of Ajanta (UNESCO).' },
  { id: 'kolhapur', name: 'Kolhapur', state_id: 'maharashtra', district: 'Kolhapur', lat: 16.7050, lng: 74.2433, type: 'city', desc: 'Historic Maratha kingdom on the Panchganga river famed for Mahalakshmi Ambabai Temple, New Palace museum, wrestling (Kushti), and leather chappals.' },
  { id: 'mahabaleshwar', name: 'Mahabaleshwar', state_id: 'maharashtra', district: 'Satara', lat: 17.9237, lng: 73.6586, type: 'hill_station', desc: 'Highest hill station in the Western Ghats, strawberry capital of India, featuring Arthur\'s Seat cliff, Venna Lake, and Old Mahabaleshwar temple.' },
  { id: 'mumbai', name: 'Mumbai', state_id: 'maharashtra', district: 'Mumbai City / Mumbai Suburban', lat: 18.9431, lng: 72.8230, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Financial capital of India featuring UNESCO Victorian Gothic Ensembles, Chhatrapati Shivaji Maharaj Terminus, Elephanta Caves, and Gateway of India.' },
  { id: 'nagpur', name: 'Nagpur', state_id: 'maharashtra', district: 'Nagpur', lat: 21.1458, lng: 79.0882, capital_status: 'winter_capital', type: 'city', desc: 'Winter Capital of Maharashtra, Orange City, geographic Zero Mile Stone of India, Deekshabhoomi stupa, and tiger gateway to central India.' },
  { id: 'nashik', name: 'Nashik', state_id: 'maharashtra', district: 'Nashik', lat: 19.9975, lng: 73.7898, type: 'city', desc: 'Wine Capital of India on the Godavari river, host of Kumbh Mela, holding Trimbakeshwar Jyotirlinga, Panchavati, and Pandavleni Buddhist caves.' },
  { id: 'pune', name: 'Pune', state_id: 'maharashtra', district: 'Pune', lat: 18.5204, lng: 73.8567, type: 'city', desc: 'Oxford of the East and Maratha cultural capital, featuring Shaniwar Wada peshwa palace, Sinhagad hilltop fort, Aga Khan Palace, and Osho Ashram.' },
  { id: 'satara', name: 'Satara', state_id: 'maharashtra', district: 'Satara', lat: 17.6805, lng: 73.9935, type: 'heritage_site', desc: 'Historic capital of Chhatrapati Shahu Maharaj guarded by Ajinkyatara fort, gateway to UNESCO World Heritage Kaas Valley of Flowers and Thoseghar waterfalls.' },

  // Manipur (1)
  { id: 'imphal', name: 'Imphal', state_id: 'manipur', district: 'Imphal West / Imphal East', lat: 24.8170, lng: 93.9368, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Capital city holding ancient Kangla Fort, Ima Keithel (world\'s only women-run market), Shri Govindaji Temple, and gateway to Loktak Lake.' },

  // Meghalaya (2)
  { id: 'cherrapunjee', name: 'Cherrapunjee', state_id: 'meghalaya', district: 'East Khasi Hills', lat: 25.2986, lng: 91.7323, type: 'hill_station', desc: 'Sohra — wettest place on Earth featuring dramatic Nohkalikai waterfall, Mawsmai limestone cave, and bio-engineered double-decker living root bridges.' },
  { id: 'shillong', name: 'Shillong', state_id: 'meghalaya', district: 'East Khasi Hills', lat: 25.5788, lng: 91.8933, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Scotland of the East, pine-covered hill capital featuring Ward\'s Lake, Elephant Falls, Don Bosco Museum of Indigenous Cultures, and Shillong Peak.' },

  // Mizoram (4)
  { id: 'aizawl', name: 'Aizawl', state_id: 'mizoram', district: 'Aizawl', lat: 23.7271, lng: 92.7176, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Spectacular ridge-top capital at 3,700 feet, featuring Solomon\'s Temple, Mizoram State Museum, Durtlang Hills, and vibrant Bara Bazar handloom market.' },
  { id: 'champhai', name: 'Champhai', state_id: 'mizoram', district: 'Champhai', lat: 23.4735, lng: 93.3275, type: 'town', desc: 'Rice Bowl of Mizoram on the Myanmar border with verdant valley views, ancient monoliths at Mungmang, and heart-shaped Rih Dil lake nearby.' },
  { id: 'lunglei', name: 'Lunglei', state_id: 'mizoram', district: 'Lunglei', lat: 22.8878, lng: 92.7428, type: 'town', desc: 'Second largest city of Mizoram named after a stone bridge landmark on the Nghasih stream, offering views of Tlawng river valley and Khawnglung wildlife.' },
  { id: 'serchhip', name: 'Serchhip', state_id: 'mizoram', district: 'Serchhip', lat: 23.3105, lng: 92.8504, type: 'town', desc: 'Central district featuring highest literacy, spectacular Vantawng Falls (highest waterfall in Mizoram), and tranquil Thenzawl handloom village.' },

  // Nagaland (3)
  { id: 'dimapur', name: 'Dimapur', state_id: 'nagaland', district: 'Dimapur', lat: 25.9094, lng: 93.7266, type: 'city', desc: 'Commercial gateway of Nagaland holding ancient 10th-century Kachari Kingdom mushroom-domed monolith ruins, Diezephe craft village, and Triple Falls.' },
  { id: 'kohima', name: 'Kohima', state_id: 'nagaland', district: 'Kohima', lat: 25.6751, lng: 94.1086, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Hilltop capital holding historic World War II Kohima War Cemetery (Battle of the Tennis Court), Kisama Heritage Village (Hornbill Festival), and Dzukou Valley.' },
  { id: 'mokokchung', name: 'Mokokchung', state_id: 'nagaland', district: 'Mokokchung', lat: 26.3245, lng: 94.5167, type: 'town', desc: 'Cultural and intellectual heart of the Ao Naga tribe, scenic hill ridges, Longkhum eagle-view village, and traditional Moatsu festival.' },

  // Odisha (5)
  { id: 'bhubaneswar', name: 'Bhubaneswar', state_id: 'odisha', district: 'Khordha', lat: 20.2961, lng: 85.8245, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Temple City of India boasting 500+ sandstone Kalinga temples (Lingaraj, Mukteshvara, Rajarani), 1st-century BCE Udayagiri & Khandagiri Jain caves, and Dhauli.' },
  { id: 'cuttack', name: 'Cuttack', state_id: 'odisha', district: 'Cuttack', lat: 20.4625, lng: 85.8830, type: 'city', desc: 'Millennium City on the Mahanadi-Kathajodi delta, famed for the medieval 14th-century Barabati Fort, silver filigree Tarakasi crafts, and Bali Yatra.' },
  { id: 'koraput', name: 'Koraput', state_id: 'odisha', district: 'Koraput', lat: 18.8135, lng: 82.7118, type: 'town', desc: 'Eastern Ghats tribal heartland famed for Jagannath Sabara Srikhetra temple, Duduma waterfall, Gupteswar limestone cave, and coffee plantations.' },
  { id: 'mayurbhanj', name: 'Mayurbhanj', state_id: 'odisha', district: 'Mayurbhanj', lat: 21.9333, lng: 86.7333, type: 'town', desc: 'Royal district home to UNESCO Similipal Biosphere Reserve (tigers and waterfalls), Baripada royal palace, and acrobatic Mayurbhanj Chhau martial dance.' },
  { id: 'puri', name: 'Puri', state_id: 'odisha', district: 'Puri', lat: 19.8135, lng: 85.8312, type: 'pilgrimage_destination', desc: 'Sacred coastal Char Dham holy city centered on the 12th-century Jagannath Temple (Rath Yatra), Golden Beach (Blue Flag), and nearby Konark Sun Temple (UNESCO).' },

  // Punjab (12)
  { id: 'amritsar', name: 'Amritsar', state_id: 'punjab', district: 'Amritsar', lat: 31.6340, lng: 74.8723, type: 'city', desc: 'Spiritual and cultural capital of Sikhism holding the gold-gilded Sri Harmandir Sahib (Golden Temple), Jallianwala Bagh national memorial, and Wagah Border.' },
  { id: 'fatehgarh-sahib', name: 'Fatehgarh Sahib', state_id: 'punjab', district: 'Fatehgarh Sahib', lat: 30.6483, lng: 76.3986, type: 'pilgrimage_destination', desc: 'Hallowed Sikh pilgrimage town marking the martyrdom site of Sahibzada Zorawar Singh and Fateh Singh, holding Gurdwara Fatehgarh Sahib.' },
  { id: 'fazilka', name: 'Fazilka', state_id: 'punjab', district: 'Fazilka', lat: 30.4038, lng: 74.0255, type: 'town', desc: 'Border heritage town known as Bangla on the Sutlej, historic Asafwala War Memorial, Sadiqi border retreat ceremony, and Toshi footwear.' },
  { id: 'firozepur', name: 'Firozepur', state_id: 'punjab', district: 'Firozepur', lat: 30.9237, lng: 74.6118, type: 'city', desc: 'Historic border fortress city along the Sutlej holding the National Martyrs Memorial at Hussainiwala (Bhagat Singh, Rajguru, Sukhdev) and Saragarhi memorial.' },
  { id: 'gurdaspur', name: 'Gurdaspur', state_id: 'punjab', district: 'Gurdaspur', lat: 32.0419, lng: 75.4053, type: 'city', desc: 'Majha heritage district holding Dera Baba Nanak (gateway to Kartarpur Corridor), historic Takht-e-Akbari coronation platform of Akbar at Kalanaur.' },
  { id: 'jalandhar', name: 'Jalandhar', state_id: 'punjab', district: 'Jalandhar', lat: 31.3260, lng: 75.5762, type: 'city', desc: 'Ancient Doaba city mentioned in Mahabharata, sports goods manufacturing capital of India, Devi Talab Mandir, and Wonderland theme park.' },
  { id: 'kapurthala', name: 'Kapurthala', state_id: 'punjab', district: 'Kapurthala', lat: 31.3800, lng: 75.3800, type: 'city', desc: 'Paris of Punjab celebrated for Indo-French architecture in Jagatjit Palace (modeled on Versailles), Moorish Mosque, Elysee Palace, and Shalimar Gardens.' },
  { id: 'ludhiana', name: 'Ludhiana', state_id: 'punjab', district: 'Ludhiana', lat: 30.9010, lng: 75.8573, type: 'city', desc: 'Manchester of India on the Sutlej river featuring Maharaja Ranjit Singh War Museum, historic Lodhi Fort, and Punjab Agricultural University.' },
  { id: 'pathankot', name: 'Pathankot', state_id: 'punjab', district: 'Pathankot', lat: 32.2684, lng: 75.6499, type: 'city', desc: 'Strategic gateway city where Punjab, J&K and Himachal meet, home to 9th-century Shahpurkandi Fort on the Ravi, Nurpur Fort, and Mukteshwar temple caves.' },
  { id: 'patiala', name: 'Patiala', state_id: 'punjab', district: 'Patiala', lat: 30.3398, lng: 76.3869, type: 'city', desc: 'Royal heritage city famed for the colossal Sikh-Mughal Qila Mubarak fort complex, Sheesh Mahal mirror palace, Baradari Gardens, and Patiala Shahi turban.' },
  { id: 'rupnagar', name: 'Rupnagar', state_id: 'punjab', district: 'Rupnagar', lat: 30.9664, lng: 76.5331, type: 'heritage_site', desc: 'Historic Ropar holding prominent Harappan Indus Valley Civilization archaeological excavated mound and museum, wetland sanctuary, and canals.' },
  { id: 'sas-nagar', name: 'SAS Nagar', state_id: 'punjab', district: 'SAS Nagar', lat: 30.7046, lng: 76.7179, type: 'city', desc: 'Mohali — modern commercial and sports metropolis holding Fateh Burj (tallest minar in India celebrating victory of Baba Banda Singh Bahadur) and PCA Stadium.' },

  // Rajasthan (15)
  { id: 'ajmer', name: 'Ajmer', state_id: 'rajasthan', district: 'Ajmer', lat: 26.4499, lng: 74.6399, type: 'pilgrimage_destination', desc: 'Spiritual oasis in the Aravalli hills holding the world-renowned Sufi shrine Dargah Sharif of Khwaja Moinuddin Chishti, Adhai Din Ka Jhonpra, and Taragarh Fort.' },
  { id: 'alwar', name: 'Alwar', state_id: 'rajasthan', district: 'Alwar', lat: 27.5530, lng: 76.6346, type: 'heritage_site', desc: 'Gateway city of Rajasthan crowned by Bala Quila fort, marble Moosi Maharani ki Chhatri, City Palace, and gateway to Sariska Tiger Reserve and Bhangarh.' },
  { id: 'banswara', name: 'Banswara', state_id: 'rajasthan', district: 'Banswara', lat: 23.5461, lng: 74.4422, type: 'city', desc: 'City of Hundred Islands set amidst the Mahi river archipelago, green southern Aravalli hills, Anand Sagar Lake, and Arthuna medieval temple ruins.' },
  { id: 'bharatpur', name: 'Bharatpur', state_id: 'rajasthan', district: 'Bharatpur', lat: 27.2152, lng: 77.5030, type: 'city', desc: 'Eastern gateway of Rajasthan famed for Keoladeo National Park (UNESCO bird paradise), Lohagarh Fort (iron fort that withstood British sieges), and Deeg Water Palaces.' },
  { id: 'bikaner', name: 'Bikaner', state_id: 'rajasthan', district: 'Bikaner', lat: 28.0229, lng: 73.3119, type: 'desert', desc: 'Desert citadel featuring the invincible red sandstone Junagarh Fort, Lalgarh Palace, Karni Mata rat temple at Deshnoke, and camel breeding center.' },
  { id: 'bundi', name: 'Bundi', state_id: 'rajasthan', district: 'Bundi', lat: 25.4415, lng: 75.6441, type: 'heritage_site', desc: 'Untouched Rajput town celebrated for the dramatic cliff-hugging Taragarh Fort, frescoed Bundi murals in Chitrashala, and 50+ ornate stepwells like Raniji ki Baori.' },
  { id: 'chittorgarh', name: 'Chittorgarh', state_id: 'rajasthan', district: 'Chittorgarh', lat: 24.8887, lng: 74.6269, type: 'heritage_site', desc: 'Symbol of Rajput chivalry, largest fort in India (UNESCO), holding Vijay Stambha (Tower of Victory), Kirti Stambha, and Queen Padmini\'s Palace.' },
  { id: 'dausa', name: 'Dausa', state_id: 'rajasthan', district: 'Dausa', lat: 26.8928, lng: 76.3375, type: 'heritage_site', desc: 'Historic district home to the architectural wonder Chand Baori stepwell at Abhaneri (3,500 geometric steps), Harshat Mata temple, and Mehandipur Balaji.' },
  { id: 'dholpur', name: 'Dholpur', state_id: 'rajasthan', district: 'Dholpur', lat: 26.7025, lng: 77.8933, type: 'heritage_site', desc: 'Red sandstone city on the Chambal river holding the historic Machkund sacred water tank, Shergarh Fort, royal chhatris, and National Chambal Sanctuary.' },
  { id: 'jaipur', name: 'Jaipur', state_id: 'rajasthan', district: 'Jaipur', lat: 26.9124, lng: 75.7873, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'The Pink City (UNESCO World Heritage), holding the honeycombed Hawa Mahal, Amer Fort hill complex, City Palace, and Jantar Mantar astronomical observatory.' },
  { id: 'jaisalmer', name: 'Jaisalmer', state_id: 'rajasthan', district: 'Jaisalmer', lat: 26.9157, lng: 70.9083, type: 'desert', desc: 'The Golden City rising out of the Thar Desert, holding the living Sonar Qila (UNESCO Golden Fort), Patwon ki Haveli, Gadisar Lake, and Sam sand dunes.' },
  { id: 'jodhpur', name: 'Jodhpur', state_id: 'rajasthan', district: 'Jodhpur', lat: 26.2389, lng: 73.0243, type: 'city', desc: 'The Blue City crowned by the colossal Mehrangarh Fort rising 400 feet above the city, Umaid Bhawan Art Deco palace, and marble Jaswant Thada memorial.' },
  { id: 'kota', name: 'Kota', state_id: 'rajasthan', district: 'Kota', lat: 25.2138, lng: 75.8648, type: 'city', desc: 'Industrial and educational hub on the Chambal river, holding the Garh City Palace with Rajput miniature frescoes, Kishore Sagar Jagmandir, and Seven Wonders Park.' },
  { id: 'mount-abu', name: 'Mount Abu', state_id: 'rajasthan', district: 'Sirohi', lat: 24.5926, lng: 72.7156, type: 'hill_station', desc: 'Only hill station in Rajasthan at 4,000 ft in the Aravallis, home to the exquisite 11th-13th century Dilwara Jain marble temples, Nakki Lake, and Guru Shikhar peak.' },
  { id: 'udaipur', name: 'Udaipur', state_id: 'rajasthan', district: 'Udaipur', lat: 24.5854, lng: 73.7125, type: 'city', desc: 'City of Lakes and Venice of the East, holding the sprawling City Palace complex on Lake Pichola, island Lake Palace (Taj), Jag Mandir, and Saheliyon-ki-Bari.' },

  // Sikkim (3)
  { id: 'gangtok', name: 'Gangtok', state_id: 'sikkim', district: 'East Sikkim', lat: 27.3314, lng: 88.6138, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Scenic mountain capital perched at 5,400 ft overlooking Mt. Khangchendzonga, featuring Enchey Monastery, Namgyal Institute of Tibetology, and MG Marg.' },
  { id: 'mangan', name: 'Mangan', state_id: 'sikkim', district: 'North Sikkim', lat: 27.5039, lng: 88.5297, type: 'town', desc: 'Cardamom capital and gateway to high-altitude North Sikkim, alpine Yumthang Valley of Flowers, Gurudongmar glacial lake, and hot springs.' },
  { id: 'pelling', name: 'Pelling', state_id: 'sikkim', district: 'West Sikkim', lat: 27.3180, lng: 88.2383, type: 'town', desc: 'Hill retreat offering closest views of Khangchendzonga, holding 1705 Pemayangtse Monastery, Rabdentse royal ruins, and Singshore suspension bridge.' },

  // Tamil Nadu (10)
  { id: 'chennai', name: 'Chennai', state_id: 'tamil-nadu', district: 'Chennai', lat: 13.0827, lng: 80.2707, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Cultural gateway of South India, featuring Marina Beach, 7th-century Kapaleeshwarar temple, British Fort St. George, and San Thome Basilica.' },
  { id: 'coimbatore', name: 'Coimbatore', state_id: 'tamil-nadu', district: 'Coimbatore', lat: 11.0168, lng: 76.9558, type: 'city', desc: 'Manchester of South India at the foothills of Nilgiris, home to the colossal Adiyogi Shiva bust statue, Marudhamalai temple, and textile museums.' },
  { id: 'kanchipuram', name: 'Kanchipuram', state_id: 'tamil-nadu', district: 'Kanchipuram', lat: 12.8342, lng: 79.7036, type: 'heritage_site', desc: 'City of Thousand Temples and world-famous Kanchipuram mulberry silk sarees, holding Ekambareswarar, Kailasanathar, and Varadharaja Perumal temples.' },
  { id: 'kanniyakumari', name: 'Kanniyakumari', state_id: 'tamil-nadu', district: 'Kanniyakumari', lat: 8.0883, lng: 77.5385, type: 'coastal', desc: 'Southernmost tip of mainland India where Arabian Sea, Indian Ocean and Bay of Bengal converge, with Vivekananda Rock Memorial and Thiruvalluvar Statue.' },
  { id: 'madurai', name: 'Madurai', state_id: 'tamil-nadu', district: 'Madurai', lat: 9.9252, lng: 78.1198, type: 'pilgrimage_destination', desc: 'One of the oldest continuously inhabited cities in the world, soul of Tamil culture centered on the towering multi-sculptured gopurams of Meenakshi Amman Temple.' },
  { id: 'mamallapuram', name: 'Mamallapuram', state_id: 'tamil-nadu', district: 'Chengalpattu', lat: 12.6269, lng: 80.1927, type: 'heritage_site', desc: 'UNESCO World Heritage 7th-century Pallava coastal monuments including the Shore Temple, monolithic Pancha Rathas, and Descent of the Ganges rock relief.' },
  { id: 'ooty', name: 'Ooty', state_id: 'tamil-nadu', district: 'Nilgiris', lat: 11.4102, lng: 76.6950, type: 'hill_station', desc: 'Queen of Hill Stations (Udhagamandalam) at 7,350 ft in the Nilgiris, terminus of UNESCO Nilgiri Mountain Toy Train, Botanical Gardens, and tea hills.' },
  { id: 'rameswaram', name: 'Rameswaram', state_id: 'tamil-nadu', district: 'Ramanathapuram', lat: 9.2876, lng: 79.3129, type: 'pilgrimage_destination', desc: 'Sacred Char Dham island temple town connected by Pamban Bridge, home to Ramanathaswamy Temple with world\'s longest pillared corridor and Dhanushkodi ghost town.' },
  { id: 'thanjavur', name: 'Thanjavur', state_id: 'tamil-nadu', district: 'Thanjavur', lat: 10.7870, lng: 79.1378, type: 'heritage_site', desc: 'Rice Bowl of Tamil Nadu and Chola imperial capital holding UNESCO World Heritage Brihadisvara Temple (Big Temple), Maratha Palace, and Tanjore paintings.' },
  { id: 'tiruchirappalli', name: 'Tiruchirappalli', state_id: 'tamil-nadu', district: 'Tiruchirappalli', lat: 10.7905, lng: 78.7047, type: 'city', desc: 'Historic Cauvery river city dominated by the dramatic 83-meter high Rockfort Ucchi Pillayar Temple and colossal Ranganathaswamy Temple complex at Srirangam.' },

  // Telangana (5)
  { id: 'bhongir', name: 'Bhongir', state_id: 'telangana', district: 'Yadadri Bhuvanagiri', lat: 17.5108, lng: 78.8899, type: 'heritage_site', desc: 'Historic town famed for the monolithic egg-shaped Bhongir Fort built by Western Chalukya ruler Tribhuvanamalla Vikramaditya VI on a single isolated rock.' },
  { id: 'hyderabad', name: 'Hyderabad', state_id: 'telangana', district: 'Hyderabad', lat: 17.3850, lng: 78.4867, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'City of Pearls and Nizams, holding the 1591 Charminar, massive Golconda Fort with acoustic engineering, Qutb Shahi Tombs, and Salar Jung Museum.' },
  { id: 'karimnagar', name: 'Karimnagar', state_id: 'telangana', district: 'Karimnagar', lat: 18.4386, lng: 79.1288, type: 'city', desc: 'Historic town on the Manair river famed for Silver Filigree (Tarkashi) delicate jewelry, Elgandal hill fortress, and Lower Manair Dam.' },
  { id: 'khammam', name: 'Khammam', state_id: 'telangana', district: 'Khammam', lat: 17.2473, lng: 80.1514, type: 'city', desc: 'Historic town featuring the 10th-century Kakatiya stone Khammam Fort perched on Stambhadri hill, Palair lake, and gateway to Bhadrachalam temple.' },
  { id: 'warangal', name: 'Warangal', state_id: 'telangana', district: 'Hanamkonda / Warangal', lat: 17.9689, lng: 79.5941, type: 'heritage_site', desc: 'Historic Kakatiya capital holding the 12th-century Thousand Pillar Temple, Warangal Fort stone gateways (Kakatiya Kala Thoranam), and UNESCO Ramappa Temple.' },

  // Tripura (2)
  { id: 'agartala', name: 'Agartala', state_id: 'tripura', district: 'West Tripura', lat: 23.8315, lng: 91.2868, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'Royal capital city holding neoclassical white marble Ujjayanta Palace, water palace Neermahal on Rudrasagar Lake, and Tripura Sundari Shakti Peetha.' },
  { id: 'unakoti', name: 'Unakoti', state_id: 'tripura', district: 'Unakoti', lat: 24.3214, lng: 92.0169, type: 'heritage_site', desc: 'Ancient Shaivite pilgrimage wonder in forested hills holding massive 7th-9th century rock-carved reliefs (including 30-foot Shiva Unakotiswara Kal Bhairava).' },

  // Uttar Pradesh (10)
  { id: 'agra', name: 'Agra', state_id: 'uttar-pradesh', district: 'Agra', lat: 27.1767, lng: 78.0081, type: 'city', desc: 'Mughal imperial capital holding the iconic white marble Taj Mahal (UNESCO), Agra Fort, Itmad-ud-Daulah (Baby Taj), and nearby Fatehpur Sikri (UNESCO).' },
  { id: 'ayodhya', name: 'Ayodhya', state_id: 'uttar-pradesh', district: 'Ayodhya', lat: 26.7922, lng: 82.1998, type: 'pilgrimage_destination', desc: 'Sacred birthplace of Lord Rama on the holy Saryu river, holding the grand Ram Mandir, Hanuman Garhi fortress temple, and ancient Ram Ki Paidi ghats.' },
  { id: 'bareilly', name: 'Bareilly', state_id: 'uttar-pradesh', district: 'Bareilly', lat: 28.3670, lng: 79.4304, type: 'city', desc: 'Historic Rohilkhand trade city celebrated for Zari-Zardozi embroidery, cane furniture, seven ancient Shiva Nath temples (Alakhnath, Trivatinath), and Jhumka.' },
  { id: 'chitrakoot-up', name: 'Chitrakoot', state_id: 'uttar-pradesh', district: 'Chitrakoot', lat: 25.2064, lng: 80.8931, type: 'pilgrimage_destination', desc: 'Sacred pilgrim town straddling the Mandakini river, holding Bharat Milap shrine, Hanuman Dhara spring temple on a cliff, and Sphatik Shila rock footprints.' },
  { id: 'jhansi', name: 'Jhansi', state_id: 'uttar-pradesh', district: 'Jhansi', lat: 25.4484, lng: 78.5685, type: 'heritage_site', desc: 'Gateway to Bundelkhand and seat of legendary 1857 warrior queen Rani Lakshmibai, holding the formidable granite Jhansi Fort and Government Museum.' },
  { id: 'kanpur', name: 'Kanpur', state_id: 'uttar-pradesh', district: 'Kanpur Nagar', lat: 26.4499, lng: 80.3319, type: 'city', desc: 'Major industrial and historical city on the Ganges holding 5th-century Gupta brick temple at Bhitargaon, Bithoor sacred ghats of Maharishi Valmiki, and Allen Forest Zoo.' },
  { id: 'lucknow', name: 'Lucknow', state_id: 'uttar-pradesh', district: 'Lucknow', lat: 26.8467, lng: 80.9462, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'City of Nawabs famed for refined Tehzeeb culture, colossal gravity-defying arch of Bara Imambara (Bhulbhulaiya maze), Rumi Darwaza, and Chikankari embroidery.' },
  { id: 'mathura', name: 'Mathura', state_id: 'uttar-pradesh', district: 'Mathura', lat: 27.4924, lng: 77.6737, type: 'pilgrimage_destination', desc: 'Sacred birthplace of Lord Krishna on the Yamuna river, holding Shri Krishna Janmasthan temple, Vishram Ghat aarti, and neighboring sacred Vrindavan.' },
  { id: 'prayagraj', name: 'Prayagraj', state_id: 'uttar-pradesh', district: 'Prayagraj', lat: 25.4358, lng: 81.8463, type: 'pilgrimage_destination', desc: 'Triveni Sangam sacred confluence of Ganga, Yamuna, and mythical Saraswati, site of the Maha Kumbh Mela, Mughal Allahabad Fort, and Anand Bhavan.' },
  { id: 'varanasi', name: 'Varanasi', state_id: 'uttar-pradesh', district: 'Varanasi', lat: 25.3176, lng: 82.9739, type: 'pilgrimage_destination', desc: 'Spiritual capital of India and one of the world\'s oldest living cities, featuring sacred Ganga river ghats, Kashi Vishwanath Jyotirlinga, and nearby Sarnath (UNESCO).' },

  // Uttarakhand (17)
  { id: 'almora', name: 'Almora', state_id: 'uttarakhand', district: 'Almora', lat: 29.5971, lng: 79.6591, type: 'hill_station', desc: 'Cultural capital of Kumaon perched on a horse-saddle ridge, holding Bright End Corner sunset point, Kasar Devi hippie trail, and Jageshwar temple valley.' },
  { id: 'badrinath', name: 'Badrinath', state_id: 'uttarakhand', district: 'Chamoli', lat: 30.7433, lng: 79.4938, type: 'pilgrimage_destination', desc: 'Premier Himalayan Char Dham holy shrine of Lord Vishnu on the Alaknanda River, framed by Nar and Narayana mountain ranges, Tapt Kund, and Mana village.' },
  { id: 'berinag', name: 'Berinag', state_id: 'uttarakhand', district: 'Pithoragarh', lat: 29.8000, lng: 80.0500, type: 'town', desc: 'Tranquil Kumaon town renowned for tea gardens, serpent temples (Nag Devta), and panoramic vistas of the snow-clad Panchachuli and Nanda Devi peaks.' },
  { id: 'bhimtal', name: 'Bhimtal', state_id: 'uttarakhand', district: 'Nainital', lat: 29.3500, lng: 79.5667, type: 'town', desc: 'Scenic lake resort town centered on a picturesque lake with an island aquarium, Victorian dam, and 17th-century Bhimeshwar Mahadev temple.' },
  { id: 'chamoli', name: 'Chamoli', state_id: 'uttarakhand', district: 'Chamoli', lat: 30.4000, lng: 79.3333, type: 'town', desc: 'Himalayan district gateway to UNESCO Valley of Flowers, Hemkund Sahib high-altitude lake, Badrinath, and cradle of the historic Chipko forest movement.' },
  { id: 'dehradun', name: 'Dehradun', state_id: 'uttarakhand', district: 'Dehradun', lat: 30.3165, lng: 78.0322, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'State capital nestled in the Doon Valley, home to Forest Research Institute Greco-Roman architecture, Robber\'s Cave (Guchhupani), and Mindrolling Monastery.' },
  { id: 'gangotri', name: 'Gangotri', state_id: 'uttarakhand', district: 'Uttarkashi', lat: 30.9944, lng: 78.9398, type: 'pilgrimage_destination', desc: 'Sacred Char Dham high-altitude shrine of Goddess Ganga on the Bhagirathi river at 10,200 ft, gateway to Gaumukh glacier and Tapovan trekking routes.' },
  { id: 'haridwar', name: 'Haridwar', state_id: 'uttarakhand', district: 'Haridwar', lat: 29.9457, lng: 78.1642, type: 'pilgrimage_destination', desc: 'Gateway to the Gods where the Ganges leaves the Himalayas, famed for Har Ki Pauri ghat evening Ganga Aarti, Mansa Devi ropeway, and Kumbh Mela.' },
  { id: 'kausani', name: 'Kausani', state_id: 'uttarakhand', district: 'Bageshwar', lat: 29.8546, lng: 79.5969, type: 'hill_station', desc: 'Switzerland of India as called by Mahatma Gandhi, offering an uninterrupted 300-km panoramic view of Himalayan peaks (Trisul, Nanda Devi, Panchachuli).' },
  { id: 'kedarnath', name: 'Kedarnath', state_id: 'uttarakhand', district: 'Rudraprayag', lat: 30.7352, lng: 79.0669, type: 'pilgrimage_destination', desc: 'Most revered Himalayan Jyotirlinga shrine dedicated to Lord Shiva, resting at 11,755 ft near Mandakini river headwaters against the Kedarnath glacier peak.' },
  { id: 'lansdowne', name: 'Lansdowne', state_id: 'uttarakhand', district: 'Pauri Garhwal', lat: 29.8377, lng: 78.6872, type: 'hill_station', desc: 'Quiet cantonment hill station founded in 1887, headquarters of the Garhwal Rifles, surrounded by thick oak and blue pine woods, Bhulla Lake, and Tip-in-Top.' },
  { id: 'mussoorie', name: 'Mussoorie', state_id: 'uttarakhand', district: 'Dehradun', lat: 30.4598, lng: 78.0644, type: 'hill_station', desc: 'Queen of the Hills at 6,500 ft, featuring Mall Road promenade, Kempty Falls, Gun Hill cable car, Lal Tibba viewpoint, and colonial heritage estates.' },
  { id: 'nainital', name: 'Nainital', state_id: 'uttarakhand', district: 'Nainital', lat: 29.3919, lng: 79.4542, type: 'hill_station', desc: 'Famous lake district town nestled around the emerald eye-shaped Naini Lake, Naina Devi temple, Snow View cable car, and British Governor\'s Raj Bhavan.' },
  { id: 'new-tehri', name: 'New Tehri', state_id: 'uttarakhand', district: 'Tehri Garhwal', lat: 30.3789, lng: 78.4803, type: 'town', desc: 'Planned modern hill town overlooking Tehri Dam (tallest dam in India) and massive green reservoir lake offering water sports, boating, and scenic vistas.' },
  { id: 'pithoragarh', name: 'Pithoragarh', state_id: 'uttarakhand', district: 'Pithoragarh', lat: 29.5829, lng: 80.2182, type: 'town', desc: 'Little Kashmir in the Soar Valley, border district gateway to Kailash Mansarovar pilgrimage route, Chand-era Pithoragarh Fort, and alpine meadows.' },
  { id: 'rishikesh', name: 'Rishikesh', state_id: 'uttarakhand', district: 'Dehradun / Tehri Garhwal', lat: 30.0869, lng: 78.2676, type: 'pilgrimage_destination', desc: 'Yoga Capital of the World along the turquoise Ganges, famed for Lakshman Jhula, Ram Jhula, Beatles Ashram (Chaurasi Kutia), and whitewater rafting.' },
  { id: 'uttarkashi', name: 'Uttarkashi', state_id: 'uttarakhand', district: 'Uttarkashi', lat: 30.7268, lng: 78.4354, type: 'town', desc: 'Northern holy town on the Bhagirathi river, home to ancient Vishwanath Temple with brass trident, Nehru Institute of Mountaineering, and Gangotri base.' },

  // West Bengal (6)
  { id: 'darjeeling', name: 'Darjeeling', state_id: 'west-bengal', district: 'Darjeeling', lat: 27.0410, lng: 88.2663, type: 'hill_station', desc: 'Queen of the Hills holding the UNESCO World Heritage Darjeeling Himalayan Railway (Toy Train), Tiger Hill sunrise over Kanchenjunga, and tea gardens.' },
  { id: 'durgapur', name: 'Durgapur', state_id: 'west-bengal', district: 'Paschim Bardhaman', lat: 23.5204, lng: 87.3119, type: 'city', desc: 'Steel city on the Damodar River, planned by Joseph Allen Stein, featuring Durgapur Barrage, Troika Park, and gateway to terracotta temples of Bishnupur.' },
  { id: 'howrah', name: 'Howrah', state_id: 'west-bengal', district: 'Howrah', lat: 22.5958, lng: 88.2636, type: 'city', desc: 'Historic twin city to Kolkata on the Hooghly river, holding iconic cantilevered Howrah Bridge, Belur Math (Ramakrishna Mission), and Indian Botanical Garden (Great Banyan).' },
  { id: 'kalimpong', name: 'Kalimpong', state_id: 'west-bengal', district: 'Kalimpong', lat: 27.0667, lng: 88.4667, type: 'hill_station', desc: 'Quiet mountain ridge town in the eastern Himalayas renowned for Tibetan Buddhist monasteries (Zang Dhok Palri Phodang), flower nurseries, and Deolo Hill.' },
  { id: 'kolkata', name: 'Kolkata', state_id: 'west-bengal', district: 'Kolkata', lat: 22.5726, lng: 88.3639, is_capital: true, capital_status: 'state_capital', type: 'city', desc: 'City of Joy and cultural capital of India, featuring Victoria Memorial, Dakshineswar Kali Temple, Indian Museum, Park Street, and Durga Puja festival (UNESCO).' },
  { id: 'siliguri', name: 'Siliguri', state_id: 'west-bengal', district: 'Darjeeling / Jalpaiguri', lat: 26.7271, lng: 88.3953, type: 'city', desc: 'Strategic transportation hub in the chicken\'s neck corridor, gateway to Darjeeling, Sikkim, and Bhutan, featuring Salugara Buddhist Stupa and Mahananda sanctuary.' },

  // Andaman and Nicobar Islands (3)
  { id: 'mayabunder', name: 'Mayabunder', state_id: 'andaman-and-nicobar-islands', district: 'North and Middle Andaman', lat: 12.9250, lng: 92.9300, type: 'coastal', desc: 'Administrative town in Middle Andaman known for Karmatang beach turtle nesting ground, mangrove creeks, and Karen Burmese settler culture.' },
  { id: 'rangat', name: 'Rangat', state_id: 'andaman-and-nicobar-islands', district: 'North and Middle Andaman', lat: 12.5000, lng: 92.9000, type: 'town', desc: 'Eco-tourism destination in Middle Andaman boasting the Dhaninallah Mangrove Walkway (longest in India), Amkunj beach, and Cutbert Bay turtle haven.' },
  { id: 'sri-vijaya-puram', name: 'Sri Vijaya Puram', state_id: 'andaman-and-nicobar-islands', district: 'South Andaman', lat: 11.6234, lng: 92.7265, is_capital: true, capital_status: 'ut_capital', type: 'city', desc: 'Territory capital (formerly Port Blair) holding the National Memorial Cellular Jail, Netaji Subhash Chandra Bose Island (Ross Island), and coral beaches.' },

  // Chandigarh (1)
  { id: 'chandigarh', name: 'Chandigarh', state_id: 'chandigarh', district: 'Chandigarh', lat: 30.7333, lng: 76.7794, is_capital: true, capital_status: 'ut_capital', type: 'city', desc: 'The City Beautiful, planned by Le Corbusier, featuring the UNESCO World Heritage Capitol Complex, Nek Chand Rock Garden, and Sukhna Lake.' },

  // Dadra and Nagar Haveli and Daman and Diu (3)
  { id: 'daman', name: 'Daman', state_id: 'dadra-and-nagar-haveli-and-daman-and-diu', district: 'Daman', lat: 20.3974, lng: 72.8328, is_capital: true, capital_status: 'ut_capital', type: 'coastal', desc: 'Coastal Portuguese enclave on the Gulf of Khambhat featuring the 16th-century Moti Daman Fort, Church of Bom Jesus, and Devka beach.' },
  { id: 'diu', name: 'Diu', state_id: 'dadra-and-nagar-haveli-and-daman-and-diu', district: 'Diu', lat: 20.7144, lng: 70.9874, type: 'island', desc: 'Picturesque island citadel surrounded by sea waves, holding formidable sea-facing Diu Fort, St. Paul Church, Naida Caves, and Nagoa beach.' },
  { id: 'silvassa', name: 'Silvassa', state_id: 'dadra-and-nagar-haveli-and-daman-and-diu', district: 'Dadra and Nagar Haveli', lat: 20.2763, lng: 73.0083, type: 'city', desc: 'Capital of Dadra and Nagar Haveli, featuring Portuguese Church of Our Lady of Piety, Warli tribal cultural museum, and Madhuban dam reservoir.' },

  // Delhi (1)
  { id: 'delhi', name: 'Delhi', state_id: 'delhi', district: 'Central Delhi', lat: 28.6139, lng: 77.2090, is_capital: true, capital_status: 'ut_capital', type: 'city', desc: 'National Capital Territory of India featuring three UNESCO World Heritage monuments (Qutub Minar, Humayun\'s Tomb, Red Fort), India Gate, and Chandni Chowk.' },

  // Jammu and Kashmir (6)
  { id: 'anantnag', name: 'Anantnag', state_id: 'jammu-and-kashmir', district: 'Anantnag', lat: 33.7311, lng: 75.1522, type: 'city', desc: 'Commercial capital of South Kashmir known for mineral water springs, 8th-century Martand Sun Temple ruins, and gateway to Amarnath Cave.' },
  { id: 'gulmarg', name: 'Gulmarg', state_id: 'jammu-and-kashmir', district: 'Baramulla', lat: 34.0484, lng: 74.3805, type: 'hill_station', desc: 'Meadow of Flowers, premier winter ski resort of India, holding the world\'s second-highest operating cable car (Gulmarg Gondola to Apharwat peak at 13,780 ft).' },
  { id: 'jammu', name: 'Jammu', state_id: 'jammu-and-kashmir', district: 'Jammu', lat: 32.7266, lng: 74.8570, capital_status: 'winter_capital', type: 'city', desc: 'City of Temples and winter capital on the Tawi River, holding historic Bahu Fort, Raghunath Temple, Amar Mahal palace museum, and gateway to Vaishno Devi.' },
  { id: 'pahalgam', name: 'Pahalgam', state_id: 'jammu-and-kashmir', district: 'Anantnag', lat: 34.0161, lng: 75.3150, type: 'hill_station', desc: 'Valley of the Shepherds on the Lidder River, starting point for the annual Amarnath Yatra, featuring Betaab Valley, Aru Valley, and Baisaran meadow.' },
  { id: 'patnitop', name: 'Patnitop', state_id: 'jammu-and-kashmir', district: 'Udhampur', lat: 33.0844, lng: 75.3283, type: 'hill_station', desc: 'Picturesque pine-forested plateau at 6,640 ft along the Jammu-Srinagar highway, Skyview cable car ropeway, Sanasar Lake, and Nag Temple.' },
  { id: 'srinagar', name: 'Srinagar', state_id: 'jammu-and-kashmir', district: 'Srinagar', lat: 34.0837, lng: 74.7973, is_capital: true, capital_status: 'summer_capital', type: 'city', desc: 'Summer capital situated in the heart of Kashmir Valley, world-famous for Dal Lake houseboats and shikaras, Mughal Pleasure Gardens, and wooden Jama Masjid.' },

  // Ladakh (2)
  { id: 'kargil', name: 'Kargil', state_id: 'ladakh', district: 'Kargil', lat: 34.5539, lng: 76.1349, type: 'town', desc: 'Historic transit city on the Suru river, holding the Kargil War Memorial at Dras, ancient Rock-cut Maitreya Buddha at Mulbekh, and gateway to Zanskar.' },
  { id: 'leh', name: 'Leh', state_id: 'ladakh', district: 'Leh', lat: 34.1526, lng: 77.5771, is_capital: true, capital_status: 'ut_capital', type: 'city', desc: 'Capital of Ladakh at 11,500 ft, featuring the 9-storey 17th-century Leh Palace, white Shanti Stupa, Hemis & Thiksey monasteries, and Khardung La pass.' },

  // Lakshadweep (1)
  { id: 'kavaratti', name: 'Kavaratti', state_id: 'lakshadweep', district: 'Lakshadweep', lat: 10.5669, lng: 72.6420, is_capital: true, capital_status: 'ut_capital', type: 'island', desc: 'Capital of Lakshadweep territory, an idyllic coral atoll with crystal-clear turquoise lagoons, marine aquarium, and 17th-century carved wooden Ujra Mosque.' },

  // Puducherry (1)
  { id: 'puducherry', name: 'Puducherry', state_id: 'puducherry', district: 'Puducherry', lat: 11.9416, lng: 79.8083, is_capital: true, capital_status: 'ut_capital', type: 'coastal', desc: 'French Riviera of the East, famed for French Quarter (White Town) colonial architecture, Sri Aurobindo Ashram, Promenade Beach, and experimental township Auroville.' }
];

console.log(`Successfully verified and compiled ${CITIES_DATA.length} Cities across all 36 States/UTs.`);
