import fs from 'node:fs';
import path from 'node:path';

const dataDir = path.join(process.cwd(), 'data');

const nagalandData = {
  "dataset": "Nagaland Tourist Places",
  "administrative_type": "State",
  "name": "Nagaland",
  "country": "India",
  "total_places": 10,
  "total_cities": 5,
  "cities": [
    { "name": "Kohima", "total_places": 5, "place_ids": ["nagaland_001", "nagaland_002", "nagaland_003", "nagaland_004", "nagaland_005"] },
    { "name": "Mokokchung", "total_places": 1, "place_ids": ["nagaland_006"] },
    { "name": "Mon", "total_places": 1, "place_ids": ["nagaland_007"] },
    { "name": "Phek", "total_places": 1, "place_ids": ["nagaland_008"] },
    { "name": "Peren", "total_places": 2, "place_ids": ["nagaland_009", "nagaland_010"] }
  ],
  "places": [
    {
      "id": "nagaland_001",
      "name": "Kohima",
      "category": "capital_city_culture",
      "area": "Kohima",
      "description": "The capital city known for Naga culture, markets, museums, and surrounding hills.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Kohima Nagaland",
      "tags": ["capital_city_culture", "Nagaland"],
      "city": "Kohima"
    },
    {
      "id": "nagaland_002",
      "name": "Kohima War Cemetery",
      "category": "war_memorial",
      "area": "Kohima",
      "description": "A beautifully maintained memorial cemetery commemorating soldiers of the Second World War.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Kohima War Cemetery Nagaland",
      "tags": ["war_memorial", "Nagaland"],
      "city": "Kohima"
    },
    {
      "id": "nagaland_003",
      "name": "Dzukou Valley",
      "category": "valley_nature",
      "area": "Kohima district",
      "description": "A spectacular valley famous for rolling grasslands, seasonal flowers, and trekking trails.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Dzukou Valley Nagaland",
      "tags": ["valley_nature", "Nagaland"],
      "city": "Kohima"
    },
    {
      "id": "nagaland_004",
      "name": "Japfu Peak",
      "category": "mountain_trekking",
      "area": "Kohima district",
      "description": "A prominent peak offering challenging treks and panoramic views of the Naga hills.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Japfu Peak Nagaland",
      "tags": ["mountain_trekking", "Nagaland"],
      "city": "Kohima"
    },
    {
      "id": "nagaland_005",
      "name": "Naga Heritage Village",
      "category": "tribal_culture",
      "area": "Kisama, near Kohima",
      "description": "A cultural village showcasing traditional Naga houses, festivals, crafts, and customs.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Naga Heritage Village Nagaland",
      "tags": ["tribal_culture", "Nagaland"],
      "city": "Kohima"
    },
    {
      "id": "nagaland_006",
      "name": "Mokokchung",
      "category": "hill_station_culture",
      "area": "Mokokchung district",
      "description": "A scenic hill town associated with Ao Naga culture, viewpoints, and traditional villages.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Mokokchung Nagaland",
      "tags": ["hill_station_culture", "Nagaland"],
      "city": "Mokokchung"
    },
    {
      "id": "nagaland_007",
      "name": "Longwa Village",
      "category": "tribal_culture",
      "area": "Mon district",
      "description": "A distinctive border village known for Konyak Naga culture and traditional architecture.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Longwa Village Nagaland",
      "tags": ["tribal_culture", "Nagaland"],
      "city": "Mon"
    },
    {
      "id": "nagaland_008",
      "name": "Shilloi Lake",
      "category": "lake_nature",
      "area": "Phek district",
      "description": "A scenic natural lake surrounded by hills and local legends.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Shilloi Lake Nagaland",
      "tags": ["lake_nature", "Nagaland"],
      "city": "Phek"
    },
    {
      "id": "nagaland_009",
      "name": "Mount Pauna",
      "category": "mountain_nature",
      "area": "Benreu, Peren district",
      "description": "A peaceful mountain destination with forest trails and views across the hills.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Mount Pauna Nagaland",
      "tags": ["mountain_nature", "Nagaland"],
      "city": "Peren"
    },
    {
      "id": "nagaland_010",
      "name": "Intangki National Park",
      "category": "wildlife_national_park",
      "area": "Peren district",
      "description": "A forested protected area known for biodiversity and wildlife habitats.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Intangki National Park Nagaland",
      "tags": ["wildlife_national_park", "Nagaland"],
      "city": "Peren"
    }
  ]
};

const meghalayaData = {
  "dataset": "Meghalaya Tourist Places",
  "administrative_type": "State",
  "name": "Meghalaya",
  "country": "India",
  "total_places": 10,
  "total_cities": 6,
  "cities": [
    { "id": "shillong", "name": "Shillong", "place_ids": ["meghalaya_001", "meghalaya_003", "meghalaya_004"], "total_places": 3 },
    { "id": "umiam", "name": "Umiam", "place_ids": ["meghalaya_002"], "total_places": 1 },
    { "id": "cherrapunji", "name": "Cherrapunji", "place_ids": ["meghalaya_005", "meghalaya_006", "meghalaya_007"], "total_places": 3 },
    { "id": "nongriat", "name": "Nongriat", "place_ids": ["meghalaya_008"], "total_places": 1 },
    { "id": "dawki", "name": "Dawki", "place_ids": ["meghalaya_009"], "total_places": 1 },
    { "id": "mawlynnong", "name": "Mawlynnong", "place_ids": ["meghalaya_010"], "total_places": 1 }
  ],
  "places": [
    {
      "id": "meghalaya_001",
      "name": "Shillong",
      "category": "hill_station_city",
      "area": "East Khasi Hills",
      "city": "Shillong",
      "description": "The capital of Meghalaya, known for waterfalls, viewpoints, music, markets, and colonial-era attractions.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Shillong Meghalaya",
      "tags": ["hill_station_city", "Meghalaya"]
    },
    {
      "id": "meghalaya_002",
      "name": "Umiam Lake",
      "category": "lake_recreation",
      "area": "Ri-Bhoi district",
      "city": "Umiam",
      "description": "A large scenic reservoir popular for boating, water activities, and lakeside views.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Umiam Lake Meghalaya",
      "tags": ["lake_recreation", "Meghalaya"]
    },
    {
      "id": "meghalaya_003",
      "name": "Elephant Falls",
      "category": "waterfall_nature",
      "area": "Near Shillong",
      "city": "Shillong",
      "description": "A multi-tiered waterfall surrounded by lush greenery and an accessible walking trail.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Elephant Falls Meghalaya",
      "tags": ["waterfall_nature", "Meghalaya"]
    },
    {
      "id": "meghalaya_004",
      "name": "Shillong Peak",
      "category": "viewpoint_nature",
      "area": "East Khasi Hills",
      "city": "Shillong",
      "description": "A high viewpoint offering sweeping views of Shillong and the surrounding hills.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Shillong Peak Meghalaya",
      "tags": ["viewpoint_nature", "Meghalaya"]
    },
    {
      "id": "meghalaya_005",
      "name": "Cherrapunji",
      "category": "hill_station_nature",
      "area": "East Khasi Hills",
      "city": "Cherrapunji",
      "description": "A famous high-rainfall destination known for cliffs, waterfalls, caves, and living root bridges.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Cherrapunji Meghalaya",
      "tags": ["hill_station_nature", "Meghalaya"]
    },
    {
      "id": "meghalaya_006",
      "name": "Nohkalikai Falls",
      "category": "waterfall_nature",
      "area": "Near Cherrapunji",
      "city": "Cherrapunji",
      "description": "A dramatic waterfall dropping into a deep blue-green pool.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Nohkalikai Falls Meghalaya",
      "tags": ["waterfall_nature", "Meghalaya"]
    },
    {
      "id": "meghalaya_007",
      "name": "Mawsmai Cave",
      "category": "cave_nature",
      "area": "Near Cherrapunji",
      "city": "Cherrapunji",
      "description": "A popular limestone cave with narrow passages and striking rock formations.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Mawsmai Cave Meghalaya",
      "tags": ["cave_nature", "Meghalaya"]
    },
    {
      "id": "meghalaya_008",
      "name": "Living Root Bridge",
      "category": "heritage_nature",
      "area": "Nongriat village",
      "city": "Nongriat",
      "description": "A remarkable bridge formed by guiding living tree roots across a stream.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Living Root Bridge Meghalaya",
      "tags": ["heritage_nature", "Meghalaya"]
    },
    {
      "id": "meghalaya_009",
      "name": "Dawki",
      "category": "river_border",
      "area": "West Jaintia Hills",
      "city": "Dawki",
      "description": "A scenic border town known for the clear waters of the Umngot River and boating.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Dawki Meghalaya",
      "tags": ["river_border", "Meghalaya"]
    },
    {
      "id": "meghalaya_010",
      "name": "Mawlynnong",
      "category": "village_culture",
      "area": "East Khasi Hills",
      "city": "Mawlynnong",
      "description": "A well-known village destination celebrated for cleanliness, greenery, and traditional Khasi surroundings.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Mawlynnong Meghalaya",
      "tags": ["village_culture", "Meghalaya"]
    }
  ]
};

const manipurData = {
  "dataset": "Manipur Tourist Places",
  "administrative_type": "State",
  "name": "Manipur",
  "country": "India",
  "total_places": 10,
  "total_cities": 6,
  "cities": [
    { "id": "imphal", "name": "Imphal", "place_ids": ["manipur_001", "manipur_004", "manipur_005", "manipur_006", "manipur_007"], "total_places": 5 },
    { "id": "loktak", "name": "Loktak", "place_ids": ["manipur_002", "manipur_003"], "total_places": 2 },
    { "id": "ukhrul", "name": "Ukhrul", "place_ids": ["manipur_008"], "total_places": 1 },
    { "id": "dzukou", "name": "Dzukou Valley", "place_ids": ["manipur_009"], "total_places": 1 },
    { "id": "khongjom", "name": "Khongjom", "place_ids": ["manipur_010"], "total_places": 1 },
    { "id": "bishnupur", "name": "Bishnupur", "place_ids": [], "total_places": 0 }
  ],
  "places": [
    {
      "id": "manipur_001",
      "name": "Imphal",
      "category": "capital_city_culture",
      "area": "Imphal West",
      "city": "Imphal",
      "description": "The capital of Manipur, known for markets, museums, historic sites, and surrounding hills.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Imphal Manipur",
      "tags": ["capital_city_culture", "Manipur"]
    },
    {
      "id": "manipur_002",
      "name": "Loktak Lake",
      "category": "lake_nature",
      "area": "Bishnupur district",
      "city": "Loktak",
      "description": "The largest freshwater lake in Northeast India, famous for floating phumdis and scenic landscapes.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Loktak Lake Manipur",
      "tags": ["lake_nature", "Manipur"]
    },
    {
      "id": "manipur_003",
      "name": "Keibul Lamjao National Park",
      "category": "wildlife_national_park",
      "area": "Bishnupur district",
      "city": "Loktak",
      "description": "The world’s only floating national park and the natural habitat of the endangered Sangai deer.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Keibul Lamjao National Park Manipur",
      "tags": ["wildlife_national_park", "Manipur"]
    },
    {
      "id": "manipur_004",
      "name": "Kangla Fort",
      "category": "heritage_fort",
      "area": "Imphal",
      "city": "Imphal",
      "description": "A historic fortified complex and an important symbol of Manipur’s royal heritage.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Kangla Fort Manipur",
      "tags": ["heritage_fort", "Manipur"]
    },
    {
      "id": "manipur_005",
      "name": "Shree Govindajee Temple",
      "category": "religious_heritage",
      "area": "Imphal",
      "city": "Imphal",
      "description": "A prominent Vaishnavite temple dedicated to Radha and Krishna.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Shree Govindajee Temple Manipur",
      "tags": ["religious_heritage", "Manipur"]
    },
    {
      "id": "manipur_006",
      "name": "Ema Keithel",
      "category": "market_culture",
      "area": "Imphal",
      "city": "Imphal",
      "description": "A historic women-run market showcasing local handicrafts, textiles, food, and traditional commerce.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Ema Keithel Manipur",
      "tags": ["market_culture", "Manipur"]
    },
    {
      "id": "manipur_007",
      "name": "Andro Village",
      "category": "tribal_culture",
      "area": "Imphal East",
      "city": "Imphal",
      "description": "A cultural village known for traditional houses, crafts, heritage practices, and local traditions.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Andro Village Manipur",
      "tags": ["tribal_culture", "Manipur"]
    },
    {
      "id": "manipur_008",
      "name": "Shirui Hills",
      "category": "mountain_nature",
      "area": "Ukhrul district",
      "city": "Ukhrul",
      "description": "A scenic hill destination famous for the rare Shirui lily and panoramic mountain views.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Shirui Hills Manipur",
      "tags": ["mountain_nature", "Manipur"]
    },
    {
      "id": "manipur_009",
      "name": "Dzukou Valley",
      "category": "valley_nature",
      "area": "Manipur–Nagaland border",
      "city": "Dzukou Valley",
      "description": "A beautiful trekking destination with rolling grasslands, seasonal flowers, and mountain scenery.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Dzukou Valley Manipur",
      "tags": ["valley_nature", "Manipur"]
    },
    {
      "id": "manipur_010",
      "name": "Khongjom War Memorial",
      "category": "war_memorial",
      "area": "Thoubal district",
      "city": "Khongjom",
      "description": "A memorial commemorating the soldiers of the Anglo-Manipur War of 1891.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Khongjom War Memorial Manipur",
      "tags": ["war_memorial", "Manipur"]
    }
  ]
};

const mizoramData = {
  "dataset": "Mizoram Tourist Places",
  "administrative_type": "State",
  "name": "Mizoram",
  "country": "India",
  "total_places": 10,
  "total_cities": 7,
  "cities": [
    { "id": "aizawl", "name": "Aizawl", "place_ids": ["mizoram_001", "mizoram_002", "mizoram_003", "mizoram_009", "mizoram_010"], "total_places": 5 },
    { "id": "serchhip", "name": "Serchhip", "place_ids": ["mizoram_004"], "total_places": 1 },
    { "id": "lawngtlai", "name": "Lawngtlai", "place_ids": ["mizoram_005"], "total_places": 1 },
    { "id": "champhai", "name": "Champhai", "place_ids": ["mizoram_006"], "total_places": 1 },
    { "id": "saitual", "name": "Saitual", "place_ids": ["mizoram_007"], "total_places": 1 },
    { "id": "siaha", "name": "Siaha", "place_ids": ["mizoram_008"], "total_places": 1 },
    { "id": "hmuifang", "name": "Hmuifang", "place_ids": [], "total_places": 0 }
  ],
  "places": [
    {
      "id": "mizoram_001",
      "name": "Aizawl",
      "category": "capital_city_culture",
      "area": "Aizawl",
      "city": "Aizawl",
      "description": "The capital of Mizoram, known for hilltop views, markets, churches, and Mizo culture.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Aizawl Mizoram",
      "tags": ["capital_city_culture", "Mizoram"]
    },
    {
      "id": "mizoram_002",
      "name": "Durtlang Hills",
      "category": "viewpoint_nature",
      "area": "Near Aizawl",
      "city": "Aizawl",
      "description": "A popular viewpoint offering panoramic views of Aizawl and the surrounding hills.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Durtlang Hills Mizoram",
      "tags": ["viewpoint_nature", "Mizoram"]
    },
    {
      "id": "mizoram_003",
      "name": "Reiek",
      "category": "mountain_viewpoint",
      "area": "Near Aizawl",
      "city": "Aizawl",
      "description": "A scenic mountain destination with trekking trails and wide views across Mizoram.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Reiek Mizoram",
      "tags": ["mountain_viewpoint", "Mizoram"]
    },
    {
      "id": "mizoram_004",
      "name": "Vantawng Falls",
      "category": "waterfall_nature",
      "area": "Serchhip district",
      "city": "Serchhip",
      "description": "The highest waterfall in Mizoram, surrounded by lush forested hills.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Vantawng Falls Mizoram",
      "tags": ["waterfall_nature", "Mizoram"]
    },
    {
      "id": "mizoram_005",
      "name": "Phawngpui National Park",
      "category": "wildlife_national_park",
      "area": "Lawngtlai district",
      "city": "Lawngtlai",
      "description": "A protected mountain landscape known for orchids, birds, forests, and spectacular viewpoints.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Phawngpui National Park Mizoram",
      "tags": ["wildlife_national_park", "Mizoram"]
    },
    {
      "id": "mizoram_006",
      "name": "Murlen National Park",
      "category": "wildlife_national_park",
      "area": "Champhai district",
      "city": "Champhai",
      "description": "A forested national park with rich biodiversity and scenic mountain surroundings.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Murlen National Park Mizoram",
      "tags": ["wildlife_national_park", "Mizoram"]
    },
    {
      "id": "mizoram_007",
      "name": "Tam Dil",
      "category": "lake_nature",
      "area": "Saitual district",
      "city": "Saitual",
      "description": "A peaceful natural lake surrounded by greenery and popular for boating and picnics.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Tam Dil Mizoram",
      "tags": ["lake_nature", "Mizoram"]
    },
    {
      "id": "mizoram_008",
      "name": "Palak Lake",
      "category": "lake_nature",
      "area": "Siaha district",
      "city": "Siaha",
      "description": "A picturesque lake set amid forested hills and known for its tranquil setting.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Palak Lake Mizoram",
      "tags": ["lake_nature", "Mizoram"]
    },
    {
      "id": "mizoram_009",
      "name": "Hmuifang",
      "category": "hill_station_nature",
      "area": "Aizawl district",
      "city": "Aizawl",
      "description": "A hill destination with forests, grasslands, traditional cultural experiences, and scenic views.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Hmuifang Mizoram",
      "tags": ["hill_station_nature", "Mizoram"]
    },
    {
      "id": "mizoram_010",
      "name": "Falkawn Village",
      "category": "tribal_culture",
      "area": "Near Aizawl",
      "city": "Aizawl",
      "description": "A cultural village presenting traditional Mizo lifestyles, houses, customs, and community heritage.",
      "best_for": ["nature", "photography", "culture"],
      "suggested_duration": "2–4 hours",
      "best_time_to_visit": "October to April",
      "entry_fee": "Free or paid depending on attraction; verify current rates",
      "opening_hours": "Usually daytime; timings vary by attraction",
      "visitor_notes": ["Check local access rules and timings before visiting", "Carry water and comfortable footwear"],
      "map_search": "Falkawn Village Mizoram",
      "tags": ["tribal_culture", "Mizoram"]
    }
  ]
};

fs.writeFileSync(path.join(dataDir, 'nagaland.json'), JSON.stringify(nagalandData, null, 2), 'utf-8');
fs.writeFileSync(path.join(dataDir, 'meghalaya.json'), JSON.stringify(meghalayaData, null, 2), 'utf-8');
fs.writeFileSync(path.join(dataDir, 'manipur.json'), JSON.stringify(manipurData, null, 2), 'utf-8');
fs.writeFileSync(path.join(dataDir, 'mizoram.json'), JSON.stringify(mizoramData, null, 2), 'utf-8');

console.log('Successfully written raw JSON files for Nagaland, Meghalaya, Manipur, and Mizoram!');
