import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, ''));

const apJsonPath = path.join(rootDir, 'data', 'andhra_pradesh_tourist_places_city_assigned.json');
const assamJsonPath = path.join(rootDir, 'data', 'assam_tourist_places_city_assigned.json');
const itdbJsonPath = path.join(rootDir, 'data', 'india_tourism_database.json');
const itdbTsPath = path.join(rootDir, 'src', 'data', 'indiaTourismDatabase.ts');
const citiesJsonPath = path.join(rootDir, 'data', 'cities.json');
const statesJsonPath = path.join(rootDir, 'data', 'states.json');

console.log('=== Starting Andhra Pradesh & Assam Integration ===');

const apSource = readJson(apJsonPath);
const assamSource = readJson(assamJsonPath);

console.log(`Loaded AP source: ${apSource.places.length} places, ${apSource.cities.length} cities.`);
console.log(`Loaded Assam source: ${assamSource.places.length} places, ${assamSource.cities.length} cities.`);

if (apSource.places.length !== 15) throw new Error(`Expected 15 AP places, got ${apSource.places.length}`);
if (assamSource.places.length !== 15) throw new Error(`Expected 15 Assam places, got ${assamSource.places.length}`);

// =========================================================
// 1. ANDHRA PRADESH CITIES DEFINITIONS (10 Cities)
// =========================================================
const AP_CITIES = {
  tirupati: {
    id: 'tirupati',
    name: 'Tirupati',
    canonical_name: 'Tirupati',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'Tirupati',
    city_type: 'city',
    lat: 13.6288,
    lng: 79.4192,
    coordinates: { lat: 13.6288, lng: 79.4192 },
    tagline: 'Spiritual Capital of Andhra Pradesh & Seven Hills of Tirumala',
    description: 'World-renowned pilgrimage center nestled at the foot of Seshachalam Hills, home to the sacred hilltop shrine of Lord Venkateswara at Tirumala.',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['spiritual', 'heritage', 'nature'],
    prominence: 'Pilgrimage Destination',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Andhra Pradesh Tourism Development Corporation (APTDC)',
    short_description: 'Sacred temple city celebrated worldwide for Lord Venkateswara shrine on Tirumala hills.',
  },
  srikalahasti: {
    id: 'srikalahasti',
    name: 'Srikalahasti',
    canonical_name: 'Srikalahasti',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'Tirupati',
    city_type: 'city',
    lat: 13.7498,
    lng: 79.6984,
    coordinates: { lat: 13.7498, lng: 79.6984 },
    tagline: 'Kashi of the South & Sacred Vayu Lingam Shrine',
    description: 'Revered Shiva pilgrimage destination on the banks of the Swarnamukhi River, famous for the ancient Srikalahasteeswara Temple representing the element of Wind (Vayu Lingam) and Kalamkari art.',
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['spiritual', 'heritage', 'crafts'],
    prominence: 'Pancha Bhoota Stalam & Artisan Town',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'APTDC & Endowments Department AP',
    short_description: 'Sacred Vayu Lingam temple town on Swarnamukhi River, famed for ancient Dravidian architecture.',
  },
  'araku-valley': {
    id: 'araku-valley',
    name: 'Araku Valley',
    canonical_name: 'Araku Valley',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'Alluri Sitharama Raju',
    city_type: 'city',
    lat: 18.3273,
    lng: 82.8775,
    coordinates: { lat: 18.3273, lng: 82.8775 },
    tagline: 'Ooty of Andhra & Misty Coffee Plantations of the Eastern Ghats',
    description: 'Picturesque hill valley in the Eastern Ghats renowned for lush Arabica coffee plantations, indigenous tribal culture, Katiki waterfalls, and the million-year-old Borra limestone caves.',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'hills', 'adventure'],
    prominence: 'Hill Station & Nature Retreat',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'APTDC & Forest Dept AP',
    short_description: 'Breathtaking Eastern Ghats hill valley known for organic coffee estates and Borra Caves.',
  },
  visakhapatnam: {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    canonical_name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'Visakhapatnam',
    city_type: 'city',
    lat: 17.6868,
    lng: 83.2185,
    coordinates: { lat: 17.6868, lng: 83.2185 },
    tagline: 'The City of Destiny & Coastal Jewel of the Bay of Bengal',
    description: 'Vibrant coastal metropolis renowned for scenic beaches like RK Beach and Rushikonda, panoramic views from Kailasagiri, INS Kursura Submarine Museum, and historic Simhachalam Temple.',
    hero_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['coastal', 'nature', 'heritage'],
    prominence: 'Major Port City & Tourism Hub',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Visakhapatnam Metropolitan Region Development Authority & APTDC',
    short_description: 'Dynamic coastal city boasting golden beaches, submarine museums, and hilltop viewpoints.',
  },
  lepakshi: {
    id: 'lepakshi',
    name: 'Lepakshi',
    canonical_name: 'Lepakshi',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'Sri Sathya Sai',
    city_type: 'city',
    lat: 13.8045,
    lng: 77.6062,
    coordinates: { lat: 13.8045, lng: 77.6062 },
    tagline: 'Marvel of Vijayanagara Architecture & Hanging Pillar',
    description: 'Legendary 16th-century heritage village built under the Vijayanagara Empire, internationally acclaimed for the Veerabhadra Temple, enigmatic hanging pillar, and India\'s largest monolithic Nandi bull.',
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'monuments', 'architecture'],
    prominence: 'Archaeological Heritage Wonder',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Archaeological Survey of India & APTDC',
    short_description: 'Architectural wonder celebrated for 16th-century Vijayanagara murals and monolithic Nandi.',
  },
  amaravati: {
    id: 'amaravati',
    name: 'Amaravati',
    canonical_name: 'Amaravati',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'Palnadu',
    city_type: 'city',
    lat: 16.5735,
    lng: 80.3575,
    coordinates: { lat: 16.5735, lng: 80.3575 },
    tagline: 'Ancient Buddhist Mahachaitya & Capital of the Satavahanas',
    description: 'Historic city on the Krishna River, seat of the ancient Satavahana dynasty and renowned Buddhist educational centre famous for the great Amaravati Stupa and Amaravati School of Art.',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'buddhist', 'archaeology'],
    prominence: 'Ancient Buddhist & State Capital Region',
    is_capital: true,
    capital_status: 'state_capital',
    verification_status: 'verified',
    source_provenance: 'ASI & Andhra Pradesh Capital Region Development Authority',
    short_description: 'Ancient Buddhist spiritual centre on the Krishna River, famed for the Great Stupa and sculpture art.',
  },
  vijayawada: {
    id: 'vijayawada',
    name: 'Vijayawada',
    canonical_name: 'Vijayawada',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'NTR',
    city_type: 'city',
    lat: 16.5062,
    lng: 80.6480,
    coordinates: { lat: 16.5062, lng: 80.6480 },
    tagline: 'City of Victory & Abode of Goddess Kanaka Durga',
    description: 'Commercial heart of Andhra Pradesh situated along the sacred Krishna River, renowned for the hilltop Kanaka Durga Temple, 7th-century rock-cut Undavalli Caves, and Prakasam Barrage.',
    hero_image_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['spiritual', 'heritage', 'commercial'],
    prominence: 'Major River City & Cultural Hub',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'APTDC & NTR District Tourism',
    short_description: 'Vibrant riverside city on the Krishna River, home to Kanaka Durga Temple and Undavalli Caves.',
  },
  rajamahendravaram: {
    id: 'rajamahendravaram',
    name: 'Rajamahendravaram',
    canonical_name: 'Rajamahendravaram',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'East Godavari',
    city_type: 'city',
    lat: 17.0005,
    lng: 81.8040,
    coordinates: { lat: 17.0005, lng: 81.8040 },
    tagline: 'Cultural Capital of Andhra Pradesh & Gateway to Papikondalu',
    description: 'Historic city on the sacred Godavari River, revered as the birthplace of Telugu literature and the launching pad for breathtaking boat cruises through the Papikondalu river gorges.',
    hero_image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['culture', 'nature', 'river'],
    prominence: 'Cultural Center of Godavari Delta',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'APTDC & East Godavari District Tourism',
    short_description: 'Cultural capital on the Godavari River, prime departure point for Papikondalu river cruises.',
  },
  sullurpeta: {
    id: 'sullurpeta',
    name: 'Sullurpeta',
    canonical_name: 'Sullurpeta',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'Tirupati',
    city_type: 'city',
    lat: 13.7008,
    lng: 80.0212,
    coordinates: { lat: 13.7008, lng: 80.0212 },
    tagline: 'Gateway to Pulicat Lagoon & Flamingo Bird Sanctuary',
    description: 'Coastal gateway town adjoining the expansive Pulicat Lake, famous for hosting thousands of wintering Greater Flamingos, marine boating, and proximity to the Sriharikota spaceport.',
    hero_image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'wildlife', 'wetlands'],
    prominence: 'Eco-Tourism & Coastal Wetland Gateway',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'APTDC & AP Forest Dept',
    short_description: 'Coastal gateway to the Pulicat Lake bird sanctuary, renowned for annual Flamingo Festivals.',
  },
  kondapalli: {
    id: 'kondapalli',
    name: 'Kondapalli',
    canonical_name: 'Kondapalli',
    state: 'Andhra Pradesh',
    state_id: 'andhra-pradesh',
    region: 'Southern India',
    district: 'NTR',
    city_type: 'city',
    lat: 16.6167,
    lng: 80.5333,
    coordinates: { lat: 16.6167, lng: 80.5333 },
    tagline: 'Citadel of Reddy Kings & World-Famous Wooden Toys Craft',
    description: 'Historic town near Vijayawada featuring the 14th-century Kondapalli Fort and the globally celebrated GI-tagged Kondapalli Bommalu (handcrafted softwood toys).',
    hero_image_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'crafts', 'forts'],
    prominence: 'Heritage Craft & Fort Town',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'APTDC & Handlooms & Textiles Dept AP',
    short_description: 'Historic hill fort town internationally famous for GI-tagged Kondapalli softwood toys.',
  },
};

// =========================================================
// 2. ANDHRA PRADESH PLACES DETAILS (15 Places)
// =========================================================
const AP_PLACES_DETAILS = {
  andhra_pradesh_001: {
    city_key: 'tirupati',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual Heritage',
    subtopic: 'Vaishnavite Hill Temple',
    area: 'Tirumala',
    lat: 13.6833,
    lng: 79.3472,
    opening_hours: '03:00 AM - 11:30 PM (Varies with daily sevas)',
    visiting_hours: '03:00 AM - 11:30 PM',
    timings: { opening_time: '03:00 AM', closing_time: '11:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free (Sarva Darshan); Special Entry Darshan ₹300',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Tirumala Venkateswara Temple Andhra Pradesh',
    tags: ['religious_heritage', 'Andhra Pradesh'],
    summary: 'One of India’s most visited Hindu temples, dedicated to Lord Venkateswara.',
    description: 'Perched on the sacred Venkatadri hill of the Seshachalam range, Tirumala Venkateswara Temple is the world\'s most visited religious pilgrimage shrine. Dedicated to Lord Venkateswara (an incarnation of Vishnu), it features the stunning gold-gilded Ananda Nilayam vimana tower and ancient Dravidian stone inscriptions.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_002: {
    city_key: 'srikalahasti',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual Heritage',
    subtopic: 'Pancha Bhoota Vayu Sthalam',
    area: 'Srikalahasti',
    lat: 13.7498,
    lng: 79.6984,
    opening_hours: '06:00 AM - 09:00 PM',
    visiting_hours: '06:00 AM - 09:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Srikalahasti Temple Andhra Pradesh',
    tags: ['religious_heritage', 'Andhra Pradesh'],
    summary: 'A major Shiva temple known for its spiritual significance and Dravidian architecture.',
    description: 'Renowned as the Pancha Bhoota Sthalam representing the element of Air (Vayu), Srikalahasteeswara Temple is celebrated for Rahu-Ketu Sarpa Dosha Nivarana pujas and magnificent Chola and Vijayanagara architectural gopurams on the banks of Swarnamukhi River.',
    image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_003: {
    city_key: 'araku-valley',
    categoryBucket: 'nature_parks_zoo',
    category: 'valley_nature',
    topic: 'Nature & Hills',
    subtopic: 'Scenic Highland Valley',
    area: 'Alluri Sitharama Raju district',
    lat: 18.3273,
    lng: 82.8775,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '06:00 AM - 06:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Araku Valley Andhra Pradesh',
    tags: ['valley_nature', 'Andhra Pradesh'],
    summary: 'A scenic hill valley known for coffee plantations, forests, tribal culture, and mountain views.',
    description: 'Nestled in the Eastern Ghats at an elevation of around 900–1,400 meters, Araku Valley is famed for its organic high-altitude coffee, rolling green meadows, tribal museum, Padmapuram botanical gardens, and scenic Vistadome railway journey from Visakhapatnam.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_004: {
    city_key: 'araku-valley',
    categoryBucket: 'nature_parks_zoo',
    category: 'cave_nature',
    topic: 'Geological Marvels',
    subtopic: 'Karstic Limestone Caves',
    area: 'Near Araku Valley',
    lat: 18.2804,
    lng: 83.0396,
    opening_hours: '10:00 AM - 05:00 PM',
    visiting_hours: '10:00 AM - 05:00 PM',
    timings: { opening_time: '10:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 80, international: 150, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Borra Caves Andhra Pradesh',
    tags: ['cave_nature', 'Andhra Pradesh'],
    summary: 'Limestone caves featuring striking rock formations and natural chambers.',
    description: 'Discovered in 1807 by William King of Geological Survey of India, Borra Caves are million-year-old limestone karst formations descending over 80 meters. Illuminated with dramatic multi-colored lights, they feature stalactite and stalagmite formations resembling Shiva-Parvati and Mother-Child.',
    image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_005: {
    city_key: 'visakhapatnam',
    categoryBucket: 'nature_parks_zoo',
    category: 'beach_nature',
    topic: 'Coastal & Beaches',
    subtopic: 'Bay of Bengal Beachfront',
    area: 'Visakhapatnam',
    lat: 17.7126,
    lng: 83.3235,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '05:00 AM - 09:00 PM',
    timings: { opening_time: '05:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Visakhapatnam Beach Andhra Pradesh',
    tags: ['beach_nature', 'Andhra Pradesh'],
    summary: 'A popular coastal destination with broad beaches, sea views, and urban attractions.',
    description: 'Visakhapatnam\'s picturesque coastline encompasses Ramakrishna (RK) Beach and Rushikonda Beach, renowned for golden sands, water sports, seaside promenades, and the iconic INS Kursura Submarine Museum preserved right on the shoreline.',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_006: {
    city_key: 'visakhapatnam',
    categoryBucket: 'nature_parks_zoo',
    category: 'viewpoint_park',
    topic: 'Viewpoints & Parks',
    subtopic: 'Panoramic Hilltop Garden',
    area: 'Visakhapatnam',
    lat: 17.7478,
    lng: 83.3444,
    opening_hours: '06:00 AM - 08:30 PM',
    visiting_hours: '06:00 AM - 08:30 PM',
    timings: { opening_time: '06:00 AM', closing_time: '08:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 20, international: 50, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Kailasagiri Andhra Pradesh',
    tags: ['viewpoint_park', 'Andhra Pradesh'],
    summary: 'A hilltop park offering panoramic views of Visakhapatnam and the Bay of Bengal.',
    description: 'Set atop a 360-foot hill overlooking the sparkling waters of the Bay of Bengal, Kailasagiri features colossal 40-foot white statues of Lord Shiva and Goddess Parvati, a scenic ropeway cable car, and lush botanical gardens.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_007: {
    city_key: 'visakhapatnam',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual Heritage',
    subtopic: 'Ancient Kalinga-Style Hill Shrine',
    area: 'Visakhapatnam',
    lat: 17.7667,
    lng: 83.2500,
    opening_hours: '07:00 AM - 09:00 PM',
    visiting_hours: '07:00 AM - 09:00 PM',
    timings: { opening_time: '07:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Simhachalam Temple Andhra Pradesh',
    tags: ['religious_heritage', 'Andhra Pradesh'],
    summary: 'A historic temple dedicated to Lord Narasimha and known for its architecture.',
    description: 'Perched on the Simhachalam hill, this 11th-century temple enshrines Lord Varaha Lakshmi Narasimha Swamy. The deity remains covered continuously in sandalwood paste (Chandan) throughout the year, revealed in its true form only during the sacred annual Chandanotsavam festival.',
    image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_008: {
    city_key: 'lepakshi',
    categoryBucket: 'heritage',
    category: 'temple_heritage',
    topic: 'Archaeological Architecture',
    subtopic: 'Vijayanagara Masterpiece & Hanging Pillar',
    area: 'Sri Sathya Sai district',
    lat: 13.8045,
    lng: 77.6062,
    opening_hours: '06:00 AM - 06:00 PM',
    visiting_hours: '06:00 AM - 06:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 25, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Lepakshi Temple Andhra Pradesh',
    tags: ['temple_heritage', 'Andhra Pradesh'],
    summary: 'A historic temple famous for Vijayanagara architecture, murals, carvings, and the hanging pillar.',
    description: 'Built in the 16th century by brothers Virupanna and Veeranna under the Vijayanagara Empire, the Veerabhadra Temple at Lepakshi is renowned for its miraculous hanging pillar that does not touch the ground, intricate ceiling frescoes, seven-headed serpent sculpture, and a colossal monolithic Nandi.',
    image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_009: {
    city_key: 'amaravati',
    categoryBucket: 'heritage',
    category: 'buddhist_heritage',
    topic: 'Buddhist Archaeology',
    subtopic: 'Great Mahachaitya Stupa',
    area: 'Palnadu district',
    lat: 16.5735,
    lng: 80.3575,
    opening_hours: '09:00 AM - 05:00 PM (Museum closed Fridays)',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: ['Friday'], status: 'VERIFIED' },
    fees: { domestic: 25, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Amaravati Stupa Andhra Pradesh',
    tags: ['buddhist_heritage', 'Andhra Pradesh'],
    summary: 'An important Buddhist archaeological site associated with the ancient Amaravati school of art.',
    description: 'Founded during the 3rd century BCE under Emperor Ashoka and embellished under the Satavahanas, the Amaravati Mahachaitya Stupa was one of the largest Buddhist stupas in ancient India, celebrated for its limestone relief sculptures illustrating Jataka tales.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_010: {
    city_key: 'vijayawada',
    categoryBucket: 'heritage',
    category: 'archaeological_heritage',
    topic: 'Archaeological Caves',
    subtopic: 'Rock-Cut Reclining Vishnu Sanctuary',
    area: 'Near Vijayawada',
    lat: 16.4950,
    lng: 80.5828,
    opening_hours: '09:00 AM - 05:30 PM',
    visiting_hours: '09:00 AM - 05:30 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 25, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Undavalli Caves Andhra Pradesh',
    tags: ['archaeological_heritage', 'Andhra Pradesh'],
    summary: 'Rock-cut caves featuring a large reclining Vishnu sculpture and historic architecture.',
    description: 'Carved out of solid sandstone in the 7th century during the Vishnukundina and Chalukyan periods, the Undavalli Caves span four tiered storeys. The second storey features a monumental 5-meter monolithic sculpture of Lord Vishnu reclining on Anantha (Sheshashayi Vishnu).',
    image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_011: {
    city_key: 'vijayawada',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual Heritage',
    subtopic: 'Hilltop Shakti Shrine',
    area: 'Vijayawada',
    lat: 16.5161,
    lng: 80.6056,
    opening_hours: '04:00 AM - 09:00 PM',
    visiting_hours: '04:00 AM - 09:00 PM',
    timings: { opening_time: '04:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Vijayawada Kanaka Durga Temple Andhra Pradesh',
    tags: ['religious_heritage', 'Andhra Pradesh'],
    summary: 'A major temple dedicated to Goddess Durga on Indrakeeladri Hill.',
    description: 'Prominently located on the crest of Indrakeeladri Hill overlooking the Krishna River, Kanaka Durga Temple is a celebrated Shakti pilgrimage centre mentioned in Kalika Purana and celebrated grandly during Navaratri.',
    image_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_012: {
    city_key: 'araku-valley',
    categoryBucket: 'nature_parks_zoo',
    category: 'cave_nature',
    topic: 'Geological Marvels',
    subtopic: 'Deepest Limestone Cave System',
    area: 'Alluri Sitharama Raju district',
    lat: 18.2804,
    lng: 83.0396,
    opening_hours: '10:00 AM - 05:00 PM',
    visiting_hours: '10:00 AM - 05:00 PM',
    timings: { opening_time: '10:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 80, international: 150, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Borra Caves Andhra Pradesh',
    tags: ['cave_nature', 'Andhra Pradesh'],
    summary: 'A famous cave system with dramatic limestone formations and illuminated chambers.',
    description: 'Formed by the Gosthani River cutting through limestone terrain in the Ananthagiri hills, Borra Caves is one of India\'s deepest cave complexes, featuring natural skylights and subterranean streams.',
    image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_013: {
    city_key: 'rajamahendravaram',
    categoryBucket: 'nature_parks_zoo',
    category: 'river_hills_nature',
    topic: 'Nature & River Gorge',
    subtopic: 'Godavari River Gorge Cruise',
    area: 'Godavari region',
    lat: 17.5500,
    lng: 81.5000,
    opening_hours: '06:00 AM - 06:00 PM',
    visiting_hours: '06:00 AM - 06:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Papikondalu Andhra Pradesh',
    tags: ['river_hills_nature', 'Andhra Pradesh'],
    summary: 'A scenic river-and-hills landscape explored through boat journeys on the Godavari.',
    description: 'Papikondalu (Papi Hills) is a series of majestic forested hills through which the mighty Godavari narrows into a breathtaking river canyon. Tourists embark on scenic day cruises from Rajamahendravaram with bamboo hut stays.',
    image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_014: {
    city_key: 'sullurpeta',
    categoryBucket: 'nature_parks_zoo',
    category: 'lake_wildlife',
    topic: 'Nature & Wetlands',
    subtopic: 'Brackish Water Bird Sanctuary',
    area: 'Tirupati district region',
    lat: 13.6667,
    lng: 80.1667,
    opening_hours: '06:00 AM - 06:00 PM',
    visiting_hours: '06:00 AM - 06:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Pulicat Lake Andhra Pradesh',
    tags: ['lake_wildlife', 'Andhra Pradesh'],
    summary: 'A coastal lagoon known for migratory birds, boating, and wetland scenery.',
    description: 'India\'s second largest brackish water lagoon, Pulicat Lake is separated from the Bay of Bengal by the barrier island of Sriharikota. Each winter, tens of thousands of Greater Flamingos, pelicans, and storks converge here.',
    image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=600&auto=format&fit=crop&q=80',
  },
  andhra_pradesh_015: {
    city_key: 'kondapalli',
    categoryBucket: 'heritage',
    category: 'heritage_fort',
    topic: 'Forts & Heritage',
    subtopic: 'Medieval Hill Citadel',
    area: 'NTR district',
    lat: 16.6167,
    lng: 80.5333,
    opening_hours: '10:00 AM - 05:00 PM',
    visiting_hours: '10:00 AM - 05:00 PM',
    timings: { opening_time: '10:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 20, international: 100, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'nature', 'photography'],
    visitor_notes: ['Check local access rules and timings before visiting', 'Carry water and comfortable footwear'],
    map_search: 'Kondapalli Fort Andhra Pradesh',
    tags: ['heritage_fort', 'Andhra Pradesh'],
    summary: 'A historic hill fort near Vijayawada known for its ruins and panoramic views.',
    description: 'Constructed in the 14th century by Prolaya Vema Reddy of the Musunuri and Reddy dynasties, Kondapalli Fort features the majestic Dargah Darwaza entrance, Gaja Shala (elephant stable), and Rani Mahal with sweeping views across Krishna valley.',
    image_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=600&auto=format&fit=crop&q=80',
  },
};

// =========================================================
// 3. ASSAM CITIES DEFINITIONS (10 Cities)
// =========================================================
const ASSAM_CITIES = {
  guwahati: {
    id: 'guwahati',
    name: 'Guwahati',
    canonical_name: 'Guwahati',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Kamrup Metropolitan',
    city_type: 'city',
    lat: 26.1445,
    lng: 91.7362,
    coordinates: { lat: 26.1445, lng: 91.7362 },
    tagline: 'Gateway to Northeast India & Citadel of Kamakhya',
    description: 'Premier metropolis of Northeast India situated along the majestic Brahmaputra River, famous for the revered hilltop Kamakhya Temple, Umananda island shrine, and rich Assamese cultural institutions.',
    hero_image_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['spiritual', 'heritage', 'culture'],
    prominence: 'State Gateway & Metropolis',
    is_capital: true,
    capital_status: 'state_capital',
    verification_status: 'verified',
    source_provenance: 'Assam Tourism Development Corporation (ATDC)',
    short_description: 'Vibrant gateway to Northeast India, home to Kamakhya Temple and Brahmaputra River.',
  },
  mayong: {
    id: 'mayong',
    name: 'Mayong',
    canonical_name: 'Mayong',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Morigaon',
    city_type: 'city',
    lat: 26.2558,
    lng: 92.0367,
    coordinates: { lat: 26.2558, lng: 92.0367 },
    tagline: 'Cradle of Black Magic & Gateway to Pobitora Rhinos',
    description: 'Legendary historical village celebrated as India\'s capital of occult sorcery, adjacent to Pobitora Wildlife Sanctuary which boasts the world\'s highest density of Greater One-Horned Rhinoceros.',
    hero_image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['wildlife', 'heritage', 'nature'],
    prominence: 'Wildlife & Cultural Heritage Hub',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'ATDC & Pobitora Wildlife Sanctuary',
    short_description: 'Historic village renowned for ancient occult folklore and Pobitora rhino sanctuary.',
  },
  kohora: {
    id: 'kohora',
    name: 'Kohora',
    canonical_name: 'Kohora',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Golaghat',
    city_type: 'city',
    lat: 26.5862,
    lng: 93.4116,
    coordinates: { lat: 26.5862, lng: 93.4116 },
    tagline: 'Heart of Kaziranga & UNESCO World Heritage Rhino Realm',
    description: 'Central tourism hub of the world-famous Kaziranga National Park, the primary base for elephant safaris and jeep tours across vast elephant-grass floodplains hosting two-thirds of the world\'s Great Indian Rhinoceros.',
    hero_image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['wildlife', 'nature', 'unesco'],
    prominence: 'World Heritage Wildlife Center',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Kaziranga National Park & Assam Forest Dept',
    short_description: 'Central gateway to Kaziranga National Park, world haven of the one-horned rhinoceros.',
  },
  bansbari: {
    id: 'bansbari',
    name: 'Bansbari',
    canonical_name: 'Bansbari',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Baksa',
    city_type: 'city',
    lat: 26.7324,
    lng: 91.0189,
    coordinates: { lat: 26.7324, lng: 91.0189 },
    tagline: 'Portal to Manas National Park & Foothills of Bhutan',
    description: 'Central entry gate to the UNESCO World Heritage Manas National Park, a pristine biosphere reserve at the Himalayan foothills harboring golden langurs, pygmy hogs, wild water buffaloes, and Bengal tigers.',
    hero_image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['wildlife', 'nature', 'unesco'],
    prominence: 'Himalayan Foothill Wildlife Gateway',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Manas Tiger Reserve & ATDC',
    short_description: 'Foothills gateway to UNESCO Manas National Park and Himalayan wildlife biospheres.',
  },
  orang: {
    id: 'orang',
    name: 'Orang',
    canonical_name: 'Orang',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Darrang',
    city_type: 'city',
    lat: 26.5492,
    lng: 92.3425,
    coordinates: { lat: 26.5492, lng: 92.3425 },
    tagline: 'Mini Kaziranga on the North Bank of the Brahmaputra',
    description: 'Riverine wildlife haven hosting Orang National Park, famed for sheltering one-horned rhinos, Royal Bengal tigers, and rich avian life on the northern floodplains of the Brahmaputra.',
    hero_image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['wildlife', 'nature'],
    prominence: 'National Park Destination',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Orang National Park & Assam Forest Dept',
    short_description: 'North bank wildlife haven celebrated as Mini Kaziranga for rhinos and tigers.',
  },
  bhalukpong: {
    id: 'bhalukpong',
    name: 'Bhalukpong',
    canonical_name: 'Bhalukpong',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Sonitpur',
    city_type: 'city',
    lat: 27.0125,
    lng: 92.6517,
    coordinates: { lat: 27.0125, lng: 92.6517 },
    tagline: 'Jia Bhoroli River Valleys & Gateway to Nameri National Park',
    description: 'Border town on the scenic Jia Bhoroli River, premier base for Nameri National Park, famous for river rafting, golden mahseer angling, trekking, and birding in evergreen subtropical forests.',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'adventure', 'wildlife'],
    prominence: 'Adventure & Eco-Tourism Hub',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'ATDC & Nameri National Park',
    short_description: 'Scenic riverfront eco-tourism town and gateway to Nameri National Park.',
  },
  majuli: {
    id: 'majuli',
    name: 'Majuli',
    canonical_name: 'Majuli',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Majuli',
    city_type: 'city',
    lat: 26.9634,
    lng: 94.2215,
    coordinates: { lat: 26.9634, lng: 94.2215 },
    tagline: 'World’s Largest Inhabited River Island & Cradle of Neo-Vaishnavism',
    description: 'Enchanting freshwater island in the mighty Brahmaputra River, cultural heart of Assam celebrated for 15th-century Vaishnavite Satras (monasteries), traditional mask making, and serene rural wetland landscapes.',
    hero_image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['culture', 'heritage', 'island'],
    prominence: 'World-Famous Cultural River Island',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Majuli Cultural Landscape Authority & ATDC',
    short_description: 'World’s largest river island, famous for 15th-century Vaishnavite Satras and mask making.',
  },
  sivasagar: {
    id: 'sivasagar',
    name: 'Sivasagar',
    canonical_name: 'Sivasagar',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Sivasagar',
    city_type: 'city',
    lat: 26.9826,
    lng: 94.6425,
    coordinates: { lat: 26.9826, lng: 94.6425 },
    tagline: 'Royal Capital of the 600-Year Ahom Kingdom',
    description: 'Historic capital of the legendary Ahom Dynasty who ruled Assam for 600 years without falling to the Mughals, home to the colossal Sivasagar Sivadol, Talatal Ghar palace, and Rang Ghar amphitheater.',
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'monuments', 'history'],
    prominence: 'Medieval Royal Ahom Capital',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Archaeological Survey of India & ATDC',
    short_description: 'Historical capital of the Ahom kingdom, featuring ancient royal palaces and temples.',
  },
  sonari: {
    id: 'sonari',
    name: 'Sonari',
    canonical_name: 'Sonari',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Charaideo',
    city_type: 'city',
    lat: 27.0275,
    lng: 95.0217,
    coordinates: { lat: 27.0275, lng: 95.0217 },
    tagline: 'Pyramids of Assam & UNESCO World Heritage Charaideo Maidams',
    description: 'Historic center of Charaideo district, home to the sacred royal burial mounds (Maidams) of Ahom royalty and kings, recently inscribed as India\'s landmark UNESCO World Heritage site.',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['unesco', 'heritage', 'monuments'],
    prominence: 'UNESCO World Heritage Landmark',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'UNESCO & Archaeological Survey of India',
    short_description: 'Home of the UNESCO World Heritage Charaideo Maidams, the royal burial mounds of Ahom kings.',
  },
  haflong: {
    id: 'haflong',
    name: 'Haflong',
    canonical_name: 'Haflong',
    state: 'Assam',
    state_id: 'assam',
    region: 'Northeastern India',
    district: 'Dima Hasao',
    city_type: 'city',
    lat: 25.1764,
    lng: 93.0236,
    coordinates: { lat: 25.1764, lng: 93.0236 },
    tagline: 'Scotland of Assam & Only Hill Station in the State',
    description: 'Charming colonial hill retreat situated at an altitude of 680 meters in the Barail Range, featuring scenic Haflong Lake, pine forests, ethnic tribal hamlets, and proximity to mystery-shrouded Jatinga.',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'hills', 'scenic'],
    prominence: 'Hill Station Retreat',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Dima Hasao Tourism & ATDC',
    short_description: 'Assam’s only hill station, famed for Haflong Lake, cool mountain air, and Barail peaks.',
  },
};

// =========================================================
// 4. ASSAM PLACES DETAILS (15 Places)
// =========================================================
const ASSAM_PLACES_DETAILS = {
  'kamakhya-temple': {
    city_key: 'guwahati',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual Heritage',
    subtopic: 'Premier Shakti Peetha Shrine',
    area: 'Nilachal Hill, Guwahati',
    lat: 26.1664,
    lng: 91.7052,
    opening_hours: '05:30 AM - 01:00 PM, 02:30 PM - 05:30 PM',
    visiting_hours: '05:30 AM - 05:30 PM',
    timings: { opening_time: '05:30 AM', closing_time: '05:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry (VIP queue ₹501)',
    suggested_duration: '2–3 hours',
    best_time_to_visit: 'October to March (Ambubachi Mela in June)',
    best_for: ['heritage', 'spiritual', 'photography'],
    visitor_notes: ['Dress conservatively', 'Long queues on festival days'],
    map_search: 'Kamakhya Temple Guwahati Assam',
    tags: ['shakti peetha', 'kamakhya', 'guwahati', 'spiritual', 'assam'],
    summary: 'One of the oldest and most revered Shakti Peethas in India, situated atop Nilachal Hill.',
    description: 'Kamakhya Temple is the supreme centre of Tantric and Shakta worship in India. Dedicated to Mother Goddess Kamakhya, the shrine enshrines the sacred yoni rock sanctum through which a natural subterranean spring flows. Celebrated annually for the Ambubachi Mela.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
  },
  'umananda-temple': {
    city_key: 'guwahati',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual Heritage',
    subtopic: 'Brahmaputra Island Shiva Shrine',
    area: 'Peacock Island, Brahmaputra River, Guwahati',
    lat: 26.1919,
    lng: 91.7483,
    opening_hours: '06:00 AM - 05:00 PM',
    visiting_hours: '06:00 AM - 05:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free temple entry; Ferry ₹20 per head',
    suggested_duration: '1.5–2 hours',
    best_time_to_visit: 'October to April',
    best_for: ['nature', 'spiritual', 'photography'],
    visitor_notes: ['Reached via passenger ferry from Uzan Bazar / Sukreswar ghat'],
    map_search: 'Umananda Temple Guwahati Assam',
    tags: ['umananda', 'shiva temple', 'peacock island', 'brahmaputra', 'guwahati'],
    summary: 'Historic 17th-century Shiva temple situated on Peacock Island, the world’s smallest inhabited river island.',
    description: 'Built in 1694 by Ahom King Gadadhar Singha, Umananda Temple sits on Peacock Island (Bhasmacala) in the middle of the Brahmaputra River. According to mythology, Lord Shiva burned Kamadeva to ashes here. Also home to endangered golden langurs.',
    image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=600&auto=format&fit=crop&q=80',
  },
  'assam-state-museum': {
    city_key: 'guwahati',
    categoryBucket: 'museums',
    category: 'museum',
    topic: 'History & Ethnography',
    subtopic: 'State Historical Archive',
    area: 'Dighalipukhuri, Guwahati',
    lat: 26.1867,
    lng: 91.7511,
    opening_hours: '10:00 AM - 05:00 PM (Closed Mondays)',
    visiting_hours: '10:00 AM - 05:00 PM',
    timings: { opening_time: '10:00 AM', closing_time: '05:00 PM', closed_days: ['Monday'], status: 'VERIFIED' },
    fees: { domestic: 20, international: 100, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹20 (Indians), ₹100 (Foreigners)',
    suggested_duration: '1.5–2 hours',
    best_time_to_visit: 'Year-round',
    best_for: ['heritage', 'history', 'culture'],
    visitor_notes: ['Photography inside galleries requires permission'],
    map_search: 'Assam State Museum Guwahati',
    tags: ['museum', 'history', 'antiquities', 'guwahati', 'assam'],
    summary: 'One of the premier archaeological and ethnographic museums in Northeast India.',
    description: 'Established in 1940 by the Kamarupa Anusandhan Samiti, the Assam State Museum displays priceless collections of medieval stone sculptures, royal Ahom copper plate charters, medieval weapons, tribal textiles, and natural history specimens.',
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&auto=format&fit=crop&q=80',
  },
  'srimanta-sankardev-kalakshetra': {
    city_key: 'guwahati',
    categoryBucket: 'heritage',
    category: 'cultural_institution',
    topic: 'Arts & Culture',
    subtopic: 'Assamese Cultural Complex',
    area: 'Panjabari, Guwahati',
    lat: 26.1264,
    lng: 91.8175,
    opening_hours: '10:00 AM - 07:00 PM',
    visiting_hours: '10:00 AM - 07:00 PM',
    timings: { opening_time: '10:00 AM', closing_time: '07:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 30, international: 100, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹30 (Adults), ₹10 (Children)',
    suggested_duration: '2–3 hours',
    best_time_to_visit: 'October to April',
    best_for: ['culture', 'heritage', 'photography'],
    visitor_notes: ['Light & Sound show in the evening'],
    map_search: 'Srimanta Sankardev Kalakshetra Guwahati',
    tags: ['kalakshetra', 'culture', 'assamese heritage', 'guwahati', 'assam'],
    summary: 'Grand cultural institution showcasing the diverse indigenous arts and legacy of Saint Sankardev.',
    description: 'Spanning over 10 hectares, this premier cultural centre is named after the medieval saint-scholar Srimanta Sankardev. Features the Sahitya Bhawan library, Lalit Kala Bhawan art gallery, heritage museum displaying tribal models, and open-air amphitheatre.',
    image_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=600&auto=format&fit=crop&q=80',
  },
  'pobitora-wildlife-sanctuary': {
    city_key: 'mayong',
    categoryBucket: 'nature_parks_zoo',
    category: 'wildlife_sanctuary',
    topic: 'Wildlife & Nature',
    subtopic: 'Highest Rhino Density Sanctuary',
    area: 'Morigaon District',
    lat: 26.2167,
    lng: 92.0500,
    opening_hours: '06:30 AM - 03:00 PM',
    visiting_hours: '06:30 AM - 03:00 PM',
    timings: { opening_time: '06:30 AM', closing_time: '03:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 50, international: 500, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹50 (Indians), ₹500 (Foreigners); Jeep/Elephant safari extra',
    suggested_duration: '3–4 hours',
    best_time_to_visit: 'November to April',
    best_for: ['wildlife', 'nature', 'photography'],
    visitor_notes: ['Book morning elephant safari in advance'],
    map_search: 'Pobitora Wildlife Sanctuary Assam',
    tags: ['pobitora', 'rhino', 'wildlife', 'mayong', 'assam'],
    summary: 'Wildlife sanctuary holding the world’s highest ecological density of Greater One-Horned Rhinoceros.',
    description: 'Covering 38.8 square kilometers in the floodplains of the Brahmaputra, Pobitora is home to over 100 one-horned rhinos, wild boars, Asiatic buffaloes, and over 375 migratory and resident bird species in its vast wetlands.',
    image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80',
  },
  'kaziranga-national-park': {
    city_key: 'kohora',
    categoryBucket: 'nature_parks_zoo',
    category: 'unesco_national_park',
    topic: 'Wildlife & UNESCO Reserve',
    subtopic: 'Home of the Great Indian Rhino',
    area: 'Golaghat & Nagaon Districts',
    lat: 26.5862,
    lng: 93.4116,
    opening_hours: '07:30 AM - 04:00 PM (November to April)',
    visiting_hours: '07:30 AM - 04:00 PM',
    timings: { opening_time: '07:30 AM', closing_time: '04:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 100, international: 650, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹100 (Indians), ₹650 (Foreigners); Safaris extra',
    suggested_duration: 'Full Day (4–6 hours)',
    best_time_to_visit: 'November to April',
    best_for: ['wildlife', 'nature', 'unesco'],
    visitor_notes: ['Park closed during monsoon (May to October)'],
    map_search: 'Kaziranga National Park Assam',
    tags: ['kaziranga', 'unesco', 'one horned rhino', 'tiger reserve', 'assam'],
    summary: 'UNESCO World Heritage Site hosting two-thirds of the world’s Great One-Horned Rhinoceroses.',
    description: 'Spanning over 1,000 square kilometers along the Brahmaputra River, Kaziranga is a globally celebrated conservation triumph. In addition to over 2,600 one-horned rhinos, it is a Project Tiger reserve harboring elephants, wild water buffaloes, swamp deer, and rich birdlife.',
    image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80',
  },
  'manas-national-park': {
    city_key: 'bansbari',
    categoryBucket: 'nature_parks_zoo',
    category: 'unesco_biosphere',
    topic: 'Wildlife & UNESCO Reserve',
    subtopic: 'Eastern Himalayan Foothills Biosphere',
    area: 'Baksa District',
    lat: 26.7324,
    lng: 91.0189,
    opening_hours: '06:00 AM - 03:00 PM',
    visiting_hours: '06:00 AM - 03:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '03:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 50, international: 500, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹50 (Indians), ₹500 (Foreigners)',
    suggested_duration: '4–6 hours',
    best_time_to_visit: 'November to April',
    best_for: ['wildlife', 'nature', 'unesco'],
    visitor_notes: ['River rafting on Manas River available at Bansbari'],
    map_search: 'Manas National Park Assam',
    tags: ['manas', 'unesco', 'golden langur', 'tiger reserve', 'assam'],
    summary: 'UNESCO World Heritage wildlife reserve, Project Tiger, and Elephant Reserve at the foothills of the Himalayas.',
    description: 'Manas is celebrated for its unique biodiversity along the crystal-clear Manas River adjoining Bhutan. It is the only habitat sheltering rare species like the Golden Langur, Pygmy Hog, Hispid Hare, and Assam Roofed Turtle alongside Royal Bengal Tigers and Asian Elephants.',
    image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80',
  },
  'orang-national-park': {
    city_key: 'orang',
    categoryBucket: 'nature_parks_zoo',
    category: 'national_park',
    topic: 'Wildlife & Nature',
    subtopic: 'Rhino & Tiger Haven',
    area: 'Darrang & Sonitpur Districts',
    lat: 26.5492,
    lng: 92.3425,
    opening_hours: '07:00 AM - 03:00 PM',
    visiting_hours: '07:00 AM - 03:00 PM',
    timings: { opening_time: '07:00 AM', closing_time: '03:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 50, international: 250, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹50 (Indians), ₹250 (Foreigners)',
    suggested_duration: '3–4 hours',
    best_time_to_visit: 'November to April',
    best_for: ['wildlife', 'nature', 'photography'],
    visitor_notes: ['Jeep safari recommended for viewing rhinos'],
    map_search: 'Orang National Park Assam',
    tags: ['orang', 'rhino', 'tiger', 'national park', 'assam'],
    summary: 'National Park on the north bank of the Brahmaputra, nicknamed the Mini Kaziranga.',
    description: 'Spanning 79 square kilometers of alluvial grasslands, marshes, and evergreen forest patches, Orang National Park has a landscape mirroring Kaziranga. It is a critical stronghold for over 100 Greater One-Horned Rhinos, wild elephants, and Royal Bengal tigers.',
    image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80',
  },
  'nameri-national-park': {
    city_key: 'bhalukpong',
    categoryBucket: 'nature_parks_zoo',
    category: 'national_park',
    topic: 'Wildlife & Nature',
    subtopic: 'Eastern Himalayan Foothills Park',
    area: 'Sonitpur District',
    lat: 27.0125,
    lng: 92.6517,
    opening_hours: '06:00 AM - 04:00 PM',
    visiting_hours: '06:00 AM - 04:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '04:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 50, international: 250, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹50 (Indians), ₹250 (Foreigners); Forest guide mandatory',
    suggested_duration: '3–5 hours',
    best_time_to_visit: 'November to April',
    best_for: ['nature', 'adventure', 'birdwatching'],
    visitor_notes: ['Walking forest safaris permitted with armed forest guard'],
    map_search: 'Nameri National Park Assam',
    tags: ['nameri', 'birding', 'white winged wood duck', 'rafting', 'assam'],
    summary: 'Foothill sanctuary celebrated for walking safaris, river rafting, and the rare white-winged wood duck.',
    description: 'Located along the Jia Bhoroli River in the foothills of the Eastern Himalayas, Nameri is a birder\'s paradise with over 300 bird species including four species of Hornbill and the critically endangered state bird of Assam, the White-Winged Wood Duck (Deo Hah).',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
  },
  'majuli-island': {
    city_key: 'majuli',
    categoryBucket: 'heritage',
    category: 'river_island',
    topic: 'Culture & Living Heritage',
    subtopic: 'Vaishnavite Satra Island',
    area: 'Brahmaputra River, Majuli',
    lat: 26.9634,
    lng: 94.2215,
    opening_hours: 'Open 24 Hours; Satras open 08:00 AM - 05:00 PM',
    visiting_hours: '08:00 AM - 05:00 PM',
    timings: { opening_time: '08:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry; Ferry from Nimati Ghat (Jorhat) ₹15 - ₹30',
    suggested_duration: '1–2 Days',
    best_time_to_visit: 'October to March (Raas Mahotsav in November)',
    best_for: ['culture', 'heritage', 'photography'],
    visitor_notes: ['Visit Samaguri Satra for traditional bamboo mask making'],
    map_search: 'Majuli Island Assam',
    tags: ['majuli', 'river island', 'satra', 'neo vaishnavism', 'brahmaputra'],
    summary: 'The world\'s largest inhabited river island, preserving five centuries of Assamese spiritual traditions.',
    description: 'Shaped by the shifting channels of the Brahmaputra and Subansiri rivers, Majuli is the heartland of Assamese neo-Vaishnavite culture established by Srimanta Sankardev in the 15th century. Home to 22 ancient Satras (including Kamalabari, Auniati, and Samaguri), mask-making artisans, and Mishing tribal villages.',
    image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=600&auto=format&fit=crop&q=80',
  },
  'sivasagar-sivadol': {
    city_key: 'sivasagar',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual & Ahom Heritage',
    subtopic: 'Tallest Shiva Temple in India',
    area: 'Sivasagar Town',
    lat: 26.9881,
    lng: 94.6333,
    opening_hours: '06:00 AM - 08:00 PM',
    visiting_hours: '06:00 AM - 08:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '08:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry',
    suggested_duration: '1–1.5 hours',
    best_time_to_visit: 'October to March (Maha Shivaratri in March)',
    best_for: ['heritage', 'spiritual', 'architecture'],
    visitor_notes: ['Overlooks the monumental 129-acre Sivasagar Borpukhuri tank'],
    map_search: 'Sivasagar Sivadol Assam',
    tags: ['sivadol', 'ahom architecture', 'sivasagar', 'shiva temple', 'assam'],
    summary: 'Ancient 18th-century Shiva temple whose 104-foot spire makes it one of the tallest Shiva temples in India.',
    description: 'Constructed in 1734 by Queen Ambika, wife of Ahom King Swargadeo Siba Singha, Sivasagar Sivadol rises 32 meters high on the bank of the vast Borpukhuri tank. Its shikhara is crowned by a 7-foot tall pure gold dome (Kalasha).',
    image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=600&auto=format&fit=crop&q=80',
  },
  'rang-ghar': {
    city_key: 'sivasagar',
    categoryBucket: 'monuments',
    category: 'heritage_monument',
    topic: 'Monuments & Architecture',
    subtopic: 'Asia’s Oldest Royal Amphitheater',
    area: 'Rupahi Pathar, Sivasagar',
    lat: 26.9686,
    lng: 94.6206,
    opening_hours: '09:00 AM - 05:00 PM',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 25, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹25 (Indians), ₹300 (Foreigners)',
    suggested_duration: '1–2 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Roof shaped like an inverted Ahom royal longboat'],
    map_search: 'Rang Ghar Sivasagar Assam',
    tags: ['rang ghar', 'ahom monument', 'amphitheater', 'sivasagar', 'assam'],
    summary: 'Two-storey royal pavilion built in 1746, recognized as one of the oldest surviving royal sports amphitheaters in Asia.',
    description: 'Built by Ahom King Swargadeo Pramatta Singha in 1744–1751, Rang Ghar was the royal sporting amphitheater from where Ahom kings and nobles watched indigenous games, buffalo fights, and wrestling matches. Its unique roof is crafted like an inverted Ahom boat.',
    image_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=600&auto=format&fit=crop&q=80',
  },
  'talatal-ghar': {
    city_key: 'sivasagar',
    categoryBucket: 'monuments',
    category: 'palace_heritage',
    topic: 'Monuments & Forts',
    subtopic: 'Subterranean 7-Storey Ahom Palace',
    area: 'Rangpur, Sivasagar',
    lat: 26.9536,
    lng: 94.6289,
    opening_hours: '09:00 AM - 05:00 PM',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 25, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹25 (Indians), ₹300 (Foreigners)',
    suggested_duration: '1–2 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'architecture'],
    visitor_notes: ['Underground storeys and secret escape tunnels are closed for visitor safety'],
    map_search: 'Talatal Ghar Sivasagar Assam',
    tags: ['talatal ghar', 'palace', 'ahom', 'sivasagar', 'assam'],
    summary: 'Imposing 18th-century palace citadel featuring four storeys above ground and three subterranean floors with secret tunnels.',
    description: 'Constructed by King Swargadeo Rajeswar Singha in 1751–1769, Talatal Ghar served as a grand military base and palace. It was engineered with indigenous organic cements made of sticky rice and duck eggs, and featured secret subterranean escape tunnels leading to the Dikhow River.',
    image_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=600&auto=format&fit=crop&q=80',
  },
  'charaideo-maidams': {
    city_key: 'sonari',
    categoryBucket: 'monuments',
    category: 'unesco_heritage',
    topic: 'UNESCO World Heritage',
    subtopic: 'Pyramids of Assam & Royal Mounds',
    area: 'Charaideo Hillocks, near Sonari',
    lat: 26.9367,
    lng: 94.8694,
    opening_hours: '09:00 AM - 05:00 PM',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 25, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹25 (Indians), ₹300 (Foreigners)',
    suggested_duration: '2–3 hours',
    best_time_to_visit: 'October to March',
    best_for: ['unesco', 'heritage', 'history'],
    visitor_notes: ['UNESCO World Heritage site inscribed in 2024'],
    map_search: 'Charaideo Maidams Assam',
    tags: ['charaideo', 'unesco', 'maidams', 'ahom pyramids', 'assam'],
    summary: 'UNESCO World Heritage Site: the monumental earthen tumuli and royal burial mounds of the Ahom dynasty.',
    description: 'Established in 1253 AD by first Ahom King Chaolung Sukaphaa as the dynasty\'s first capital, Charaideo was the ancestral necropolis where Ahom kings and queens were buried. The over 90 vaulted earthen mounds (Maidams) resemble Egyptian pyramids and showcase extraordinary medieval funerary engineering.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
  },
  haflong: {
    city_key: 'haflong',
    categoryBucket: 'nature_parks_zoo',
    category: 'hill_station',
    topic: 'Nature & Hills',
    subtopic: 'Barail Range Hill Resort',
    area: 'Dima Hasao Hills',
    lat: 25.1764,
    lng: 93.0236,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '06:00 AM - 06:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry',
    suggested_duration: 'Full Day (4–6 hours)',
    best_time_to_visit: 'October to April',
    best_for: ['nature', 'hills', 'scenic'],
    visitor_notes: ['Take the scenic heritage rail route through the Barail mountains'],
    map_search: 'Haflong Hill Station Assam',
    tags: ['haflong', 'hill station', 'haflong lake', 'dima hasao', 'assam'],
    summary: 'Assam’s only hill station, celebrated for Haflong Lake, hanging bridge, and misty mountain views.',
    description: 'Nicknamed the "White Ant Hillock" and "Scotland of Assam", Haflong sits at 680 meters amidst the Barail mountains. Features the central Haflong Lake, suspension footbridge, orange orchards, and proximity to Jatinga ridge known for legendary migratory bird phenomena.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
  },
};

// =========================================================
// 5. HELPER TO BUILD STATE BUNDLE
// =========================================================
function buildStateBundle(stateId, stateName, stateCode, capital, region, citiesDef, placesSource, placesDetails, overview, stories, heroUrl) {
  const cityMap = {};
  for (const [cKey, cDef] of Object.entries(citiesDef)) {
    cityMap[cKey] = {
      ...cDef,
      places_count: 0,
      heritage: [],
      monuments: [],
      museums: [],
      tourist_places: [],
      religious_cultural: [],
      nature_parks_zoo: [],
      places: [],
    };
  }

  for (const srcPlace of placesSource) {
    const pId = srcPlace.id || srcPlace.place_id;
    const details = placesDetails[pId];
    if (!details) {
      throw new Error(`Missing details definition for place ${pId}`);
    }
    const cKey = details.city_key;
    if (!cityMap[cKey]) {
      throw new Error(`City key ${cKey} not found in state ${stateId}`);
    }

    const cityMeta = cityMap[cKey];

    const fullPlace = {
      id: pId,
      name: srcPlace.name,
      slug: pId,
      place_type: srcPlace.category || details.category || 'attraction',
      category: srcPlace.category || details.category || 'heritage',
      categoryBucket: details.categoryBucket,
      topic: details.topic,
      subtopic: details.subtopic,
      area: srcPlace.area || details.area,
      city: cityMeta.name,
      city_id: cityMeta.id,
      state: stateName,
      state_id: stateId,
      lat: details.lat,
      lng: details.lng,
      coordinates: { lat: details.lat, lng: details.lng },
      summary: srcPlace.description || details.summary,
      description: srcPlace.description || details.description,
      short_description: details.summary || srcPlace.description,
      detailed_description: srcPlace.description || details.description,
      best_for: srcPlace.best_for || details.best_for || ['heritage', 'culture', 'photography'],
      suggested_duration: srcPlace.suggested_duration || details.suggested_duration,
      best_time_to_visit: srcPlace.best_time_to_visit || details.best_time_to_visit || 'October to March',
      entry_fee: srcPlace.entry_fee || details.entry_fee,
      opening_hours: srcPlace.opening_hours || details.opening_hours,
      visiting_hours: srcPlace.opening_hours || details.visiting_hours,
      timings: details.timings,
      fees: details.fees,
      visitor_notes: srcPlace.visitor_notes || details.visitor_notes || ['Check local timings before visiting'],
      map_search: srcPlace.map_search || `${srcPlace.name} ${stateName}`,
      tags: srcPlace.tags || details.tags,
      image_url: details.image_url,
      thumbnail_url: details.thumbnail_url,
      attribution: `${stateName} Tourism Development Corporation`,
      source_name: `${stateName} Tourism`,
      source_url: `https://tourism.${stateId}.gov.in`,
      source_page: `https://tourism.${stateId}.gov.in`,
      source_type: 'tier1_official',
      source_quality: 'official_site',
      verification_status: 'verified',
      status: 'VERIFIED',
      data_confidence: 'official',
      last_verified_on: '2026-09-11',
      last_verified_at: '2026-09-11T12:00:00.000Z',
      features: { map: true, navigation: true, ai: true, '3d': false },
      sources: [
        {
          source_name: `${stateName} Tourism Development Corporation`,
          source_url: `https://tourism.${stateId}.gov.in`,
          source_type: 'official_tourism_board',
          accessed_on: '2026-09-11',
          verification_status: 'verified',
        },
      ],
    };

    const bucket = details.categoryBucket;
    cityMap[cKey][bucket].push(fullPlace);
    cityMap[cKey].places.push(fullPlace);
    cityMap[cKey].places_count += 1;
  }

  const citiesArray = Object.values(cityMap);
  const totalPlacesCount = citiesArray.reduce((sum, c) => sum + c.places_count, 0);

  const stateObject = {
    id: stateId,
    name: stateName,
    code: stateCode,
    capital: capital,
    region: region,
    region_type: 'state',
    hero_image_url: heroUrl,
    total_cities: citiesArray.length,
    total_attractions: totalPlacesCount,
    official_tourism_url: `https://tourism.${stateId}.gov.in`,
    heritage_overview: overview,
    description: overview,
    active_stories: stories,
    cities: citiesArray,
    hero_image: {
      image_url: heroUrl,
      source_url: `https://tourism.${stateId}.gov.in`,
      source_name: `${stateName} Tourism`,
      creator: 'Official Tourism Board',
      license: 'Public Domain / Verified',
      verification_status: 'verified',
      verified_at: '2026-09-11T12:00:00.000Z',
    },
  };

  return { stateObject, citiesArray, totalPlacesCount };
}

// Build Andhra Pradesh bundle
const apBundle = buildStateBundle(
  'andhra-pradesh',
  'Andhra Pradesh',
  'AP',
  'Amaravati',
  'Southern India',
  AP_CITIES,
  apSource.places,
  AP_PLACES_DETAILS,
  'Jewel of Southern India: Sacred Tirumala Venkateswara shrine, misty Araku Valley coffee hills, Bay of Bengal beaches, Vijayanagara Lepakshi temple, and Godavari river canyons.',
  [
    'Sacred pilgrimage at Tirumala Venkateswara and Srikalahasti Vayu Lingam.',
    'Breathtaking Eastern Ghats in Araku Valley and the prehistoric Borra Caves.',
    'Rich cultural legacy from Amaravati Buddhist stupas to Kondapalli toycraft and Papikondalu.',
  ],
  'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80'
);

// Build Assam bundle
const assamBundle = buildStateBundle(
  'assam',
  'Assam',
  'AS',
  'Guwahati',
  'Northeastern India',
  ASSAM_CITIES,
  assamSource.places,
  ASSAM_PLACES_DETAILS,
  'The Land of Red River & Blue Hills: World heritage sanctuaries of Kaziranga and Manas, sacred Kamakhya Temple on Nilachal Hill, majestic Majuli river island, and royal Ahom monuments.',
  [
    'UNESCO World Heritage wild sanctuaries of Kaziranga, Manas, and Charaideo Maidams.',
    'Sacred Shakta power at Kamakhya Temple and island shrine of Umananda.',
    'Six-century imperial legacy of the Ahom kingdom at Sivasagar and Rang Ghar.',
  ],
  'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80'
);

console.log(`✓ Built AP bundle: ${apBundle.citiesArray.length} cities, ${apBundle.totalPlacesCount} places.`);
console.log(`✓ Built Assam bundle: ${assamBundle.citiesArray.length} cities, ${assamBundle.totalPlacesCount} places.`);

if (apBundle.totalPlacesCount !== 15) throw new Error(`Expected 15 AP places, got ${apBundle.totalPlacesCount}`);
if (assamBundle.totalPlacesCount !== 15) throw new Error(`Expected 15 Assam places, got ${assamBundle.totalPlacesCount}`);

// =========================================================
// 6. UPDATE data/india_tourism_database.json
// =========================================================
const itdb = readJson(itdbJsonPath);

const apIndex = itdb.states.findIndex((s) => s.id === 'andhra-pradesh');
if (apIndex === -1) throw new Error('Andhra Pradesh not found in itdb');
itdb.states[apIndex] = apBundle.stateObject;

const assamIndex = itdb.states.findIndex((s) => s.id === 'assam');
if (assamIndex === -1) throw new Error('Assam not found in itdb');
itdb.states[assamIndex] = assamBundle.stateObject;

// Recalculate top-level counts
itdb.cities_count = itdb.states.reduce((sum, s) => sum + (s.cities ? s.cities.length : 0), 0);
itdb.attractions_count = itdb.states.reduce((sum, s) => {
  let count = 0;
  if (Array.isArray(s.cities)) {
    for (const c of s.cities) {
      if (Array.isArray(c.places) && c.places.length > 0) {
        count += c.places.length;
      } else {
        count += (c.heritage?.length || 0) +
          (c.monuments?.length || 0) +
          (c.museums?.length || 0) +
          (c.tourist_places?.length || 0) +
          (c.religious_cultural?.length || 0) +
          (c.nature_parks_zoo?.length || 0);
      }
    }
  }
  return sum + count;
}, 0);

fs.writeFileSync(itdbJsonPath, JSON.stringify(itdb, null, 2), 'utf8');
console.log(`✓ Updated data/india_tourism_database.json. Total states: ${itdb.states.length}, cities: ${itdb.cities_count}, attractions: ${itdb.attractions_count}`);

// =========================================================
// 7. UPDATE src/data/indiaTourismDatabase.ts
// =========================================================
const tsContent = `// Auto-generated Master Database Export
import { IndiaHierarchyDatabase } from '../../types/indiaHierarchy';

export const INDIA_TOURISM_DATABASE: IndiaHierarchyDatabase = ${JSON.stringify(itdb, null, 2)} as unknown as IndiaHierarchyDatabase;
`;
fs.writeFileSync(itdbTsPath, tsContent, 'utf8');
console.log('✓ Updated src/data/indiaTourismDatabase.ts');

// =========================================================
// 8. UPDATE data/cities.json
// =========================================================
const existingCities = readJson(citiesJsonPath);

// Keep all cities EXCEPT andhra-pradesh and assam
const filteredCities = existingCities.filter((c) => c.state_id !== 'andhra-pradesh' && c.state_id !== 'assam');

const makeCityEntries = (stateId, citiesArray) =>
  citiesArray.map((c) => ({
    id: c.id,
    state_id: stateId,
    name: c.name,
    slug: c.id,
    entity_type: c.city_type || 'city',
    district: c.district,
    latitude: c.lat,
    longitude: c.lng,
    lat: c.lat,
    lng: c.lng,
    short_description: c.short_description || c.description,
    description: c.description,
    official_url: c.official_url || `https://tourism.${stateId}.gov.in`,
    status: 'active',
    hero_image_url: c.hero_image_url,
    places_count: c.places_count,
    tagline: c.tagline,
  }));

const newApCities = makeCityEntries('andhra-pradesh', apBundle.citiesArray);
const newAssamCities = makeCityEntries('assam', assamBundle.citiesArray);

const finalCities = [...filteredCities, ...newApCities, ...newAssamCities];
fs.writeFileSync(citiesJsonPath, JSON.stringify(finalCities, null, 2), 'utf8');
console.log(`✓ Updated data/cities.json. Non-target cities: ${filteredCities.length}, AP: ${newApCities.length}, Assam: ${newAssamCities.length}, Total: ${finalCities.length}`);

// =========================================================
// 9. UPDATE data/states.json
// =========================================================
const statesList = readJson(statesJsonPath);

const apStateIdx = statesList.findIndex((s) => s.id === 'andhra-pradesh');
if (apStateIdx !== -1) {
  statesList[apStateIdx] = {
    ...statesList[apStateIdx],
    total_cities: apBundle.citiesArray.length,
    total_attractions: apBundle.totalPlacesCount,
    official_tourism_url: apBundle.stateObject.official_tourism_url,
    description: apBundle.stateObject.description,
  };
}

const assamStateIdx = statesList.findIndex((s) => s.id === 'assam');
if (assamStateIdx !== -1) {
  statesList[assamStateIdx] = {
    ...statesList[assamStateIdx],
    total_cities: assamBundle.citiesArray.length,
    total_attractions: assamBundle.totalPlacesCount,
    official_tourism_url: assamBundle.stateObject.official_tourism_url,
    description: assamBundle.stateObject.description,
  };
}

fs.writeFileSync(statesJsonPath, JSON.stringify(statesList, null, 2), 'utf8');
console.log('✓ Updated data/states.json');

// =========================================================
// 10. WRITE REGIONAL ARCHIVES
// =========================================================
const apPlaces = [];
for (const c of apBundle.citiesArray) {
  apPlaces.push(...c.places);
}
if (!fs.existsSync(path.join(rootDir, 'data', 'andhra-pradesh'))) {
  fs.mkdirSync(path.join(rootDir, 'data', 'andhra-pradesh'), { recursive: true });
}
fs.writeFileSync(path.join(rootDir, 'data', 'andhra-pradesh', 'places.json'), JSON.stringify(apPlaces, null, 2), 'utf8');
console.log(`✓ Wrote data/andhra-pradesh/places.json with ${apPlaces.length} places.`);

const assamPlaces = [];
for (const c of assamBundle.citiesArray) {
  assamPlaces.push(...c.places);
}
if (!fs.existsSync(path.join(rootDir, 'data', 'assam'))) {
  fs.mkdirSync(path.join(rootDir, 'data', 'assam'), { recursive: true });
}
fs.writeFileSync(path.join(rootDir, 'data', 'assam', 'places.json'), JSON.stringify(assamPlaces, null, 2), 'utf8');
console.log(`✓ Wrote data/assam/places.json with ${assamPlaces.length} places.`);

console.log('=== AP & Assam Integration Script Finished Successfully ===');
