import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, ''));

const odishaJsonPath = path.join(rootDir, 'data', 'odisha_tourist_places_city_assigned.json');
const rajasthanJsonPath = path.join(rootDir, 'data', 'rajasthan_tourist_places_city_assigned.json');
const itdbJsonPath = path.join(rootDir, 'data', 'india_tourism_database.json');
const itdbTsPath = path.join(rootDir, 'src', 'data', 'indiaTourismDatabase.ts');
const citiesJsonPath = path.join(rootDir, 'data', 'cities.json');
const statesJsonPath = path.join(rootDir, 'data', 'states.json');

console.log('=== Starting Odisha & Rajasthan Integration ===');

const odishaSource = readJson(odishaJsonPath);
const rajasthanSource = readJson(rajasthanJsonPath);

console.log(`Loaded Odisha source: ${odishaSource.places.length} places, ${odishaSource.cities.length} cities.`);
console.log(`Loaded Rajasthan source: ${rajasthanSource.places.length} places, ${rajasthanSource.cities.length} cities.`);

if (odishaSource.places.length !== 15) throw new Error(`Expected 15 Odisha places, got ${odishaSource.places.length}`);
if (rajasthanSource.places.length !== 20) throw new Error(`Expected 20 Rajasthan places, got ${rajasthanSource.places.length}`);

// ==========================================
// 1. ODISHA CITIES DEFINITIONS (10 Cities)
// ==========================================
const ODISHA_CITIES = {
  puri: {
    id: 'puri',
    name: 'Puri',
    canonical_name: 'Puri',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Puri',
    city_type: 'city',
    lat: 19.8135,
    lng: 85.8312,
    coordinates: { lat: 19.8135, lng: 85.8312 },
    tagline: 'Sacred Jagannath Dham & Golden Coastal Beach',
    description: 'Spiritual jewel of the Char Dham pilgrimage, home to the sacred 12th-century Jagannath Temple, vibrant Golden Beach, and world-renowned Pattachitra arts.',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['spiritual', 'heritage', 'nature'],
    prominence: 'Pilgrimage & Coastal Destination',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Odisha Tourism Development Corporation (OTDC) & Ministry of Tourism',
    short_description: 'Sacred Char Dham coastal city celebrated for the Jagannath Temple and Golden Beach.',
  },
  konark: {
    id: 'konark',
    name: 'Konark',
    canonical_name: 'Konark',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Puri',
    city_type: 'city',
    lat: 19.8876,
    lng: 86.0945,
    coordinates: { lat: 19.8876, lng: 86.0945 },
    tagline: 'Architectural Wonder of the Black Pagoda',
    description: 'Home to the magnificent UNESCO World Heritage 13th-century Sun Temple, celebrated globally for its massive stone chariot wheels and exquisite Kalinga architecture.',
    hero_image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'monuments'],
    prominence: 'World Heritage Landmark',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Archaeological Survey of India & Odisha Tourism',
    short_description: 'UNESCO World Heritage city famous for the monolithic 13th-century Sun Temple.',
  },
  chilika: {
    id: 'chilika',
    name: 'Chilika',
    canonical_name: 'Chilika',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Khordha',
    city_type: 'city',
    lat: 19.7165,
    lng: 85.3214,
    coordinates: { lat: 19.7165, lng: 85.3214 },
    tagline: 'Asia’s Largest Brackish Water Lagoon & Dolphin Sanctuary',
    description: 'Sprawling Ramsar wetland haven hosting endangered Irrawaddy dolphins, migratory bird wintering grounds at Nalabana, and tranquil island boat expeditions.',
    hero_image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'wildlife'],
    prominence: 'Eco-Tourism & Ramsar Site',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Chilika Development Authority & Odisha Tourism',
    short_description: 'Asia’s largest lagoon renowned for Irrawaddy dolphins and millions of migratory birds.',
  },
  bhubaneswar: {
    id: 'bhubaneswar',
    name: 'Bhubaneswar',
    canonical_name: 'Bhubaneswar',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Khordha',
    city_type: 'city',
    lat: 20.2961,
    lng: 85.8245,
    coordinates: { lat: 20.2961, lng: 85.8245 },
    tagline: 'Temple City of India & Modern Capital of Odisha',
    description: 'Ancient capital of Kalinga combining over 500 historic temples including Lingaraj, rock-cut Jain caves of Udayagiri & Khandagiri, and modern civic infrastructure.',
    hero_image_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'culture', 'nature'],
    prominence: 'State Capital',
    is_capital: true,
    capital_status: 'state_capital',
    verification_status: 'verified',
    source_provenance: 'Odisha Tourism Development Corporation & Ministry of Tourism',
    short_description: 'The Temple City of India, blending 7th-century shrines with lush botanical reserves.',
  },
  cuttack: {
    id: 'cuttack',
    name: 'Cuttack',
    canonical_name: 'Cuttack',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Cuttack',
    city_type: 'city',
    lat: 20.4625,
    lng: 85.8828,
    coordinates: { lat: 20.4625, lng: 85.8828 },
    tagline: 'Silver City & Historic Medieval Capital on the Mahanadi',
    description: 'Odisha’s former historic capital, famed for its intricate silver filigree (Tarakasi) craftsmanship, ancient Barabati Fort, and vibrant Bali Jatra river celebrations.',
    hero_image_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'crafts'],
    prominence: 'Commercial & Heritage Center',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Odisha Tourism & INTACH Cuttack',
    short_description: 'Historic Millennium City celebrated for medieval Barabati Fort and silver filigree art.',
  },
  baripada: {
    id: 'baripada',
    name: 'Baripada',
    canonical_name: 'Baripada',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Mayurbhanj',
    city_type: 'city',
    lat: 21.9346,
    lng: 86.7335,
    coordinates: { lat: 21.9346, lng: 86.7335 },
    tagline: 'Gateway to Similipal Biosphere & Royal Mayurbhanj Heritage',
    description: 'Headquarters of Mayurbhanj district, renowned as the entry point to Similipal Tiger Reserve, Mayurbhanj Chhau dance, and historic Bhanja royal palace.',
    hero_image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['wildlife', 'nature', 'culture'],
    prominence: 'District Headquarters & Wildlife Gateway',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Similipal Tiger Reserve & Odisha Tourism',
    short_description: 'Gateway to the UNESCO Similipal Biosphere Reserve and royal Mayurbhanj arts.',
  },
  rajnagar: {
    id: 'rajnagar',
    name: 'Rajnagar',
    canonical_name: 'Rajnagar',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Kendrapara',
    city_type: 'city',
    lat: 20.5756,
    lng: 86.7865,
    coordinates: { lat: 20.5756, lng: 86.7865 },
    tagline: 'Coastal Mangrove Sanctuary & Saltwater Crocodile Haven',
    description: 'Gateway to Bhitarkanika National Park, India’s premier tidal mangrove delta home to giant saltwater crocodiles, spotted deer, and pristine creek waterways.',
    hero_image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['wildlife', 'nature'],
    prominence: 'Eco-Tourism Destination',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Bhitarkanika Wildlife Sanctuary & Odisha Forest Dept',
    short_description: 'Coastal portal to the rich mangrove waterways and crocodile sanctuaries of Bhitarkanika.',
  },
  gopalpur: {
    id: 'gopalpur',
    name: 'Gopalpur',
    canonical_name: 'Gopalpur',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Ganjam',
    city_type: 'city',
    lat: 19.2606,
    lng: 84.9088,
    coordinates: { lat: 19.2606, lng: 84.9088 },
    tagline: 'Tranquil Maritime Seaport & Serene Casuarina Beach',
    description: 'Historic East India Company seaport transformed into a calm coastal haven, renowned for its heritage lighthouse, tranquil waters, and palm-fringed sands.',
    hero_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'heritage'],
    prominence: 'Coastal Resort Town',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Odisha Tourism & District Tourism Promotion Council Ganjam',
    short_description: 'Historic seaport and serene beach retreat with a functioning 19th-century lighthouse.',
  },
  daringbadi: {
    id: 'daringbadi',
    name: 'Daringbadi',
    canonical_name: 'Daringbadi',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Kandhamal',
    city_type: 'city',
    lat: 19.9079,
    lng: 84.1306,
    coordinates: { lat: 19.9079, lng: 84.1306 },
    tagline: 'Kashmir of Odisha & Serene Highland Hill Station',
    description: 'Scenic high-altitude hill resort in the Kandhamal plateau, blessed with fragrant pine forests, organic coffee gardens, lush valleys, and crisp winter breezes.',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'adventure'],
    prominence: 'Hill Station Retreat',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Kandhamal District Tourism & Odisha Tourism',
    short_description: 'Picturesque hill station featuring misty pine forests, coffee estates, and waterfalls.',
  },
  sambalpur: {
    id: 'sambalpur',
    name: 'Sambalpur',
    canonical_name: 'Sambalpur',
    state: 'Odisha',
    state_id: 'odisha',
    region: 'Eastern India',
    district: 'Sambalpur',
    city_type: 'city',
    lat: 21.4669,
    lng: 83.9812,
    coordinates: { lat: 21.4669, lng: 83.9812 },
    tagline: 'Cultural Hub of Western Odisha & Home to Hirakud Dam',
    description: 'Cultural powerhouse on the Mahanadi River, celebrated for the world-famous Sambalpuri handloom sarees, Samaleswari Temple, and monumental Hirakud Dam.',
    hero_image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['culture', 'nature', 'crafts'],
    prominence: 'Regional Hub of Western Odisha',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Sambalpur District Administration & Odisha Tourism',
    short_description: 'Western Odisha cultural capital renowned for Sambalpuri textiles and Hirakud Dam.',
  },
};

// ==========================================
// 2. ODISHA PLACES DETAILS (15 Places)
// ==========================================
const ODISHA_PLACES_DETAILS = {
  odisha_001: {
    city_key: 'puri',
    categoryBucket: 'religious_cultural',
    category: 'religious_cultural',
    topic: 'Spiritual Heritage',
    subtopic: 'Char Dham Temple',
    area: 'Bada Danda (Grand Road), Puri',
    lat: 19.8048,
    lng: 85.8179,
    opening_hours: '05:00 AM - 11:00 PM',
    visiting_hours: '05:00 AM - 11:00 PM',
    timings: { opening_time: '05:00 AM', closing_time: '11:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry (special pujas extra)',
    suggested_duration: '2 - 3 Hours',
    summary: 'Sacred 12th-century temple of Lord Jagannath, one of the four Char Dham pilgrimage sites, celebrated for the mega Rath Yatra.',
    description: 'Constructed by King Anantavarman Chodaganga Deva in the 12th century, this iconic temple enshrines Lord Jagannath along with brother Balabhadra and sister Subhadra. The temple is famous for its towering 65-meter deula, mysterious flag fluttering opposite to wind direction, the world\'s largest kitchen (Ananda Bazar) preparing Mahaprasad, and the internationally celebrated annual Chariot Festival (Ratha Yatra).',
    historical_significance: 'One of the holiest Char Dham sanctuaries in Hinduism, revered since ancient antiquity and celebrated in sacred Puranas.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
    tags: ['jagannath temple', 'char dham', 'puri', 'rath yatra', 'spiritual', 'odisha'],
  },
  odisha_002: {
    city_key: 'konark',
    categoryBucket: 'monuments',
    category: 'monuments',
    topic: 'Architecture & Monuments',
    subtopic: 'UNESCO Sun Temple',
    area: 'Konark Coastal Highway',
    lat: 19.8876,
    lng: 86.0945,
    opening_hours: '06:00 AM - 08:00 PM',
    visiting_hours: '06:00 AM - 08:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '08:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 40, international: 600, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹40 (Indians), ₹600 (Foreigners)',
    suggested_duration: '2 - 3 Hours',
    summary: 'Monumental 13th-century UNESCO World Heritage Sun Temple sculpted as a gigantic cosmic stone chariot.',
    description: 'Built in 1250 AD by King Narasimhadeva I of the Eastern Ganga Dynasty, Konark Sun Temple is an architectural summit of ancient Kalinga stonecraft. Designed as a mammoth chariot of the Sun God Surya, it features 24 exquisitely carved 12-spoked wheels acting as accurate astronomical sundials and seven horses galloping towards the dawn.',
    historical_significance: 'Designated a UNESCO World Heritage Site in 1984, praised by Rabindranath Tagore as a place where the language of stone surpasses the language of man.',
    image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=600&auto=format&fit=crop&q=80',
    tags: ['sun temple', 'konark', 'unesco', 'chariot', 'kalinga architecture', 'odisha'],
  },
  odisha_003: {
    city_key: 'puri',
    categoryBucket: 'nature_parks_zoo',
    category: 'nature_parks_zoo',
    topic: 'Nature & Coastal',
    subtopic: 'Beach & Marine Shoreline',
    area: 'Puri Sea Beach Promenade',
    lat: 19.7983,
    lng: 85.8249,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '05:00 AM - 09:00 PM',
    timings: { opening_time: '05:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry',
    suggested_duration: '1.5 - 2 Hours',
    summary: 'Golden sandy shore on the Bay of Bengal, famous for dramatic sunrises, sacred pilgrim bathing, and sand art.',
    description: 'Puri Beach (Golden Beach) is one of the most vibrant coastlines in Eastern India, certified with the prestigious Blue Flag tag at designated stretches for impeccable cleanliness and safety. Renowned globally for intricate sand sculptures by Padma Shri Sudarsan Pattnaik, evening seafood stalls, and lively beach markets.',
    historical_significance: 'Considered sacred as Mahodadhi, where millions of devotees take customary purifying dips before paying homage at the Jagannath Temple.',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80',
    tags: ['puri beach', 'golden beach', 'sand art', 'bay of bengal', 'blue flag', 'odisha'],
  },
  odisha_004: {
    city_key: 'chilika',
    categoryBucket: 'nature_parks_zoo',
    category: 'nature_parks_zoo',
    topic: 'Nature & Wetlands',
    subtopic: 'Brackish Lagoon & Dolphin Sanctuary',
    area: 'Satapada / Barkul, Chilika',
    lat: 19.7165,
    lng: 85.3214,
    opening_hours: '06:00 AM - 06:00 PM',
    visiting_hours: '06:00 AM - 05:30 PM',
    timings: { opening_time: '06:00 AM', closing_time: '05:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free access; boat safaris ₹1,200 - ₹2,500 per boat',
    suggested_duration: '3 - 5 Hours',
    summary: 'Asia\'s largest coastal lagoon and Ramsar Wetland site, famous for playful Irrawaddy dolphins and migratory birds.',
    description: 'Chilika Lake covers over 1,100 square kilometers across three districts of Odisha. It supports one of the world\'s only two surviving populations of Irrawaddy dolphins, predominantly spotted at Satapada. During winter, Nalabana Island becomes host to over one million migratory birds arriving from Siberia, Mongolia, and Central Asia.',
    historical_significance: 'Designated the first Indian wetland of international importance under the Ramsar Convention in 1981.',
    image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=600&auto=format&fit=crop&q=80',
    tags: ['chilika lake', 'dolphins', 'irrawaddy', 'ramsar wetland', 'satapada', 'odisha'],
  },
  odisha_005: {
    city_key: 'bhubaneswar',
    categoryBucket: 'heritage',
    category: 'heritage',
    topic: 'Archaeology & Heritage',
    subtopic: 'Rock-Cut Jain Caves',
    area: 'Khandagiri, Bhubaneswar',
    lat: 20.2592,
    lng: 85.7858,
    opening_hours: '09:00 AM - 06:00 PM',
    visiting_hours: '09:00 AM - 06:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 25, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹25 (Indians), ₹300 (Foreigners)',
    suggested_duration: '2 - 3 Hours',
    summary: 'Historic rock-cut cave complexes carved in the 1st-2nd century BCE under Emperor Kharavela for Jain monks.',
    description: 'The twin hills of Udayagiri (Sunrise Hill) and Khandagiri (Broken Hill) feature 33 partly artificial rock-cut caverns built during the Chedi dynasty. Udayagiri contains the famous Rani Gumpha (Queen\'s Cave) with two-storey reliefs, and Hathigumpha featuring the 17-line Brahmi inscription chronicling the military expeditions and civic works of King Kharavela.',
    historical_significance: 'Crucial epigraphical monument of ancient India, detailing early Jain monastic architecture and Kalinga imperial history.',
    image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=600&auto=format&fit=crop&q=80',
    tags: ['udayagiri', 'khandagiri', 'jain caves', 'kharavela', 'hathigumpha', 'bhubaneswar'],
  },
  odisha_006: {
    city_key: 'bhubaneswar',
    categoryBucket: 'religious_cultural',
    category: 'religious_cultural',
    topic: 'Spiritual Heritage',
    subtopic: 'Kalinga Architecture Temple',
    area: 'Old Town, Bhubaneswar',
    lat: 20.2382,
    lng: 85.8338,
    opening_hours: '06:00 AM - 09:00 PM',
    visiting_hours: '06:00 AM - 09:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry (Hindu devotees only in sanctum; viewing platform for all visitors)',
    suggested_duration: '1.5 - 2 Hours',
    summary: 'Majestic 11th-century temple representing the pinnacle of mature Kalinga architecture, dedicated to Lord Harihara.',
    description: 'The largest temple in Bhubaneswar, Lingaraj Temple stands inside a spacious compound with 108 subsidiary shrines. The central deula rises to an imposing 55 meters and is dedicated to Tribhuvaneswara (Lord of Three Worlds, Shiva combined with Vishnu as Harihara). The complex overlooks the sacred Bindusagar Lake.',
    historical_significance: 'Constructed by Somavamsi dynasty kings Jajati Keshari and completed by Lalatendu Keshari in the 11th century.',
    image_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1627993077753-907656552e71?w=600&auto=format&fit=crop&q=80',
    tags: ['lingaraj temple', 'kalinga architecture', 'harihara', 'bhubaneswar', 'spiritual', 'odisha'],
  },
  odisha_007: {
    city_key: 'bhubaneswar',
    categoryBucket: 'monuments',
    category: 'monuments',
    topic: 'Historical Monuments',
    subtopic: 'Buddhist Peace Pagoda',
    area: 'Dhauli Hills, Bhubaneswar',
    lat: 20.1924,
    lng: 85.8394,
    opening_hours: '06:00 AM - 07:00 PM',
    visiting_hours: '06:00 AM - 07:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '07:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry; Light & Sound show: ₹25',
    suggested_duration: '1.5 - 2 Hours',
    summary: 'Striking white peace pagoda atop Dhauli Hills marking Ashoka\'s conversion to Buddhism and non-violence.',
    description: 'Dhauli Shanti Stupa sits beside the Daya River where the monumental Kalinga War occurred in 261 BCE. Seeing the river turn crimson with bloodshed, Emperor Ashoka renounced conquest by war (Digvijaya) in favor of conquest through dharma (Dharmavijaya). The stupa was built jointly in 1972 by the Kalinga Nippon Buddha Sangha and the Government of Odisha.',
    historical_significance: 'Site of Emperor Ashoka\'s rock edicts inscribed in Prakrit and Brahmi script, declaring all men are his children.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
    tags: ['dhauli', 'shanti stupa', 'peace pagoda', 'ashoka', 'kalinga war', 'bhubaneswar'],
  },
  odisha_008: {
    city_key: 'bhubaneswar',
    categoryBucket: 'nature_parks_zoo',
    category: 'nature_parks_zoo',
    topic: 'Wildlife & Nature',
    subtopic: 'Zoological & Botanical Sanctuary',
    area: 'Nandankanan Road, Bhubaneswar',
    lat: 20.3958,
    lng: 85.8248,
    opening_hours: '08:00 AM - 05:00 PM (Closed Mondays)',
    visiting_hours: '08:00 AM - 05:00 PM',
    timings: { opening_time: '08:00 AM', closing_time: '05:00 PM', closed_days: ['Monday'], status: 'VERIFIED' },
    fees: { domestic: 50, international: 100, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹50 (Adults), ₹10 (Children), Safaris ₹60',
    suggested_duration: '3 - 4 Hours',
    summary: 'Internationally celebrated zoological garden nestled around Kanjia Lake, famous for white tigers and lion safaris.',
    description: 'Nandankanan, literally meaning "Garden of Heavens", covers 437 hectares across the Chandaka forest. It was the first zoo in the world where white tigers were bred in captivity and the first to breed Indian pangolins successfully. Features open-moated enclosures, ropeway over the lake, nocturnal animal house, and boat safaris.',
    historical_significance: 'Established in 1960 and declared a designated sanctuary in 1979, an exemplary hub for conservation biology in India.',
    image_url: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=600&auto=format&fit=crop&q=80',
    tags: ['nandankanan', 'zoo', 'white tiger', 'wildlife', 'safari', 'bhubaneswar'],
  },
  odisha_009: {
    city_key: 'cuttack',
    categoryBucket: 'heritage',
    category: 'heritage',
    topic: 'History & Forts',
    subtopic: 'Medieval Ganga Dynasty Fort',
    area: 'Biju Patnaik Colony, Cuttack',
    lat: 20.4856,
    lng: 85.8672,
    opening_hours: '08:00 AM - 06:00 PM',
    visiting_hours: '08:00 AM - 06:00 PM',
    timings: { opening_time: '08:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry',
    suggested_duration: '1.5 - 2 Hours',
    summary: '14th-century medieval citadel on the Mahanadi River, featuring an ornate stone gateway, deep moat, and earthen ramparts.',
    description: 'Built by the Ganga dynasty in the 14th century, Barabati Fort protected the strategic delta capital of Cuttack. Surviving remnants include an impressive arched gateway decorated with fine stone relief carvings, a moat, and the stone foundations of an ancient nine-storey palace described enthusiastically in Persian chronicles.',
    historical_significance: 'Strategic bastion of Odisha\'s medieval rulers, later occupied by the Mughals, Marathas, and British forces in 1803.',
    image_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=600&auto=format&fit=crop&q=80',
    tags: ['barabati fort', 'cuttack', 'ganga dynasty', 'mahanadi', 'heritage', 'odisha'],
  },
  odisha_010: {
    city_key: 'puri',
    categoryBucket: 'heritage',
    category: 'heritage',
    topic: 'Culture & Handicrafts',
    subtopic: 'Artisanal Heritage Village',
    area: 'Raghurajpur Village, near Puri',
    lat: 19.8974,
    lng: 85.8267,
    opening_hours: '08:00 AM - 07:00 PM',
    visiting_hours: '08:00 AM - 07:00 PM',
    timings: { opening_time: '08:00 AM', closing_time: '07:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry (craft purchases optional)',
    suggested_duration: '2 - 3 Hours',
    summary: 'World-renowned artisan village where every household preserves the age-old master craft of Pattachitra cloth paintings.',
    description: 'Nestled amidst coconut and palm groves 14 km from Puri, Raghurajpur is India\'s premier heritage crafts village. Every villager is an artisan specializing in Pattachitra (cloth-based scroll painting with mineral pigments), palm leaf carvings (Talapatra Chitra), cow dung toys, and wood sculptures. It is also the birthplace of legendary Odissi maestro Guru Kelucharan Mohapatra and the traditional Gotipua dance.',
    historical_significance: 'Recognized by INTACH in 2000 as Odisha\'s first Heritage Crafts Village, keeping unbroken millennium-old artistic traditions alive.',
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&auto=format&fit=crop&q=80',
    tags: ['raghurajpur', 'pattachitra', 'handicrafts', 'gotipua', 'heritage village', 'puri'],
  },
  odisha_011: {
    city_key: 'baripada',
    categoryBucket: 'nature_parks_zoo',
    category: 'nature_parks_zoo',
    topic: 'Wildlife & Nature',
    subtopic: 'National Park & Tiger Reserve',
    area: 'Mayurbhanj District Highlands',
    lat: 21.8492,
    lng: 86.4172,
    opening_hours: '06:00 AM - 03:00 PM (Entry permitted until 09:00 AM)',
    visiting_hours: '06:00 AM - 05:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 100, international: 1000, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹100 (Indians), ₹1,000 (Foreigners); vehicle entry extra',
    suggested_duration: 'Full Day Safari (6 - 8 Hours)',
    summary: 'UNESCO Biosphere Reserve boasting lush Sal forest ranges, rare pseudo-melanistic black tigers, and cascading waterfalls.',
    description: 'Covering 2,750 square kilometers, Similipal is the 7th largest national park in India. Named after the red silk cotton (Semul) trees that blossom here, it features dramatic escarpments, Barehipani Falls (399m) and Joranda Falls (150m), and is the only habitat on Earth hosting wild pseudo-melanistic Royal Bengal tigers.',
    historical_significance: 'Part of the UNESCO World Network of Biosphere Reserves since 2009 and one of India\'s original nine Project Tiger reserves (1973).',
    image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80',
    tags: ['similipal', 'tiger reserve', 'biosphere', 'melanistic tiger', 'baripada', 'odisha'],
  },
  odisha_012: {
    city_key: 'rajnagar',
    categoryBucket: 'nature_parks_zoo',
    category: 'nature_parks_zoo',
    topic: 'Wildlife & Wetlands',
    subtopic: 'Mangrove National Park & Crocodile Sanctuary',
    area: 'Kendrapara Coastal Delta',
    lat: 20.7206,
    lng: 86.8683,
    opening_hours: '07:00 AM - 05:00 PM',
    visiting_hours: '07:00 AM - 05:00 PM',
    timings: { opening_time: '07:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 40, international: 500, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹40 (Indians), ₹500 (Foreigners); boat hire extra',
    suggested_duration: '4 - 6 Hours',
    summary: 'Vibrant mangrove estuary and Ramsar site sheltering India\'s largest population of giant saltwater crocodiles.',
    description: 'Bhitarkanika is India\'s second largest mangrove ecosystem after the Sundarbans, created by the rivers Brahmani, Baitarani, and Dhamra. The park is home to over 1,700 saltwater crocodiles (including record-holding specimens exceeding 20 feet), king cobras, spotted deer, wild boars, and 215 bird species.',
    historical_significance: 'Designated as a National Park in 1998 and Ramsar Wetland in 2002, adjacent to the Gahirmatha Olive Ridley sea turtle rookery.',
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&auto=format&fit=crop&q=80',
    tags: ['bhitarkanika', 'mangrove', 'crocodile', 'ramsar', 'rajnagar', 'odisha'],
  },
  odisha_013: {
    city_key: 'gopalpur',
    categoryBucket: 'nature_parks_zoo',
    category: 'nature_parks_zoo',
    topic: 'Nature & Coastal',
    subtopic: 'Heritage Port & Beach',
    area: 'Gopalpur-on-Sea, Ganjam Coast',
    lat: 19.2606,
    lng: 84.9088,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '06:00 AM - 08:30 PM',
    timings: { opening_time: '06:00 AM', closing_time: '08:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry',
    suggested_duration: '2 - 3 Hours',
    summary: 'Historic maritime commercial seaport and tranquil beach getaway renowned for its 1871 lighthouse and casuarina groves.',
    description: 'Gopalpur-on-Sea was a bustling commercial sea port during the British and Kalinga maritime eras, trading silk and rice with Burma. Today it is a peaceful, uncrowded beach destination featuring scenic casuarina plantations, a historic operational lighthouse with panoramic coast views, and golden sunrises.',
    historical_significance: 'Historic port of the ancient Kalinga sea empire, retaining colonial bungalows, pier ruins, and maritime lighthouses.',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80',
    tags: ['gopalpur', 'beach', 'lighthouse', 'ganjam', 'coastal', 'odisha'],
  },
  odisha_014: {
    city_key: 'daringbadi',
    categoryBucket: 'nature_parks_zoo',
    category: 'nature_parks_zoo',
    topic: 'Nature & Hill Station',
    subtopic: 'Highland Pine Forests & Valleys',
    area: 'Kandhamal Highlands',
    lat: 19.9079,
    lng: 84.1306,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '07:00 AM - 06:00 PM',
    timings: { opening_time: '07:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free entry (small entry fee at specific gardens)',
    suggested_duration: '3 - 5 Hours',
    summary: 'Idyllic highland hill station named the "Kashmir of Odisha", featuring pine groves, coffee plantations, and winter frost.',
    description: 'Perched at an elevation of 915 meters in the Eastern Ghats of Kandhamal, Daringbadi is the only place in Odisha that occasionally experiences sub-zero temperatures and winter ground frost. Attractions include dense pine forests, lush organic coffee plantations, Hill View Point, Midubanda Waterfall, and vibrant tribal villages.',
    historical_significance: 'Named after Daring Sahib, a British officer in charge of the hill tracts during the colonial era.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
    tags: ['daringbadi', 'hill station', 'kashmir of odisha', 'pine forest', 'coffee', 'kandhamal'],
  },
  odisha_015: {
    city_key: 'sambalpur',
    categoryBucket: 'tourist_places',
    category: 'tourist_places',
    topic: 'Engineering & Scenic Reservoir',
    subtopic: 'World’s Longest Earthen Dam',
    area: 'Burla / Hirakud, Sambalpur',
    lat: 21.5700,
    lng: 83.8710,
    opening_hours: '06:00 AM - 06:00 PM',
    visiting_hours: '06:00 AM - 06:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 10, international: 50, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: '₹10 (Minar view towers)',
    suggested_duration: '2 - 3 Hours',
    summary: 'Engineering marvel across the Mahanadi River, the world\'s longest earthen dam stretching 25.8 kilometers.',
    description: 'Constructed between 1948 and 1957 as India\'s first major multipurpose river valley project after independence, Hirakud Dam forms a massive reservoir covering 743 square kilometers. Visitors can ascend Gandhi Minar and Nehru Minar watchtowers for breathtaking 360-degree views of the waters and surrounding Barapahad hills.',
    historical_significance: 'Inaugurated by Prime Minister Jawaharlal Nehru in 1957, a historic cornerstone of post-independence Indian hydraulic engineering.',
    image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600&auto=format&fit=crop&q=80',
    tags: ['hirakud dam', 'sambalpur', 'mahanadi', 'earthen dam', 'reservoir', 'odisha'],
  },
};

// ==========================================
// 3. RAJASTHAN CITIES DEFINITIONS (9 Cities)
// ==========================================
const RAJASTHAN_CITIES = {
  jaipur: {
    id: 'jaipur',
    name: 'Jaipur',
    canonical_name: 'Jaipur',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Jaipur',
    city_type: 'city',
    lat: 26.9124,
    lng: 75.7873,
    coordinates: { lat: 26.9124, lng: 75.7873 },
    tagline: 'The Pink City & UNESCO World Heritage Royal Capital',
    description: 'Capital of Rajasthan, famed globally as the Pink City, home to majestic Amber Fort, Hawa Mahal, City Palace, and UNESCO-listed Jantar Mantar.',
    hero_image_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'monuments', 'culture'],
    prominence: 'State Capital',
    is_capital: true,
    capital_status: 'state_capital',
    verification_status: 'verified',
    source_provenance: 'Rajasthan Tourism Development Corporation (RTDC) & Ministry of Tourism',
    short_description: 'Capital of Rajasthan, world-famous Pink City rich in royal Rajput palaces and forts.',
  },
  jaisalmer: {
    id: 'jaisalmer',
    name: 'Jaisalmer',
    canonical_name: 'Jaisalmer',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Jaisalmer',
    city_type: 'city',
    lat: 26.9157,
    lng: 70.9083,
    coordinates: { lat: 26.9157, lng: 70.9083 },
    tagline: 'The Golden City of Thar & Living Hill Fort',
    description: 'The Golden City in the heart of the Great Indian Thar Desert, famed for its living sandstone fort, intricately carved havelis, and Sam Sand Dunes camel safaris.',
    hero_image_url: 'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'desert', 'nature'],
    prominence: 'Desert Heritage Destination',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Rajasthan Tourism (RTDC) & Ministry of Tourism',
    short_description: 'The Golden City renowned for the golden living fort and Sam Desert sand dunes.',
  },
  jodhpur: {
    id: 'jodhpur',
    name: 'Jodhpur',
    canonical_name: 'Jodhpur',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Jodhpur',
    city_type: 'city',
    lat: 26.2389,
    lng: 73.0243,
    coordinates: { lat: 26.2389, lng: 73.0243 },
    tagline: 'The Blue City & Sun City of Marwar',
    description: 'Historic capital of the Kingdom of Marwar, famed for the colossal Mehrangarh Fort towering above sea of indigo blue houses, Jaswant Thada, and Umaid Bhawan Palace.',
    hero_image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'monuments', 'culture'],
    prominence: 'Heritage Capital of Marwar',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Rajasthan Tourism & Mehrangarh Museum Trust',
    short_description: 'The Blue City overlooked by the impregnable cliffs of Mehrangarh Fort.',
  },
  udaipur: {
    id: 'udaipur',
    name: 'Udaipur',
    canonical_name: 'Udaipur',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Udaipur',
    city_type: 'city',
    lat: 24.5854,
    lng: 73.7125,
    coordinates: { lat: 24.5854, lng: 73.7125 },
    tagline: 'City of Lakes & Venice of the East',
    description: 'Romantic capital of the Mewar kingdom, celebrated worldwide for tranquil Lake Pichola, towering marble City Palace, Jag Mandir, and hilltop Monsoon Palace.',
    hero_image_url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'lakes', 'nature'],
    prominence: 'Mewar Heritage Capital',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Rajasthan Tourism (RTDC) & Maharana of Mewar Charitable Foundation',
    short_description: 'The City of Lakes, legendary for grand lakeside palaces and Aravalli mountain backdrops.',
  },
  'sawai-madhopur': {
    id: 'sawai-madhopur',
    name: 'Sawai Madhopur',
    canonical_name: 'Sawai Madhopur',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Sawai Madhopur',
    city_type: 'city',
    lat: 25.9928,
    lng: 76.3533,
    coordinates: { lat: 25.9928, lng: 76.3533 },
    tagline: 'Tiger Capital & Gateway to Ranthambore',
    description: 'Renowned wildlife sanctuary hub encompassing Ranthambore National Park, historic 10th-century UNESCO World Heritage Ranthambore Fort, and pristine tiger habitats.',
    hero_image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['wildlife', 'nature', 'heritage'],
    prominence: 'Wildlife & National Park Hub',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Ranthambore Tiger Reserve & Rajasthan Forest Dept',
    short_description: 'Renowned wildlife haven featuring Ranthambore National Park and historic fort ruins.',
  },
  chittorgarh: {
    id: 'chittorgarh',
    name: 'Chittorgarh',
    canonical_name: 'Chittorgarh',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Chittorgarh',
    city_type: 'city',
    lat: 24.8887,
    lng: 74.6269,
    coordinates: { lat: 24.8887, lng: 74.6269 },
    tagline: 'Citadel of Rajput Valor & Largest Fort in India',
    description: 'Legendary bastion of Mewar Rajput chivalry and sacrifice, home to India\'s largest fort complex, towering Vijay Stambh, Kirti Stambh, and Padmini Palace.',
    hero_image_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'monuments'],
    prominence: 'Historic Fortress Center',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Archaeological Survey of India & Rajasthan Tourism',
    short_description: 'Immense 700-acre UNESCO World Heritage fort celebrated for heroic Rajput history.',
  },
  pushkar: {
    id: 'pushkar',
    name: 'Pushkar',
    canonical_name: 'Pushkar',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Ajmer',
    city_type: 'city',
    lat: 26.4897,
    lng: 74.5511,
    coordinates: { lat: 26.4897, lng: 74.5511 },
    tagline: 'Sacred Tirtharaj & Home to the Brahma Temple',
    description: 'One of the five sacred dhams in Sanatan Dharma, nestled around holy Pushkar Lake with 52 ghats, the rare Brahma Temple, and the world-famous Pushkar Camel Fair.',
    hero_image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['spiritual', 'culture'],
    prominence: 'Sacred Pilgrimage Center',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Rajasthan Tourism Development Corporation (RTDC)',
    short_description: 'Sacred lake town famed for the rare Lord Brahma Temple and 52 bathing ghats.',
  },
  'mount-abu': {
    id: 'mount-abu',
    name: 'Mount Abu',
    canonical_name: 'Mount Abu',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Sirohi',
    city_type: 'city',
    lat: 24.5926,
    lng: 72.7156,
    coordinates: { lat: 24.5926, lng: 72.7156 },
    tagline: 'Oasis in the Desert & Aravalli Hill Station',
    description: 'Rajasthan\'s only hill resort, perched at 1,220m in the Aravalli range, home to the exquisite 11th-century marble Dilwara Jain Temples and picturesque Nakki Lake.',
    hero_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['nature', 'heritage', 'spiritual'],
    prominence: 'Hill Station Retreat',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Rajasthan Tourism & Mount Abu Municipality',
    short_description: 'Cool Aravalli hill station world-famous for the intricate marble Dilwara Temples.',
  },
  bikaner: {
    id: 'bikaner',
    name: 'Bikaner',
    canonical_name: 'Bikaner',
    state: 'Rajasthan',
    state_id: 'rajasthan',
    region: 'Northern India',
    district: 'Bikaner',
    city_type: 'city',
    lat: 28.0229,
    lng: 73.3119,
    coordinates: { lat: 28.0229, lng: 73.3119 },
    tagline: 'Camel Country & Home of Unconquered Junagarh Fort',
    description: 'Desert fortress city founded in 1488 by Rao Bika, celebrated for the unconquered red sandstone Junagarh Fort, ornate havelis, and vibrant camel culture.',
    hero_image_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=1200&auto=format&fit=crop&q=80',
    tourism_categories: ['heritage', 'monuments', 'culture'],
    prominence: 'Desert Citadel & Cultural Hub',
    is_capital: false,
    capital_status: 'none',
    verification_status: 'verified',
    source_provenance: 'Junagarh Fort Trust & Rajasthan Tourism',
    short_description: 'Desert citadel featuring the invincible Junagarh Fort and rich culinary traditions.',
  },
};

// ==========================================
// 4. RAJASTHAN PLACES DETAILS (20 Places)
// ==========================================
const RAJASTHAN_PLACES_DETAILS = {
  rajasthan_001: {
    city_key: 'jaipur',
    categoryBucket: 'heritage',
    category: 'heritage_city',
    topic: 'Heritage & City',
    subtopic: 'UNESCO Walled City',
    area: 'Jaipur district',
    lat: 26.9124,
    lng: 75.7873,
    opening_hours: 'Usually daytime; timings vary by attraction',
    visiting_hours: '09:00 AM - 06:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Jaipur Rajasthan',
    tags: ['heritage_city', 'Rajasthan'],
    summary: 'The Pink City, known for forts, palaces, markets, and historic architecture.',
    description: 'The Pink City, known for forts, palaces, markets, and historic architecture.',
    image_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_002: {
    city_key: 'jaipur',
    categoryBucket: 'monuments',
    category: 'fort_palace',
    topic: 'Architecture & Forts',
    subtopic: 'UNESCO Hill Fort',
    area: 'Amer, Jaipur',
    lat: 26.9855,
    lng: 75.8513,
    opening_hours: '08:00 AM - 05:30 PM, Light Show 06:30 PM - 09:00 PM',
    visiting_hours: '08:00 AM - 05:30 PM',
    timings: { opening_time: '08:00 AM', closing_time: '05:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 100, international: 500, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Amber Fort Rajasthan',
    tags: ['fort_palace', 'Rajasthan'],
    summary: 'A grand hilltop fort featuring courtyards, gateways, palaces, and artistic interiors.',
    description: 'A grand hilltop fort featuring courtyards, gateways, palaces, and artistic interiors.',
    image_url: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_003: {
    city_key: 'jaipur',
    categoryBucket: 'heritage',
    category: 'palace_museum',
    topic: 'Royal Heritage',
    subtopic: 'Palace Museum Complex',
    area: 'Old City, Jaipur',
    lat: 26.9258,
    lng: 75.8237,
    opening_hours: '09:30 AM - 05:00 PM',
    visiting_hours: '09:30 AM - 05:00 PM',
    timings: { opening_time: '09:30 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 200, international: 700, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'City Palace Rajasthan',
    tags: ['palace_museum', 'Rajasthan'],
    summary: 'A royal complex containing courtyards, museums, and palace buildings.',
    description: 'A royal complex containing courtyards, museums, and palace buildings.',
    image_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_004: {
    city_key: 'jaipur',
    categoryBucket: 'monuments',
    category: 'heritage_monument',
    topic: 'Monuments',
    subtopic: 'Palace of Winds',
    area: 'Badi Choupad, Jaipur',
    lat: 26.9239,
    lng: 75.8267,
    opening_hours: '09:00 AM - 05:00 PM',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 50, international: 200, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Hawa Mahal Rajasthan',
    tags: ['heritage_monument', 'Rajasthan'],
    summary: 'An iconic five-storey palace façade famous for its honeycomb windows.',
    description: 'An iconic five-storey palace façade famous for its honeycomb windows.',
    image_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_005: {
    city_key: 'jaipur',
    categoryBucket: 'monuments',
    category: 'scientific_heritage',
    topic: 'Scientific Heritage',
    subtopic: 'Astronomical Observatory',
    area: 'City Palace Complex, Jaipur',
    lat: 26.9248,
    lng: 75.8246,
    opening_hours: '09:00 AM - 04:30 PM',
    visiting_hours: '09:00 AM - 04:30 PM',
    timings: { opening_time: '09:00 AM', closing_time: '04:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 50, international: 200, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Jantar Mantar Rajasthan',
    tags: ['scientific_heritage', 'Rajasthan'],
    summary: 'A UNESCO-listed astronomical observatory with monumental instruments.',
    description: 'A UNESCO-listed astronomical observatory with monumental instruments.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_006: {
    city_key: 'jaisalmer',
    categoryBucket: 'heritage',
    category: 'fort_heritage',
    topic: 'Heritage & Forts',
    subtopic: 'Living Golden Fort',
    area: 'Trikuta Hill, Jaisalmer',
    lat: 26.9124,
    lng: 70.9128,
    opening_hours: '06:00 AM - 05:00 PM',
    visiting_hours: '06:00 AM - 05:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Jaisalmer Fort Rajasthan',
    tags: ['fort_heritage', 'Rajasthan'],
    summary: 'A living golden sandstone fort containing residences, temples, shops, and viewpoints.',
    description: 'A living golden sandstone fort containing residences, temples, shops, and viewpoints.',
    image_url: 'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_007: {
    city_key: 'jaisalmer',
    categoryBucket: 'nature_parks_zoo',
    category: 'desert_adventure',
    topic: 'Nature & Desert',
    subtopic: 'Thar Desert Dunes',
    area: 'Sam, Jaisalmer district',
    lat: 26.8317,
    lng: 70.5042,
    opening_hours: 'Open 24 Hours; Safaris 05:00 AM - 07:00 PM',
    visiting_hours: '05:00 AM - 07:00 PM',
    timings: { opening_time: '05:00 AM', closing_time: '07:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['nature', 'culture', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Sam Sand Dunes Rajasthan',
    tags: ['desert_adventure', 'Rajasthan'],
    summary: 'A popular desert landscape for camel rides, dune views, and cultural camps.',
    description: 'A popular desert landscape for camel rides, dune views, and cultural camps.',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_008: {
    city_key: 'jodhpur',
    categoryBucket: 'monuments',
    category: 'fort_museum',
    topic: 'Monuments & Forts',
    subtopic: 'Clifftop Citadel',
    area: 'Fort Road, Jodhpur',
    lat: 26.2978,
    lng: 73.0185,
    opening_hours: '09:00 AM - 05:00 PM',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 100, international: 600, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Mehrangarh Fort Rajasthan',
    tags: ['fort_museum', 'Rajasthan'],
    summary: 'A massive hilltop fort overlooking the Blue City, with museums and historic palaces.',
    description: 'A massive hilltop fort overlooking the Blue City, with museums and historic palaces.',
    image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_009: {
    city_key: 'jodhpur',
    categoryBucket: 'monuments',
    category: 'memorial_heritage',
    topic: 'Heritage Memorial',
    subtopic: 'Marble Royal Cenotaph',
    area: 'Lawaran, Jodhpur',
    lat: 26.3044,
    lng: 73.0238,
    opening_hours: '09:00 AM - 05:00 PM',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 30, international: 50, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Jaswant Thada Rajasthan',
    tags: ['memorial_heritage', 'Rajasthan'],
    summary: 'A white-marble memorial known for its delicate carvings and peaceful gardens.',
    description: 'A white-marble memorial known for its delicate carvings and peaceful gardens.',
    image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_010: {
    city_key: 'jodhpur',
    categoryBucket: 'heritage',
    category: 'palace_museum',
    topic: 'Royal Heritage',
    subtopic: 'Art Deco Royal Palace',
    area: 'Circuit House Road, Jodhpur',
    lat: 26.2809,
    lng: 73.0475,
    opening_hours: '09:00 AM - 05:00 PM',
    visiting_hours: '09:00 AM - 05:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 30, international: 100, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Umaid Bhawan Palace Rajasthan',
    tags: ['palace_museum', 'Rajasthan'],
    summary: 'A grand 20th-century palace showcasing royal history and decorative architecture.',
    description: 'A grand 20th-century palace showcasing royal history and decorative architecture.',
    image_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_011: {
    city_key: 'udaipur',
    categoryBucket: 'nature_parks_zoo',
    category: 'lake_recreation',
    topic: 'Nature & Lakes',
    subtopic: 'Historic Freshwater Lake',
    area: 'Old City, Udaipur',
    lat: 24.5750,
    lng: 73.6780,
    opening_hours: 'Open 24 Hours; Boat Rides 09:00 AM - 06:00 PM',
    visiting_hours: '09:00 AM - 06:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['nature', 'culture', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Lake Pichola Rajasthan',
    tags: ['lake_recreation', 'Rajasthan'],
    summary: 'A scenic lake surrounded by palaces, ghats, islands, and Aravalli hills.',
    description: 'A scenic lake surrounded by palaces, ghats, islands, and Aravalli hills.',
    image_url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_012: {
    city_key: 'udaipur',
    categoryBucket: 'heritage',
    category: 'palace_museum',
    topic: 'Royal Heritage',
    subtopic: 'Lakeside Palace Complex',
    area: 'Old City, Udaipur',
    lat: 24.5764,
    lng: 73.6835,
    opening_hours: '09:00 AM - 09:00 PM',
    visiting_hours: '09:00 AM - 09:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 300, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'City Palace Udaipur Rajasthan',
    tags: ['palace_museum', 'Rajasthan'],
    summary: 'A large palace complex overlooking Lake Pichola with museums and courtyards.',
    description: 'A large palace complex overlooking Lake Pichola with museums and courtyards.',
    image_url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_013: {
    city_key: 'udaipur',
    categoryBucket: 'monuments',
    category: 'palace_viewpoint',
    topic: 'Monuments & Viewpoints',
    subtopic: 'Hilltop Monsoon Palace',
    area: 'Bansdara Peak, Udaipur',
    lat: 24.5898,
    lng: 73.6358,
    opening_hours: '09:00 AM - 06:00 PM',
    visiting_hours: '09:00 AM - 06:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 110, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Sajjangarh Monsoon Palace Rajasthan',
    tags: ['palace_viewpoint', 'Rajasthan'],
    summary: 'A hilltop palace offering panoramic views over Udaipur and its lakes.',
    description: 'A hilltop palace offering panoramic views over Udaipur and its lakes.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_014: {
    city_key: 'sawai-madhopur',
    categoryBucket: 'nature_parks_zoo',
    category: 'wildlife_national_park',
    topic: 'Wildlife & Nature',
    subtopic: 'National Park & Tiger Reserve',
    area: 'Sawai Madhopur',
    lat: 26.0173,
    lng: 76.5026,
    opening_hours: '06:00 AM - 10:00 AM, 02:00 PM - 06:00 PM',
    visiting_hours: '06:00 AM - 06:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 100, international: 800, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['nature', 'culture', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Ranthambore National Park Rajasthan',
    tags: ['wildlife_national_park', 'Rajasthan'],
    summary: 'A renowned wildlife reserve known for tigers, forests, lakes, and historic ruins.',
    description: 'A renowned wildlife reserve known for tigers, forests, lakes, and historic ruins.',
    image_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_015: {
    city_key: 'chittorgarh',
    categoryBucket: 'heritage',
    category: 'fort_heritage',
    topic: 'Heritage & Forts',
    subtopic: 'Largest Fort Complex',
    area: 'Chittorgarh',
    lat: 24.8879,
    lng: 74.6450,
    opening_hours: '09:00 AM - 06:00 PM',
    visiting_hours: '09:00 AM - 06:00 PM',
    timings: { opening_time: '09:00 AM', closing_time: '06:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 40, international: 600, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Chittorgarh Fort Rajasthan',
    tags: ['fort_heritage', 'Rajasthan'],
    summary: 'A vast historic fort associated with Rajput history, towers, palaces, and temples.',
    description: 'A vast historic fort associated with Rajput history, towers, palaces, and temples.',
    image_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1609946850722-8f6545441d68?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_016: {
    city_key: 'pushkar',
    categoryBucket: 'religious_cultural',
    category: 'religious_lake',
    topic: 'Sacred Sites',
    subtopic: 'Holy Pilgrimage Lake',
    area: 'Pushkar',
    lat: 26.4883,
    lng: 74.5539,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '05:00 AM - 09:00 PM',
    timings: { opening_time: '05:00 AM', closing_time: '09:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['nature', 'culture', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Pushkar Lake Rajasthan',
    tags: ['religious_lake', 'Rajasthan'],
    summary: 'A sacred lake surrounded by bathing ghats and temples in the holy town of Pushkar.',
    description: 'A sacred lake surrounded by bathing ghats and temples in the holy town of Pushkar.',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_017: {
    city_key: 'pushkar',
    categoryBucket: 'religious_cultural',
    category: 'religious_heritage',
    topic: 'Spiritual Heritage',
    subtopic: 'Lord Brahma Shrine',
    area: 'Pushkar',
    lat: 26.4887,
    lng: 74.5518,
    opening_hours: '06:00 AM - 08:30 PM',
    visiting_hours: '06:00 AM - 08:30 PM',
    timings: { opening_time: '06:00 AM', closing_time: '08:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Brahma Temple Rajasthan',
    tags: ['religious_heritage', 'Rajasthan'],
    summary: 'One of the best-known temples dedicated to Lord Brahma.',
    description: 'One of the best-known temples dedicated to Lord Brahma.',
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_018: {
    city_key: 'mount-abu',
    categoryBucket: 'religious_cultural',
    category: 'religious_architecture',
    topic: 'Architecture & Temples',
    subtopic: 'Jain Marble Temples',
    area: 'Mount Abu',
    lat: 24.6062,
    lng: 72.7231,
    opening_hours: '12:00 PM - 05:00 PM (for non-Jain tourists)',
    visiting_hours: '12:00 PM - 05:00 PM',
    timings: { opening_time: '12:00 PM', closing_time: '05:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Dilwara Temples Rajasthan',
    tags: ['religious_architecture', 'Rajasthan'],
    summary: 'Famous Jain temples celebrated for exceptionally detailed marble carvings.',
    description: 'Famous Jain temples celebrated for exceptionally detailed marble carvings.',
    image_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600100397608-f4b66f284e3e?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_019: {
    city_key: 'mount-abu',
    categoryBucket: 'nature_parks_zoo',
    category: 'hill_station_nature',
    topic: 'Nature & Hill Station',
    subtopic: 'Aravalli Hill Resort',
    area: 'Sirohi district',
    lat: 24.5926,
    lng: 72.7156,
    opening_hours: 'Open 24 Hours',
    visiting_hours: '06:00 AM - 08:00 PM',
    timings: { opening_time: '06:00 AM', closing_time: '08:00 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 0, international: 0, currency: 'INR', free_entry: true, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['nature', 'culture', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Mount Abu Rajasthan',
    tags: ['hill_station_nature', 'Rajasthan'],
    summary: 'Rajasthan’s hill station, known for cool weather, viewpoints, forests, and lakes.',
    description: 'Rajasthan’s hill station, known for cool weather, viewpoints, forests, and lakes.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
  },
  rajasthan_020: {
    city_key: 'bikaner',
    categoryBucket: 'heritage',
    category: 'fort_museum',
    topic: 'Heritage & Forts',
    subtopic: 'Desert Citadel',
    area: 'Bikaner',
    lat: 28.0219,
    lng: 73.3184,
    opening_hours: '10:00 AM - 04:30 PM',
    visiting_hours: '10:00 AM - 04:30 PM',
    timings: { opening_time: '10:00 AM', closing_time: '04:30 PM', closed_days: [], status: 'VERIFIED' },
    fees: { domestic: 50, international: 300, currency: 'INR', free_entry: false, status: 'VERIFIED' },
    entry_fee: 'Free or paid depending on attraction; verify current rates',
    suggested_duration: '2–4 hours',
    best_time_to_visit: 'October to March',
    best_for: ['heritage', 'history', 'photography'],
    visitor_notes: ['Carry water and sun protection', 'Check local timings and access rules before visiting'],
    map_search: 'Bikaner Junagarh Fort Rajasthan',
    tags: ['fort_museum', 'Rajasthan'],
    summary: 'A well-preserved fort containing palaces, courtyards, museums, and ornate interiors.',
    description: 'A well-preserved fort containing palaces, courtyards, museums, and ornate interiors.',
    image_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=600&auto=format&fit=crop&q=80',
  },
};

// ==========================================
// 5. HELPER TO BUILD STATE CITIES & PLACES
// ==========================================
function buildStateBundle(stateId, stateName, stateCode, capital, region, citiesDef, placesSource, placesDetails, overview, stories, heroUrl) {
  const cityMap = {};
  for (const [cKey, cDef] of Object.entries(citiesDef)) {
    cityMap[cKey] = {
      ...cDef,
      places_count: 0,
      heritage: [],
      monuments: [],
      museums: [],
      tourist_places: [],
      religious_cultural: [],
      nature_parks_zoo: [],
      places: [],
    };
  }

  for (const srcPlace of placesSource) {
    const details = placesDetails[srcPlace.id];
    if (!details) {
      throw new Error(`Missing details definition for place ${srcPlace.id}`);
    }
    const cKey = details.city_key;
    if (!cityMap[cKey]) {
      throw new Error(`City key ${cKey} not found in state ${stateId}`);
    }

    const cityMeta = cityMap[cKey];

    const fullPlace = {
      id: srcPlace.id,
      name: srcPlace.name,
      slug: srcPlace.id,
      place_type: srcPlace.category || details.category || 'attraction',
      category: srcPlace.category || details.category || 'heritage',
      categoryBucket: details.categoryBucket,
      topic: details.topic,
      subtopic: details.subtopic,
      area: srcPlace.area || details.area,
      city: cityMeta.name,
      city_id: cityMeta.id,
      state: stateName,
      state_id: stateId,
      lat: details.lat,
      lng: details.lng,
      coordinates: { lat: details.lat, lng: details.lng },
      summary: srcPlace.description || details.summary,
      description: srcPlace.description || details.description,
      short_description: details.summary || srcPlace.description,
      detailed_description: srcPlace.description || details.description,
      best_for: srcPlace.best_for || details.best_for || ['heritage', 'culture', 'photography'],
      suggested_duration: srcPlace.suggested_duration || details.suggested_duration,
      best_time_to_visit: srcPlace.best_time_to_visit || details.best_time_to_visit || 'October to March',
      entry_fee: srcPlace.entry_fee || details.entry_fee,
      opening_hours: srcPlace.opening_hours || details.opening_hours,
      visiting_hours: srcPlace.opening_hours || details.visiting_hours,
      timings: details.timings,
      fees: details.fees,
      visitor_notes: srcPlace.visitor_notes || details.visitor_notes || ['Check local timings before visiting'],
      map_search: srcPlace.map_search || `${srcPlace.name} ${stateName}`,
      tags: srcPlace.tags || details.tags,
      image_url: details.image_url,
      thumbnail_url: details.thumbnail_url,
      attribution: `${stateName} Tourism Development Corporation`,
      source_name: `${stateName} Tourism`,
      source_url: `https://tourism.${stateId}.gov.in`,
      source_page: `https://tourism.${stateId}.gov.in`,
      source_type: 'tier1_official',
      source_quality: 'official_site',
      verification_status: 'verified',
      status: 'VERIFIED',
      data_confidence: 'official',
      last_verified_on: '2026-09-11',
      last_verified_at: '2026-09-11T12:00:00.000Z',
      features: { map: true, navigation: true, ai: true, '3d': false },
      sources: [
        {
          source_name: `${stateName} Tourism Development Corporation`,
          source_url: `https://tourism.${stateId}.gov.in`,
          source_type: 'official_tourism_board',
          accessed_on: '2026-09-11',
          verification_status: 'verified',
        },
      ],
    };

    const bucket = details.categoryBucket;
    cityMap[cKey][bucket].push(fullPlace);
    cityMap[cKey].places.push(fullPlace);
    cityMap[cKey].places_count += 1;
  }

  const citiesArray = Object.values(cityMap);
  const totalPlacesCount = citiesArray.reduce((sum, c) => sum + c.places_count, 0);

  const stateObject = {
    id: stateId,
    name: stateName,
    code: stateCode,
    capital: capital,
    region: region,
    region_type: 'state',
    hero_image_url: heroUrl,
    total_cities: citiesArray.length,
    total_attractions: totalPlacesCount,
    official_tourism_url: `https://tourism.${stateId}.gov.in`,
    heritage_overview: overview,
    description: overview,
    active_stories: stories,
    cities: citiesArray,
    hero_image: {
      image_url: heroUrl,
      source_url: `https://tourism.${stateId}.gov.in`,
      source_name: `${stateName} Tourism`,
      creator: 'Official Tourism Board',
      license: 'Public Domain / Verified',
      verification_status: 'verified',
      verified_at: '2026-09-11T12:00:00.000Z',
    },
  };

  return { stateObject, citiesArray, totalPlacesCount };
}

// Build Odisha bundle
const odishaBundle = buildStateBundle(
  'odisha',
  'Odisha',
  'OD',
  'Bhubaneswar',
  'Eastern India',
  ODISHA_CITIES,
  odishaSource.places,
  ODISHA_PLACES_DETAILS,
  'Soul of Incredible India: Sacred Char Dham Jagannath Temple, UNESCO Konark Sun Temple, Asia\'s largest Chilika lagoon, and living Pattachitra crafts.',
  [
    'Sacred Char Dham pilgrimage and millennium-old Kalinga temple architecture.',
    'Sun Temple of Konark and world-heritage rock-cut caves of Kharavela.',
    'Chilika lagoon wetland biodiversity, Irrawaddy dolphins, and Similipal tigers.',
  ],
  'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&auto=format&fit=crop&q=80'
);

// Build Rajasthan bundle
const rajasthanBundle = buildStateBundle(
  'rajasthan',
  'Rajasthan',
  'RJ',
  'Jaipur',
  'Northern India',
  RAJASTHAN_CITIES,
  rajasthanSource.places,
  RAJASTHAN_PLACES_DETAILS,
  'Land of Kings: Monumental hill forts of Rajasthan, royal palaces, Thar Desert sand dunes, sacred lakes, and vibrant Rajput heritage.',
  [
    'UNESCO World Heritage Hill Forts: Amber, Mehrangarh, Jaisalmer, and Chittorgarh.',
    'Royal palaces and astronomical marvels across the Pink City and Lake City.',
    'Vibrant Thar Desert safaris, Pushkar sacred ghats, and Mount Abu hills.',
  ],
  'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=1200&auto=format&fit=crop&q=80'
);

console.log(`✓ Built Odisha bundle: ${odishaBundle.citiesArray.length} cities, ${odishaBundle.totalPlacesCount} places.`);
console.log(`✓ Built Rajasthan bundle: ${rajasthanBundle.citiesArray.length} cities, ${rajasthanBundle.totalPlacesCount} places.`);

if (odishaBundle.totalPlacesCount !== 15) throw new Error(`Expected 15 Odisha places, got ${odishaBundle.totalPlacesCount}`);
if (rajasthanBundle.totalPlacesCount !== 20) throw new Error(`Expected 20 Rajasthan places, got ${rajasthanBundle.totalPlacesCount}`);

// ==========================================
// 6. UPDATE data/india_tourism_database.json
// ==========================================
const itdb = readJson(itdbJsonPath);

const odishaIndex = itdb.states.findIndex((s) => s.id === 'odisha');
if (odishaIndex === -1) throw new Error('Odisha not found in itdb');
itdb.states[odishaIndex] = odishaBundle.stateObject;

const rajasthanIndex = itdb.states.findIndex((s) => s.id === 'rajasthan');
if (rajasthanIndex === -1) throw new Error('Rajasthan not found in itdb');
itdb.states[rajasthanIndex] = rajasthanBundle.stateObject;

// Recalculate top-level counts
itdb.cities_count = itdb.states.reduce((sum, s) => sum + (s.cities ? s.cities.length : 0), 0);
itdb.attractions_count = itdb.states.reduce((sum, s) => {
  let count = 0;
  if (Array.isArray(s.cities)) {
    for (const c of s.cities) {
      if (Array.isArray(c.places) && c.places.length > 0) {
        count += c.places.length;
      } else {
        count += (c.heritage?.length || 0) +
          (c.monuments?.length || 0) +
          (c.museums?.length || 0) +
          (c.tourist_places?.length || 0) +
          (c.religious_cultural?.length || 0) +
          (c.nature_parks_zoo?.length || 0);
      }
    }
  }
  return sum + count;
}, 0);

fs.writeFileSync(itdbJsonPath, JSON.stringify(itdb, null, 2), 'utf8');
console.log(`✓ Updated data/india_tourism_database.json. Total states: ${itdb.states.length}, cities: ${itdb.cities_count}, attractions: ${itdb.attractions_count}`);

// ==========================================
// 7. UPDATE src/data/indiaTourismDatabase.ts
// ==========================================
const tsContent = `// Auto-generated Master Database Export
import { IndiaHierarchyDatabase } from '../../types/indiaHierarchy';

export const INDIA_TOURISM_DATABASE: IndiaHierarchyDatabase = ${JSON.stringify(itdb, null, 2)} as unknown as IndiaHierarchyDatabase;
`;
fs.writeFileSync(itdbTsPath, tsContent, 'utf8');
console.log('✓ Updated src/data/indiaTourismDatabase.ts');

// ==========================================
// 8. UPDATE data/cities.json
// ==========================================
const existingCities = readJson(citiesJsonPath);

// Keep all cities EXCEPT odisha and rajasthan
const filteredCities = existingCities.filter((c) => c.state_id !== 'odisha' && c.state_id !== 'rajasthan');

const makeCityEntries = (stateId, citiesArray) =>
  citiesArray.map((c) => ({
    id: c.id,
    state_id: stateId,
    name: c.name,
    slug: c.id,
    entity_type: c.city_type || 'city',
    district: c.district,
    latitude: c.lat,
    longitude: c.lng,
    lat: c.lat,
    lng: c.lng,
    short_description: c.short_description || c.description,
    description: c.description,
    official_url: c.official_url || `https://tourism.${stateId}.gov.in`,
    status: 'active',
    hero_image_url: c.hero_image_url,
    places_count: c.places_count,
    tagline: c.tagline,
  }));

const newOdishaCities = makeCityEntries('odisha', odishaBundle.citiesArray);
const newRajasthanCities = makeCityEntries('rajasthan', rajasthanBundle.citiesArray);

const finalCities = [...filteredCities, ...newOdishaCities, ...newRajasthanCities];
fs.writeFileSync(citiesJsonPath, JSON.stringify(finalCities, null, 2), 'utf8');
console.log(`✓ Updated data/cities.json. Non-target cities: ${filteredCities.length}, Odisha: ${newOdishaCities.length}, Rajasthan: ${newRajasthanCities.length}, Total: ${finalCities.length}`);

// ==========================================
// 9. UPDATE data/states.json
// ==========================================
const statesList = readJson(statesJsonPath);

const odishaStateIdx = statesList.findIndex((s) => s.id === 'odisha');
if (odishaStateIdx !== -1) {
  statesList[odishaStateIdx] = {
    ...statesList[odishaStateIdx],
    total_cities: odishaBundle.citiesArray.length,
    total_attractions: odishaBundle.totalPlacesCount,
    official_tourism_url: odishaBundle.stateObject.official_tourism_url,
    description: odishaBundle.stateObject.description,
  };
}

const rajasthanStateIdx = statesList.findIndex((s) => s.id === 'rajasthan');
if (rajasthanStateIdx !== -1) {
  statesList[rajasthanStateIdx] = {
    ...statesList[rajasthanStateIdx],
    total_cities: rajasthanBundle.citiesArray.length,
    total_attractions: rajasthanBundle.totalPlacesCount,
    official_tourism_url: rajasthanBundle.stateObject.official_tourism_url,
    description: rajasthanBundle.stateObject.description,
  };
}

fs.writeFileSync(statesJsonPath, JSON.stringify(statesList, null, 2), 'utf8');
console.log('✓ Updated data/states.json');

console.log('=== Integration Script Finished Successfully ===');
