// Generator for 45 curated, pan-Indian monuments representing North, South, East, West, Central and Northeast India.
import fs from 'fs';
import path from 'path';

const monuments = [
  // --- NORTH INDIA (12) ---
  {
    id: "taj-mahal",
    name: "Taj Mahal",
    city: "Agra",
    state: "Uttar Pradesh",
    region: "Northern India",
    coordinates: { lat: 27.1751, lng: 78.0421 },
    era: "1632 - 1653 CE",
    historical_period: "Mughal Empire (Shah Jahan)",
    architectural_style: "Mughal Architecture (Persian, Islamic & Indian)",
    architect: "Ustad Ahmad Lahori",
    material: "Makrana white marble with Pietra Dura inlay",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "17th-century white marble mausoleum built by Mughal Emperor Shah Jahan, universally admired as an eternal jewel of Muslim art in India.",
    historical_significance: "Commissioned by Mughal Emperor Shah Jahan to house the tomb of Mumtaz Mahal. Universally admired as an eternal symbol of devotion and the pinnacle of Mughal aesthetic symmetry.",
    cultural_significance: "A masterpiece of symmetrical proportion and marble carvings, representing the highest peak of Mughal aesthetic craftsmanship and global heritage.",
    visiting_hours: "Sunrise to Sunset (Closed on Fridays)",
    entry_fee_inr: 50,
    entry_fee: { domestic: 50, international: 1100, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Agra Fort", "Fatehpur Sikri", "Mehtab Bagh"],
    transport_information: {
      air: "Agra Airport (AGR) - 12 km; Delhi IGI Airport - 220 km",
      rail: "Agra Cantt (AGC) - 6 km; regular Gatimaan and Vande Bharat Express",
      road: "Yamuna Expressway connects directly from Delhi NCR (3.5 hrs drive)",
      local: "Electric autos, cycle-rickshaws, and government battery shuttle carts"
    },
    nearest_transport: { railway_station: "Agra Cantt (AGC)" },
    thumbnail_url: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80"
    ],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["monument", "unesco", "mughal", "marble", "agra", "uttar pradesh"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "fatehpur-sikri",
    name: "Fatehpur Sikri City of Victory",
    city: "Agra District",
    state: "Uttar Pradesh",
    region: "Northern India",
    coordinates: { lat: 27.0945, lng: 77.6679 },
    era: "1571 - 1585 CE",
    historical_period: "Mughal Empire (Akbar the Great)",
    architectural_style: "Classical Mughal Red Sandstone",
    architect: "Bahauddin",
    material: "Sikri red sandstone",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Walled royal capital built by Emperor Akbar featuring Buland Darwaza, Panch Mahal, and the white marble Tomb of Salim Chishti.",
    historical_significance: "Founded by Emperor Akbar as the imperial capital, representing an architectural synthesis of Persian, Central Asian, and indigenous Indian traditions.",
    cultural_significance: "Houses the revered Sufi dargah of Sheikh Salim Chishti and the magnificent 54-meter Buland Darwaza commemorating Gujarat victory.",
    visiting_hours: "Sunrise to Sunset (06:00 AM - 06:00 PM)",
    entry_fee_inr: 50,
    entry_fee: { domestic: 50, international: 610, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Taj Mahal", "Agra Fort", "Keoladeo Bird Sanctuary Bharatpur"],
    transport_information: {
      air: "Agra Kheria Airport (AGR) - 36 km; Delhi IGI - 235 km",
      rail: "Fatehpur Sikri (FTS) - 1.5 km; Agra Cantt (AGC) - 38 km",
      road: "NH 21 connects directly to Agra and Bharatpur (1 hr drive)",
      local: "Eco shuttle buses, tongas, and licensed ASI heritage guides"
    },
    nearest_transport: { railway_station: "Fatehpur Sikri (FTS) / Agra Cantt (AGC)" },
    thumbnail_url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["fort", "unesco", "mughal", "sandstone", "uttar pradesh"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "qutub-minar",
    name: "Qutub Minar & Complex",
    city: "New Delhi",
    state: "Delhi (NCT)",
    region: "Northern India",
    coordinates: { lat: 28.5245, lng: 77.1855 },
    era: "1192 - 1220 CE",
    historical_period: "Delhi Sultanate (Mamluk / Slave Dynasty)",
    architectural_style: "Indo-Islamic Afghan Architecture",
    architect: "Qutb-ud-din Aibak & Shams-ud-din Iltutmish",
    material: "Fluted red and buff sandstone with marble bands",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "World's tallest brick minaret at 72.5 meters surrounded by ancient funerary and ceremonial monuments, including the 4th-century rust-resistant Iron Pillar.",
    historical_significance: "Marks the establishment of the Delhi Sultanate in 1192 CE. Contains inscriptions in Parso-Arabic and Nagari characters recording historic repairs.",
    cultural_significance: "An extraordinary landmark of early Indo-Islamic artistic synthesis showcasing intricate calligraphic bands and geometric balconies.",
    visiting_hours: "Sunrise to Sunset (07:00 AM - 07:00 PM)",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "1.5 - 2 Hours",
    best_season: "October to March",
    nearby_destinations: ["Mehrauli Archaeological Park", "Hauz Khas Village", "Safdarjung Tomb"],
    transport_information: {
      air: "Indira Gandhi International Airport (DEL) - 12 km",
      rail: "New Delhi Railway Station (NDLS) - 15 km; Hazrat Nizamuddin - 13 km",
      road: "Aurobindo Marg / Mehrauli Badarpur Road interchange",
      local: "Delhi Metro Yellow Line (Qutab Minar Station - 1 km)"
    },
    nearest_transport: { railway_station: "New Delhi (NDLS) / Qutab Minar Metro" },
    thumbnail_url: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["minaret", "unesco", "delhi sultanate", "iron pillar", "delhi"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "red-fort",
    name: "Red Fort (Lal Qila)",
    city: "Old Delhi",
    state: "Delhi (NCT)",
    region: "Northern India",
    coordinates: { lat: 28.6562, lng: 77.2410 },
    era: "1638 - 1648 CE",
    historical_period: "Mughal Empire (Shah Jahan)",
    architectural_style: "Mughal Imperial Fort Architecture",
    architect: "Ustad Ahmad Lahori",
    material: "Red sandstone and white marble",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Massive red sandstone citadel served as the seat of the Mughal Empire for nearly 200 years and the traditional venue for the national Independence Day address.",
    historical_significance: "Constructed when Shah Jahan shifted his capital from Agra to Shahjahanabad. Witnessed key historic epochs from Mughal zenith to the 1857 First War of Independence.",
    cultural_significance: "National symbol of Indian sovereignty; houses Diwan-i-Aam, Diwan-i-Khas, and the iconic Lahori Gate ramparts.",
    visiting_hours: "09:30 AM - 04:30 PM (Closed Mondays)",
    entry_fee_inr: 35,
    entry_fee: { domestic: 35, international: 550, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Jama Masjid Delhi", "Chandni Chowk", "Raj Ghat"],
    transport_information: {
      air: "Delhi IGI Airport (DEL) - 18 km",
      rail: "Old Delhi Railway Station (DLI) - 1.5 km; New Delhi (NDLS) - 4 km",
      road: "Netaji Subhash Marg across historic Chandni Chowk",
      local: "Delhi Metro Heritage Line (Lal Qila Station - 200 m)"
    },
    nearest_transport: { railway_station: "Old Delhi (DLI) / Lal Qila Metro" },
    thumbnail_url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["fort", "unesco", "mughal", "shahjahanabad", "delhi"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "humayuns-tomb",
    name: "Humayun's Tomb",
    city: "New Delhi",
    state: "Delhi (NCT)",
    region: "Northern India",
    coordinates: { lat: 28.5933, lng: 77.2507 },
    era: "1565 - 1572 CE",
    historical_period: "Mughal Empire (Empress Bega Begum / Akbar)",
    architectural_style: "Persian Charbagh Garden Tomb Architecture",
    architect: "Mirak Mirza Ghiyas",
    material: "Red sandstone with white and black marble inlay",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "The first monumental garden tomb on the Indian subcontinent, establishing the architectural prototype that culminated in the Taj Mahal.",
    historical_significance: "Commissioned by Empress Bega Begum for Emperor Humayun. Reached modern renown following landmark AKTC conservation that revived the historic waterways.",
    cultural_significance: "Exemplifies the Persian Charbagh geometric paradise garden divided into four quadrants with flowing water channels.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "1.5 - 2 Hours",
    best_season: "October to March",
    nearby_destinations: ["Hazrat Nizamuddin Dargah", "Sundar Nursery", "National Zoological Park"],
    transport_information: {
      air: "Delhi IGI Airport (DEL) - 16 km",
      rail: "Hazrat Nizamuddin (NZM) - 1.5 km; New Delhi (NDLS) - 7 km",
      road: "Mathura Road & Lodhi Road junction",
      local: "JLN Stadium Metro (Violet Line) & Sarai Kale Khan Metro (Pink Line)"
    },
    nearest_transport: { railway_station: "Hazrat Nizamuddin (NZM)" },
    thumbnail_url: "https://images.unsplash.com/photo-1597044141245-3e28e18f26b5?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1597044141245-3e28e18f26b5?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["tomb", "unesco", "mughal", "garden", "delhi"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "india-gate",
    name: "India Gate & National War Memorial",
    city: "New Delhi",
    state: "Delhi (NCT)",
    region: "Northern India",
    coordinates: { lat: 28.6129, lng: 77.2295 },
    era: "1921 - 1931 CE",
    historical_period: "British Indian Era / Modern National Memorial",
    architectural_style: "Neoclassical Triumphal Arch",
    architect: "Sir Edwin Lutyens",
    material: "Pale red and yellow Bharatpur sandstone",
    unesco_site: false,
    heritage_status: "National War Memorial & Monument",
    summary: "42-meter-high triumphal arch honoring over 84,000 soldiers, standing at the eastern terminal of Kartavya Path with the adjoining National War Memorial.",
    historical_significance: "Commemorates soldiers of the British Indian Army who lost their lives in the First World War and Third Anglo-Afghan War, inscribed with over 13,000 names.",
    cultural_significance: "National civic ceremonial focal point; hosts the Republic Day Parade on Kartavya Path and the eternal flame honoring armed forces.",
    visiting_hours: "Open 24 Hours (Illumination 07:00 PM - 09:30 PM)",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "1 - 1.5 Hours",
    best_season: "October to March",
    nearby_destinations: ["Kartavya Path", "Rashtrapati Bhavan", "National Gallery of Modern Art"],
    transport_information: {
      air: "Delhi IGI Airport (DEL) - 14 km",
      rail: "New Delhi Railway Station (NDLS) - 4 km",
      road: "Rajpath / C-Hexagon Kartavya Path",
      local: "Central Secretariat Metro Station (Yellow / Violet Lines) - 1.2 km"
    },
    nearest_transport: { railway_station: "New Delhi (NDLS) / Central Secretariat Metro" },
    thumbnail_url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "National Monuments Authority (NMA)",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["memorial", "arch", "lutyens", "kartavya path", "delhi"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "golden-temple-amritsar",
    name: "Sri Harmandir Sahib (The Golden Temple)",
    city: "Amritsar",
    state: "Punjab",
    region: "Northern India",
    coordinates: { lat: 31.6200, lng: 74.8765 },
    era: "1581 - 1604 CE (Gold foil added 1830)",
    historical_period: "Sikh Gurus Era & Sikh Empire (Maharaja Ranjit Singh)",
    architectural_style: "Sikh Architecture (Fusion of Indo-Islamic and Rajput)",
    architect: "Guru Arjan Dev Ji & Maharaja Ranjit Singh",
    material: "White marble lower level with pure gold-plated copper leaf domes",
    unesco_site: false,
    heritage_status: "National Sacred Heritage (SGPC)",
    summary: "The holiest gurdwara of Sikhism surrounded by the holy Amrit Sarovar, famed for spiritual harmony and the world's largest free community kitchen (Langar).",
    historical_significance: "Fifth Sikh Guru, Guru Arjan Dev Ji, designed the gurdwara with four entrances welcoming people of all castes, and installed the Adi Granth in 1604.",
    cultural_significance: "Center of Sikh spiritual and temporal identity; home to the Akal Takht and serving tens of thousands of pilgrims daily with selfless service.",
    visiting_hours: "Open 24 Hours (Langar operates 24x7)",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 - 4 Hours",
    best_season: "October to March",
    nearby_destinations: ["Jallianwala Bagh", "Partition Museum", "Attari-Wagah Border"],
    transport_information: {
      air: "Sri Guru Ram Dass Jee International Airport (ATQ) - 12 km",
      rail: "Amritsar Junction (ASR) - 2.5 km (Direct Vande Bharat and Shatabdi)",
      road: "GT Road (NH 44) connects to Delhi and Chandigarh",
      local: "Free SGPC electric shuttle buses, e-rickshaws, and auto-rickshaws"
    },
    nearest_transport: { railway_station: "Amritsar Junction (ASR)" },
    thumbnail_url: "https://images.unsplash.com/photo-1588096344356-9b634839cf9e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1588096344356-9b634839cf9e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Shiromani Gurdwara Parbandhak Committee (SGPC)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["gurdwara", "sacred", "sikh", "gold", "amritsar", "punjab"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "kalka-shimla-railway",
    name: "Kalka-Shimla Mountain Railway",
    city: "Shimla",
    state: "Himachal Pradesh",
    region: "Northern India",
    coordinates: { lat: 31.1048, lng: 77.1734 },
    era: "1898 - 1903 CE",
    historical_period: "British Colonial Hill Station Infrastructure",
    architectural_style: "Victorian Alpine Mountain Rail Engineering",
    architect: "H.S. Harington & Baba Bhalku",
    material: "2 ft 6 in narrow-gauge tracks, multi-arch stone viaducts, 102 tunnels",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site (Mountain Railways of India)",
    summary: "Historic 96-km narrow-gauge railway climbing through 102 tunnels and over 800 stone arch bridges from the Himalayan foothills to Shimla.",
    historical_significance: "Constructed under severe Himalayan terrain constraints to connect British India's summer capital; Baba Bhalku guided tunnel alignments using his stick.",
    cultural_significance: "Living heritage marvel operating vintage steam and diesel heritage railcars offering breathtaking panoramic Shivalik mountain vistas.",
    visiting_hours: "06:00 AM - 08:00 PM (Regular Scheduled Trains)",
    entry_fee_inr: 50,
    entry_fee: { domestic: 50, international: 500, currency: "INR" },
    recommended_visit_duration: "5 Hours (Journey time)",
    best_season: "March to June & September to December",
    nearby_destinations: ["The Ridge Shimla", "Mall Road", "Jakhu Temple", "Kalka"],
    transport_information: {
      air: "Shimla Airport Jubbarhatti (SLV) - 22 km; Chandigarh (IXC) - 120 km",
      rail: "Shimla Railway Station (SML) & Kalka Junction (KLK)",
      road: "Himalayan Expressway (NH 5) connects Chandigarh to Shimla",
      local: "Heritage Toy Train services (Shivalik Deluxe, Himalayan Queen)"
    },
    nearest_transport: { railway_station: "Shimla (SML) / Kalka (KLK)" },
    thumbnail_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Indian Railways / UNESCO World Heritage Centre",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["railway", "unesco", "himalayas", "toy train", "himachal pradesh"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "kedarnath-temple",
    name: "Kedarnath Temple",
    city: "Rudraprayag District",
    state: "Uttarakhand",
    region: "Northern India",
    coordinates: { lat: 30.7352, lng: 79.0669 },
    era: "8th Century CE (Current stone structure)",
    historical_period: "Adi Shankaracharya Era / Pandava mythological origins",
    architectural_style: "North Indian Katyuri Nagara Stone Temple",
    architect: "Adi Shankaracharya (Reconstruction)",
    material: "Massive grey cut-stone slabs interlocked without mortar",
    unesco_site: false,
    heritage_status: "Ancient Sacred Shrine (Char Dham & Jyotirlinga)",
    summary: "One of the twelve sacred Jyotirlingas of Lord Shiva standing at 3,584m altitude against the towering snowbound Kedarnath peak in the Garhwal Himalayas.",
    historical_significance: "Confounded modern structural engineers by surviving the catastrophic 2013 Himalayan deluge thanks to its massive interlocking stone foundation.",
    cultural_significance: "Pinnacle of the Panch Kedar pilgrimage and the Northern Chota Char Dham circuit, visited by hundreds of thousands of pilgrims each summer.",
    visiting_hours: "04:00 AM - 09:00 PM (May to November seasonal)",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "1 - 2 Days (Trek required)",
    best_season: "May to June & September to October",
    nearby_destinations: ["Bhairavnath Temple", "Gandhi Sarovar", "Vasuki Tal", "Gaurikund"],
    transport_information: {
      air: "Jolly Grant Airport Dehradun (DED) - 238 km; Helipad at Kedarnath",
      rail: "Rishikesh Railway Station (RKSH) - 215 km; Yog Nagari Rishikesh (YNRK)",
      road: "Motorable road ends at Gaurikund (16 km trek to Kedarnath shrine)",
      local: "Pedestrian trek route, ponies, palanquins (doli), and Pawan Hans heli-shuttle"
    },
    nearest_transport: { railway_station: "Rishikesh (RKSH) / Gaurikund Base" },
    thumbnail_url: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Badrinath-Kedarnath Temple Committee (BKTC)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "sacred", "jyotirlinga", "himalayas", "uttarakhand"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "shalimar-bagh-srinagar",
    name: "Shalimar Bagh Mughal Garden",
    city: "Srinagar",
    state: "Jammu and Kashmir",
    region: "Northern India",
    coordinates: { lat: 34.1488, lng: 74.8724 },
    era: "1619 CE",
    historical_period: "Mughal Empire (Emperor Jahangir)",
    architectural_style: "Persian Terraced Charbagh Garden Architecture",
    architect: "Commissioned by Emperor Jahangir for Empress Nur Jahan",
    material: "Black marble pavilions, stone water flumes, century-old chinar groves",
    unesco_site: false,
    heritage_status: "ASI Protected Heritage Garden (UNESCO Tentative List)",
    summary: "Royal Mughal garden terraced across Dal Lake, built by Jahangir for Nur Jahan with black marble pavilions, fountains, and towering chinar trees.",
    historical_significance: "Celebrated by Emperor Jahangir with his famed verse: 'Gar Firdaus bar-rue zamin ast, hamin ast-o hamin ast-o hamin ast' (If paradise is on earth, it is here).",
    cultural_significance: "Masterwork of water garden engineering that funnels snowmelt cascades through cascades and chini-khanas (candle niches behind waterfalls).",
    visiting_hours: "09:00 AM - 07:00 PM",
    entry_fee_inr: 24,
    entry_fee: { domestic: 24, international: 200, currency: "INR" },
    recommended_visit_duration: "1.5 - 2 Hours",
    best_season: "April to October",
    nearby_destinations: ["Nishat Bagh", "Dal Lake", "Chashme Shahi", "Hari Parbat"],
    transport_information: {
      air: "Sheikh ul-Alam International Airport Srinagar (SXR) - 25 km",
      rail: "Srinagar Railway Station (SINA) - 20 km",
      road: "Foreshore Road / Boulevard along Dal Lake",
      local: "Shikara boats across Dal Lake, tourist taxis, and auto-rickshaws"
    },
    nearest_transport: { railway_station: "Srinagar (SINA)" },
    thumbnail_url: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Jammu & Kashmir Tourism & ASI",
    last_updated: "2026-03-01",
    category: "Natural & Ghats",
    tags: ["garden", "mughal", "dal lake", "srinagar", "jammu and kashmir"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "leh-palace",
    name: "Leh Palace & Tsemo Fort",
    city: "Leh",
    state: "Ladakh",
    region: "Northern India",
    coordinates: { lat: 34.1663, lng: 77.5857 },
    era: "1600 CE",
    historical_period: "Kingdom of Ladakh (Namgyal Dynasty)",
    architectural_style: "Medieval Tibetan Cliffside Dzong Architecture",
    architect: "King Sengge Namgyal",
    material: "Sun-dried mud-brick, stone masonry, and timber beams",
    unesco_site: false,
    heritage_status: "ASI Monument of National Importance",
    summary: "Nine-storey royal citadel towering over Leh Old Town modeled after Lhasa's Potala Palace, offering sweeping panoramic views of the Zanskar range.",
    historical_significance: "Built by King Sengge Namgyal as the royal residence of the Namgyal dynasty until the Dogra invasion in the mid-19th century.",
    cultural_significance: "Houses rich collections of 450-year-old Buddhist thangkas, ceremonial robes, Tibetan manuscripts, and an ASI heritage museum.",
    visiting_hours: "07:00 AM - 06:00 PM",
    entry_fee_inr: 25,
    entry_fee: { domestic: 25, international: 300, currency: "INR" },
    recommended_visit_duration: "1.5 - 2 Hours",
    best_season: "May to October",
    nearby_destinations: ["Namgyal Tsemo Gompa", "Shanti Stupa", "Leh Main Bazaar", "Hall of Fame"],
    transport_information: {
      air: "Kushok Bakula Rimpochee Airport Leh (IXL) - 5 km",
      rail: "Jammu Tawi (JAT) - 700 km / Udhampur (UHP)",
      road: "Leh-Manali Highway (NH 3) & Srinagar-Leh Highway (NH 1)",
      local: "Walking ascent through Old Town, local taxis, and rental motorbikes"
    },
    nearest_transport: { railway_station: "Leh Airport (IXL) / Jammu Tawi (JAT)" },
    thumbnail_url: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["palace", "dzong", "tibetan", "ladakh", "himalayas"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "capitol-complex-chandigarh",
    name: "The Capitol Complex (Le Corbusier)",
    city: "Chandigarh",
    state: "Chandigarh",
    region: "Northern India",
    coordinates: { lat: 30.7583, lng: 76.8055 },
    era: "1951 - 1962 CE",
    historical_period: "Post-Independence Modern India",
    architectural_style: "Modernist Brutalism Architecture",
    architect: "Le Corbusier (Charles-Édouard Jeanneret)",
    material: "Shutter-finished reinforced raw concrete (béton brut)",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Masterpiece of 20th-century modern architecture comprising the Secretariat, High Court, Legislative Assembly, and the iconic 26-meter Open Hand Monument.",
    historical_significance: "Commissioned by Prime Minister Jawaharlal Nehru as a city unfettered by existing traditions, symbolizing a newly independent democratic India.",
    cultural_significance: "Inscribed by UNESCO as part of the transnational nomination of Le Corbusier's architectural works, celebrating revolutionary urban design.",
    visiting_hours: "09:00 AM - 05:00 PM (Official guided tours available)",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Sukhna Lake", "Rock Garden Chandigarh", "Zakir Hussain Rose Garden"],
    transport_information: {
      air: "Shaheed Bhagat Singh International Airport (IXC) - 18 km",
      rail: "Chandigarh Junction (CDG) - 10 km (Fast Shatabdi and Vande Bharat)",
      road: "Himalaya Marg / Jan Marg in Sector 1",
      local: "Chandigarh CTU public AC buses, radio cabs, and cycle-sharing network"
    },
    nearest_transport: { railway_station: "Chandigarh Junction (CDG)" },
    thumbnail_url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Chandigarh Tourism / UNESCO World Heritage Centre",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["modernist", "unesco", "le corbusier", "open hand", "chandigarh"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  }
];

export { monuments };
