// Curated South India monuments (12): Karnataka, Tamil Nadu, Kerala, Andhra Pradesh, Telangana, Puducherry
const monuments = [
  // --- SOUTH INDIA (12) ---
  {
    id: "hampi-monuments",
    name: "Group of Monuments at Hampi (Vijayanagara)",
    city: "Vijayanagara District",
    state: "Karnataka",
    region: "Southern India",
    coordinates: { lat: 15.3350, lng: 76.4600 },
    era: "14th - 16th Century CE",
    historical_period: "Vijayanagara Empire (Krishnadevaraya)",
    architectural_style: "Dravidian Vijayanagara Architecture",
    architect: "Vijayanagara Royal Builders",
    material: "Locally quarried granite boulders",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Sprawling capital of the Vijayanagara Empire dotted with over 1,600 surviving monuments, iconic monolithic Stone Chariot, and musical pillars at Vittala Temple.",
    historical_significance: "Capital of the opulent Vijayanagara Empire described by medieval Portuguese and Persian travelers as larger and wealthier than Rome.",
    cultural_significance: "Surreal boulder-strewn landscape along the sacred Tungabhadra River; centers around the continuously active Virupaksha Temple.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "1 - 2 Days",
    best_season: "October to March",
    nearby_destinations: ["Virupaksha Temple", "Vittala Temple", "Lotus Mahal", "Elephant Stables"],
    transport_information: {
      air: "Jindal Vijayanagar Airport Bellary (VDY) - 35 km; Hubballi (HBX) - 145 km",
      rail: "Hosapete Junction (HPT) - 13 km (Regular trains from Bengaluru & Goa)",
      road: "NH 50 & NH 67 connect from Bengaluru (340 km) and Hyderabad",
      local: "Electric buggy carts inside Vittala complex, rental mopeds, and auto-rickshaws"
    },
    nearest_transport: { railway_station: "Hosapete Junction (HPT)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["ruins", "unesco", "vijayanagara", "stone chariot", "hampi", "karnataka"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "pattadakal-monuments",
    name: "Group of Monuments at Pattadakal",
    city: "Bagalkot District",
    state: "Karnataka",
    region: "Southern India",
    coordinates: { lat: 15.9489, lng: 75.8160 },
    era: "7th - 8th Century CE",
    historical_period: "Badami Chalukya Dynasty (Vikramaditya II)",
    architectural_style: "Vesara Style (Fusion of Nagara and Dravidian)",
    architect: "Gundan Anivaritachari",
    material: "Red-golden sandstone",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Royal coronation site of the Badami Chalukyas showcasing an eclectic synthesis of northern Nagara and southern Dravidian temple styles.",
    historical_significance: "Site where Chalukya emperors were crowned; Virupaksha Temple was built in 740 CE by Queen Lokamahadevi to celebrate victory over the Pallavas.",
    cultural_significance: "Regarded as the testing cradle of early medieval Indian temple architecture along the Malaprabha River, inspiring subsequent Deccan dynasties.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "2 Hours",
    best_season: "October to March",
    nearby_destinations: ["Badami Cave Temples", "Aihole Temple Complex", "Banashankari Temple"],
    transport_information: {
      air: "Hubballi Airport (HBX) - 130 km; Belagavi Airport - 140 km",
      rail: "Badami Railway Station (BDM) - 22 km; Bagalkot (BGK) - 45 km",
      road: "State Highway 14 connects Badami, Pattadakal, and Aihole",
      local: "KSRTC local shuttle buses, shared cruiser jeeps, and tourist cabs"
    },
    nearest_transport: { railway_station: "Badami (BDM)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "chalukya", "dravidian", "nagara", "karnataka"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "hoysala-temples-belur",
    name: "Sacred Ensembles of the Hoysalas (Belur & Halebidu)",
    city: "Hassan District",
    state: "Karnataka",
    region: "Southern India",
    coordinates: { lat: 13.1623, lng: 75.8596 },
    era: "1117 - 1268 CE",
    historical_period: "Hoysala Empire (King Vishnuvardhana)",
    architectural_style: "Hoysala Karnata Dravida Star-Shaped Architecture",
    architect: "Ruvari Mallitamma, Dasoja & Jakanachari",
    material: "Finely carved chloritic schist (soapstone)",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Star-shaped soapstone temple sanctums featuring intricate friezes of celestial dancers (Shilabhalikas), elephants, and epics carved like lace.",
    historical_significance: "Commissioned by King Vishnuvardhana after his victory against the Cholas; inscribed on the UNESCO World Heritage List in 2023.",
    cultural_significance: "Pinnacle of medieval South Indian soapstone sculpting; artists signed their names on temple walls, unprecedented in ancient Indian history.",
    visiting_hours: "07:30 AM - 06:30 PM",
    entry_fee_inr: 25,
    entry_fee: { domestic: 25, international: 300, currency: "INR" },
    recommended_visit_duration: "3 - 4 Hours",
    best_season: "October to March",
    nearby_destinations: ["Halebidu Hoysaleshwara Temple", "Somnathapura Keshava Temple", "Shravanabelagola"],
    transport_information: {
      air: "Mangalore International Airport (IXE) - 150 km; Bengaluru (BLR) - 220 km",
      rail: "Hassan Junction (HAS) - 38 km (Regular trains to Bengaluru and Mysuru)",
      road: "NH 75 from Bengaluru to Hassan, then SH 57 to Belur",
      local: "KSRTC buses between Hassan, Belur, and Halebidu; tourist taxis"
    },
    nearest_transport: { railway_station: "Hassan Junction (HAS)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI) / UNESCO",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "hoysala", "soapstone", "belur", "karnataka"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "brihadisvara-temple",
    name: "Brihadisvara Temple (Peruvudaiyar Kovil)",
    city: "Thanjavur",
    state: "Tamil Nadu",
    region: "Southern India",
    coordinates: { lat: 10.7828, lng: 79.1318 },
    era: "1003 - 1010 CE",
    historical_period: "Chola Empire (Raja Raja Chola I)",
    architectural_style: "High Dravidian Temple Architecture",
    architect: "Kunjara Mallan Raja Raja Perunthachan",
    material: "Complete granite construction with 80-tonne monolithic kumbam",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site (Great Living Chola Temples)",
    summary: "Magnificent granite temple built by Emperor Raja Raja Chola I, featuring a 66-meter towering vimana capped by an 80-tonne single-stone cupola.",
    historical_significance: "Celebrated its millennium (1000 years) in 2010; constructed entirely of granite hauled from quarries over 50 km away using inclined earthen ramps.",
    cultural_significance: "Living temple dedicated to Lord Shiva; preserves original 11th-century Chola wall frescoes, Tamil inscriptions, and a massive monolithic Nandi statue.",
    visiting_hours: "06:00 AM - 12:30 PM, 04:00 PM - 08:30 PM",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "November to February",
    nearby_destinations: ["Thanjavur Maratha Palace", "Saraswathi Mahal Library", "Gangaikonda Cholapuram"],
    transport_information: {
      air: "Tiruchirappalli International Airport (TRZ) - 55 km",
      rail: "Thanjavur Junction (TJ) - 2 km (Connected to Chennai and Madurai)",
      road: "NH 83 connects to Tiruchirappalli and Nagapattinam",
      local: "Auto-rickshaws, municipal town buses, and walking heritage promenades"
    },
    nearest_transport: { railway_station: "Thanjavur Junction (TJ)" },
    thumbnail_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI) / HR&CE",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "chola", "granite", "vimana", "tamil nadu"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "shore-temple-mahabalipuram",
    name: "Shore Temple & Monuments at Mahabalipuram",
    city: "Chengalpattu District",
    state: "Tamil Nadu",
    region: "Southern India",
    coordinates: { lat: 12.6164, lng: 80.1983 },
    era: "700 - 728 CE",
    historical_period: "Pallava Dynasty (Narasimhavarman II / Rajasimha)",
    architectural_style: "Early Dravidian Structural & Rock-Cut Architecture",
    architect: "Pallava Royal Sculptors",
    material: "Cut granite blocks perched on the Bay of Bengal coastline",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "One of the oldest structural stone temples in South India, framed by the roaring surf of the Bay of Bengal alongside the monolithic Pancha Rathas.",
    historical_significance: "Served as a navigational landmark and premier maritime trading emporium connecting the Pallava dynasty with Southeast Asia and China.",
    cultural_significance: "Site includes Arjuna's Penance (Descent of the Ganges), the world's largest open-air stone bas-relief depicting life and celestials.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "November to February",
    nearby_destinations: ["Pancha Rathas", "Krishna's Butterball", "Arjuna's Penance", "Covelong Beach"],
    transport_information: {
      air: "Chennai International Airport (MAA) - 55 km",
      rail: "Chengalpattu Junction (CGL) - 29 km; Chennai Central (MAS) - 60 km",
      road: "East Coast Road (ECR) scenic coastal highway from Chennai",
      local: "Local auto-rickshaws, rental bicycles, and coastal walking paths"
    },
    nearest_transport: { railway_station: "Chengalpattu (CGL) / Chennai Central" },
    thumbnail_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "pallava", "shore temple", "ecr", "tamil nadu"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "meenakshi-amman-temple",
    name: "Arulmigu Meenakshi Amman Temple",
    city: "Madurai",
    state: "Tamil Nadu",
    region: "Southern India",
    coordinates: { lat: 9.9195, lng: 78.1193 },
    era: "1623 - 1655 CE (Expanded form)",
    historical_period: "Madurai Nayak Dynasty (Tirumala Nayaka) & Pandya origins",
    architectural_style: "Classical Dravidian Temple Architecture",
    architect: "Vishwanatha Nayak & Ariyanatha Mudaliar",
    material: "Granite temple complex with 14 multi-tiered stucco-sculpted gopurams",
    unesco_site: false,
    heritage_status: "Historic Sacred Shrine (HR&CE Protected)",
    summary: "Ancient city temple centered around Goddess Meenakshi with 14 rainbow-colored sculpted gopurams and the celebrated Hall of 1,000 Pillars.",
    historical_significance: "Heart of the 2,500-year-old historic city of Madurai, laid out in concentric squares modeled after the lotus petals of the cosmos.",
    cultural_significance: "Famous for the Hall of Thousand Pillars (Ayiram Kaal Mandapam) with musical pillars and the daily celestial night wedding ceremony of Shiva and Parvati.",
    visiting_hours: "05:00 AM - 12:30 PM, 04:00 PM - 10:00 PM",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Thirumalai Nayakkar Mahal", "Gandhi Memorial Museum Madurai", "Vandiyur Mariamman Teppakulam"],
    transport_information: {
      air: "Madurai International Airport (IXM) - 12 km",
      rail: "Madurai Junction (MDU) - 1.5 km (Direct Tejas and Vande Bharat)",
      road: "NH 38 & NH 44 pass through Madurai city center",
      local: "Auto-rickshaws, battery-operated buggies around temple streets"
    },
    nearest_transport: { railway_station: "Madurai Junction (MDU)" },
    thumbnail_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Hindu Religious and Charitable Endowments (HR&CE)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "sacred", "dravidian", "gopuram", "madurai", "tamil nadu"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "fort-kochi-heritage",
    name: "Fort Kochi & Mattancherry Palace",
    city: "Kochi",
    state: "Kerala",
    region: "Southern India",
    coordinates: { lat: 9.9675, lng: 76.2425 },
    era: "1503 - 1663 CE",
    historical_period: "Portuguese, Dutch, and Kingdom of Kochi Eras",
    architectural_style: "Kerala-Colonial Dutch & Portuguese Maritime Architecture",
    architect: "Portuguese and Dutch Colonial Builders & Kochi Artisans",
    material: "Teakwood, laterite masonry, terracotta tiles, and mural plasters",
    unesco_site: false,
    heritage_status: "ASI Protected Heritage Precinct",
    summary: "Historic spice port featuring iconic Chinese fishing nets, St. Francis Church (oldest European church in India), and the Dutch Palace with Ramayana murals.",
    historical_significance: " Vasco da Gama was initially buried at St. Francis Church in 1524; Mattancherry Palace was gifted to the Raja of Kochi by the Portuguese.",
    cultural_significance: "Melting pot of Jewish, Portuguese, Dutch, British, and indigenous Malayali cultures; hosts the prestigious Kochi-Muziris Biennale.",
    visiting_hours: "09:45 AM - 01:00 PM, 02:00 PM - 04:45 PM (Closed Fridays)",
    entry_fee_inr: 5,
    entry_fee: { domestic: 5, international: 100, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "September to March",
    nearby_destinations: ["Chinese Fishing Nets", "Paradesi Synagogue", "Jew Town", "St. Francis Church"],
    transport_information: {
      air: "Cochin International Airport (COK) - 42 km",
      rail: "Ernakulam Junction (ERS) - 12 km; Ernakulam Town (ERN) - 14 km",
      road: "NH 966B connects Ernakulam city via Thoppumpady Bridge",
      local: "Water Metro passenger ferries from Marine Drive, rental cycles, tuk-tuks"
    },
    nearest_transport: { railway_station: "Ernakulam Junction (ERS)" },
    thumbnail_url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI) & Kerala Tourism",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["colonial", "palace", "chinese fishing nets", "spice trade", "kochi", "kerala"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "lepakshi-veerabhadra-temple",
    name: "Lepakshi Veerabhadra Temple & Nandi",
    city: "Sri Sathya Sai (Anantapur)",
    state: "Andhra Pradesh",
    region: "Southern India",
    coordinates: { lat: 13.8041, lng: 77.6067 },
    era: "1530 - 1545 CE",
    historical_period: "Vijayanagara Empire (King Achyuta Deva Raya)",
    architectural_style: "Vijayanagara Temple Architecture & Frescoes",
    architect: "Virupanna Nayaka & Viranna",
    material: "Monolithic granite carving, famous hanging pillar, and ceiling frescoes",
    unesco_site: false,
    heritage_status: "ASI Monument of National Importance (UNESCO Tentative List)",
    summary: "16th-century Vijayanagara engineering marvel renowned for its gravity-defying Hanging Pillar, India's largest monolithic Nandi bull, and exquisite ceiling murals.",
    historical_significance: "Built by brothers Virupanna and Viranna, governors under King Achyuta Deva Raya; preserves the largest single fresco in Asia depicting Veerabhadra.",
    cultural_significance: "The famous Hanging Pillar slightly disengages from the ground allowing a cloth or paper to pass underneath, baffling visitors for centuries.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 Hours",
    best_season: "October to March",
    nearby_destinations: ["Monolithic Nandi Lepakshi", "Nagalinga Monolith", "Hindupur"],
    transport_information: {
      air: "Kempegowda International Airport Bengaluru (BLR) - 100 km",
      rail: "Hindupur Railway Station (HUP) - 14 km (Well connected from Bengaluru)",
      road: "NH 44 (Bengaluru-Hyderabad Highway) via Kodikonda Checkpost",
      local: "APSRTC buses from Hindupur, local shared autos, and taxi rentals"
    },
    nearest_transport: { railway_station: "Hindupur (HUP)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "hanging pillar", "nandi", "vijayanagara", "andhra pradesh"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "ramappa-temple",
    name: "Kakatiya Rudreshwara (Ramappa) Temple",
    city: "Palampet, Mulugu",
    state: "Telangana",
    region: "Southern India",
    coordinates: { lat: 18.2605, lng: 79.9431 },
    era: "1213 CE",
    historical_period: "Kakatiya Empire (King Ganapati Deva)",
    architectural_style: "Kakatiya Sandbox & Floating Brick Architecture",
    architect: "Sculptor Ramappa",
    material: "Red sandstone sanctum, floating porous bricks, carved black basalt Madanika brackets",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "13th-century Kakatiya temple named after its master sculptor Ramappa, celebrated for earthquake-resistant sandbox foundations and floating light-weight bricks.",
    historical_significance: "The only temple in India named after its sculptor rather than the presiding deity; inscribed as a UNESCO World Heritage Site in 2021.",
    cultural_significance: "Distinguished by lustrous black basalt bracket figures (Madanikas) depicting graceful dancers with intricate anatomical detail.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 25,
    entry_fee: { domestic: 25, international: 300, currency: "INR" },
    recommended_visit_duration: "2 Hours",
    best_season: "October to March",
    nearby_destinations: ["Ramappa Lake", "Warangal Fort", "Thousand Pillar Temple Warangal", "Laknavaram Lake"],
    transport_information: {
      air: "Rajiv Gandhi International Airport Hyderabad (HYD) - 210 km",
      rail: "Kazipet Junction (KZJ) - 65 km; Warangal Railway Station (WL) - 68 km",
      road: "NH 163 from Hyderabad to Mulugu/Palampet (4 hrs drive)",
      local: "TSRTC buses from Warangal/Hanamkonda, tourist cabs"
    },
    nearest_transport: { railway_station: "Kazipet (KZJ) / Warangal (WL)" },
    thumbnail_url: "https://images.unsplash.com/photo-1616198814651-e71f960c3180?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1616198814651-e71f960c3180?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI) / UNESCO",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "kakatiya", "floating bricks", "telangana"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "charminar",
    name: "Charminar Monument & Mosque",
    city: "Hyderabad",
    state: "Telangana",
    region: "Southern India",
    coordinates: { lat: 17.3616, lng: 78.4747 },
    era: "1591 CE",
    historical_period: "Qutb Shahi Dynasty (Muhammad Quli Qutb Shah)",
    architectural_style: "Indo-Islamic Qutb Shahi Architecture",
    architect: "Mir Momin Astarabadi",
    material: "Granite, limestone, mortar, and pulverized marble",
    unesco_site: false,
    heritage_status: "ASI Monument of National Importance",
    summary: "Four-minareted square arch monument standing at the heart of Hyderabad's historic walled city, built to commemorate the eradication of a deadly plague.",
    historical_significance: "Commissioned by Muhammad Quli Qutb Shah in 1591 when establishing Hyderabad as his new capital, centered around a legendary open-air mosque.",
    cultural_significance: "Global symbol of Hyderabad; anchors the buzzing Laad Bazaar lacquer bangle market and Mecca Masjid heritage precinct.",
    visiting_hours: "09:00 AM - 05:30 PM",
    entry_fee_inr: 25,
    entry_fee: { domestic: 25, international: 300, currency: "INR" },
    recommended_visit_duration: "1 - 1.5 Hours",
    best_season: "October to March",
    nearby_destinations: ["Mecca Masjid", "Laad Bazaar", "Chowmahalla Palace", "Salar Jung Museum"],
    transport_information: {
      air: "Rajiv Gandhi International Airport (HYD) - 18 km",
      rail: "Hyderabad Deccan Nampally (HYB) - 4 km; Secunderabad (SC) - 10 km",
      road: "Charminar pedestrianized heritage zone / Pathergatti Road",
      local: "Hyderabad Metro Green Line (MGBS Station - 1.5 km), TSRTC buses"
    },
    nearest_transport: { railway_station: "Hyderabad Deccan (HYB)" },
    thumbnail_url: "https://images.unsplash.com/photo-1588097281266-31018512954b?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1588097281266-31018512954b?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["monument", "qutb shahi", "minaret", "hyderabad", "telangana"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "golconda-fort",
    name: "Golconda Fort & Citadel",
    city: "Hyderabad",
    state: "Telangana",
    region: "Southern India",
    coordinates: { lat: 17.3833, lng: 78.4011 },
    era: "1512 - 1687 CE",
    historical_period: "Kakatiya & Qutb Shahi Dynasties",
    architectural_style: "Medieval Islamic Military Citadel & Acoustic Engineering",
    architect: "Sultan Quli Qutb-ul-Mulk",
    material: "Granite rubble masonry and massive arched bastions",
    unesco_site: false,
    heritage_status: "ASI Monument of National Importance",
    summary: "Massive granite hilltop citadel famed for acoustic engineering where a handclap at the entrance gate can be heard 1 km away at the summit pavilion.",
    historical_significance: "Capital of the Qutb Shahi Sultanate and global trade center for legendary Golconda diamonds including the Koh-i-Noor and Hope diamonds.",
    cultural_significance: "Dramatic 87-bastion fortress with sound and light shows, secret subterranean escape tunnels, and panoramic city views from the Bala Hissar.",
    visiting_hours: "09:00 AM - 05:30 PM (Sound & Light Show: 06:30 PM - 08:30 PM)",
    entry_fee_inr: 25,
    entry_fee: { domestic: 25, international: 300, currency: "INR" },
    recommended_visit_duration: "2.5 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Qutb Shahi Tombs", "Taramati Baradari", "Charminar"],
    transport_information: {
      air: "Rajiv Gandhi International Airport (HYD) - 25 km",
      rail: "Hyderabad Deccan (HYB) - 9 km",
      road: "Mehdipatnam-Golconda Road",
      local: "City buses (Route 66G from Charminar / 5K), app cabs, autos"
    },
    nearest_transport: { railway_station: "Hyderabad Deccan (HYB)" },
    thumbnail_url: "https://images.unsplash.com/photo-1616198814651-e71f960c3180?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1616198814651-e71f960c3180?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["fort", "acoustics", "diamonds", "qutb shahi", "hyderabad", "telangana"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "french-quarter-puducherry",
    name: "French Quarter (White Town) Heritage Precinct",
    city: "Puducherry",
    state: "Puducherry",
    region: "Southern India",
    coordinates: { lat: 11.9338, lng: 79.8357 },
    era: "18th - 19th Century CE",
    historical_period: "French East India Company & Union Territory Heritage",
    architectural_style: "Franco-Tamil Colonial Architecture",
    architect: "French colonial urban planners",
    material: "Lime-plastered masonry with pastel yellow facades and arched courtyards",
    unesco_site: false,
    heritage_status: "State Heritage Conservation Precinct",
    summary: "Grid-patterned seaside colonial quarter featuring mustard-yellow villas, bougainvillea gates, French street signs, and the scenic Promenade Beach.",
    historical_significance: "Established in 1674 by François Martin as the capital of French settlements in India, separated by a canal from the Tamil quarter.",
    cultural_significance: "Unique Franco-Indian cultural sanctuary; home to Sri Aurobindo Ashram, French Institute of Pondicherry, and heritage bakeries.",
    visiting_hours: "Open 24 Hours (Promenade closed to vehicular traffic in evenings)",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Promenade Beach", "Sri Aurobindo Ashram", "Auroville", "Arikamedu Roman Site"],
    transport_information: {
      air: "Puducherry Airport (PNY) - 6 km; Chennai Airport (MAA) - 145 km",
      rail: "Puducherry Railway Station (PDY) - 1.5 km",
      road: "East Coast Road (ECR) connects directly from Chennai (3 hrs drive)",
      local: "Rental vintage bicycles, electric scooters, and coastal walking trails"
    },
    nearest_transport: { railway_station: "Puducherry (PDY)" },
    thumbnail_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Puducherry Tourism / INTACH",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["colonial", "french quarter", "promenade", "white town", "puducherry"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  }
];

export { monuments };
