// Curated Central (3), East (5), and Northeast (3) India monuments: Total 11
const monuments = [
  // --- CENTRAL INDIA (3) ---
  {
    id: "khajuraho-monuments",
    name: "Khajuraho Group of Monuments",
    city: "Chhatarpur District",
    state: "Madhya Pradesh",
    region: "Central India",
    coordinates: { lat: 24.8318, lng: 79.9199 },
    era: "950 - 1050 CE",
    historical_period: "Chandela Dynasty (Kings Yashovarman and Dhanga)",
    architectural_style: "Nagara Style Hindu and Jain Temple Architecture",
    architect: "Chandela Master Builders",
    material: "Golden sandstone dry-mortise masonry",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "World-famous Nagara-style temple complex celebrating the cosmos and human celebration, featuring the soaring Kandariya Mahadeva Temple.",
    historical_significance: "Built during the zenith of the Chandela Rajput dynasty; hidden by dense forests for centuries until rediscovered by British surveyor T.S. Burt in 1838.",
    cultural_significance: "Celebrated for its harmonious balance of spiritual sanctums and expressive stone carvings depicting everyday life, music, dance, and human passion.",
    visiting_hours: "Sunrise to Sunset (06:00 AM - 06:00 PM)",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "3 - 4 Hours",
    best_season: "October to March",
    nearby_destinations: ["Kandariya Mahadeva Temple", "Lakshmana Temple", "Raneh Waterfalls", "Panna National Park"],
    transport_information: {
      air: "Khajuraho Airport (HJR) - 5 km",
      rail: "Khajuraho Railway Station (KURJ) - 6 km; Mahoba (MBA) - 75 km",
      road: "NH 39 connects Jhansi (175 km) and Satna (120 km)",
      local: "Auto-rickshaws, rental bicycles for western and eastern group circuits"
    },
    nearest_transport: { railway_station: "Khajuraho (KURJ)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "chandela", "sculpture", "khajuraho", "madhya pradesh"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "sanchi-stupa",
    name: "Great Stupa at Sanchi",
    city: "Raisen District",
    state: "Madhya Pradesh",
    region: "Central India",
    coordinates: { lat: 23.4793, lng: 77.7397 },
    era: "3rd Century BCE - 12th Century CE",
    historical_period: "Maurya Empire (Emperor Ashoka) & Shunga Dynasty",
    architectural_style: "Ancient Buddhist Monolithic Stupa & Torana Architecture",
    architect: "Commissioned by Emperor Ashoka the Great",
    material: "Sandstone hemispherical mound with four intricately carved Toranas",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Oldest stone structure in India commissioned by Emperor Ashoka, featuring four grand ceremonial gateways (Toranas) narrating Jataka parables in stone.",
    historical_significance: "Ashoka erected this stupa to enshrine relics of the Buddha; his Greek-influenced pillars and lion capitals established India's national iconography.",
    cultural_significance: "Spiritual epicenter of Buddhist pilgrimage; preserved virtually intact due to its peaceful hilltop sanctuary overlooking the Betwa Valley.",
    visiting_hours: "Sunrise to Sunset (06:30 AM - 06:30 PM)",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Sanchi Archaeological Museum", "Udayagiri Caves", "Vidisha Heliodorus Pillar"],
    transport_information: {
      air: "Raja Bhoj Airport Bhopal (BHO) - 55 km",
      rail: "Sanchi Railway Station (SCI) - 1.5 km; Bhopal Junction (BPL) - 48 km",
      road: "Bhopal-Vidisha Highway (SH 19)",
      local: "Local shared autos from Sanchi station, tourist battery carts"
    },
    nearest_transport: { railway_station: "Sanchi (SCI) / Bhopal (BPL)" },
    thumbnail_url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["stupa", "unesco", "ashoka", "buddhist", "sanchi", "madhya pradesh"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "sirpur-monuments",
    name: "Laxman Brick Temple & Sirpur Monuments",
    city: "Mahasamund District",
    state: "Chhattisgarh",
    region: "Central India",
    coordinates: { lat: 21.3417, lng: 82.1794 },
    era: "7th Century CE (625 - 650 CE)",
    historical_period: "Panduvamshi Dynasty (Queen Vasata)",
    architectural_style: "Early Central Indian Brick Nagara Architecture",
    architect: "Queen Vasata (Mother of King Mahashivagupta Balarjuna)",
    material: "Finely molded burnt red clay bricks with stone lintel carvings",
    unesco_site: false,
    heritage_status: "ASI Monument of National Importance",
    summary: "One of India's finest 7th-century brick temples, dedicated to Lord Vishnu with exquisitely carved red terracotta lintels depicting Krishna Leela parables.",
    historical_significance: "Ancient capital of South Kosala visited by Chinese pilgrim Xuanzang in 639 CE, who recorded a thriving university with over 10,000 monks.",
    cultural_significance: "Extensive excavation site revealing coexisting Hindu temples, Buddhist monasteries (viharas), and underground market plazas along the Mahanadi River.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 25,
    entry_fee: { domestic: 25, international: 300, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Surang Tila Temple", "Teevardev Vihara", "Barnawapara Wildlife Sanctuary"],
    transport_information: {
      air: "Swami Vivekananda Airport Raipur (RPR) - 78 km",
      rail: "Mahasamund (MSMD) - 40 km; Raipur Junction (R) - 82 km",
      road: "NH 53 (Mumbai-Kolkata Highway) via Arang and Tumgaon",
      local: "Tourist taxis from Raipur, shared passenger jeeps from Mahasamund"
    },
    nearest_transport: { railway_station: "Mahasamund (MSMD) / Raipur (R)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "brick", "terracotta", "sirpur", "chhattisgarh"],
    rating: 4.6,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },

  // --- EAST INDIA (5) ---
  {
    id: "sun-temple-konark",
    name: "Sun Temple Konark (Black Pagoda)",
    city: "Puri District",
    state: "Odisha",
    region: "Eastern India",
    coordinates: { lat: 19.8876, lng: 86.0945 },
    era: "1250 CE",
    historical_period: "Eastern Ganga Dynasty (King Narasimhadeva I)",
    architectural_style: "Kalinga Temple Architecture (Gigantic Sun Chariot)",
    architect: "Bisu Maharana & 1200 Artisans",
    material: "Chlorite, laterite, and khondalite stone",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Colossal 13th-century temple fashioned as Surya's chariot with 24 carved stone wheels serving as functioning sundials, pulled by seven galloping stone horses.",
    historical_significance: "Conceived by King Narasimhadeva I to commemorate military victories; European sailors used its magnetic tower as a navigational landmark ('Black Pagoda').",
    cultural_significance: "Crown jewel of Odishan architectural art, immortalized by Rabindranath Tagore: 'Here the language of stone surpasses the language of human.'",
    visiting_hours: "06:00 AM - 08:00 PM (Light & Sound Show in Evening)",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Chandrabhaga Beach", "Konark ASI Archaeological Museum", "Jagannath Temple Puri"],
    transport_information: {
      air: "Biju Patnaik International Airport Bhubaneswar (BBI) - 65 km",
      rail: "Puri Railway Station (PURI) - 35 km; Bhubaneswar (BBS) - 65 km",
      road: "Marine Drive scenic coastal highway connects Puri and Konark",
      local: "Battery shuttle carts from parking, OTDC conducted tour AC coaches"
    },
    nearest_transport: { railway_station: "Puri (PURI) / Bhubaneswar (BBS)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "sundial", "kalinga", "konark", "odisha"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "mahabodhi-temple",
    name: "Mahabodhi Temple Complex",
    city: "Bodh Gaya",
    state: "Bihar",
    region: "Eastern India",
    coordinates: { lat: 24.6960, lng: 84.9914 },
    era: "3rd Century BCE (Ashoka) & 5th - 6th Century CE",
    historical_period: "Maurya Empire & Gupta Empire",
    architectural_style: "Classical Grand Indian Brick Temple",
    architect: "Emperor Ashoka & Gupta Dynasty Architects",
    material: "Stucco-covered brickwork and polished sandstone Vajrasana",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "One of the four sacred sites associated with the life of Lord Buddha, marking the exact spot beneath the sacred Bodhi Tree where Prince Siddhartha attained Enlightenment.",
    historical_significance: "First temple built by Emperor Ashoka in 260 BCE; contains the ancient Diamond Throne (Vajrasana) and sandstone Ashokan railings.",
    cultural_significance: "Supreme pilgrimage shrine for over 500 million Buddhists worldwide; surrounded by monasteries built in the traditional styles of Thailand, Tibet, Japan, and Bhutan.",
    visiting_hours: "05:00 AM - 09:00 PM",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Sacred Bodhi Tree", "Muchalinda Lake", "Great Buddha Statue 80ft", "Thai Monastery"],
    transport_information: {
      air: "Gaya International Airport (GAY) - 10 km; Patna Airport (PAT) - 110 km",
      rail: "Gaya Junction (GAYA) - 16 km (Direct Rajdhani and Vande Bharat)",
      road: "NH 83 connects Gaya to Bodh Gaya and Patna",
      local: "Electric battery carts around the temple perimeter, auto-rickshaws"
    },
    nearest_transport: { railway_station: "Gaya Junction (GAYA)" },
    thumbnail_url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Bodhgaya Temple Management Committee (BTMC) / UNESCO",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "unesco", "bodhi tree", "enlightenment", "bodh gaya", "bihar"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "nalanda-university-ruins",
    name: "Archaeological Site of Nalanda Mahavihara",
    city: "Nalanda",
    state: "Bihar",
    region: "Eastern India",
    coordinates: { lat: 25.1357, lng: 85.4439 },
    era: "5th Century CE - 1200 CE",
    historical_period: "Gupta Empire (Kumaragupta I) & Pala Empire",
    architectural_style: "Ancient Monastic Stupa & Vihara Architecture",
    architect: "Gupta and Pala Royal Monastic Architects",
    material: "Red brick masonry with ornamental plaster molding",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Ancient residential monastic university that flourished for 800 years, educating over 10,000 international scholars with the world's greatest ancient library, Dharmaganja.",
    historical_significance: "Pioneered structured higher education in astronomy, medicine, logic, and philosophy, documented extensively by Chinese traveler Xuanzang.",
    cultural_significance: "Remarkable complex of 11 monasteries and 6 brick temples centered around the iconic Sariputra Stupa with stepped corner shrines.",
    visiting_hours: "09:00 AM - 05:00 PM",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Nalanda Archaeological Museum", "Hiuen Tsang Memorial Hall", "Rajgir Hot Springs"],
    transport_information: {
      air: "Patna Airport (PAT) - 90 km",
      rail: "Rajgir (RGD) - 12 km; Nalanda Station (NLD) - 2 km; Bakhtiyarpur (BKP) - 50 km",
      road: "NH 120 connects Patna, Bihar Sharif, and Rajgir",
      local: "Electric rickshaws, horse-drawn tongas, and Bihar State Tourism coaches"
    },
    nearest_transport: { railway_station: "Rajgir (RGD) / Bakhtiyarpur (BKP)" },
    thumbnail_url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["university", "unesco", "ruins", "buddhist", "nalanda", "bihar"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "victoria-memorial-kolkata",
    name: "Victoria Memorial Hall",
    city: "Kolkata",
    state: "West Bengal",
    region: "Eastern India",
    coordinates: { lat: 22.5448, lng: 88.3426 },
    era: "1906 - 1921 CE",
    historical_period: "British Raj Era (Lord Curzon initiative)",
    architectural_style: "Indo-Saracenic & British Neoclassical",
    architect: "Sir William Emerson",
    material: "White Makrana marble from Rajasthan",
    unesco_site: false,
    heritage_status: "National Memorial & Museum (ASI)",
    summary: "Grand white Makrana marble monument set in 64 acres of landscaped gardens, housing 25 galleries of priceless historical paintings, manuscripts, and Raj artefacts.",
    historical_significance: "Conceived by Viceroy Lord Curzon as a stately monument; topped by the 16-foot bronze rotating Angel of Victory that turns with the wind.",
    cultural_significance: "Kolkata's most iconic civic monument and premier cultural museum, representing the historic heritage of the former imperial capital.",
    visiting_hours: "Gardens: 05:30 AM - 06:00 PM; Museum: 10:00 AM - 06:00 PM (Closed Mondays)",
    entry_fee_inr: 50,
    entry_fee: { domestic: 50, international: 500, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["St. Paul's Cathedral Kolkata", "Indian Museum", "Howrah Bridge", "Maidan"],
    transport_information: {
      air: "Netaji Subhash Chandra Bose International Airport (CCU) - 22 km",
      rail: "Howrah Junction (HWH) - 6 km; Sealdah (SDAH) - 5 km",
      road: "Jawaharlal Nehru Road / Queens Way bordering the Maidan",
      local: "Kolkata Metro Blue Line (Rabindra Sadan / Maidan Stations - 600 m)"
    },
    nearest_transport: { railway_station: "Howrah Junction (HWH) / Sealdah" },
    thumbnail_url: "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1558431382-27e303142255?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Victoria Memorial Hall Board of Trustees / Ministry of Culture",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["museum", "marble", "colonial", "maidan", "kolkata", "west bengal"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "baidyanath-dham-deoghar",
    name: "Baidyanath Jyotirlinga Temple Complex",
    city: "Deoghar",
    state: "Jharkhand",
    region: "Eastern India",
    coordinates: { lat: 24.4925, lng: 86.7001 },
    era: "1596 CE (Current main temple consecrated by Puran Mal)",
    historical_period: "Ancient Shiva Shrine & Gidhaur Dynasty",
    architectural_style: "Traditional Nagara Stone Temple Architecture",
    architect: "Raja Puran Mal of Gidhaur",
    material: "Carved sandstone with gold Chandra-Kanta trident finials",
    unesco_site: false,
    heritage_status: "Ancient Sacred Jyotirlinga (State Trust)",
    summary: "One of the revered twelve Jyotirlingas, center of the epic annual Shravani Mela where millions of barefoot Kanwariyas carry holy Ganges water over 100 km.",
    historical_significance: "According to Hindu lore, Ravana worshipped Lord Shiva here, offering his ten heads; Shiva acted as 'Vaidya' (divine physician) to heal him.",
    cultural_significance: "Cluster of 22 stone temples within a fortified compound, crowned by an auspicious Panchashula (five-tined brass trident) atop the 72-foot sanctum.",
    visiting_hours: "04:00 AM - 03:30 PM, 06:00 PM - 09:00 PM",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March (and Shravan July-August)",
    nearby_destinations: ["Naulakha Mandir", "Trikuta Parvat Ropeway", "Tapovan Caves"],
    transport_information: {
      air: "Deoghar Airport (DGH) - 8 km",
      rail: "Baidyanathdham Deoghar (BDME) - 1 km; Jasidih Junction (JSME) - 7 km",
      road: "NH 333 connects Jasidih, Deoghar, and Dumka",
      local: "E-rickshaws, shared auto-rickshaws, and official pilgrim buses"
    },
    nearest_transport: { railway_station: "Jasidih Junction (JSME)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Baidyanath Dham Temple Trust / Jharkhand Tourism",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["temple", "sacred", "jyotirlinga", "deoghar", "jharkhand"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },

  // --- NORTHEAST INDIA (3) ---
  {
    id: "kaziranga-living-heritage",
    name: "Kaziranga Living Heritage & Wilderness",
    city: "Golaghat & Nagaon",
    state: "Assam",
    region: "Northeast India",
    coordinates: { lat: 26.5775, lng: 93.1711 },
    era: "Reserved 1908; Inscribed UNESCO 1985",
    historical_period: "Mary Curzon Conservation Era & Living Indigenous Mising Culture",
    architectural_style: "Natural Living Heritage & Traditional Stilt-House Eco-Architecture",
    architect: "Preserved by Assam Forest Department & Indigenous Communities",
    material: "Brahmaputra alluvial tall elephant grass, wetlands, and tropical broadleaf forests",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "World's primary sanctuary of the Great Indian One-Horned Rhinoceros (housing over 2,400 rhinos), sprawling across the fertile Brahmaputra floodplains.",
    historical_significance: "Established in 1905 upon the initiative of Lady Curzon; represents India's greatest conservation triumph from near-extinction to flourishing population.",
    cultural_significance: "Living landscape blending indigenous Mising tribal weaving, Assamese tea heritage, and unparalleled megafauna (rhinos, wild water buffaloes, tigers).",
    visiting_hours: "07:00 AM - 04:30 PM (Safari windows: Morning & Afternoon, Nov to Apr)",
    entry_fee_inr: 100,
    entry_fee: { domestic: 100, international: 650, currency: "INR" },
    recommended_visit_duration: "1 - 2 Days",
    best_season: "November to April",
    nearby_destinations: ["Kohora Central Range", "Kaziranga National Orchid Park", "Brahmaputra Riverfront"],
    transport_information: {
      air: "Jorhat Airport (JRH) - 95 km; Guwahati Airport (GAU) - 225 km",
      rail: "Furkating Junction (FKG) - 75 km; Guwahati (GHY) - 215 km",
      road: "NH 715 (Asian Highway 1) runs along the entire southern boundary",
      local: "Registered 4x4 open safari gypsies and department elephant patrols"
    },
    nearest_transport: { railway_station: "Furkating (FKG) / Guwahati (GHY)" },
    thumbnail_url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Assam Forest Department / UNESCO World Heritage Centre",
    last_updated: "2026-03-01",
    category: "Natural & Ghats",
    tags: ["national park", "unesco", "rhino", "brahmaputra", "wildlife", "assam"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "living-root-bridges",
    name: "Living Root Bridges of Cherrapunji (Nongriat)",
    city: "Cherrapunji (Sohra) / Nongriat",
    state: "Meghalaya",
    region: "Northeast India",
    coordinates: { lat: 25.2505, lng: 91.6702 },
    era: "Continuous living tradition (200+ years per mature bridge)",
    historical_period: "Indigenous Khasi and Jaintia Tribal Living Heritage",
    architectural_style: "Indigenous Living Bio-Architecture & Agro-Engineering",
    architect: "Khasi Elders & Forest Keepers",
    material: "Living aerial roots of Ficus elastica trained through hollowed betel nut trunks",
    unesco_site: false,
    heritage_status: "Indigenous Living Bio-Heritage (UNESCO Tentative List)",
    summary: "Extraordinary bio-engineered suspension bridges grown by Khasi tribes from living rubber fig tree roots, including the famous Umshiang Double Decker bridge.",
    historical_significance: "Centuries-old indigenous botanical engineering designed to withstand torrential monsoon river torrents in the wettest place on Earth.",
    cultural_significance: "Living symbiosis between indigenous humans and rainforest nature; roots grow stronger and thicker over generations rather than decaying like steel or wood.",
    visiting_hours: "Sunrise to Sunset (06:00 AM - 05:00 PM)",
    entry_fee_inr: 50,
    entry_fee: { domestic: 50, international: 100, currency: "INR" },
    recommended_visit_duration: "4 - 5 Hours (Trek required)",
    best_season: "October to April",
    nearby_destinations: ["Nohkalikai Falls", "Mawsmai Cave", "Seven Sisters Falls", "Nongriat Natural Pools"],
    transport_information: {
      air: "Shillong Airport Umroi (SHL) - 85 km; Guwahati Airport (GAU) - 165 km",
      rail: "Guwahati Railway Station (GHY) - 145 km",
      road: "Shillong-Cherrapunji Highway (SH 5) to Tyrna village base",
      local: "Foot trail with ~3,500 stone steps descending from Tyrna to Nongriat"
    },
    nearest_transport: { railway_station: "Guwahati (GHY) / Tyrna Base" },
    thumbnail_url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Meghalaya Tourism / INTACH",
    last_updated: "2026-03-01",
    category: "Natural & Ghats",
    tags: ["living bridge", "bio-engineering", "khasi", "rainforest", "cherrapunji", "meghalaya"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "rumtek-monastery",
    name: "Rumtek Monastery (Dharma Chakra Centre)",
    city: "Gangtok",
    state: "Sikkim",
    region: "Northeast India",
    coordinates: { lat: 27.3039, lng: 88.5492 },
    era: "Founded 1966 CE (Origins from 1730s Tsurphu)",
    historical_period: "16th Gyalwa Karmapa (Rangjung Rigpe Dorje) Era",
    architectural_style: "Traditional Tibetan Buddhist Monastic Architecture",
    architect: "16th Karmapa & Tibetan Master Craftsmen",
    material: "Carved timber, stone masonry, gold-leaf stupa, and silk thangkas",
    unesco_site: false,
    heritage_status: "State Heritage Monastic Sanctum",
    summary: "Principal seat of the Karma Kagyu lineage in exile, housing a magnificent golden stupa with the relics of the 16th Gyalwa Karmapa and rare Tibetan art.",
    historical_significance: "Established by the 16th Karmapa after escaping Tibet in 1959, modeled directly on the ancestral Tsurphu Monastery.",
    cultural_significance: "Premier center of Tibetan Buddhist philosophical studies and monastic Cham sacred ritual mask dances against Kangchenjunga mountain backdrops.",
    visiting_hours: "06:00 AM - 06:00 PM",
    entry_fee_inr: 10,
    entry_fee: { domestic: 10, international: 50, currency: "INR" },
    recommended_visit_duration: "1.5 - 2 Hours",
    best_season: "March to May & October to December",
    nearby_destinations: ["Nalanda Buddhist Institute", "Gangtok MG Marg", "Enchey Monastery", "Tsomgo Lake"],
    transport_information: {
      air: "Pakyong Airport (PYG) - 30 km; Bagdogra Airport (IXB) - 125 km",
      rail: "New Jalpaiguri Junction (NJP) - 120 km; Siliguri (SGUJ) - 115 km",
      road: "NH 10 from Siliguri to Ranipool, then Rumtek road (24 km from Gangtok)",
      local: "Local shared jeeps from Gangtok / Ranipool, private tourist taxis"
    },
    nearest_transport: { railway_station: "New Jalpaiguri (NJP)" },
    thumbnail_url: "https://images.unsplash.com/photo-1617854818583-09e7f077a156?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1617854818583-09e7f077a156?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Sikkim Tourism & Ecclesiastical Affairs Department",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["monastery", "buddhist", "tibetan", "gangtok", "sikkim", "himalayas"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  }
];

export { monuments };
