// Curated West India monuments (10): Rajasthan, Gujarat, Maharashtra, Goa
const monuments = [
  // --- WEST INDIA (10) ---
  {
    id: "amber-fort",
    name: "Amber Fort & Palace (Amer)",
    city: "Jaipur",
    state: "Rajasthan",
    region: "Western India",
    coordinates: { lat: 26.9855, lng: 75.8513 },
    era: "1592 - 1727 CE",
    historical_period: "Kachwaha Rajput Dynasty (Raja Man Singh I)",
    architectural_style: "Rajput-Mughal Fort Architecture",
    architect: "Raja Man Singh I & Mirza Raja Jai Singh",
    material: "Yellow and pink sandstone with white marble courtyards",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site (Hill Forts of Rajasthan)",
    summary: "Hilltop citadel overlooking Maota Lake, famous for the glittering Sheesh Mahal (Mirror Palace) and majestic Rajput courtyards.",
    historical_significance: "Served as the principal fortress and royal residence of the Kachwaha clan until Maharaja Sawai Jai Singh II founded Jaipur in 1727.",
    cultural_significance: "Renowned for its mirror palace where a single candle flame illuminates the entire chamber through thousands of convex Belgian glass mirrors.",
    visiting_hours: "08:00 AM - 05:30 PM, Night Viewing: 06:30 PM - 09:15 PM",
    entry_fee_inr: 100,
    entry_fee: { domestic: 100, international: 500, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Jaigarh Fort", "Nahargarh Fort", "Jal Mahal", "Hawa Mahal"],
    transport_information: {
      air: "Jaipur International Airport (JAI) - 22 km",
      rail: "Jaipur Junction (JP) - 13 km",
      road: "Delhi-Jaipur Highway (NH 48) passes directly through Amer",
      local: "Elephant rides, battery golf carts, government AC low-floor buses"
    },
    nearest_transport: { railway_station: "Jaipur Junction (JP)" },
    thumbnail_url: "https://images.unsplash.com/photo-1603288967527-24861e6878b3?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1603288967527-24861e6878b3?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI) / UNESCO",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["fort", "unesco", "rajput", "sheesh mahal", "amer", "rajasthan"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "hawa-mahal",
    name: "Hawa Mahal (Palace of Winds)",
    city: "Jaipur",
    state: "Rajasthan",
    region: "Western India",
    coordinates: { lat: 26.9239, lng: 75.8267 },
    era: "1799 CE",
    historical_period: "Kachwaha Rajput Dynasty (Sawai Pratap Singh)",
    architectural_style: "Rajput-Mughal Architecture",
    architect: "Lal Chand Ustad",
    material: "Red and pink sandstone with 953 carved jharokhas",
    unesco_site: false,
    heritage_status: "State Heritage Monument (Rajasthan Tourism)",
    summary: "Five-storey honeycombed facade with 953 filigreed lattice windows, designed to let royal ladies observe street festivals unobserved.",
    historical_significance: "Commissioned by Maharaja Sawai Pratap Singh, inspired by the unique structure of the Khetri Mahal in Jhunjhunu.",
    cultural_significance: "Signature icon of Jaipur's 'Pink City' urban heritage; features the Venturi effect that naturally circulates cooling breezes through its casements.",
    visiting_hours: "09:00 AM - 05:00 PM",
    entry_fee_inr: 50,
    entry_fee: { domestic: 50, international: 200, currency: "INR" },
    recommended_visit_duration: "1 Hour",
    best_season: "October to March",
    nearby_destinations: ["City Palace Jaipur", "Jantar Mantar Jaipur", "Johari Bazaar"],
    transport_information: {
      air: "Jaipur International Airport (JAI) - 12 km",
      rail: "Jaipur Junction (JP) - 4.5 km",
      road: "Badi Chaupar in central Walled City Jaipur",
      local: "Jaipur Metro Pink Line (Badi Chaupar Station - 100 m)"
    },
    nearest_transport: { railway_station: "Jaipur Junction (JP) / Badi Chaupar Metro" },
    thumbnail_url: "https://images.unsplash.com/photo-1609946850720-6d4323229b46?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1609946850720-6d4323229b46?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Department of Archaeology and Museums, Rajasthan",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["palace", "rajput", "pink city", "jharokha", "jaipur", "rajasthan"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "jaisalmer-fort",
    name: "Jaisalmer Fort (Sonar Qila / Golden Fort)",
    city: "Jaisalmer",
    state: "Rajasthan",
    region: "Western India",
    coordinates: { lat: 26.9124, lng: 70.9127 },
    era: "1156 CE",
    historical_period: "Bhati Rajput Dynasty (Rawal Jaisal)",
    architectural_style: "Medieval Rajput Desert Fort Architecture",
    architect: "Rawal Jaisal",
    material: "Yellow Thar desert sandstone that turns golden at sunset",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site (Hill Forts of Rajasthan)",
    summary: "One of the world's few surviving 'living forts', housing over 4,000 residents, ancient Jain temples, and intricate royal havelis atop Trikuta Hill.",
    historical_significance: "Guarded the historic caravan trade route connecting India with Central Asia and Persia across the Thar Desert for eight centuries.",
    cultural_significance: "Celebrated in Satyajit Ray's classic film 'Sonar Kella'; preserves 12th-century Jain temples with precious palm-leaf manuscripts.",
    visiting_hours: "09:00 AM - 06:00 PM (Fort town accessible 24/7)",
    entry_fee_inr: 50,
    entry_fee: { domestic: 50, international: 250, currency: "INR" },
    recommended_visit_duration: "2 - 3 Hours",
    best_season: "October to March",
    nearby_destinations: ["Patwon Ki Haveli", "Gadisar Lake", "Sam Sand Dunes", "Thar Desert"],
    transport_information: {
      air: "Jaisalmer Airport (JSA) - 15 km; Jodhpur Airport - 280 km",
      rail: "Jaisalmer Railway Station (JSM) - 2 km (Direct express from Delhi)",
      road: "NH 11 connects Bikaner and Jodhpur",
      local: "Walking tours inside fort bastions, auto-rickshaws, and camel safaris"
    },
    nearest_transport: { railway_station: "Jaisalmer (JSM)" },
    thumbnail_url: "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Forts & Palaces",
    tags: ["fort", "unesco", "living fort", "desert", "jaisalmer", "rajasthan"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "rani-ki-vav",
    name: "Rani ki Vav (The Queen's Stepwell)",
    city: "Patan",
    state: "Gujarat",
    region: "Western India",
    coordinates: { lat: 23.8589, lng: 72.1018 },
    era: "1063 - 1068 CE",
    historical_period: "Solanki / Chaulukya Dynasty (Queen Udayamati)",
    architectural_style: "Maru-Gurjara Inverted Temple Architecture",
    architect: "Commissioned by Queen Udayamati in memory of King Bhima I",
    material: "Sandstone carved with over 500 principal sculptures",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Subterranean stepwell designed as an inverted seven-tiered temple honoring water sanctity, embellished with over 500 exquisite avatars of Vishnu.",
    historical_significance: "Buried under silt for centuries by the shifting Saraswati River, which preserved its intricate carvings in pristine condition until ASI excavated it.",
    cultural_significance: "Represents the supreme artistic and hydraulic engineering achievement of subterranean water architecture in ancient Western India.",
    visiting_hours: "08:00 AM - 06:00 PM",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "1.5 - 2 Hours",
    best_season: "October to March",
    nearby_destinations: ["Patan Patola Heritage Museum", "Modhera Sun Temple", "Sahasralinga Talav"],
    transport_information: {
      air: "Sardar Vallabhbhai Patel International Airport Ahmedabad (AMD) - 125 km",
      rail: "Patan Railway Station (PTN) - 4 km; Mehsana Junction (MSH) - 50 km",
      road: "Ahmedabad-Patan State Highway (SH 41)",
      local: "Local auto-rickshaws, GSRTC luxury express buses, and cabs"
    },
    nearest_transport: { railway_station: "Patan (PTN) / Mehsana (MSH)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Caves & Rock-Cut",
    tags: ["stepwell", "unesco", "solanki", "sculpture", "patan", "gujarat"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "champaner-pavagadh",
    name: "Champaner-Pavagadh Archaeological Park",
    city: "Panchmahal",
    state: "Gujarat",
    region: "Western India",
    coordinates: { lat: 22.4833, lng: 73.5333 },
    era: "8th - 16th Century CE",
    historical_period: "Gujarat Sultanate (Mahmud Begada) & Chavda Dynasty",
    architectural_style: "Indo-Saracenic & Solanki Temple Architecture",
    architect: "Sultan Mahmud Begada",
    material: "Sandstone, brick fortifications, and hillside stone masonry",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Sprawling unexcavated archaeological city containing pre-Mughal Islamic monuments, Hindu-Jain sanctums, and the hilltop Kalika Mata Temple.",
    historical_significance: "The only complete and intact pre-Mughal Islamic city in India, showcasing the transition from Hindu temple traditions to Islamic domes.",
    cultural_significance: "Famous for the monumental Jama Masjid with its 172 intricately carved pillars and the sacred Pavagadh hill pilgrimage.",
    visiting_hours: "08:30 AM - 05:30 PM",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "3 - 4 Hours",
    best_season: "October to March",
    nearby_destinations: ["Kalika Mata Temple Pavagadh", "Vada Talav", "Vadodara Laxmi Vilas Palace"],
    transport_information: {
      air: "Vadodara Airport (BDQ) - 45 km; Ahmedabad Airport - 145 km",
      rail: "Champaner Road (CPN) - 10 km; Vadodara Junction (BRC) - 48 km",
      road: "Vadodara-Halol Expressway",
      local: "Pavagadh passenger ropeway, local shared jeeps, and state buses"
    },
    nearest_transport: { railway_station: "Vadodara Junction (BRC)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Caves & Rock-Cut",
    tags: ["archaeology", "unesco", "sultanate", "mosque", "gujarat"],
    rating: 4.7,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "ajanta-caves",
    name: "Ajanta Caves",
    city: "Chhatrapati Sambhajinagar",
    state: "Maharashtra",
    region: "Western India",
    coordinates: { lat: 20.5519, lng: 75.7033 },
    era: "2nd Century BCE - 6th Century CE",
    historical_period: "Satavahana and Vakataka Dynasties (King Harishena)",
    architectural_style: "Rock-Cut Buddhist Cave Architecture & Murals",
    architect: "Buddhist Monks & Guild Sculptors",
    material: "Volcanic basalt rock cliff carvings with tempera murals",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Thirty rock-hewn Buddhist cave temples cut into a horseshoe gorge, housing classical masterpieces of ancient Indian mural painting and sculpture.",
    historical_significance: "Discovered accidentally by British officer John Smith in 1819 while tiger hunting; preserves Jataka tale paintings executed by natural mineral pigments.",
    cultural_significance: "The fountainhead of classical Buddhist art in Asia, influencing temple and monastery mural traditions across Sri Lanka, China, and Japan.",
    visiting_hours: "09:00 AM - 05:00 PM (Closed Mondays)",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "3 - 4 Hours",
    best_season: "October to March",
    nearby_destinations: ["Ellora Caves", "Daulatabad Fort", "Bibi Ka Maqbara"],
    transport_information: {
      air: "Chhatrapati Sambhajinagar Airport (IXU) - 100 km",
      rail: "Jalgaon Junction (JL) - 60 km; Aurangabad Station (AWB) - 100 km",
      road: "Aurangabad-Jalgaon Highway (NH 753F)",
      local: "Eco-friendly electric shuttle buses from T-Junction to cave foot"
    },
    nearest_transport: { railway_station: "Jalgaon (JL) / Aurangabad (AWB)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e421e4a3?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e421e4a3?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Caves & Rock-Cut",
    tags: ["caves", "unesco", "buddhist", "murals", "maharashtra"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "ellora-caves",
    name: "Ellora Caves & Kailasa Temple",
    city: "Chhatrapati Sambhajinagar",
    state: "Maharashtra",
    region: "Western India",
    coordinates: { lat: 20.0268, lng: 75.1780 },
    era: "6th - 10th Century CE",
    historical_period: "Rashtrakuta (King Krishna I) and Yadava Dynasties",
    architectural_style: "Rock-Cut Monolithic Dravidian Architecture",
    architect: "Rashtrakuta Guild Craftsmen",
    material: "Basalt cliff excavated top-down (single monolithic rock)",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Monumental complex of 34 Hindu, Buddhist, and Jain cave temples, dominated by Cave 16 (Kailasa Temple), the world's largest monolithic rock excavation.",
    historical_significance: "Kailasa Temple was sculpted vertically downwards from the basalt cliff face, removing over 200,000 tonnes of volcanic rock with precision chisels.",
    cultural_significance: "Testament to ancient India's spirit of religious harmony (sarva dharma sambhava) featuring side-by-side Hindu, Buddhist, and Jain sanctuaries.",
    visiting_hours: "Sunrise to Sunset (Closed Tuesdays)",
    entry_fee_inr: 40,
    entry_fee: { domestic: 40, international: 600, currency: "INR" },
    recommended_visit_duration: "3 - 4 Hours",
    best_season: "October to March",
    nearby_destinations: ["Grishneshwar Jyotirlinga", "Daulatabad Fort", "Ajanta Caves"],
    transport_information: {
      air: "Chhatrapati Sambhajinagar Airport (IXU) - 30 km",
      rail: "Aurangabad Railway Station (AWB) - 28 km",
      road: "SH 22 connects directly from central Aurangabad city (45 mins drive)",
      local: "Internal battery shuttle buggies, tourist taxis, and MSRTC buses"
    },
    nearest_transport: { railway_station: "Aurangabad (AWB)" },
    thumbnail_url: "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI)",
    last_updated: "2026-03-01",
    category: "Caves & Rock-Cut",
    tags: ["caves", "unesco", "kailasa", "monolith", "maharashtra"],
    rating: 4.9,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "gateway-of-india",
    name: "Gateway of India",
    city: "Mumbai",
    state: "Maharashtra",
    region: "Western India",
    coordinates: { lat: 18.9220, lng: 72.8347 },
    era: "1911 - 1924 CE",
    historical_period: "British Colonial Era (Commemorating King George V)",
    architectural_style: "Indo-Saracenic Arch Architecture",
    architect: "George Wittet",
    material: "Yellow basalt and reinforced concrete",
    unesco_site: false,
    heritage_status: "State Heritage Landmark (ASI Protected)",
    summary: "Waterfront arch monument overlooking Mumbai Harbour, symbolizing the city's maritime gateway and the ceremonial exit point of the British Raj in 1948.",
    historical_significance: "Erected to commemorate the 1911 landing of King George V and Queen Mary. In 1948, the Somerset Light Infantry marched through it, marking the end of colonial rule.",
    cultural_significance: "Mumbai's most visited civic gathering space facing the Arabian Sea and the Taj Mahal Palace Hotel; starting point for Elephanta island ferries.",
    visiting_hours: "Open 24 Hours",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "1 Hour",
    best_season: "October to March",
    nearby_destinations: ["Taj Mahal Palace Hotel", "Colaba Causeway", "CSMT", "Marine Drive"],
    transport_information: {
      air: "Chhatrapati Shivaji Maharaj International Airport (BOM) - 25 km",
      rail: "Churchgate Station (CCG) - 2.5 km; CSMT Terminus - 2.8 km",
      road: "Apollo Bunder waterfront terminal at Colaba",
      local: "BEST feeder buses, Mumbai kaali-peeli taxis, and Elephanta harbour launches"
    },
    nearest_transport: { railway_station: "CSMT / Churchgate (CCG)" },
    thumbnail_url: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Maharashtra Tourism Development Corporation (MTDC)",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["monument", "indo-saracenic", "mumbai", "waterfront", "maharashtra"],
    rating: 4.6,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "csmt",
    name: "Chhatrapati Shivaji Maharaj Terminus (CSMT)",
    city: "Mumbai",
    state: "Maharashtra",
    region: "Western India",
    coordinates: { lat: 18.9398, lng: 72.8355 },
    era: "1878 - 1887 CE",
    historical_period: "British Victorian Era (Victoria Terminus)",
    architectural_style: "Victorian Gothic Revival & Traditional Indian Palace Motifs",
    architect: "Frederick William Stevens",
    material: "Sandstone, limestone, Italian marble, and stained glass",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site",
    summary: "Historic railway terminus melding High Victorian Gothic design with traditional Indian palace motifs, serving over 3 million suburban commuters daily.",
    historical_significance: "Headquarters of the Central Railway; built over 10 years to mark Queen Victoria's Golden Jubilee, representing Mumbai's emergence as 'Urbs Prima in Indis'.",
    cultural_significance: "Celebrated for its stone dome, gargoyles, stained glass rosettes, and bronze statue of Progress atop the central octagonal rib-vaulted dome.",
    visiting_hours: "Operational 24x7; Heritage Gallery: 02:00 PM - 05:00 PM",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "1 Hour",
    best_season: "October to March",
    nearby_destinations: ["BMC Headquarters", "Crawford Market", "Flora Fountain", "Marine Drive"],
    transport_information: {
      air: "Mumbai Airport (BOM) - 20 km",
      rail: "CSMT Main Line & Suburban Terminal on site",
      road: "DN Road junction opposite BMC Building",
      local: "Mumbai Suburban Central and Harbour line trains, AC city buses"
    },
    nearest_transport: { railway_station: "CSMT Station" },
    thumbnail_url: "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Central Railway / UNESCO World Heritage Centre",
    last_updated: "2026-03-01",
    category: "Architectural & Colonial",
    tags: ["railway", "unesco", "gothic", "mumbai", "maharashtra"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  },
  {
    id: "basilica-of-bom-jesus",
    name: "Basilica of Bom Jesus & Old Goa Churches",
    city: "Old Goa",
    state: "Goa",
    region: "Western India",
    coordinates: { lat: 15.5009, lng: 73.9116 },
    era: "1594 - 1605 CE",
    historical_period: "Portuguese Colonial Era (Relics of St. Francis Xavier)",
    architectural_style: "Baroque & Manueline Architecture",
    architect: "Domingos Fernandes & Jesuit Architects",
    material: "Black laterite stone, plaster, and gilded wooden altars",
    unesco_site: true,
    heritage_status: "UNESCO World Heritage Site (Churches of Goa)",
    summary: "16th-century Jesuit basilica housing the sacred relics of St. Francis Xavier, renowned for unplastered black laterite facades and ornate gilded Baroque altars.",
    historical_significance: "Consecrated in 1605, marking the epicenter of the Jesuit missions across Asia; holds the silver reliquary casket crafted by Florentine jeweller Giovanni Battista Foggini.",
    cultural_significance: "Attracts millions of pilgrims worldwide during the decennial exposition of the sacred relics; stands facing the majestic Sé Cathedral.",
    visiting_hours: "09:00 AM - 06:30 PM (Sundays 10:30 AM - 06:30 PM)",
    entry_fee_inr: 0,
    entry_fee: { domestic: 0, international: 0, currency: "INR" },
    recommended_visit_duration: "1 - 2 Hours",
    best_season: "November to March",
    nearby_destinations: ["Sé Cathedral", "Church of St. Francis of Assisi", "Church of St. Cajetan"],
    transport_information: {
      air: "Dabolim Airport (GOI) - 26 km; Manohar International Airport Mopa (GOX) - 50 km",
      rail: "Karmali Railway Station (KRMI) - 3 km; Madgaon Junction (MAO) - 34 km",
      road: "Panaji-Old Goa Bypass (NH 748) - 10 km from Panaji capital",
      local: "Kadamba inter-city buses, motorcycle pilot taxis, tourist cabs"
    },
    nearest_transport: { railway_station: "Karmali (KRMI) / Madgaon (MAO)" },
    thumbnail_url: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    images: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80"],
    model_3d: { available: true, type: "webgl-interactive", poly_count: "high" },
    has_360: true,
    has_video: true,
    source: "Archaeological Survey of India (ASI) / Archdiocese of Goa",
    last_updated: "2026-03-01",
    category: "Temples & Sacred",
    tags: ["church", "unesco", "baroque", "jesuit", "old goa", "goa"],
    rating: 4.8,
    features: { map: true, navigation: true, ai: true, '3d': true }
  }
];

export { monuments };
