// scripts/update_india_database_pune.mjs
import fs from 'fs';

const punePlaces = JSON.parse(fs.readFileSync('data/pune/places.json', 'utf8'));

// 1. Update data/cities.json
const cities = JSON.parse(fs.readFileSync('data/cities.json', 'utf8'));
const puneCity = cities.find(c => c.id === 'pune' || c.name.toLowerCase() === 'pune');
if (puneCity) {
  puneCity.places_count = punePlaces.length;
}
fs.writeFileSync('data/cities.json', JSON.stringify(cities, null, 2), 'utf8');
console.log('✓ Updated data/cities.json with Pune places_count =', punePlaces.length);

// 2. Update data/india_tourism_database.json
const db = JSON.parse(fs.readFileSync('data/india_tourism_database.json', 'utf8'));
const maharashtra = db.states.find(s => s.id === 'maharashtra');
if (maharashtra) {
  const cMatch = maharashtra.cities.find(c => c.id === 'pune');
  if (cMatch) {
    cMatch.places_count = punePlaces.length;
    cMatch.total_attractions = punePlaces.length;
    cMatch.heritage = punePlaces.map(p => ({
      id: p.id,
      name: p.name,
      category: p.category,
      area: p.area,
      summary: p.description,
      description: p.description,
      thumbnail_url: p.thumbnail_url,
      image_url: p.image_url,
      coordinates: p.coordinates,
      tags: p.tags,
      map_search: p.map_search,
      entry_fee: p.entry_fee,
      opening_hours: p.opening_hours,
      suggested_duration: p.suggested_duration,
      best_time_to_visit: p.best_time_to_visit,
      visitor_notes: p.visitor_notes
    }));
  }
}
fs.writeFileSync('data/india_tourism_database.json', JSON.stringify(db, null, 2), 'utf8');
console.log('✓ Updated data/india_tourism_database.json for Pune');

// 3. Update src/data/indiaTourismDatabase.ts
const tsContent = `// Autogenerated verified database export\nexport const INDIA_TOURISM_DATABASE = ${JSON.stringify(db, null, 2)};\n`;
fs.writeFileSync('src/data/indiaTourismDatabase.ts', tsContent, 'utf8');
console.log('✓ Updated src/data/indiaTourismDatabase.ts for Pune');
