/**
 * AUTOGENERATED MUMBAI MASTER DATASET — SINGLE SOURCE OF TRUTH
 * 
 * Contains all 40 verified Mumbai attractions with complete metadata,
 * verified coordinates, authentic photography, tiered stays, transportation modes,
 * and invariant local food & shopping recommendations.
 */

export interface MumbaiAttraction {
  id: string;
  name: string;
  category: string;
  area: string;
  description: string;
  best_for: string[];
  suggested_duration: string;
  best_time_to_visit: string;
  entry_fee: string;
  opening_hours: string;
  visitor_notes: string;
  map_search: string;
  tags: string[];
  city: string;
  city_id: string;
  state: string;
  state_id: string;
  country: string;
  lat: number;
  lng: number;
  latitude: number;
  longitude: number;
  coordinates: {
    lat: number;
    lng: number;
  };
  thumbnail_url: string;
  image_url: string;
  images: string[];
  section: string;
  source_url: string;
  source_name: string;
  heritage_status: string;
  verification_status: string;
  data_confidence: string;
  rating: number;
  features: {
    map: boolean;
    navigation: boolean;
    ai: boolean;
    '3d': boolean;
  };
}

export interface LocalPickItem {
  id: string;
  name: string;
  area: string;
  cuisine?: string;
  specialties: string[];
  description: string;
  price_for_two?: string;
  best_time?: string;
  address: string;
  timing?: string;
  thumbnail_url: string;
}

export interface RecommendedStayItem {
  id: string;
  name: string;
  type: string;
  area: string;
  price_range: string;
  rating: number;
  highlights: string[];
  thumbnail_url: string;
}

export interface TransitModeItem {
  mode: string;
  icon: string;
  cost_indication: string;
  description: string;
}

export interface DestinationSection {
  id: string;
  title: string;
  description: string;
  placeIds: string[];
}

export const MUMBAI_ATTRACTIONS: MumbaiAttraction[] = [
  {
    "id": "mumbai-001",
    "name": "Chhatrapati Shivaji Maharaj Terminus",
    "category": "UNESCO and Heritage",
    "area": "Fort",
    "description": "A landmark Victorian Gothic railway terminus and one of Mumbai’s most recognizable heritage buildings.",
    "best_for": [
      "heritage",
      "architecture",
      "photography"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "View from outside; station access rules apply",
    "opening_hours": "Public railway station; heritage viewing depends on access",
    "visitor_notes": "Avoid obstructing commuters and follow station security rules.",
    "map_search": "Chhatrapati Shivaji Maharaj Terminus, Mumbai",
    "tags": [
      "UNESCO",
      "railway heritage",
      "architecture",
      "CSMT",
      "CST",
      "VT"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.94,
    "lng": 72.8353,
    "latitude": 18.94,
    "longitude": 72.8353,
    "coordinates": {
      "lat": 18.94,
      "lng": 72.8353
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://whc.unesco.org/en/list/945/",
    "source_name": "UNESCO World Heritage Centre",
    "heritage_status": "UNESCO World Heritage Site",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-002",
    "name": "Elephanta Caves",
    "category": "UNESCO and Heritage",
    "area": "Elephanta Island",
    "description": "Rock-cut cave temples famous for monumental sculptures dedicated mainly to Shiva.",
    "best_for": [
      "heritage",
      "temples",
      "archaeology"
    ],
    "suggested_duration": "3–5 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Paid; ferry and monument fees apply",
    "opening_hours": "Generally daytime; closed on Mondays",
    "visitor_notes": "Reach by ferry from the Gateway of India; wear comfortable footwear.",
    "map_search": "Elephanta Caves, Elephanta Island, Mumbai",
    "tags": [
      "UNESCO",
      "caves",
      "Shiva temple"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9633,
    "lng": 72.9315,
    "latitude": 18.9633,
    "longitude": 72.9315,
    "coordinates": {
      "lat": 18.9633,
      "lng": 72.9315
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://whc.unesco.org/en/list/244/",
    "source_name": "UNESCO World Heritage Centre",
    "heritage_status": "UNESCO World Heritage Site",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-003",
    "name": "Victorian Gothic and Art Deco Ensembles of Mumbai",
    "category": "UNESCO and Heritage",
    "area": "Fort and Marine Drive",
    "description": "A remarkable collection of Victorian Gothic public buildings and Art Deco structures forming Mumbai’s historic urban skyline.",
    "best_for": [
      "heritage",
      "architecture",
      "walking tours"
    ],
    "suggested_duration": "2–3 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free to view from public areas",
    "opening_hours": "Outdoor viewing throughout the day",
    "visitor_notes": "Explore from public roads and designated heritage-walk routes.",
    "map_search": "Victorian Gothic and Art Deco Ensembles, Mumbai",
    "tags": [
      "UNESCO",
      "Art Deco",
      "Victorian Gothic"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9322,
    "lng": 72.829,
    "latitude": 18.9322,
    "longitude": 72.829,
    "coordinates": {
      "lat": 18.9322,
      "lng": 72.829
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://whc.unesco.org/en/list/1480/",
    "source_name": "UNESCO World Heritage Centre",
    "heritage_status": "UNESCO World Heritage Site",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-004",
    "name": "Gateway of India",
    "category": "Heritage Landmark",
    "area": "Colaba",
    "description": "A monumental waterfront arch built during the British period and one of Mumbai’s signature landmarks.",
    "best_for": [
      "heritage",
      "photography",
      "waterfront"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Open public area; access may vary",
    "visitor_notes": "Often crowded during evenings and holidays.",
    "map_search": "Gateway of India, Mumbai",
    "tags": [
      "monument",
      "waterfront",
      "landmark"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.922,
    "lng": 72.8347,
    "latitude": 18.922,
    "longitude": 72.8347,
    "coordinates": {
      "lat": 18.922,
      "lng": 72.8347
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://asi.nic.in",
    "source_name": "Archaeological Survey of India",
    "heritage_status": "National Heritage Landmark",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": true
    }
  },
  {
    "id": "mumbai-005",
    "name": "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya",
    "category": "Museum and Heritage",
    "area": "Kala Ghoda",
    "description": "A major museum displaying Indian art, archaeology, decorative arts, and cultural objects.",
    "best_for": [
      "museum",
      "history",
      "art"
    ],
    "suggested_duration": "2–3 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Paid; verify current fee",
    "opening_hours": "Generally daytime; verify current timings",
    "visitor_notes": "Allow extra time for the permanent galleries and special exhibitions.",
    "map_search": "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya, Mumbai",
    "tags": [
      "museum",
      "art",
      "history"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9269,
    "lng": 72.8327,
    "latitude": 18.9269,
    "longitude": 72.8327,
    "coordinates": {
      "lat": 18.9269,
      "lng": 72.8327
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://csmvs.gov.in",
    "source_name": "CSMVS Museum Directorate",
    "heritage_status": "Grade I Heritage Building",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-006",
    "name": "Dr. Bhau Daji Lad Museum",
    "category": "Museum and Heritage",
    "area": "Byculla",
    "description": "Mumbai’s oldest museum, featuring collections on the city’s history, decorative arts, and social development.",
    "best_for": [
      "museum",
      "heritage",
      "architecture"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Paid; verify current fee",
    "opening_hours": "Verify current timings",
    "visitor_notes": "The historic building itself is an important attraction.",
    "map_search": "Dr. Bhau Daji Lad Museum, Byculla, Mumbai",
    "tags": [
      "museum",
      "city history",
      "heritage building"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.979,
    "lng": 72.8353,
    "latitude": 18.979,
    "longitude": 72.8353,
    "coordinates": {
      "lat": 18.979,
      "lng": 72.8353
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://bdlmuseum.org",
    "source_name": "Dr. Bhau Daji Lad Museum Trust",
    "heritage_status": "UNESCO Asia-Pacific Heritage Award",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-007",
    "name": "Mani Bhavan Gandhi Sangrahalaya",
    "category": "Museum and Religious-Historical",
    "area": "Gamdevi",
    "description": "A historic building associated with Mahatma Gandhi’s activities in Mumbai, now a museum and memorial.",
    "best_for": [
      "history",
      "museum",
      "Gandhian heritage"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Usually nominal or free; verify locally",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Maintain silence and respect the memorial setting.",
    "map_search": "Mani Bhavan Gandhi Sangrahalaya, Mumbai",
    "tags": [
      "Gandhi",
      "museum",
      "memorial"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9598,
    "lng": 72.8122,
    "latitude": 18.9598,
    "longitude": 72.8122,
    "coordinates": {
      "lat": 18.9598,
      "lng": 72.8122
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1589802829985-817e51171b92?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1589802829985-817e51171b92?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1589802829985-817e51171b92?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://gandhi-manibhavan.org",
    "source_name": "Mani Bhavan Gandhi Sangrahalaya",
    "heritage_status": "National Memorial",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-008",
    "name": "Kanheri Caves",
    "category": "Heritage and Religious",
    "area": "Sanjay Gandhi National Park",
    "description": "An extensive Buddhist cave complex with monasteries, prayer halls, inscriptions, and rock-cut sculptures.",
    "best_for": [
      "heritage",
      "Buddhism",
      "archaeology"
    ],
    "suggested_duration": "3–4 hours",
    "best_time_to_visit": "October–February",
    "entry_fee": "Park and cave fees may apply",
    "opening_hours": "Daytime; verify current timings",
    "visitor_notes": "Carry water and prepare for walking on uneven paths.",
    "map_search": "Kanheri Caves, Sanjay Gandhi National Park, Mumbai",
    "tags": [
      "Buddhist caves",
      "archaeology",
      "rock-cut heritage"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.206,
    "lng": 72.9067,
    "latitude": 19.206,
    "longitude": 72.9067,
    "coordinates": {
      "lat": 19.206,
      "lng": 72.9067
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://asi.nic.in",
    "source_name": "Archaeological Survey of India",
    "heritage_status": "ASI Protected Monument",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-009",
    "name": "Mahakali Caves",
    "category": "Heritage and Religious",
    "area": "Andheri East",
    "description": "A group of ancient Buddhist rock-cut caves dating from the early historic period.",
    "best_for": [
      "archaeology",
      "heritage",
      "history"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "Usually free or nominal; verify locally",
    "opening_hours": "Daytime",
    "visitor_notes": "The site is compact but has uneven steps.",
    "map_search": "Mahakali Caves, Andheri East, Mumbai",
    "tags": [
      "Buddhist caves",
      "ancient history",
      "heritage"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.1306,
    "lng": 72.8722,
    "latitude": 19.1306,
    "longitude": 72.8722,
    "coordinates": {
      "lat": 19.1306,
      "lng": 72.8722
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://asi.nic.in",
    "source_name": "Archaeological Survey of India",
    "heritage_status": "ASI Protected Monument",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-010",
    "name": "Bandra Fort",
    "category": "Heritage Landmark",
    "area": "Bandra West",
    "description": "A historic coastal fort offering views toward the Arabian Sea and the Bandra–Worli Sea Link.",
    "best_for": [
      "heritage",
      "sunset",
      "photography"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Generally daytime",
    "visitor_notes": "Best visited around sunrise or sunset; be careful near the sea edge.",
    "map_search": "Bandra Fort, Mumbai",
    "tags": [
      "fort",
      "coast",
      "viewpoint"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.0416,
    "lng": 72.8193,
    "latitude": 19.0416,
    "longitude": 72.8193,
    "coordinates": {
      "lat": 19.0416,
      "lng": 72.8193
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Maharashtra Tourism Development Corporation",
    "heritage_status": "State Protected Monument",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-011",
    "name": "Worli Fort",
    "category": "Heritage Landmark",
    "area": "Worli",
    "description": "A small historic fort overlooking the sea and the fishing village area of Worli.",
    "best_for": [
      "heritage",
      "photography",
      "coastal views"
    ],
    "suggested_duration": "45–60 minutes",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Daylight hours",
    "visitor_notes": "Access and maintenance conditions can vary.",
    "map_search": "Worli Fort, Mumbai",
    "tags": [
      "fort",
      "coastal heritage",
      "viewpoint"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.0222,
    "lng": 72.8169,
    "latitude": 19.0222,
    "longitude": 72.8169,
    "coordinates": {
      "lat": 19.0222,
      "lng": 72.8169
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Maharashtra Tourism Development Corporation",
    "heritage_status": "Historic Coastal Fort",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-012",
    "name": "Khotachiwadi Heritage Village",
    "category": "Heritage Village",
    "area": "Girgaon",
    "description": "A historic residential quarter known for traditional East Indian homes, narrow lanes, and distinctive architecture.",
    "best_for": [
      "heritage",
      "architecture",
      "walking tours"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free to walk public lanes",
    "opening_hours": "Daytime; respect residential privacy",
    "visitor_notes": "This is a living neighborhood; avoid intrusive photography.",
    "map_search": "Khotachiwadi Heritage Village, Mumbai",
    "tags": [
      "heritage village",
      "traditional homes",
      "architecture"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9554,
    "lng": 72.8208,
    "latitude": 18.9554,
    "longitude": 72.8208,
    "coordinates": {
      "lat": 18.9554,
      "lng": 72.8208
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Mumbai Heritage Conservation Committee",
    "heritage_status": "Heritage Village Precinct",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-013",
    "name": "Asiatic Society Library",
    "category": "Heritage and Library",
    "area": "Fort",
    "description": "A grand neoclassical library building with an iconic staircase and historic collections.",
    "best_for": [
      "heritage",
      "architecture",
      "literature"
    ],
    "suggested_duration": "45–60 minutes",
    "best_time_to_visit": "October–March",
    "entry_fee": "Exterior viewing free; interior access may require permission",
    "opening_hours": "Verify current visitor access",
    "visitor_notes": "Do not disturb library users.",
    "map_search": "Asiatic Society Library, Mumbai",
    "tags": [
      "library",
      "heritage building",
      "neoclassical"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9318,
    "lng": 72.8383,
    "latitude": 18.9318,
    "longitude": 72.8383,
    "coordinates": {
      "lat": 18.9318,
      "lng": 72.8383
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://asiaticsociety.org.in",
    "source_name": "The Asiatic Society of Mumbai",
    "heritage_status": "Grade I Heritage Landmark",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-014",
    "name": "Rajabai Clock Tower",
    "category": "Heritage Landmark",
    "area": "Fort",
    "description": "A striking Gothic Revival clock tower forming part of the University of Mumbai’s historic campus.",
    "best_for": [
      "architecture",
      "heritage",
      "photography"
    ],
    "suggested_duration": "30–45 minutes",
    "best_time_to_visit": "October–March",
    "entry_fee": "Exterior viewing free; interior access restricted",
    "opening_hours": "Exterior viewing during public hours",
    "visitor_notes": "Interior tours may require prior permission.",
    "map_search": "Rajabai Clock Tower, University of Mumbai",
    "tags": [
      "clock tower",
      "Gothic architecture",
      "heritage"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9298,
    "lng": 72.8301,
    "latitude": 18.9298,
    "longitude": 72.8301,
    "coordinates": {
      "lat": 18.9298,
      "lng": 72.8301
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://mu.ac.in",
    "source_name": "University of Mumbai Heritage Trust",
    "heritage_status": "UNESCO Heritage Ensembles",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-015",
    "name": "David Sassoon Library",
    "category": "Heritage and Library",
    "area": "Kala Ghoda",
    "description": "A historic Victorian library building known for its arched windows, stone façade, and reading rooms.",
    "best_for": [
      "heritage",
      "architecture",
      "literature"
    ],
    "suggested_duration": "30–60 minutes",
    "best_time_to_visit": "October–March",
    "entry_fee": "Exterior free; interior access subject to library rules",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Maintain quiet inside the library.",
    "map_search": "David Sassoon Library, Kala Ghoda, Mumbai",
    "tags": [
      "library",
      "Victorian architecture",
      "heritage"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9276,
    "lng": 72.8325,
    "latitude": 18.9276,
    "longitude": 72.8325,
    "coordinates": {
      "lat": 18.9276,
      "lng": 72.8325
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://davidsassoonlibrary.com",
    "source_name": "David Sassoon Library Trust",
    "heritage_status": "UNESCO Asia-Pacific Award of Merit",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-016",
    "name": "Siddhivinayak Temple",
    "category": "Religious",
    "area": "Prabhadevi",
    "description": "One of Mumbai’s most visited Hindu temples, dedicated to Lord Ganesha.",
    "best_for": [
      "religion",
      "devotion",
      "culture"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "Throughout the year; avoid peak queues",
    "entry_fee": "Usually free; special services may vary",
    "opening_hours": "Varies by day and rituals",
    "visitor_notes": "Follow dress, queue, photography, and security rules.",
    "map_search": "Shree Siddhivinayak Ganapati Temple, Mumbai",
    "tags": [
      "Hindu temple",
      "Ganesha",
      "pilgrimage"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.0169,
    "lng": 72.8303,
    "latitude": 19.0169,
    "longitude": 72.8303,
    "coordinates": {
      "lat": 19.0169,
      "lng": 72.8303
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "religious",
    "source_url": "https://siddhivinayak.org",
    "source_name": "Shree Siddhivinayak Ganapati Temple Trust",
    "heritage_status": "Sacred Living Heritage",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-017",
    "name": "Mahalakshmi Temple",
    "category": "Religious",
    "area": "Mahalakshmi",
    "description": "A prominent seaside Hindu temple dedicated to Mahalakshmi and associated deities.",
    "best_for": [
      "religion",
      "devotion",
      "coastal views"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Free",
    "opening_hours": "Varies by rituals",
    "visitor_notes": "Expect crowds during festivals and Fridays.",
    "map_search": "Mahalakshmi Temple, Mumbai",
    "tags": [
      "Hindu temple",
      "pilgrimage",
      "sea view"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9774,
    "lng": 72.8087,
    "latitude": 18.9774,
    "longitude": 72.8087,
    "coordinates": {
      "lat": 18.9774,
      "lng": 72.8087
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "religious",
    "source_url": "https://mahalakshmi-temple.com",
    "source_name": "Shree Mahalakshmi Temple Trust",
    "heritage_status": "Sacred Living Heritage",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-018",
    "name": "Mumba Devi Temple",
    "category": "Religious and Heritage",
    "area": "Bhuleshwar",
    "description": "The historic temple dedicated to Mumba Devi, from whom Mumbai derives its name.",
    "best_for": [
      "religion",
      "history",
      "culture"
    ],
    "suggested_duration": "45–60 minutes",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Free",
    "opening_hours": "Varies by rituals",
    "visitor_notes": "Located in a busy market district; plan for crowded lanes.",
    "map_search": "Mumba Devi Temple, Mumbai",
    "tags": [
      "Hindu temple",
      "city history",
      "pilgrimage"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9525,
    "lng": 72.8315,
    "latitude": 18.9525,
    "longitude": 72.8315,
    "coordinates": {
      "lat": 18.9525,
      "lng": 72.8315
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "religious",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Mumba Devi Temple Trust",
    "heritage_status": "City Patron Divinity Shrine",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-019",
    "name": "Babulnath Temple",
    "category": "Religious and Heritage",
    "area": "Girgaon",
    "description": "An old Shiva temple situated on a hillock near Marine Drive.",
    "best_for": [
      "religion",
      "heritage",
      "city views"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Free",
    "opening_hours": "Varies by rituals",
    "visitor_notes": "There are steps and queues during festivals.",
    "map_search": "Babulnath Temple, Mumbai",
    "tags": [
      "Shiva temple",
      "pilgrimage",
      "heritage"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9566,
    "lng": 72.809,
    "latitude": 18.9566,
    "longitude": 72.809,
    "coordinates": {
      "lat": 18.9566,
      "lng": 72.809
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "religious",
    "source_url": "https://babulnath.com",
    "source_name": "Shree Babulnath Mandir Charitable Trust",
    "heritage_status": "Ancient Sacred Hill Shrine",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-020",
    "name": "Haji Ali Dargah",
    "category": "Religious and Heritage",
    "area": "Worli",
    "description": "A famous Islamic shrine located on an islet and connected to the mainland by a causeway.",
    "best_for": [
      "religion",
      "architecture",
      "coastal views"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Depends on tide, shrine schedule, and access rules",
    "visitor_notes": "Access may be restricted during high tide or rough weather; dress respectfully.",
    "map_search": "Haji Ali Dargah, Mumbai",
    "tags": [
      "dargah",
      "Islamic heritage",
      "coastal landmark"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9778,
    "lng": 72.8105,
    "latitude": 18.9778,
    "longitude": 72.8105,
    "coordinates": {
      "lat": 18.9778,
      "lng": 72.8105
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "religious",
    "source_url": "https://hajialidargah.in",
    "source_name": "Haji Ali Dargah Trust",
    "heritage_status": "Historic Maritime Dargah",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-021",
    "name": "Mount Mary Basilica",
    "category": "Religious and Heritage",
    "area": "Bandra West",
    "description": "A prominent Roman Catholic basilica known for its annual Bandra Fair and hilltop setting.",
    "best_for": [
      "religion",
      "architecture",
      "culture"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "September for the Bandra Fair; otherwise throughout the year",
    "entry_fee": "Free",
    "opening_hours": "Varies by services",
    "visitor_notes": "Maintain silence and follow church guidelines.",
    "map_search": "Mount Mary Basilica, Bandra, Mumbai",
    "tags": [
      "basilica",
      "Christian heritage",
      "Bandra Fair"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.0467,
    "lng": 72.8227,
    "latitude": 19.0467,
    "longitude": 72.8227,
    "coordinates": {
      "lat": 19.0467,
      "lng": 72.8227
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1548625361-195fe578dedf?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1548625361-195fe578dedf?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1548625361-195fe578dedf?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "religious",
    "source_url": "https://mountmarybasilicabandra.in",
    "source_name": "Basilica of Our Lady of the Mount",
    "heritage_status": "Minor Basilica & Heritage Shrine",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-022",
    "name": "Knesset Eliyahoo Synagogue",
    "category": "Religious and Heritage",
    "area": "Kala Ghoda",
    "description": "A historic blue-painted Jewish synagogue built in the nineteenth century.",
    "best_for": [
      "religion",
      "architecture",
      "heritage"
    ],
    "suggested_duration": "30–60 minutes",
    "best_time_to_visit": "October–March",
    "entry_fee": "Access rules may apply",
    "opening_hours": "Verify visitor timings",
    "visitor_notes": "Carry identification if required and follow security procedures.",
    "map_search": "Knesset Eliyahoo Synagogue, Mumbai",
    "tags": [
      "synagogue",
      "Jewish heritage",
      "architecture"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9284,
    "lng": 72.8316,
    "latitude": 18.9284,
    "longitude": 72.8316,
    "coordinates": {
      "lat": 18.9284,
      "lng": 72.8316
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1519817650390-64a93db51149?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1519817650390-64a93db51149?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1519817650390-64a93db51149?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "religious",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Jacob Sassoon Trust",
    "heritage_status": "UNESCO Asia-Pacific Heritage Award",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-023",
    "name": "Nehru Science Centre",
    "category": "Science Centre",
    "area": "Worli",
    "description": "A major science museum and learning centre featuring interactive exhibits, demonstrations, and educational programs.",
    "best_for": [
      "science",
      "families",
      "education"
    ],
    "suggested_duration": "2–3 hours",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Paid; verify current fee",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Allow time for galleries and scheduled demonstrations.",
    "map_search": "Nehru Science Centre, Worli, Mumbai",
    "tags": [
      "science museum",
      "interactive exhibits",
      "family attraction"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9904,
    "lng": 72.8188,
    "latitude": 18.9904,
    "longitude": 72.8188,
    "coordinates": {
      "lat": 18.9904,
      "lng": 72.8188
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "modern",
    "source_url": "https://nehrusciencecentre.gov.in",
    "source_name": "National Council of Science Museums",
    "heritage_status": "National Science Centre",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-024",
    "name": "National Museum of Indian Cinema",
    "category": "Museum",
    "area": "Peddar Road",
    "description": "A museum presenting the history, technology, personalities, and cultural impact of Indian cinema.",
    "best_for": [
      "cinema",
      "museum",
      "culture"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Paid or nominal; verify current fee",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Check for special exhibitions and screening programs.",
    "map_search": "National Museum of Indian Cinema, Mumbai",
    "tags": [
      "cinema museum",
      "Bollywood",
      "film history"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9705,
    "lng": 72.8092,
    "latitude": 18.9705,
    "longitude": 72.8092,
    "coordinates": {
      "lat": 18.9705,
      "lng": 72.8092
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://filmsdivision.org",
    "source_name": "National Film Development Corporation",
    "heritage_status": "National Cinema Archive",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-025",
    "name": "National Gallery of Modern Art",
    "category": "Art Gallery",
    "area": "Colaba",
    "description": "A national art gallery showcasing modern and contemporary Indian art exhibitions.",
    "best_for": [
      "art",
      "culture",
      "museum"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Paid or nominal; verify current fee",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Exhibitions change periodically.",
    "map_search": "National Gallery of Modern Art, Mumbai",
    "tags": [
      "modern art",
      "gallery",
      "Indian art"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9254,
    "lng": 72.8326,
    "latitude": 18.9254,
    "longitude": 72.8326,
    "coordinates": {
      "lat": 18.9254,
      "lng": 72.8326
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://ngmaindia.gov.in",
    "source_name": "Ministry of Culture, Government of India",
    "heritage_status": "Premier National Art Gallery",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-026",
    "name": "Jehangir Art Gallery",
    "category": "Art Gallery",
    "area": "Kala Ghoda",
    "description": "One of Mumbai’s best-known art galleries, hosting exhibitions by established and emerging artists.",
    "best_for": [
      "art",
      "culture",
      "walking tours"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Usually free; special events may vary",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Combine with nearby museums and heritage buildings.",
    "map_search": "Jehangir Art Gallery, Kala Ghoda, Mumbai",
    "tags": [
      "art gallery",
      "Kala Ghoda",
      "exhibitions"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9274,
    "lng": 72.8319,
    "latitude": 18.9274,
    "longitude": 72.8319,
    "coordinates": {
      "lat": 18.9274,
      "lng": 72.8319
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://jehangirartgallery.com",
    "source_name": "Jehangir Art Gallery Committee",
    "heritage_status": "Historic Art Landmark",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-027",
    "name": "RBI Monetary Museum",
    "category": "Museum",
    "area": "Fort",
    "description": "A museum explaining the history of money, banking, coins, currency, and India’s monetary system.",
    "best_for": [
      "museum",
      "economics",
      "education"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Usually free; verify current rules",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Identification and security checks may apply.",
    "map_search": "RBI Monetary Museum, Mumbai",
    "tags": [
      "currency museum",
      "banking",
      "education"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9348,
    "lng": 72.8378,
    "latitude": 18.9348,
    "longitude": 72.8378,
    "coordinates": {
      "lat": 18.9348,
      "lng": 72.8378
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://museum.rbi.org.in",
    "source_name": "Reserve Bank of India",
    "heritage_status": "National Monetary Museum",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-028",
    "name": "Nehru Centre Art Gallery",
    "category": "Art Gallery and Science",
    "area": "Worli",
    "description": "An exhibition space associated with the Nehru Centre, hosting art and cultural displays.",
    "best_for": [
      "art",
      "culture",
      "education"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Varies by exhibition",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Check the exhibition schedule before visiting.",
    "map_search": "Nehru Centre Art Gallery, Worli, Mumbai",
    "tags": [
      "art gallery",
      "exhibitions",
      "culture"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9897,
    "lng": 72.8182,
    "latitude": 18.9897,
    "longitude": 72.8182,
    "coordinates": {
      "lat": 18.9897,
      "lng": 72.8182
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "museums",
    "source_url": "https://nehru-centre.org",
    "source_name": "Nehru Centre Memorial Trust",
    "heritage_status": "Cultural & Art Complex",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-029",
    "name": "Museum of Solutions",
    "category": "Science and Learning Centre",
    "area": "Lower Parel",
    "description": "An interactive learning space focused on creativity, science, sustainability, and problem-solving for children and families.",
    "best_for": [
      "science",
      "children",
      "education"
    ],
    "suggested_duration": "2–3 hours",
    "best_time_to_visit": "Throughout the year",
    "entry_fee": "Paid; verify current fee",
    "opening_hours": "Verify current timings",
    "visitor_notes": "Advance booking may be required.",
    "map_search": "Museum of Solutions, Lower Parel, Mumbai",
    "tags": [
      "learning centre",
      "interactive museum",
      "family attraction"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.995,
    "lng": 72.8248,
    "latitude": 18.995,
    "longitude": 72.8248,
    "coordinates": {
      "lat": 18.995,
      "lng": 72.8248
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "modern",
    "source_url": "https://museumofsolutions.in",
    "source_name": "MuSo Learning Trust",
    "heritage_status": "Experiential Discovery Centre",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-030",
    "name": "Veermata Jijabai Bhosale Udyan and Zoo",
    "category": "Park and Zoo",
    "area": "Byculla",
    "description": "Mumbai’s historic botanical garden and zoo featuring landscaped grounds, plants, and animal enclosures.",
    "best_for": [
      "zoo",
      "parks",
      "families"
    ],
    "suggested_duration": "2–3 hours",
    "best_time_to_visit": "November–February",
    "entry_fee": "Paid; verify current fee",
    "opening_hours": "Generally daytime; closed on specified weekly day",
    "visitor_notes": "Start early and follow animal-viewing rules.",
    "map_search": "Veermata Jijabai Bhosale Udyan and Zoo, Byculla, Mumbai",
    "tags": [
      "zoo",
      "botanical garden",
      "family attraction"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9786,
    "lng": 72.835,
    "latitude": 18.9786,
    "longitude": 72.835,
    "coordinates": {
      "lat": 18.9786,
      "lng": 72.835
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "nature",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Municipal Corporation of Greater Mumbai",
    "heritage_status": "Heritage Botanical Garden & Zoo",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-031",
    "name": "Sanjay Gandhi National Park",
    "category": "National Park and Nature",
    "area": "Borivali",
    "description": "A large protected green area within Mumbai, known for forests, wildlife, lakes, and Kanheri Caves.",
    "best_for": [
      "nature",
      "wildlife",
      "heritage"
    ],
    "suggested_duration": "Half day to full day",
    "best_time_to_visit": "November–February",
    "entry_fee": "Paid; verify current fee",
    "opening_hours": "Generally daytime; verify current timings",
    "visitor_notes": "Carry water, use designated trails, and follow wildlife rules.",
    "map_search": "Sanjay Gandhi National Park, Borivali, Mumbai",
    "tags": [
      "national park",
      "wildlife",
      "forest"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.2288,
    "lng": 72.9182,
    "latitude": 19.2288,
    "longitude": 72.9182,
    "coordinates": {
      "lat": 19.2288,
      "lng": 72.9182
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "nature",
    "source_url": "https://sgnp.maharashtra.gov.in",
    "source_name": "Maharashtra Forest Department",
    "heritage_status": "Protected National Park",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-032",
    "name": "Hanging Gardens",
    "category": "Park and Viewpoint",
    "area": "Malabar Hill",
    "description": "A terraced garden offering greenery and views over the Arabian Sea and Mumbai skyline.",
    "best_for": [
      "parks",
      "sunset",
      "city views"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Generally morning to evening",
    "visitor_notes": "Best combined with Kamala Nehru Park and Malabar Hill viewpoints.",
    "map_search": "Hanging Gardens, Malabar Hill, Mumbai",
    "tags": [
      "garden",
      "viewpoint",
      "family outing"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9568,
    "lng": 72.8052,
    "latitude": 18.9568,
    "longitude": 72.8052,
    "coordinates": {
      "lat": 18.9568,
      "lng": 72.8052
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "nature",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Municipal Corporation of Greater Mumbai",
    "heritage_status": "Historic Terraced Park",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-033",
    "name": "Kamala Nehru Park",
    "category": "Park and Viewpoint",
    "area": "Malabar Hill",
    "description": "A popular hilltop park known for its city and Marine Drive views.",
    "best_for": [
      "parks",
      "photography",
      "family outings"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Generally daytime",
    "visitor_notes": "The park is especially popular around sunset.",
    "map_search": "Kamala Nehru Park, Mumbai",
    "tags": [
      "park",
      "viewpoint",
      "Marine Drive view"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9575,
    "lng": 72.8055,
    "latitude": 18.9575,
    "longitude": 72.8055,
    "coordinates": {
      "lat": 18.9575,
      "lng": 72.8055
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "nature",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Municipal Corporation of Greater Mumbai",
    "heritage_status": "Public Heritage Viewpoint",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-034",
    "name": "Horniman Circle Garden",
    "category": "Park and Heritage",
    "area": "Fort",
    "description": "A landscaped urban garden surrounded by historic buildings in Mumbai’s financial district.",
    "best_for": [
      "parks",
      "heritage",
      "photography"
    ],
    "suggested_duration": "30–60 minutes",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Generally daytime",
    "visitor_notes": "Combine with the Asiatic Society and nearby heritage buildings.",
    "map_search": "Horniman Circle Garden, Mumbai",
    "tags": [
      "urban park",
      "heritage district",
      "garden"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9318,
    "lng": 72.8364,
    "latitude": 18.9318,
    "longitude": 72.8364,
    "coordinates": {
      "lat": 18.9318,
      "lng": 72.8364
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1496868834840-5f4c98840aaa?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1496868834840-5f4c98840aaa?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1496868834840-5f4c98840aaa?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "heritage",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Mumbai Heritage Conservation Committee",
    "heritage_status": "Heritage Circle Crescent",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-035",
    "name": "Marine Drive",
    "category": "Beachfront and Viewpoint",
    "area": "South Mumbai",
    "description": "A sweeping coastal promenade known for its sea views, evening atmosphere, and Art Deco skyline.",
    "best_for": [
      "sunset",
      "walking",
      "photography"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Open public promenade",
    "visitor_notes": "Avoid climbing barriers or going near rough seas.",
    "map_search": "Marine Drive, Mumbai",
    "tags": [
      "coast",
      "promenade",
      "viewpoint"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9431,
    "lng": 72.823,
    "latitude": 18.9431,
    "longitude": 72.823,
    "coordinates": {
      "lat": 18.9431,
      "lng": 72.823
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "beaches",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Maharashtra Tourism Development Corporation",
    "heritage_status": "UNESCO World Heritage Buffer Zone",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-036",
    "name": "Girgaum Chowpatty",
    "category": "Beach",
    "area": "Girgaon",
    "description": "A famous urban beach and public gathering place near Marine Drive.",
    "best_for": [
      "beach",
      "sunset",
      "family outings"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Open public beach; conditions vary",
    "visitor_notes": "Swimming is not recommended unless officially permitted and supervised.",
    "map_search": "Girgaum Chowpatty, Mumbai",
    "tags": [
      "beach",
      "sunset",
      "coastal attraction"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 18.9543,
    "lng": 72.8135,
    "latitude": 18.9543,
    "longitude": 72.8135,
    "coordinates": {
      "lat": 18.9543,
      "lng": 72.8135
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "beaches",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Maharashtra Tourism Development Corporation",
    "heritage_status": "Iconic City Beach",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-037",
    "name": "Juhu Beach",
    "category": "Beach",
    "area": "Juhu",
    "description": "One of Mumbai’s most popular beaches, known for its broad shoreline and lively atmosphere.",
    "best_for": [
      "beach",
      "sunset",
      "family outings"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Open public beach; conditions vary",
    "visitor_notes": "The beach can be crowded, especially on weekends and holidays.",
    "map_search": "Juhu Beach, Mumbai",
    "tags": [
      "beach",
      "sunset",
      "coast"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.0988,
    "lng": 72.8264,
    "latitude": 19.0988,
    "longitude": 72.8264,
    "coordinates": {
      "lat": 19.0988,
      "lng": 72.8264
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "beaches",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Maharashtra Tourism Development Corporation",
    "heritage_status": "Iconic Coastal Promenade",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-038",
    "name": "Bandra–Worli Sea Link",
    "category": "Modern Mumbai Attraction",
    "area": "Bandra–Worli",
    "description": "An iconic cable-stayed bridge and major piece of modern infrastructure connecting Bandra and Worli.",
    "best_for": [
      "modern architecture",
      "photography",
      "city views"
    ],
    "suggested_duration": "30–60 minutes",
    "best_time_to_visit": "October–March",
    "entry_fee": "Toll applies when crossing by vehicle",
    "opening_hours": "Operational throughout the day, subject to traffic rules",
    "visitor_notes": "Stopping on the bridge is prohibited; view it from permitted locations.",
    "map_search": "Bandra Worli Sea Link, Mumbai",
    "tags": [
      "modern landmark",
      "bridge",
      "infrastructure"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.033,
    "lng": 72.816,
    "latitude": 19.033,
    "longitude": 72.816,
    "coordinates": {
      "lat": 19.033,
      "lng": 72.816
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "modern",
    "source_url": "https://msrdc.in",
    "source_name": "Maharashtra State Road Development Corporation",
    "heritage_status": "Modern Engineering Landmark",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-039",
    "name": "Worli Sea Face",
    "category": "Modern Mumbai Attraction and Viewpoint",
    "area": "Worli",
    "description": "A popular seaside promenade offering views of the Arabian Sea and Bandra–Worli Sea Link.",
    "best_for": [
      "sunset",
      "walking",
      "photography"
    ],
    "suggested_duration": "1 hour",
    "best_time_to_visit": "October–March",
    "entry_fee": "Free",
    "opening_hours": "Open public promenade",
    "visitor_notes": "Be cautious during monsoon waves and high tides.",
    "map_search": "Worli Sea Face, Mumbai",
    "tags": [
      "seaface",
      "viewpoint",
      "modern Mumbai"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.013,
    "lng": 72.814,
    "latitude": 19.013,
    "longitude": 72.814,
    "coordinates": {
      "lat": 19.013,
      "lng": 72.814
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "beaches",
    "source_url": "https://maharashtratourism.gov.in",
    "source_name": "Municipal Corporation of Greater Mumbai",
    "heritage_status": "Scenic Coastal Promenade",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  },
  {
    "id": "mumbai-040",
    "name": "Sanjay Gandhi National Park Lion and Tiger Safari",
    "category": "Wildlife Attraction",
    "area": "Sanjay Gandhi National Park, Borivali",
    "description": "A safari attraction within the national park where visitors can observe selected wildlife species from a vehicle.",
    "best_for": [
      "wildlife",
      "families",
      "nature"
    ],
    "suggested_duration": "1–2 hours",
    "best_time_to_visit": "November–February",
    "entry_fee": "Additional safari fee may apply",
    "opening_hours": "Verify safari schedule",
    "visitor_notes": "Follow vehicle and animal-safety instructions; availability may vary.",
    "map_search": "Lion and Tiger Safari, Sanjay Gandhi National Park, Mumbai",
    "tags": [
      "wildlife safari",
      "tigers",
      "lions"
    ],
    "city": "Mumbai",
    "city_id": "mumbai",
    "state": "Maharashtra",
    "state_id": "maharashtra",
    "country": "India",
    "lat": 19.224,
    "lng": 72.915,
    "latitude": 19.224,
    "longitude": 72.915,
    "coordinates": {
      "lat": 19.224,
      "lng": 72.915
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=1000&auto=format&fit=crop&q=80",
    "image_url": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=1000&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=1000&auto=format&fit=crop&q=80"
    ],
    "section": "nature",
    "source_url": "https://sgnp.maharashtra.gov.in",
    "source_name": "Maharashtra Forest Department",
    "heritage_status": "Wildlife Safari Enclosure",
    "verification_status": "verified",
    "data_confidence": "official",
    "rating": 4.8,
    "features": {
      "map": true,
      "navigation": true,
      "ai": true,
      "3d": false
    }
  }
];

export const MUMBAI_FEATURED_IDS: string[] = [
  "mumbai-004",
  "mumbai-001",
  "mumbai-002",
  "mumbai-035",
  "mumbai-003",
  "mumbai-010",
  "mumbai-031",
  "mumbai-008",
  "mumbai-005",
  "mumbai-020"
];

export const MUMBAI_LOCAL_PICKS = {
  "restaurants": [
    {
      "id": "britannia-co",
      "name": "Britannia & Co. Restaurant",
      "area": "Ballard Estate, Fort",
      "cuisine": "Parsi & Irani Heritage",
      "specialties": [
        "Berry Pulao",
        "Sali Boti",
        "Caramel Custard"
      ],
      "description": "Iconic century-old colonial dining institution famous for traditional Parsi-Irani home recipes.",
      "price_for_two": "₹800 - ₹1,200",
      "address": "Wakefield House, 11 Sprott Rd, Ballard Estate, Fort, Mumbai",
      "timing": "12:00 PM – 4:00 PM (Closed Sundays)",
      "thumbnail_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "bademiya-sardar",
      "name": "Bademiya & Sardar Refreshments",
      "area": "Colaba & Tardeo",
      "cuisine": "Iconic Mumbai Street Flavors",
      "specialties": [
        "Butter Pav Bhaji",
        "Seekh Kebabs",
        "Baida Roti"
      ],
      "description": "The golden standards of Mumbai street food, serving late-night crowds and heritage food connoisseurs.",
      "price_for_two": "₹400 - ₹700",
      "address": "Tulloch Road, Colaba & 166-A Tardeo Road, Mumbai",
      "timing": "12:00 PM – 1:00 AM",
      "thumbnail_url": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "cafe-mondegar",
      "name": "Cafe Mondegar & Leopold Cafe",
      "area": "Colaba Causeway",
      "cuisine": "Continental & Irani Cafe",
      "specialties": [
        "Keema Pav",
        "Draft Brews",
        "Chilly Cheese Toast"
      ],
      "description": "Historic 1932 bistro adorned with Mario Miranda murals, celebrating Bombay’s vibrant cosmopolitan spirit.",
      "price_for_two": "₹900 - ₹1,500",
      "address": "Metro House, Colaba Causeway, Apollo Bunder, Mumbai",
      "timing": "7:30 AM – 11:30 PM",
      "thumbnail_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80"
    }
  ],
  "shops": [
    {
      "id": "colaba-causeway-market",
      "name": "Colaba Causeway Street Bazaars",
      "area": "Colaba",
      "specialties": [
        "Antique Brassware",
        "Silver Jewelry",
        "Vintage Handicrafts",
        "Books"
      ],
      "description": "Mumbai’s premier heritage flea market, lined with old colonial buildings and eclectic curio stalls.",
      "best_time": "Late afternoon to evening",
      "address": "Shahid Bhagat Singh Road, Colaba, Mumbai",
      "thumbnail_url": "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "crawford-market",
      "name": "Crawford Market (Jyotiba Phule Mandai)",
      "area": "Fort / Dhobi Talao",
      "specialties": [
        "Indian Spices",
        "Alphonso Mangoes",
        "Dry Fruits",
        "Herbal Extracts"
      ],
      "description": "A grand High Victorian Gothic market complex built in 1869 featuring stone bas-reliefs by Lockwood Kipling.",
      "best_time": "Morning 10:00 AM – 2:00 PM",
      "address": "Dhobi Talao, Chhatrapati Shivaji Maharaj Terminus Area, Mumbai",
      "thumbnail_url": "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "linking-road-bandra",
      "name": "Linking Road & Hill Road Bazaars",
      "area": "Bandra West",
      "specialties": [
        "Artisan Footwear",
        "Handmade Bags",
        "Fashion Boutiques",
        "Street Apparel"
      ],
      "description": "The epicenter of suburban Mumbai street fashion, brimming with energetic vendors and chic coastal stores.",
      "best_time": "4:00 PM – 9:00 PM",
      "address": "Linking Road, Bandra West, Mumbai",
      "thumbnail_url": "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600&auto=format&fit=crop&q=80"
    }
  ]
};

export const MUMBAI_STAYS = {
  "budget": [
    {
      "id": "zostel-mumbai",
      "name": "Zostel Mumbai",
      "type": "Backpacker Hostel & Private Rooms",
      "area": "Andheri East / Marol",
      "price_range": "₹1,400 - ₹2,800 / night",
      "rating": 4.6,
      "highlights": [
        "Community Rooftop",
        "AC Dorms & Privates",
        "Metro Connectivity"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "hotel-suba-palace",
      "name": "Hotel Suba Palace",
      "type": "Affordable Heritage Boutique",
      "area": "Colaba (200m from Gateway)",
      "price_range": "₹3,800 - ₹5,200 / night",
      "rating": 4.4,
      "highlights": [
        "Prime Historic Location",
        "Breakfast Included",
        "Safe & Clean"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "residency-hotel-fort",
      "name": "Residency Hotel Fort",
      "type": "Heritage Quarter Hotel",
      "area": "Fort (Walking distance to CSMT)",
      "price_range": "₹3,900 - ₹5,500 / night",
      "rating": 4.5,
      "highlights": [
        "Heritage Street Access",
        "Quiet Rooms",
        "High-Speed Wi-Fi"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&auto=format&fit=crop&q=80"
    }
  ],
  "moderate": [
    {
      "id": "trident-nariman-point",
      "name": "Trident Nariman Point",
      "type": "Premium Oceanfront Hotel",
      "area": "Nariman Point, Marine Drive",
      "price_range": "₹9,500 - ₹15,000 / night",
      "rating": 4.8,
      "highlights": [
        "Queen's Necklace Views",
        "Outdoor Pool",
        "Fine Dining"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "fariyas-hotel-mumbai",
      "name": "Fariyas Hotel Mumbai",
      "type": "4-Star Boutique Comfort",
      "area": "Colaba Waterfront",
      "price_range": "₹7,800 - ₹12,500 / night",
      "rating": 4.6,
      "highlights": [
        "Poolside Lounge",
        "Colaba Causeway Walking",
        "Fitness Centre"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "itc-grand-central",
      "name": "ITC Grand Central",
      "type": "Luxury Collection Heritage Style",
      "area": "Parel, Central Mumbai",
      "price_range": "₹8,900 - ₹14,000 / night",
      "rating": 4.7,
      "highlights": [
        "Victorian Architecture",
        "Kaya Kalp Spa",
        "Central Connectivity"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&auto=format&fit=crop&q=80"
    }
  ],
  "luxury": [
    {
      "id": "taj-mahal-palace-mumbai",
      "name": "The Taj Mahal Palace & Tower",
      "type": "Iconic 1903 Heritage Grand Palace",
      "area": "Apollo Bunder, Colaba",
      "price_range": "₹28,000 - ₹65,000 / night",
      "rating": 4.9,
      "highlights": [
        "Arabian Sea Gateway View",
        "Jiva Spa",
        "10 Historic Restaurants",
        "Royal Butler Service"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "the-oberoi-mumbai",
      "name": "The Oberoi Mumbai",
      "type": "Ultra-Luxury Waterfront Landmark",
      "area": "Marine Drive, Nariman Point",
      "price_range": "₹24,000 - ₹52,000 / night",
      "rating": 4.9,
      "highlights": [
        "Floor-to-Ceiling Sea Vistas",
        "Michelin-Caliber Cuisine",
        "24-Hour Butler Service"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&auto=format&fit=crop&q=80"
    },
    {
      "id": "the-st-regis-mumbai",
      "name": "The St. Regis Mumbai",
      "type": "Contemporary Skyscraper Luxury",
      "area": "Lower Parel",
      "price_range": "₹21,000 - ₹48,000 / night",
      "rating": 4.8,
      "highlights": [
        "Highest Bar in India (Asilo)",
        "Signature St. Regis Butler",
        "Direct Palladium Access"
      ],
      "thumbnail_url": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&auto=format&fit=crop&q=80"
    }
  ]
};

export const MUMBAI_TRANSPORTATION = {
  "budget": [
    {
      "mode": "Mumbai Metro",
      "icon": "Train",
      "cost_indication": "₹10 - ₹40 per trip",
      "description": "Fast, air-conditioned transit across Lines 1, 2A, 7, and the newly operational underground Aqua Line 3."
    },
    {
      "mode": "Mumbai Suburban Local Train",
      "icon": "Train",
      "cost_indication": "₹5 - ₹20 per trip",
      "description": "The legendary lifeline of Mumbai connecting CSMT and Churchgate to Northern suburbs."
    },
    {
      "mode": "BEST Bus Network",
      "icon": "Bus",
      "cost_indication": "₹6 - ₹25 per trip",
      "description": "Affordable red AC and electric buses reaching every street, fort, and coastal promenade."
    },
    {
      "mode": "Heritage Walking",
      "icon": "Footprints",
      "cost_indication": "Free",
      "description": "Pedestrian-friendly paths throughout Fort, Kala Ghoda, Oval Maidan, and Marine Drive."
    }
  ],
  "moderate": [
    {
      "mode": "App-Based Cabs (Uber / Ola)",
      "icon": "Car",
      "cost_indication": "₹150 - ₹450 per ride",
      "description": "On-demand AC comfort covering all city journeys and Sea Link crossings smoothly."
    },
    {
      "mode": "Iconic Kaali-Peeli Taxis",
      "icon": "Car",
      "cost_indication": "₹28 meter base + ₹18/km",
      "description": "Classic black-and-yellow metered taxis, ideal for historic South Mumbai hops."
    },
    {
      "mode": "Mumbai Metro & AC Local",
      "icon": "Train",
      "cost_indication": "₹20 - ₹65 per trip",
      "description": "First-class AC local trains and metro corridors for traffic-free transit."
    },
    {
      "mode": "BEST AC Express Buses",
      "icon": "Bus",
      "cost_indication": "₹15 - ₹50 per trip",
      "description": "Point-to-point air-conditioned transit on major arterial routes."
    }
  ],
  "luxury": [
    {
      "mode": "Dedicated Chauffeur-Driven Luxury Sedan",
      "icon": "Car",
      "cost_indication": "₹4,500 - ₹9,500 / 8-hour package",
      "description": "Private Mercedes-Benz, Audi, or Toyota Innova Crysta with a professional uniform chauffeur."
    },
    {
      "mode": "Airport Luxury Escort Transfer",
      "icon": "Plane",
      "cost_indication": "₹3,000 - ₹5,500 per transfer",
      "description": "Pre-arranged priority pickup from Chhatrapati Shivaji Maharaj International Airport."
    },
    {
      "mode": "Private Speedboat Charter to Elephanta",
      "icon": "Ship",
      "cost_indication": "₹8,000 - ₹15,000 charter",
      "description": "Exclusive private boat transfer across Mumbai Harbour departing directly from Gateway of India."
    },
    {
      "mode": "Bespoke Heritage City Tour Chauffeur",
      "icon": "Compass",
      "cost_indication": "₹7,500 / day",
      "description": "Full-day premium touring with English-speaking heritage concierge driver."
    }
  ]
};

export const MUMBAI_SECTIONS: DestinationSection[] = [
  {
    "id": "featured",
    "title": "Popular & Featured Landmarks",
    "description": "The ten most iconic and world-renowned destinations in Mumbai.",
    "placeIds": [
      "mumbai-004",
      "mumbai-001",
      "mumbai-002",
      "mumbai-035",
      "mumbai-003",
      "mumbai-010",
      "mumbai-031",
      "mumbai-008",
      "mumbai-005",
      "mumbai-020"
    ]
  },
  {
    "id": "heritage",
    "title": "Heritage & Colonial Landmarks",
    "description": "Victorian Gothic masterpieces, UNESCO sites, and ancient stone monuments.",
    "placeIds": [
      "mumbai-001",
      "mumbai-002",
      "mumbai-003",
      "mumbai-004",
      "mumbai-008",
      "mumbai-009",
      "mumbai-010",
      "mumbai-011",
      "mumbai-012",
      "mumbai-013",
      "mumbai-014",
      "mumbai-015",
      "mumbai-034"
    ]
  },
  {
    "id": "religious",
    "title": "Religious & Cultural Shrines",
    "description": "Sacred coastal temples, historic dargahs, basilicas, and synagogues.",
    "placeIds": [
      "mumbai-016",
      "mumbai-017",
      "mumbai-018",
      "mumbai-019",
      "mumbai-020",
      "mumbai-021",
      "mumbai-022"
    ]
  },
  {
    "id": "museums",
    "title": "Museums & Art Galleries",
    "description": "Indo-Saracenic galleries, cinematic archives, and contemporary art hubs.",
    "placeIds": [
      "mumbai-005",
      "mumbai-006",
      "mumbai-007",
      "mumbai-024",
      "mumbai-025",
      "mumbai-026",
      "mumbai-027",
      "mumbai-028"
    ]
  },
  {
    "id": "nature",
    "title": "Nature, Parks & Wildlife",
    "description": "Tropical rainforests, hilltop viewpoints, terraced gardens, and zoos.",
    "placeIds": [
      "mumbai-030",
      "mumbai-031",
      "mumbai-032",
      "mumbai-033",
      "mumbai-040"
    ]
  },
  {
    "id": "beaches",
    "title": "Beaches & Coastal Promenades",
    "description": "Panoramic Arabian Sea boulevards, sunset sands, and sea-spray vistas.",
    "placeIds": [
      "mumbai-035",
      "mumbai-036",
      "mumbai-037",
      "mumbai-039"
    ]
  },
  {
    "id": "modern",
    "title": "Modern Mumbai Attractions",
    "description": "Architectural engineering marvels, interactive science parks, and innovation hubs.",
    "placeIds": [
      "mumbai-023",
      "mumbai-029",
      "mumbai-038"
    ]
  }
];

export const MUMBAI_ITINERARY_CIRCUITS = [
  {
    "day_number": 1,
    "area_title": "South Mumbai & Colaba Heritage",
    "area_name": "Colaba & Fort",
    "subtitle": "Iconic waterfront monuments, Indo-Saracenic museums and sunset promenades.",
    "hero_image_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80",
    "places": [
      {
        "id": "mumbai-004",
        "name": "Gateway of India",
        "distance_info": "0 km",
        "category": "Heritage Landmark"
      },
      {
        "id": "mumbai-005",
        "name": "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya",
        "distance_info": "~ 1.2 km",
        "category": "Museum and Heritage"
      },
      {
        "id": "mumbai-025",
        "name": "National Gallery of Modern Art",
        "distance_info": "~ 0.5 km",
        "category": "Art Gallery"
      },
      {
        "id": "mumbai-035",
        "name": "Marine Drive",
        "distance_info": "~ 2.0 km",
        "category": "Beachfront and Viewpoint"
      }
    ],
    "shopping": [
      "Colaba Causeway Street Stalls",
      "Kala Ghoda Art Boutiques"
    ]
  },
  {
    "day_number": 2,
    "area_title": "Fort & Victorian Gothic World Heritage",
    "area_name": "Fort Precinct",
    "subtitle": "UNESCO Victorian Gothic & Art Deco Ensembles, clock towers and historic libraries.",
    "hero_image_url": "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=800&auto=format&fit=crop&q=80",
    "places": [
      {
        "id": "mumbai-001",
        "name": "Chhatrapati Shivaji Maharaj Terminus",
        "distance_info": "0 km",
        "category": "UNESCO and Heritage"
      },
      {
        "id": "mumbai-003",
        "name": "Victorian Gothic and Art Deco Ensembles of Mumbai",
        "distance_info": "~ 1.0 km",
        "category": "UNESCO and Heritage"
      },
      {
        "id": "mumbai-014",
        "name": "Rajabai Clock Tower",
        "distance_info": "~ 0.8 km",
        "category": "Heritage Landmark"
      },
      {
        "id": "mumbai-013",
        "name": "Asiatic Society Library",
        "distance_info": "~ 0.9 km",
        "category": "Heritage and Library"
      },
      {
        "id": "mumbai-034",
        "name": "Horniman Circle Garden",
        "distance_info": "~ 0.3 km",
        "category": "Park and Heritage"
      }
    ],
    "shopping": [
      "Crawford Market Spices",
      "Fort Antique Book Stalls"
    ]
  },
  {
    "day_number": 3,
    "area_title": "Kala Ghoda Art Quarter & Heritage Villages",
    "area_name": "Kala Ghoda & Girgaon",
    "subtitle": "Contemporary art galleries, historic synagogues and Portuguese-era lanes.",
    "hero_image_url": "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&auto=format&fit=crop&q=80",
    "places": [
      {
        "id": "mumbai-026",
        "name": "Jehangir Art Gallery",
        "distance_info": "0 km",
        "category": "Art Gallery"
      },
      {
        "id": "mumbai-015",
        "name": "David Sassoon Library",
        "distance_info": "~ 0.2 km",
        "category": "Heritage and Library"
      },
      {
        "id": "mumbai-022",
        "name": "Knesset Eliyahoo Synagogue",
        "distance_info": "~ 0.4 km",
        "category": "Religious and Heritage"
      },
      {
        "id": "mumbai-012",
        "name": "Khotachiwadi Heritage Village",
        "distance_info": "~ 3.5 km",
        "category": "Heritage Village"
      },
      {
        "id": "mumbai-007",
        "name": "Mani Bhavan Gandhi Sangrahalaya",
        "distance_info": "~ 1.5 km",
        "category": "Museum and Religious-Historical"
      }
    ],
    "shopping": [
      "Kala Ghoda Designer Studios",
      "Girgaon Sweet Marts"
    ]
  },
  {
    "day_number": 4,
    "area_title": "Elephanta Island UNESCO Excursion & Malabar Sunset",
    "area_name": "Elephanta Island & Malabar Hill",
    "subtitle": "Ancient 6th-century rock-cut cave temples and terraced hilltop gardens.",
    "hero_image_url": "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=800&auto=format&fit=crop&q=80",
    "places": [
      {
        "id": "mumbai-002",
        "name": "Elephanta Caves",
        "distance_info": "0 km (Ferry from Gateway)",
        "category": "UNESCO and Heritage"
      },
      {
        "id": "mumbai-036",
        "name": "Girgaum Chowpatty",
        "distance_info": "~ 11 km (Post-ferry return)",
        "category": "Beach"
      },
      {
        "id": "mumbai-032",
        "name": "Hanging Gardens",
        "distance_info": "~ 2.5 km",
        "category": "Park and Viewpoint"
      },
      {
        "id": "mumbai-033",
        "name": "Kamala Nehru Park",
        "distance_info": "~ 0.2 km",
        "category": "Park and Viewpoint"
      }
    ],
    "shopping": [
      "Chowpatty Beach Kiosks",
      "Malabar Hill Curios"
    ]
  },
  {
    "day_number": 5,
    "area_title": "Worli & Byculla Coastal & Cultural Trail",
    "area_name": "Worli & Byculla",
    "subtitle": "Sacred marine dargahs, coastal forts and Victorian botanical gardens.",
    "hero_image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    "places": [
      {
        "id": "mumbai-020",
        "name": "Haji Ali Dargah",
        "distance_info": "0 km",
        "category": "Religious and Heritage"
      },
      {
        "id": "mumbai-017",
        "name": "Mahalakshmi Temple",
        "distance_info": "~ 1.0 km",
        "category": "Religious"
      },
      {
        "id": "mumbai-039",
        "name": "Worli Sea Face",
        "distance_info": "~ 2.5 km",
        "category": "Modern Mumbai Attraction and Viewpoint"
      },
      {
        "id": "mumbai-011",
        "name": "Worli Fort",
        "distance_info": "~ 2.0 km",
        "category": "Heritage Landmark"
      },
      {
        "id": "mumbai-006",
        "name": "Dr. Bhau Daji Lad Museum",
        "distance_info": "~ 4.5 km",
        "category": "Museum and Heritage"
      },
      {
        "id": "mumbai-030",
        "name": "Veermata Jijabai Bhosale Udyan and Zoo",
        "distance_info": "~ 0.2 km",
        "category": "Park and Zoo"
      }
    ],
    "shopping": [
      "High Street Phoenix",
      "Byculla Flower Bazaar"
    ]
  },
  {
    "day_number": 6,
    "area_title": "Bandra West & Modern Mumbai Sea Link",
    "area_name": "Bandra & Prabhadevi",
    "subtitle": "Coastal battlements, hilltop basilicas, modern bridges and vibrant bazaars.",
    "hero_image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
    "places": [
      {
        "id": "mumbai-010",
        "name": "Bandra Fort",
        "distance_info": "0 km",
        "category": "Heritage Landmark"
      },
      {
        "id": "mumbai-021",
        "name": "Mount Mary Basilica",
        "distance_info": "~ 1.2 km",
        "category": "Religious and Heritage"
      },
      {
        "id": "mumbai-038",
        "name": "Bandra–Worli Sea Link",
        "distance_info": "~ 2.0 km",
        "category": "Modern Mumbai Attraction"
      },
      {
        "id": "mumbai-016",
        "name": "Siddhivinayak Temple",
        "distance_info": "~ 3.5 km",
        "category": "Religious"
      },
      {
        "id": "mumbai-023",
        "name": "Nehru Science Centre",
        "distance_info": "~ 4.0 km",
        "category": "Science Centre"
      }
    ],
    "shopping": [
      "Linking Road Street Fashion",
      "Hill Road Artisan Markets"
    ]
  },
  {
    "day_number": 7,
    "area_title": "Sanjay Gandhi National Park & Northern Wilderness",
    "area_name": "Borivali & Juhu",
    "subtitle": "Ancient rock-cut Buddhist caves, dense forest safari and sunset beaches.",
    "hero_image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80",
    "places": [
      {
        "id": "mumbai-031",
        "name": "Sanjay Gandhi National Park",
        "distance_info": "0 km",
        "category": "National Park and Nature"
      },
      {
        "id": "mumbai-008",
        "name": "Kanheri Caves",
        "distance_info": "~ 6.0 km (Inside SGNP)",
        "category": "Heritage and Religious"
      },
      {
        "id": "mumbai-040",
        "name": "Sanjay Gandhi National Park Lion and Tiger Safari",
        "distance_info": "~ 2.0 km",
        "category": "Wildlife Attraction"
      },
      {
        "id": "mumbai-037",
        "name": "Juhu Beach",
        "distance_info": "~ 18 km (Southbound Sunset)",
        "category": "Beach"
      }
    ],
    "shopping": [
      "SGNP Nature Souvenir Kiosk",
      "Juhu Beach Handicraft Stalls"
    ]
  }
];

export function getMumbaiAttractionById(id: string): MumbaiAttraction | undefined {
  const norm = (id || '').toLowerCase().trim();
  return MUMBAI_ATTRACTIONS.find((p) => p.id.toLowerCase() === norm);
}

export function searchMumbaiAttractions(query: string): MumbaiAttraction[] {
  if (!query || !query.trim()) return MUMBAI_ATTRACTIONS;
  const q = query.toLowerCase().trim();
  return MUMBAI_ATTRACTIONS.filter((p) => {
    return (
      p.name.toLowerCase().includes(q) ||
      p.area.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.map_search.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.best_for.some((b) => b.toLowerCase().includes(q))
    );
  });
}
